### ISSUE TITLE
RestrictChatMemberAsync method not working properly

### ISSUE THREAD

**Issue by sajadafaghiy** [TelegramBots/Telegram.Bot#1000]
### Steps to reproduce
`await _botService.Client.RestrictChatMemberAsync(message.Chat.Id, message.From.Id, new ChatPermissions { CanSendMessages = true, CanSendOtherMessages = true, CanSendMediaMessages = false });
`

### Expected  behavior
New permissions for user that can just send text messages and sticker, game and animations.

> can_send_other_messages: Optional. True, if the user is allowed to send animations, games, stickers and use inline bots, implies can_send_media_messages

### Actual behavior
This request doesn't respect to false value of CanSendMediaMessages permission. After the request **Send Media** option in user permissions will be also true or active!

> can_send_media_messages: Optional. True, if the user is allowed to send audios, documents, photos, videos, video notes and voice notes, implies can_send_messages

### Screenshots
No Screenshots

### Environment data
No Environment data

*NuGet Package Version:* 16.0.0

*.NET Version:* Net 5.0

*IDE:* VS2019

*App:* Desktop, Android, Web

**Comment by karb0f0s** [comment]
this issue has nothing to do with he library. if you read [official docs on ChatPermissions](https://core.telegram.org/bots/api#chatpermissions) carefully, you can notice that `can_send_other_messages` permission implies `can_send_media_messages`.

Field | Type | Description
-- | -- | --
can_send_other_messages | Boolean | Optional. True, if the user is allowed to send animations, games, stickers and use inline bots, **_implies can_send_media_messages_**

**Comment by sajadafaghiy** [comment]
That's right! So how can I force user to send just stickers and no media?

**Comment by karb0f0s** [comment]
this is not a best place to ask for this. you can file an issue in official [Telegram Bot API repo](https://github.com/tdlib/telegram-bot-api/issues), or ask fellow developers in [our Telegram chat](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA)

**Comment by karb0f0s** [comment]
another option is to set permissions via desktop/mobile client and check actual permissions via [getChatMember](https://core.telegram.org/bots/api#getchatmember) method
