### ISSUE TITLE
How i can update replay keyboard without sending message?

### ISSUE THREAD

**Issue by qLlirik** [TelegramBots/Telegram.Bot#1001]
I want to update replay keyboard without sending new message, so as not to clog the chat. Is it possible?
![image](https://user-images.githubusercontent.com/33235001/125164121-493e5600-e199-11eb-8989-0ccb7cc3cd44.png)

**Comment by tuscen** [comment]
Please, read issue templates before posting. Feel free to join our group if you have questions.
