### ISSUE TITLE
Delete buttons from MarkdownV2 message preserving original text from callback - possible MarkdownV2 formatting issue

### ISSUE THREAD

**Issue by chris-rutkowski** [TelegramBots/Telegram.Bot#1005]
### Steps to reproduce

```
await client.SendTextMessageAsync({chatId}, text: "Hello *me*\\.", replyMarkup: {singleContinueButton}, parseMode: ParseMode.MarkdownV2);
```

await for Continue button callback, and delete the button from the message:

```
CallbackQuery query = ...;
await client.EditMessageTextAsync(query.Message.Chat.Id, query.Message.MessageId, text: query.Message.Text, parseMode: ParseMode.MarkdownV2);

```

### Expected  behavior

Message looking like this: Hello **me**.

### Actual behavior
Telegram.Bot.Exceptions.ApiRequestException: Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\'
   at TradeBobCommon.Services.TelegramService.HandleException(Exception exception, String source, Nullable`1 chatId) in /home/chris/TradeBobServer/TradeBobCommon/Services/TelegramService.cs:line 201

This is because `query.Message.Text == "Hello *me*."` but it should `== "Hello *me*\\."`;

### Environment data

*NuGet Package Version:* (e.g. 13.0.1)
16.0.0

*.NET Version:* (e.g. 4.7, Core 1.1, Mono, etc.)
5.0.302

**Comment by karb0f0s** [comment]
I think your issue is related to this answer - [#44](https://github.com/tdlib/telegram-bot-api/issues/44#issuecomment-730304409).
From what i see there is no way to reconstruct markup from response:
```csharp
var message = await botClient.SendTextMessageAsync(chatId,
                                     text: "Hello *me*\\.",
                                     replyMarkup: new InlineKeyboardMarkup(InlineKeyboardButton.WithCallbackData("Continue", "continue")),
                                     parseMode: ParseMode.MarkdownV2);
```

as you can see raw json for message doesn't contain any markup information:
```json
{
    "chat_id": 0123456,
    "text": "Hello *me*\\.",
    "parse_mode": "MarkdownV2",
    "reply_to_message_id": 0,
    "allow_sending_without_reply": false,
    "reply_markup": {
        "inline_keyboard": [
            [
                {
                    "text": "Continue",
                    "callback_data": "continue"
                }
            ]
        ]
    }
}
```

raw json for callback update looks similar:
```json
{
    "message_id": 31520,
    "from": {
        "id": 987654321,
        "is_bot": true,
        "first_name": "botframeworktestbot",
        "username": "botframework_test_bot"
    },
    "chat": {
        "id": 0123456,
        "first_name": "karb0f0s",
        "username": "karb0f0s",
        "type": "private"
    },
    "date": 1626698907,
    "text": "Hello me.",
    "entities": [
        {
            "offset": 6,
            "length": 2,
            "type": "bold"
        }
    ],
    "reply_markup": {
        "inline_keyboard": [
            [
                {
                    "text": "Continue",
                    "callback_data": "continue"
                }
            ]
        ]
    }
}  
```

**Comment by karb0f0s** [comment]
there are several options here: you might keep (or generate) formatted message yourself on each request, or you can send messages using `text` and `entities` parameters from the response without specifying `parseMode`.
in case you don't actually change message text you might use [editMessageReplyMarkup](https://core.telegram.org/bots/api#editmessagereplymarkup) method to edit message markup.
