### ISSUE TITLE
MarkdownV2 does not support links without domain

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [TelegramBots/Telegram.Bot#1010]
When I use the bot to send messages, I employ the **MarkdownV2** mode.

If I insert a link of the following type into my message:

`*Ticket:* [Open](https://www.google.com)`

Then the "Open" word is clickable. However, if the server name is the following:

`*Ticket:* [Open](http://my-pc:8082/mails/26785)`

The "Open" does not have a hyperlink assigned.

After a few tries, I found out that links without domain do not work, i.e. the following does work:

`*Ticket:* [Open](http://my-pc.com:8080/mails/26785)`

Is this a bug? How can I bypass this limitation?

*NuGet Package Version:* 16.0.2

**Comment by karb0f0s** [comment]
This question is outside of scope of this library. You can try to ask Telegram developers directly in [telegram-bot-api](https://github.com/tdlib/telegram-bot-api/issues) repo.

**Comment by karb0f0s** [comment]
PS: Does it work with other markup options?
PPS: Bots are rather simple concept - they are not able to control client's application behaviour. I think this question is more about client-side rendering issues. But it's understandable for me: non-qualified name could not be resolved. there is no guarantee that this message would appear on device inside local network and will be processed correctly.

**Comment by SvyatoslavRazmyslov** [comment]
> Does it work with other markup options?

I use `ParseMode.MarkdownV2` in the `SendTextMessageAsync(...)` method (this is from Telegram.Bot). `Markdown` and `Html` work worse.
