### ISSUE TITLE
CreateChatInviteLinkAsync

### ISSUE THREAD

**Issue by SergioZgz** [TelegramBots/Telegram.Bot#1014]
I found a bug to report, all created invite links are expired always

### Steps to reproduce
Just try to use CreateChatInviteLinkAsync on group when bot is an admin, the link is created ok but always is expired, you can use just chatid with not datetime or use datime.now.adddays(50) for example and you will get expired link all time

### Expected  behavior
Links should work
### Actual behavior
Links are expired

*NuGet Package Version:* Latest 16,0,2

**Comment by tuscen** [comment]
Could you give me a piece of code to reproduce the problem?

**Comment by tuscen** [comment]
I weren't able to reproduce your problem.

**Comment by SergioZgz** [comment]
I created another group and its working fine, I think that the issue is related to something in the other group, the link is not expired but telegram say that, sorry. I close the ticket and thanks for the fast responses :)
