### ISSUE TITLE
Automatically generated request parameters classes

### ISSUE THREAD

**Issue by lentrodev** [TelegramBots/Telegram.Bot#1015]
# Automatically generated request parameters classes

I'd like to propose you to implement automatic generation of request parameters classes for each method available, using [source generation](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/).

For example, for the method `SendTextMessageAsync` will be created a new class named `SendTextMessageParameters` and interface  `ISendTextMessageParameters`. Whole structure will look like this:

```csharp

public interface ISendTextMessageParameters 
{
    ChatId ChatId { get; }
    
    string Text { get; }

    ISendTextMessageParameters WithChatId(ChatId chatId);

    SendTextMessageParameters WithText(string text);
}

public class SendTextMessageParameters : ISendTextMessageParameters 
{
    public ChatId ChatId { get; private set; }

    public string Text { get; private set; }

    public ISendTextMessageParameters WithChatId(ChatId chatId)
    {
        ChatId = chatId;

        return this;
    }

    public ISendTextMessageParameters WithText(string text)
    {
        Text = text;

        return this;
    }
}


```

And for make a request using this parameters, will be created overload for each method in the library.

In the `TelegramBotClientParametersExtensions` class:

```csharp

public static Task SendTextMessageAsync(this ITelegramBotClient telegramBotClient, ISendTextMessageParameters sendTextMessageParameters)
{
    return telegramBotClient.SendTextMessageAsync(chatId: sendTextMessageParameters.ChatId, text: sendTextMessageParameters.Text, ...);
}
```

In your code:

```csharp

public async Task DoSomethingAsync(ITelegramBotClient telegramBotClient)
{
    ISendTextMessageParameters sendTextMessageParameters = new SendTextMessageParameters()
        .WithChatId(128)
        .WithText("Hello Wold!");
       
    await telegramBotClient.SendTextMessageAsync(sendTextMessageParameters);
}

```

I think, this will will help users with building and reusing this parameters for future requests.

**Comment by tuscen** [comment]
I'd be glad to do that, but unfortunately the Bot API doesn't have any machine readable documentation. Current documentation is just an html html without any classless, it's just a bunch of divs and p so one would have to rely on hueristics to differentiate between types and methods, etc. I asked bot support for a machine readable docs and they answered they don't have plans for that in near future since the team have other priorities.

**Comment by avalanche759** [comment]
@tuscen I had successfull attempts with parsing official Telegram Bot API documentation, but it wasn't good for using it as scheme for implementing requests and API models, so I abandoned this project. My idea applies to already implemented methods, so source generator will take already defined extesion methods in TelegramBotClientExtensions class and just parse they signatures and will create classes and interfaces based on them.

**Comment by tuscen** [comment]
There's one disadvantage with using builders this way: builders are convenient when you use only their methods to set parameters. But about required parameters? If you set them in builder ctor it won't be as convenient. Otherwise you loose compile type safety.

**Comment by avalanche759** [comment]
@tuscen Anyway, if one of the required parameters is missing, Telegram will result an error when sending a request, so developer will see which parameter he forgot to specify. Or be can add some validation before sending a request, which will be a more correct solution, I think. I can test different solutions and propose a most correct one.

**Comment by tuscen** [comment]
We're trying to have as much compile time safety as we reasonably can though.

**Comment by avalanche759** [comment]
@tuscen Okay, I'll think about that, will propose a solution ASAP.

**Comment by wiz0u** [comment]
We are now using `required` keyword and source generation (just not MS source generator) by parsing the official documentation.
