### ISSUE TITLE
How to validate the telegram user id is valid or not in python??

### ISSUE THREAD

**Issue by Darvin09** [TelegramBots/Telegram.Bot#1019]
Tell me how validate telegram user id is valid or not using python

**Comment by karb0f0s** [comment]
Please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)
If you want to chat, feel free to join our [group](https://t.me/tgbots_dotnet).
