### ISSUE TITLE
Cannot post link to Telegram using entities

### ISSUE THREAD

**Issue by nikkilocke** [TelegramBots/Telegram.Bot#1024]
I am trying to post a link to Telegram, with link text and a url.

### Steps to reproduce
```
string text = "@admin The Hub";
MessageEntity [] entities = new MessageEntity [] {
  new MessageEntity() { 
    Length = 7, 
    Offset = 7, 
    Type = MessageEntity.Type.Url, 
    Url = "https://example.com" 
  }
};
Message m = await SendTextMessageAsync(b.ChannelId, text, ParseMode.Default, entities, false, false, 0);
```

### Expected  behavior
A Telegram message is posted that says 
@admin [The Hub](https://example.com)

i.e. the words "The Hub" appear as a link to https://example.com

### Actual behavior

The Hub does not appear as a link

### Screenshots
![image](https://user-images.githubusercontent.com/684025/139704392-267993eb-eac4-433d-aee9-4f0cb044badf.png)

### Environment data

*NuGet Package Version:* 16.0.2

*.NET Version:* .NET Core 3.1

*IDE:* VS2019

*App:* Any app.

**Comment by nikkilocke** [comment]
Any chance of some help with this, please?

**Comment by Fedorus** [comment]
You should use MessageEntityType.TextLink

**Comment by nikkilocke** [comment]
Thankyou very much for spotting the bug in my code. I have corrected it, and it works fine now.
