### ISSUE TITLE
PromoteChatMember questions

### ISSUE THREAD

**Issue by jcmag** [TelegramBots/Telegram.Bot#1025]
Hi

I'm doing some tests with PromoteChatMemberAsync method and I don't understand how it works...
I'm calling the method like this:

`await bot.PromoteChatMemberAsync(telegramId, telegramUserId, true, true, true, true, true, true, true, true, true, true, true);`

The bot is admin in my channel, with all rights.
telegramId is the channel identifier.

1) if I set telegramUserId to the chat's owner ID, I get the error: "Bad Request: can't remove chat owner"; why?? in the doc it says to pass false for all parameters to do that...

2) if I set telegramUserId to a chat's admin ID, I get the error: "Bad Request: CHAT_ADMIN_REQUIRED". I really don't understand since the bot and the user are all admins...

3) If I set telegramUserId to a chat's member ID, I get the error: " Bad Request: RIGHT_FORBIDDEN". 

I'm completely lost here... Am I doing something wrong?

API version: 16.0.2
.NET v4.8

**Comment by tuscen** [comment]
Please, read issue templates before posting. If you have any question feel free to join our [support group](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA).

**Comment by Onix-one** [comment]
> Please, read issue templates before posting. If you have any question feel free to join our [support group](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA).

I have the same problem and couldn't find an answer. Neither in the chat nor in the documentation.
