### ISSUE TITLE
fill textbox1.text with telegram bot

### ISSUE THREAD

**Issue by mortadaali1** [TelegramBots/Telegram.Bot#1026]
i just want to know if there anyway that i can link my vb.net project with telegram bot so i can control it with my phone easily.

ok so i mean that when i send a message to the bot like username is (xxxxxx) it just fill the textbox1.text in my app with (xxxxx) and the pass is (hhhhh) so it fill the textbox2.text field with (hhhhh)

then when i say go the app just click go in my app

i hope you understand me  browser.ExecuteScriptAsync("document.all('username').value=" & "'"c & TextBox1.Text + "'"c) so the textbox1.text value Determined by the telegram bot message i sent

thanks alot

**Comment by tuscen** [comment]
Please, read issue templates before posting. If you have any question feel free to join our support [group](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA).
