### ISSUE TITLE
Being able to check if a user has "started" the bot

### ISSUE THREAD

**Issue by LechuckThePirate** [TelegramBots/Telegram.Bot#1029]
My bots normally listen to a group, then under some commands, they send the user a private message.

Telegram won't allow me to send private messages to a user if the user didn't START the bot. The problem is I don't know if the user has started the bot or not, so when I reply, I just catch the error.

This is ok, but when there are a lot of messages from users and I try to send a lot of private reply messages, which will fail, telegram starts "lagging" the messages (I guess it's some kind of protection) and after a while, I start receiving like one message per minute... that makes to bot totally unresponsive.

I tried to getChannel and getChatMember but I don't see any difference in the result... nothing gives me a hint whether the bot will be able to send a private message to the user or not.

Is there any way to do this? If not, it would be great

**Comment by tuscen** [comment]
Please, read issue templates before posting. If you have any questions feel free to join our [support group](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA).
