### ISSUE TITLE
Incorrect `operator ==` behaviour in 'ChatId'

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#1038]
Incorrect `operator ==` behaviour in 'ChatId'

**Comment by karb0f0s** [comment]
[Current logic](https://github.com/TelegramBots/Telegram.Bot/blob/6d4f85265e2939a5a4ac1eabc4f368723023133d/src/Telegram.Bot/Types/ChatId.cs#L124-L126) suggests that either `Identifier` or `Username` should be equal:

```csharp
            // checking by Identifier is more consistent but we should check that its value isn`t default
            return obj1.Identifier != 0
                ? obj1.Identifier == obj2.Identifier || obj1.Username == obj2.Username
                : obj1.Identifier == obj2.Identifier && obj1.Username == obj2.Username;
```

It's logically correct, because 'ChatId' should contain either `long` or `string` value, I think 'obj1.Identifier != 0' part is incorrect in nullable scenarios.
So, if `Identifier` is `string`, then we should check if 'obj1.Identifier is null' and compare only `obj1.Username == obj2.Username` and 'obj1.Identifier == obj2.Identifier' otherwise.
Maybe we also should add assert if both values are present.

**Comment by tuscen** [comment]
Done in #1102
