### ISSUE TITLE
Change type of Telegram Id

### ISSUE THREAD

**Issue by hamedhajiloo** [TelegramBots/Telegram.Bot#1043]
Have you changed the type of Telegram Ids?
![image](https://user-images.githubusercontent.com/45947371/144748310-9a8e6b29-9d4b-411f-8ba6-aa4db85cf4e0.png)

You should change the type of telegram Ids

- update_id
- chat_id
- message_id

![image](https://user-images.githubusercontent.com/45947371/144748387-b03ce12f-1855-4201-9e61-40c259779b03.png)

**Comment by vas7n** [comment]
Hi! 
I used the package version = "15.7.1" and faced the same problem. Updated to 16.0.2 and the problem went away.
To switch to version 17, as I understand it, you need to switch to netcore

**Comment by hamedhajiloo** [comment]
But it's still `int`

![](file:///C:/Users/Hamed/AppData/Local/Temp/SNAGHTML1a5e3558.PNG)

**Comment by hamedhajiloo** [comment]
I updated to version 17 but in `Update` class, It's still int

![](https://user-images.githubusercontent.com/45947371/144754666-36eec761-5a1e-40e8-8c47-8ab3ba4c5465.png)

**Comment by tuscen** [comment]
As far as the documentation goes only `user_id` needs to be 64 bit, `message_id` and `update_id` are still 32 bit.

**Comment by hamedhajiloo** [comment]
Done
