### ISSUE TITLE
No logging documentation

### ISSUE THREAD

**Issue by shardwolfdotnet** [TelegramBots/Telegram.Bot#1047]
The [Logging](https://telegrambots.github.io/book/4/log.html) chapter of the documentation hasn't been written. It's not immediately clear whether any logging facilities exist within Telegram.Bot (searching the codebase for `log`/`logging` didn't turn up anything useful), but if that is indeed the case it would be nice to have the [lack of] logging be codified in the docs.

**Comment by Fedorus** [comment]
Sorry, but logging of what? )

**Comment by shardwolfdotnet** [comment]
> Sorry, but logging of what? )

I feel like this is a pretty broad question -"everything" would be the naive answer, but logging of connection status, maybe reception of different update types, important state-changes within the framework, and other pertinent information would be nice.

Some of this might be accomplished via HttpClient logging, but that's a slightly lower level of abstraction than I was hoping for.

**Comment by tuscen** [comment]
But the is no long lived connection to keep track of, no status, the is no official framework. Information about received update types is quite useless since one could do it themselves. I really don't much need for logging in the client.

**Comment by wiz0u** [comment]
People can implement their own logging via events `OnMakingApiRequest` & `OnApiResponseReceived`
