### ISSUE TITLE
ForwardFromMessageId = 0

### ISSUE THREAD

**Issue by Karmageddonium** [TelegramBots/Telegram.Bot#1050]
Если боту переслать сообщение из чата между двумя пользователями (для теста я пересылал своё отправленное сообщение), то бот словит сообщение, в котором ForwardFromMessageId = 0, таким образом если отправить два разных/одинаковых сообщения из одного чата, бот не сможет их различить, если не прибегать к содержимому. Версия 16.0.2

Я не уверен до конца что это баг, возможно так и должно быть и я чего-то не понимаю. Буду благодарен за поясенения. 

И спасибо за шикарную библиотеку)

**Comment by tuscen** [comment]
Can you give me a piece of code with a repro. I can't quite understand the problem.

**Comment by karb0f0s** [comment]
> Если боту переслать сообщение из чата между двумя пользователями (для теста я пересылал своё отправленное сообщение), то бот словит сообщение, в котором ForwardFromMessageId = 0, таким образом если отправить два разных/одинаковых сообщения из одного чата, бот не сможет их различить, если не прибегать к содержимому. **Версия 16.0.2**

@Karmageddonium 
First of all - can you reproduce this behaviour with the latest version? It is possible, that you actually should get 'null' for this optional property.
