### ISSUE TITLE
HttpRequestMessage disposes user-provided Stream object

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#1056]
Wrapping `HttpRequestMessage` in `using` block causes it to call `.Dispose()` on underlying `Content` object

https://github.com/TelegramBots/Telegram.Bot/blob/a58445e42b2d34cceedfdcbf477b027c9b3e9e68/src/Telegram.Bot/TelegramBotClient.cs#L119-L122

Since we do not own this `Stream` we should either get rid of `using` block, or document this behaviour.

**Comment by karb0f0s** [comment]
Discussion links:
https://t.me/c/1142631927/89907
https://t.me/c/1142631927/89911

**Comment by tuscen** [comment]
Done in #1102
