### ISSUE TITLE
Add chat-specific overloads for PromoteChatMemberAsync

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#1060]
[promoteChatMember](https://core.telegram.org/bots/api#promotechatmember) method has subset of options, related only to specific chat types: _`can_pin_messages` - ... supergroups only_, _`can_edit_messages` - ... channels only_.
Maybe we can add overloaded methods with specific subset of options:

```csharp
// Channel-specific overload
public Task PromoteChatMemberAsync(
            this ITelegramBotClient botClient,
            ChatId chatId,
            long userId,
            ChannelPermissions channelPermissions,
            CancellationToken cancellationToken = default
        );

// Supergroup-specific overload
public Task PromoteChatMemberAsync(
            this ITelegramBotClient botClient,
            ChatId chatId,
            long userId,
            SupoergroupPermissions supergrouplPermissions,
            CancellationToken cancellationToken = default
        );
```

**Comment by tuscen** [comment]
This feature goes against our rule to stick to type hierarchy from the Bot API docs. In the docs `ChatPermissions` object doesn't have a hierarchy split between different types of chats so we shouldn't assume it.

**Comment by tuscen** [comment]
Though we can ask Telegram to do the same thing as they did with `ChatMember` object, i.e. to split it officialy in the docs.

**Comment by wiz0u** [comment]
Won't fix
