### ISSUE TITLE
Two events are only exposed from bot client

### ISSUE THREAD

**Issue by dahanj95** [TelegramBots/Telegram.Bot#1064]
Installed nuget on .NET 6 console app project, I don't see any other events on `TelegramBotClient` except `OnApiResponseReceived` and `OnMakingApiRequest`. What am I doing wrong? I need to use other events, not these. Thanks.

**Comment by Fedorus** [comment]
You don't need other events. You need https://github.com/TelegramBots/Telegram.Bot.Extensions.Polling

**Comment by dahanj95** [comment]
What do you mean? I'm expecting t o use the `OnMessage` event, what is this extensions?

**Comment by karb0f0s** [comment]
In v17 we removed events and introduced a new way of getting updates:
https://telegrambots.github.io/book/Migration-Guide-to-Version-17.x.html#removal-of-events

**Comment by dahanj95** [comment]
Thanks for the clarification, good day.
