### ISSUE TITLE
Add possibility to make VOIP audio calls via bot

### ISSUE THREAD

**Issue by akshinmustafayev** [TelegramBots/Telegram.Bot#1065]
I would like to request, possibility to make VOIP audio calls via bot

The possible way to achieve that is to read a recording from mp3 or wav file, and stream it like voice to the destination.

**Comment by tuscen** [comment]
Bot API doesn't provide such functionality. Bots can't make calls.

**Comment by akshinmustafayev** [comment]
Thanks for the information
