### ISSUE TITLE
Use .net core Default json option instead of newtonsoft

### ISSUE THREAD

**Issue by salmasi** [TelegramBots/Telegram.Bot#1069]
when use .net core default json option like:
`    services.AddControllers().AddJsonOptions(opts =>
            {
                opts.JsonSerializerOptions.IgnoreNullValues = true;
            });`
get null value in controller parametters in webhook mode
but when change this code to .AddNewtonsoftJson() everything is OK
can i set any option to default json feature to resolve this proplem?

**Comment by karb0f0s** [comment]
@salmasi I am not sure what you mean, but for now our library only supports Newtonsoft Json for serialization/deserialization. ASP.NET Core on the other hand by default uses System.Text.Json for these purposes. 
We are investigating ways to implement STJ support in our library but for now there is no way to use it.

**Comment by karb0f0s** [comment]
duplicate #839
