### ISSUE TITLE
Telegram bot c# download

### ISSUE THREAD

**Issue by Muriths** [TelegramBots/Telegram.Bot#1071]
# I need help.
In you example on github was delete art of download file on telegram bot.
In my dream create bot, and he can claim photo users, and save that on google disk, but users can see this photo or video / download its

**Comment by karb0f0s** [comment]
Please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)
If you want to chat, feel free to join our [discussion group](https://t.me/tgbots_dotnet).
