### ISSUE TITLE
Bot Framework submissions

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#1072]
We can keep track of related Bot Frameworks and accept new submissions in comments to this issue.

| Repository |  |
|:-|-|
|https://github.com/wiz0u/YourEasyBot|[![Star on GitHub](https://img.shields.io/github/stars/wiz0u/YourEasyBot.svg?style=social)](https://github.com/wiz0u/YourEasyBot)|
|https://github.com/TgBotFramework/TgBotFramework|[![Star on GitHub](https://img.shields.io/github/stars/TgBotFramework/TgBotFramework.svg?style=social)](https://github.com/TgBotFramework/TgBotFramework)|
|https://github.com/immmdreza/FlamingoFramework|[![Star on GitHub](https://img.shields.io/github/stars/immmdreza/FlamingoFramework.svg?style=social)](https://github.com/immmdreza/FlamingoFramework)|
|https://github.com/MajMcCloud/TelegramBotFramework|[![Star on GitHub](https://img.shields.io/github/stars/MajMcCloud/TelegramBotFramework.svg?style=social)](https://github.com/MajMcCloud/TelegramBotFramework)|
|https://github.com/TelegramUpdater/TelegramUpdater|[![Star on GitHub](https://img.shields.io/github/stars/TelegramUpdater/TelegramUpdater.svg?style=social)](https://github.com/TelegramUpdater/TelegramUpdater)|

**Comment by wiz0u** [comment]
Move Frameworks list to wiki: https://github.com/TelegramBots/Telegram.Bot/wiki
