### ISSUE TITLE
Add ability to react on messages, potentially in a backward compatible way

### ISSUE THREAD

**Issue by ramonsmits** [TelegramBots/Telegram.Bot#1079]
## I would like to request/propose a feature

I tried to invoke `SendTextMessageAsync` like this:

```c#
SendTextMessageAsync(chatId: chatId, text: "👍", replyToMessageId: replyToMessageId);
```

I was hoping that Telegram would then "react" to a message. Unfortunately, that just will not do a react but post a "reply" message:

![image](https://user-images.githubusercontent.com/152998/163130780-a1f7f730-673b-47d8-b11e-e25e240daf7e.png)

**Comment by karb0f0s** [comment]
This organisation is not related with Telegram in any way. As soon as this feature will be available in Bot API we will implement it in our wrapper library.

**Comment by ramonsmits** [comment]
Thanks @karb0f0s , I thought it was only a limitation in this package. Created https://github.com/tdlib/telegram-bot-api/issues/260

**Comment by tratteo** [comment]
Are there any updates? I see that the issue in the official repository has been completed (https://github.com/tdlib/telegram-bot-api/issues/260) and the reaction API has been implemented. Is there any planning to implement the reaction functionality here too?

**Comment by wiz0u** [comment]
yes, use v21 of the library
https://telegrambots.github.io/book/migrate/Version-21.x.html

**Comment by ramonsmits** [comment]
Yes, I can confirm that it works and its lovely for reporting bot action status
