### ISSUE TITLE
Add support for Telegram Bot test environment

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#1086]
Bot API 6.0 brought us official [test environment](https://core.telegram.org/bots/webapps#using-bots-in-the-test-environment).

The test environment is completely separate from the main environment, so you will need to create a new user account and a new bot with @BotFather.

After receiving your bot token, you can send requests to the Bot API in this format:

`https://api.telegram.org/bot<token>/test/METHOD_NAME`

**Comment by tuscen** [comment]
I think it might be the time to introduce `TelegramBotClientOptions` class and put `bool Test` property there.

**Comment by tuscen** [comment]
Done in #1102
