### ISSUE TITLE
Inlinekeyboard as WebApp type

### ISSUE THREAD

**Issue by mmehdidehghani** [TelegramBots/Telegram.Bot#1097]
There is no inlinekeyboard webapp type. is there any update for that?

**Comment by karb0f0s** [comment]
https://github.com/TelegramBots/Telegram.Bot/search?q=webapp

It's available in prerelease version. Check this out: https://www.nuget.org/packages/Telegram.Bot/18.0.0-alpha.3

**Comment by mmehdidehghani** [comment]
I have been unchecked "include prerelease" in vs  and didn't realize that... thanks a lot.
