### ISSUE TITLE
Use answerWebAppQuery in c#

### ISSUE THREAD

**Issue by mmehdidehghani** [TelegramBots/Telegram.Bot#1098]
How could I use answerWebAppQuery  and SentWebAppMessage in C# console application?
and I don't know how my bot realized that the webapp is closed. :

**Comment by mmehdidehghani** [comment]
if the code be in another language like php, I will find that. could you please help me?

**Comment by tuscen** [comment]
Please, read issue templates before posting. If you have questions regarding library use feel free to join our [support chat](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA)
