### ISSUE TITLE
Incorrect showing amount in invoices on Apple devices

### ISSUE THREAD

**Issue by Monk228** [TelegramBots/Telegram.Bot#1099]
# I found a bug to report

I have a bot on telegram api (.net)

when im sending Invoice in IDR currency to user, on Android/Windows devices currency and amount in invoice show correctly. BUT on apple devices it show incorrect

### Steps to reproduce

Send invoice from api, and specify 27900000 amount and currency is IDR

### Expected  behavior

In apple devices (ios, mac os) it will be 279.000 IDR in invoice

### Actual behavior
But, now, in invoice it will be 27.900.000 IDR in invoice

### Screenshots
on android/windows
![CQqCT](https://user-images.githubusercontent.com/49035634/173002496-c4c38f3a-fd41-4632-925b-14224252e877.png)

on apple devices
![OfJMy](https://user-images.githubusercontent.com/49035634/173002544-83031c8f-5b68-45fc-8e1f-082421fa0805.png)

### Environment data

*.NET Version: 5

*IDE: VS2019

* Telegram.Bot Version : 17.0.0
*  Telegram.Bot.Extensions.Polling Version : 1.0.0

**Comment by Monk228** [comment]
I using BotFather Payment  and Stripe

**Comment by Monk228** [comment]
Well...How i can send this correctly?

**Comment by karb0f0s** [comment]
@Monk228 we are not related to Telegram in any way. This library is a rather simple wrapper around Telegram Bot API.
By the looks of it, you hit a problem with Clent App. You should report an issue to Telegram see (Telegram Support page)[https://telegram.org/faq#telegram-support]. Also, you can try your luck with the official [Bot API repo](https://github.com/tdlib/telegram-bot-api) or [Telegram Core repo](https://github.com/tdlib/td)
