### ISSUE TITLE
Endless loop in IUpdateHandler, HandleErrorAsync

### ISSUE THREAD

**Issue by depler** [TelegramBots/Telegram.Bot#1104]
Here is code sample of IUpdateHandler implementation:

```
public class TelegramHandler : IUpdateHandler
    {
        public async Task HandleUpdateAsync(ITelegramBotClient botClient, Update update, CancellationToken cancellationToken)
        {
            try
            {
                //disable internet connection at this point

                if (update.Type == UpdateType.Message)
                    await botClient.SendTextMessageAsync(update.Message.Chat.Id, "test"); 
            }
            catch { }
        }

        public Task HandleErrorAsync(ITelegramBotClient botClient, Exception exception, CancellationToken cancellationToken)
        {
            //this will be called in endless loop, while internet is off
            Console.WriteLine("error");
            return Task.CompletedTask;
        }
    }
```

Now, do the following:
1. Put breakpoint at line `if (update.Type == UpdateType.Message)`
2. Send message to the bot to hit breakpoint
3. Disable your internet connection
4. Release breakpoint
5. Watch at console output and CPU load 😊

This happens because of call `_botClient.MakeRequestAsync` inside loop:
![image](https://user-images.githubusercontent.com/13541699/144717501-d0b40331-32ee-4664-86dd-d87a29f04531.png)

Which is going to exception handler:
![image](https://user-images.githubusercontent.com/13541699/144717569-ec09b8cc-e805-4da6-9a51-ba9e17d38f9f.png)

Probably some workaround can be done by catching `HttpRequestException` and invoking `Task.Delay(1000)`

**Comment by wiz0u** [comment]
Polling loop in case of error has been changed in v21.3

Comment/reopen if you still see an issue
