### ISSUE TITLE
Stopping a receiving messages when an error occurs

### ISSUE THREAD

**Issue by SijyKijy** [TelegramBots/Telegram.Bot#1107]
When an error occurs in `HandleUpdateAsync` and `HandleErrorAsync` methods, bot stop receiving messages.
Is that how it's supposed to work?

https://github.com/TelegramBots/Telegram.Bot.Extensions.Polling/blob/52c1edf4ff13d97c0b6d5ed8a62631cceadd9210/src/Telegram.Bot.Extensions.Polling/DefaultUpdateReceiver.cs#L99-L115

**Comment by lorenzo93** [comment]
There is a way to automatically restart the bot after an exception? I also have the same problem, but I'm receiving exception because a user has blocked the bot. I don't want to wrap each call to `sendMessageAsync` with a try-catch to avoid interruption, is there another way?

**Comment by karb0f0s** [comment]
#1106

**Comment by mostafafayyaz** [comment]
i have this problem,
my bot stop receiving messages for any problem and after restarting bot , it working fine again.
how i can restart bot automatically when an error occur ?

**Comment by wiz0u** [comment]
This issue was fixed in v21.3
