### ISSUE TITLE
Middleware to validate secret_token

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#1112]
We can ship middleware/extension method to validate [`secret_token`](https://core.telegram.org/bots/api#setwebhook) in ASP.NET Core applications.

> If you'd like to make sure that the webhook was set by you, you can specify secret data in the parameter secret_token. If specified, the request will contain a header “X-Telegram-Bot-Api-Secret-Token” with the secret token as content.

**Comment by wiz0u** [comment]
Some people start reproaching ASP.NET dependencies on our main library
https://github.com/TelegramBots/book/issues/112

So I put this issue on hold as we might more all ASP.NET related code in a separate package in the future

**Comment by wiz0u** [comment]
Why make things complex when it can be solved by adding a single line in the controller:
```csharp
    [HttpPost]
    public async Task<IActionResult> Post([FromBody] Update update)
    {
        if (Request.Headers["X-Telegram-Bot-Api-Secret-Token"] != SecretToken) return Forbid();
        // handle the update
    }
```

see https://github.com/TelegramBots/Telegram.Bot.Examples/blob/master/Webhook.Controllers/Controllers/BotController.cs#L24
