### ISSUE TITLE
Handle multiple requests/response

### ISSUE THREAD

**Issue by hamidreza01** [TelegramBots/Telegram.Bot#1114]
Hello.
I have a problem using the library, and when a few requests are sent to my robot, they queue up and respond one by one.
I want him to respond to all requests at the same time, do you have a solution?

**Comment by tuscen** [comment]
Please, read issue templates before posting. If you have questions regarding library use feel free to join our [support chat](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA)
