### ISSUE TITLE
Custom keyboard - Cant find keyboard button

### ISSUE THREAD

**Issue by sharkyenergy** [TelegramBots/Telegram.Bot#1116]
Hi all!

I am updating a old program that made use of version 10 of this library.

I was able to update everything, apart from this few lines. I dont seme to be able to figure out how to add buttons to a keyboard...

```
       Dim rkm As Types.ReplyMarkups.ReplyKeyboardMarkup

       Dim rkb(numrows - 1)() As Types.KeyboardButton         ***************

       Dim buttonItem As String() = {}
       For i = 0 To numrows - 1 Step 1
               If dtable.Rows.Count >= i + 1 Then
                        Dim row(0) As Types.KeyboardButton                     ***************
                        row(0) = dtable.Rows(i).Item("playername").ToString
                        rkb(i) = row
               End If
       Next

       rkm.Keyboard = rkb
       rkm.OneTimeKeyboard = True

       Await sendMessagewithkb(m.Message.Chat.Id, "Select the proper name!", rkm)
```

any help on this is greatly appreciated!

**Comment by karb0f0s** [comment]
please use issues for bug reporting or feature suggestions. for general discussions consider joining our chat.

you can find working VB example in [this link ](https://t.me/c/1142631927/96561)
