### ISSUE TITLE
Handle Updates with attributes 

### ISSUE THREAD

**Issue by lolpie244** [TelegramBots/Telegram.Bot#1118]
Hi there, can you please add handler for updates with attributes, like it is in ASP.NET endpoints.  E.g.:
```
public class SomeClass
{
    [Command("/start")]
    public async Task StartCommand(ITelegramBotClient client, Update update)
    {
        var message = update.Message;
        await client.SendTextMessageAsync(message.Chat.Id, "Hi user");
    }
}
```

**Comment by karb0f0s** [comment]
We have no plans for this functionality in core library. You can try one of the [frameworks](https://github.com/TelegramBots/Telegram.Bot/issues/1072), based on our library. Some of them already have this functionality.

**Comment by lolpie244** [comment]
ok, thx for answer

**Comment by k0dep** [comment]
Hello @lolpie244 !
I can recommend [BotF](https://github.com/deploy-f/botf).
BotF implemented on Telegram.Bot.
