### ISSUE TITLE
Can't create TelegramBotClient instance because of outdated constructor validation

### ISSUE THREAD

**Issue by yaroslavshparuk** [TelegramBots/Telegram.Bot#1122]
If you try to create a new bot in nowadays you'll get bot id value more than 2^32 and you won't satisfy a condition in 174 line
![image](https://user-images.githubusercontent.com/46866330/183298368-faeb2e71-8ca0-4973-b5da-d06f137fc992.png)

**Comment by karb0f0s** [comment]
Please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)
If you want to chat, feel free to join our [group](https://t.me/tgbots_dotnet).
