### ISSUE TITLE
Bot API 6.2 (August 12, 2022)

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#1127]
# [Bot API 6.2 (August 12, 2022)](https://core.telegram.org/bots/api#august-12-2022)

## Custom Emoji Support

- Added the [MessageEntity](https://core.telegram.org/bots/api#messageentity) type “custom_emoji”.
- Added the field custom_emoji_id to the class [MessageEntity](https://core.telegram.org/bots/api#messageentity) for “custom_emoji” entities.
- Added the method [getCustomEmojiStickers](https://core.telegram.org/bots/api#getcustomemojistickers).
- Added the fields type and custom_emoji_id to the class [Sticker](https://core.telegram.org/bots/api#sticker).
- Added the field sticker_type to the class [StickerSet](https://core.telegram.org/bots/api#stickerset), describing the type of stickers in the set.
- The field contains_masks has been removed from the documentation of the class [StickerSet](https://core.telegram.org/bots/api#stickerset). The field is still returned in the object for backward compatibility, but new bots should use the field sticker_type instead.
- Added the parameter sticker_type to the method [createNewStickerSet](https://core.telegram.org/bots/api#createnewstickerset).
- The parameter contains_masks has been removed from the documentation of the method [createNewStickerSet](https://core.telegram.org/bots/api#createnewstickerset). The parameter will still work for backward compatibility, but new bots should use the parameter sticker_type instead.

## Web App Improvements

- Added the field isClosingConfirmationEnabled and the methods enableClosingConfirmation, disableClosingConfirmation, showPopup, showAlert, showConfirm to the class [WebApp](https://core.telegram.org/bots/webapps#initializing-web-apps).
- Added the field is_premium to the class [WebAppUser](https://core.telegram.org/bots/webapps#webappuser).
- Added the event popupClosed.

## Other Changes

- Added the field has_restricted_voice_and_video_messages to the class [Chat](https://core.telegram.org/bots/api#chat) to support the [new setting](https://telegram.org/blog/custom-emoji#privacy-settings-for-voice-messages).

**Comment by DmitryTrish** [comment]
How to enable Settings Button for web-apps?
According to docs we can ask BotFather to enable it, but there is no option for that.

> You can add a 'Settings' item to the context menu of your Web App using [@BotFather](https://t.me/botfather). When users select this option from the menu, your bot will receive a settingsButtonClicked event.

**Comment by remotenode** [comment]
> How to enable Settings Button for web-apps? According to docs we can ask BotFather to enable it, but there is no option for that.
> 
> > You can add a 'Settings' item to the context menu of your Web App using [@BotFather](https://t.me/botfather). When users select this option from the menu, your bot will receive a settingsButtonClicked event.

Did you find the solution?

**Comment by DmitryTrish** [comment]
Nope :/

Счастья!
Дмитрий.

**Comment by dreka5** [comment]
enableClosingConfirmation  is cool feature, but it would be great if WebView can't be closed when scroll down. 
it is very inconvenient when you scroll down and rest on the top of the page, it starts to decrease.
Plus add oportunity to chose text and lang of message
вот реально было бы круто.   а то не очень удобно и многим не понятно

**Comment by tuscen** [comment]
Resolved by #1147.
