### ISSUE TITLE
Can't send message when using .net 7 with AOT publish set true

### ISSUE THREAD

**Issue by ductai230894** [TelegramBots/Telegram.Bot#1129]
I need your help, I use TelegramBot lib to send message to me, But when I using .net 7 with AOT set true, It allway show error  No parameterless constructor defined for 'Newtonsoft.Json.Serialization.SnakeCaseNamingStrategy'.
This made me can't send msg

**Comment by tuscen** [comment]
This library heavily relies on reflection which is heavily restricted on NativeAOT. We don’t optimize the library for this use case and don’t test.

**Comment by karb0f0s** [comment]
any repro? your project setup, publish command, target platform.. any useful information would be helpful.

**Comment by karb0f0s** [comment]
You can try to disable trimming during publish to keep NewtonSoft's code untouched:
https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-self-contained#publish-with-the-cli

```shell
dotnet publish -r win-x64 -p:PublishTrimmed=false
```

**Comment by ductai230894** [comment]
> any repro? your project setup, publish command, target platform.. any useful information would be helpful.

only test sample telegrambot for send message function, maybe because AOT make error, I will wait some time, thank you

**Comment by ductai230894** [comment]
Can't you replace Json.net in TelegramBot to System.Text.Json in .net core flatform, or anyway to archive this, like asp.net core, I can chose use Json.Net or System.Text.Json

**Comment by karb0f0s** [comment]
Please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)
If you want to chat, feel free to join our [group](https://t.me/tgbots_dotnet).

**Comment by karb0f0s** [comment]
.NET 7 introduced a [breaking change](https://rarbgmirror.org/torrents.php?search=2022&category=44%3B51%3B52&page=1) in trimming assemblies.
> ### Previous behavior
> Previously, only assemblies that were opted-in with `<IsTrimmable>true</IsTrimmable>` in the library project file were trimmed.
> ### New behavior
> Starting in .NET 7, trimming trims all the assemblies in the app by default. Apps that may have previously worked with `PublishTrimmed` may not work in .NET 7. However, only apps with trim warnings will be affected. If your app has no trim warnings, the change in behavior should not cause any adverse affects, and will likely decrease the app size.

> For example, an app that uses `Newtonsoft.Json` or `System.Text.Json` without source generation to serialize and deserialize a type in the user project may have functioned before the change, because types in the user project were fully preserved. However, one or more trim warnings (warning codes `ILxxxx`) would have been present. Now, types in the user project are trimmed, and serialization may fail or produce unexpected results.

> If your app did have trim warnings, you may see changes in behavior or exceptions. For example, an app that uses `Newtonsoft.Json` or `System.Text.Json` without source generation to serialize and deserialize a type in the user project may have functioned before the change, because types in the user project were fully preserved. However, one or more trim warnings (warning codes `ILxxxx`) would have been present. Now, types in the user project are trimmed, and serialization may fail or produce unexpected results.

> ### Recommended action
> The best resolution is to resolve all the trim warnings in your application. To revert to the previous behavior, set the TrimMode property to partial, which is the pre-.NET 7 behavior.
> ```xml
> <TrimMode>partial</TrimMode>
> ```

**Comment by karb0f0s** [comment]
`System.Text.Json` in reflection mode (which is IMO default) would also suffer from this issue. It should be set up with source generated serialization to be compliant with trimming/AOT scenarios.
