### ISSUE TITLE
Ability to get full URL from `File`

### ISSUE THREAD

**Issue by Saalvage** [TelegramBots/Telegram.Bot#1130]
When using `ITelegramBotClient.GetFileAsync` the returned `File` class only contains the `FilePath`. I think the library could be made a bit more user-friendly by providing a way to get the URL to the file directly, probably via an additional property on `File`.

If this is something that you could see being in the library I would happily look into cooking up a PR!

**Comment by Fedorus** [comment]
But it already is... GetInfoAndDownloadFileAsync()

**Comment by Saalvage** [comment]
@Fedorus That is not what I mean. I do not wish to download the file, just get the URL to it in order to forward it to a web application that downloads the file itself. Especially since `GetInfoAndDownloadFileAsync` already constructs the URL needed to download the file it seems weird that we don't have the option to just get the URL directly.

**Comment by karb0f0s** [comment]
Unless you're using a local bot server URL contains a Bot token. It is not secure to send it to 3-rd party app and I don't think we should encourage this intention. But in case you really need it - `BaseFileAddress` is a public property on `TelegramBotClientOptions` class and all you have to do is add `filePath`.

```csharp
var fileUri = $"{_options.BaseFileUrl}/{filePath}";
```
