### ISSUE TITLE
SendDocumentAsync with InputOnlineFile is not working

### ISSUE THREAD

**Issue by ahmetbasdan** [TelegramBots/Telegram.Bot#1131]
it does not send the pdf file I have selected to telegram

![image](https://user-images.githubusercontent.com/18085857/187438962-82c7665b-0443-40ca-9b2a-178d8fe732a5.png)

**Comment by karb0f0s** [comment]
Please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)
If you want to chat, feel free to join our [group](https://t.me/tgbots_dotnet).

**Comment by 4rsa** [comment]
Did you find the solution, because once I updated Telegram.Bot to (19.0.0.0) version I could not use this code anymore.

**Comment by AykutCanturk** [comment]
me too... as if there's no InputOnlineFile a method. I'm stuck. the only way for me to return back older version of telegram.bot.

**Comment by 4rsa** [comment]
Now I just use the following commands: 
async static Task SendVideo(ITelegramBotClient BotClient, Update update, CancellationToken arg3, Message message, string filename)
        {
            try
            {
                using (var videoStream = System.IO.File.OpenRead(@"D:\VideosAPI\Video"))
                {
                    await BotClient.SendVideoAsync(
                        chatId: message.Chat.Id,
                        video: new InputFileStream(videoStream, "video.mp4"), // Use InputFileStream for local files
                        supportsStreaming: true,
                        cancellationToken: arg3
                    );
                }
                Console.WriteLine("Video sent successfully!");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Failed to send the video: {ex.Message}");
            } 
        }.
Bbecause I keep video on my computer.

**Comment by Azizjan-leo** [comment]
So guys there is an abstract class. I used it's InputFile.FromStream(stream, "Points.xlsx") method. All work fine 👯
