### ISSUE TITLE
Bad Request: file is too big

### ISSUE THREAD

**Issue by ductai230894** [TelegramBots/Telegram.Bot#1133]
I want to download file from telegram but when using DownloadFileAsync, it show exception Telegram.Bot.Exceptions.ApiRequestException: Bad Request: file is too big

Anyway to fix it

**Comment by karb0f0s** [comment]
Please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)
If you want to chat, feel free to join our [group](https://t.me/tgbots_dotnet).
