### ISSUE TITLE
Well, guys, i just tried to close instance. 

### ISSUE THREAD

**Issue by spukin123** [TelegramBots/Telegram.Bot#1135]
![MF](https://user-images.githubusercontent.com/101794372/190500370-7eaee14c-dc19-42ec-9d11-395bc53a0083.png)

**Comment by spukin123** [comment]
Have some ideas to help me undestand?

**Comment by karb0f0s** [comment]
Please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)
If you want to chat, feel free to join our [group](https://t.me/tgbots_dotnet).
