### ISSUE TITLE
Bot add reaction to message

### ISSUE THREAD

**Issue by Paffo** [TelegramBots/Telegram.Bot#1136]
Hello,
I'd like to know if its possible for a bot to add reaction to a message.
The way i pictured it is that the bot can receive a command, and instead of replying by message,
can just put a ThumbUp reaction once the task is completed, not to clutter the chat.

Is there any way to do this yet or it's not an available feature?

Thanks

**Comment by tuscen** [comment]
Please, read issue templates before posting. If you have questions regarding library use feel free to join our [support chat](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA)
