### ISSUE TITLE
Why does my bot freeze once i add it to a group chat

### ISSUE THREAD

**Issue by zausenecz** [TelegramBots/Telegram.Bot#1140]
I created the simple IO test code for my bot and it works pretty well... until i add it to a group chat. After that it's just completly frosen. I can create a new bot with the same code and it works good but again after i add it to group chat it became broken.
It just probably something with my code, i am newbye with tg bots stuff. 
```
static void Main(string[] args)
        {
            var client = new TelegramBotClient("5663476931:AAE2lipsUvo6zUYyHPKHEcQl5oxU_UxOI_Y");
            client.StartReceiving(Update, Error);
            Console.ReadLine();
        }

async private static Task Update(ITelegramBotClient bot, Update update, CancellationToken token)
        {
            var message = update.Message;
            if (message.Text != null)
            {
                if (message.Text.ToLower().Contains("test"))
                {
                    //ChatId id = 449873501;
                    await bot.SendTextMessageAsync(message.Chat.Id, "Answer");
                    return;
                }
            }
   
        }
```

**Comment by zausenecz** [comment]
I attached my code, so anyone can simply create a new random bot and replace API key to test the problem

**Comment by karb0f0s** [comment]
Please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)
If you want to chat, feel free to join our [group](https://t.me/tgbots_dotnet).
