### ISSUE TITLE
Sample Source For WinForm App !

### ISSUE THREAD

**Issue by duroqin** [TelegramBots/telegram.bot#116]
Hi Sir,
Sorry , I was searching for a software code for Windows with this library
But all the sample code library for console!
I use the sample code in Windows project but does not work!
If it is possible for you, please give me a sample code for Windows Forms
So that I can get the robot online and I received messages.
Help me please .
Thank you

**Comment by dedo1911** [comment]
It works the same way.
Just replace Console.WriteLine with methods thats allow you to write in your controls (ex: textbox)

**Comment by NimaZare** [comment]
--------------------------------------------
On Fri, 4/8/16, Dario Emerson <notifications@github.com> wrote:

 Subject: Re: [MrRoundRobin/telegram.bot] Sample Source For WinForm App ! (#116)
 To: "MrRoundRobin/telegram.bot" <telegram.bot@noreply.github.com>
 Cc: "Nima" <duroqin@yahoo.com>
 Date: Friday, April 8, 2016, 5:09 PM
 
 It works the same way.
 
 Just replace Console.WriteLine with methods thats allow you
 to write in your controls (ex: textbox)
 --------------------------------------------
Hello sir,
I know that I should replace methods.
But when the token is inserted and the program I run the program does not do anything!
I did not online!
Please give me a sample code to Windows Forms to work properly!
Thank you.

**Comment by mhverbakel** [comment]
Why is this issue reopened?
