### ISSUE TITLE
ForceTemplate feature is not working in topics

### ISSUE THREAD

**Issue by KotM** [TelegramBots/Telegram.Bot#1165]
I'm note sure what is wrong, probably it is Telegram bug, but **ForceTemplate feature is not working in topics**. It works in regular chats, but doesn't display a reply interface in topics.

Not sure, maybe something wrong with my code, could someone take a look the excerpt below?

```
            await botClient.SendTextMessageAsync(
                chatId: message.Chat.Id,
                messageThreadId: message.MessageThreadId,
                replyToMessageId: message.MessageId,
                replyMarkup: new ForceReplyMarkup() { InputFieldPlaceholder = forceRepyTemplate, Selective = true },
                text: text,
                cancellationToken: cancellationToken);
```

That is what I expecting (and what I have) in regular chats:
![photo_2022-12-12_17-31-24](https://user-images.githubusercontent.com/4082879/207057333-d3435d00-ffb7-4895-b1ad-3f8b8e65c5d5.jpg)

And that is what i have in topics: no reply dialog. :(
![photo_2022-12-12_17-31-29](https://user-images.githubusercontent.com/4082879/207057426-f984387d-ca71-46b2-bd62-a537791835b4.jpg)

**Comment by tuscen** [comment]
Have you tried to reproduce the problem manually using raw API calls?

**Comment by KotM** [comment]
Not yet. Btw, can advise how to enable (if possible) debug mode in Telegram.Bots to see raw data transferred to/from the server?

**Comment by tuscen** [comment]
I meant that you should do it manually using something like Postman or Insomnia. And you don't need debug mode, there are two events in the client: `OnMakingApiRequest` and `OnApiResponseReceived` which you can use to see raw requests and responses after and before serialization.
