### ISSUE TITLE
The operation ended prematurely (StartReceiving)

### ISSUE THREAD

**Issue by jmrpineda** [TelegramBots/Telegram.Bot#1191]
# I found a bug to report

Please use the following template to ensure maintainers can reproduce the bug and solve it quickly.

> Bug reports that do not follow this template will be kept closed because [_not-reproducible_](https://github.com/TelegramBots/telegram.bot/labels/not-reproducible) until the creator edits the post properly.

### Steps to reproduce

Test:
```
[Fact]
    public void StartReceivingIssue()
    {
        string _botToken = "any-valid-token";
        TelegramBotClient? _botClient = null;
        TimeSpan _connectionTimeout = new(0, 0, 0, 30, 0);
        CancellationTokenSource? _tokenSource = new();

        _botClient = new(_botToken);
        _botClient.Timeout = _connectionTimeout;

        bool errorHandlerHit = false;

        _botClient.StartReceiving(new DefaultUpdateHandler(
            updateHandler: (ITelegramBotClient botClient, Update update, CancellationToken cancellationToken) => Task.CompletedTask,
            errorHandler: (ITelegramBotClient botClient, Exception exception, CancellationToken cancellationToken) =>
            {
                errorHandlerHit = true;
                return Task.CompletedTask;
            }), null, _tokenSource.Token);

        Task.Delay(40000).Wait();

        errorHandlerHit.Should().BeFalse();
    }
```

### Expected  behavior

No errors

### Actual behavior

Exception:

> Telegram.Bot.Exceptions.RequestException: Request timed out
>  ---> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
>  ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
> 
>  ---> System.TimeoutException: The operation was canceled.
>  ---> System.IO.IOException: The response ended prematurely.
>    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
>    --- End of inner exception stack trace ---
>    --- End of inner exception stack trace ---
>    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
>    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
>    at Telegram.Bot.TelegramBotClient.<MakeRequestAsync>g__SendRequestAsync|21_0[TResponse](HttpClient httpClient, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
>    at Telegram.Bot.TelegramBotClient.<MakeRequestAsync>g__SendRequestAsync|21_0[TResponse](HttpClient httpClient, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
>    at Telegram.Bot.Extensions.Polling.DefaultUpdateReceiver.ReceiveAsync(IUpdateHandler updateHandler, CancellationToken cancellationToken)

### Screenshots

<img width="1320" alt="Screenshot 2023-01-12 at 05 10 28" src="https://user-images.githubusercontent.com/8026507/211974038-fbce93a0-b1ba-4209-b1bc-c9186817ceb9.png">

### Environment data

*NuGet Package Version: 18.0.0

*.NET Version: net 6.0

*IDE: VS for Mac preview (17.5 build 1095)

*App: Any

**Comment by Fedorus** [comment]
Sometimes that happens, because telegram can't answer in time. Thats not a bug

**Comment by jmrpineda** [comment]
> Sometimes that happens, because telegram can't answer in time. Thats not a bug

Ah, ok, thanks mate!!
