### ISSUE TITLE
broken voice message spectrogram

### ISSUE THREAD

**Issue by magrega** [TelegramBots/Telegram.Bot#1198]
# broken voice message spectrogram

### Steps to reproduce
Just try sending any voice message (.ogg file, opus encoder) with sendVoiceAsync() that is longer than 10-15 minutes

` await using Stream stream = System.IO.File.OpenRead(@"C:\Users\magrega\YandexDisk\проги\audio.ogg");
            await client.SendVoiceAsync(
                chatId: message.Chat.Id,
                voice: new InputOnlineFile(stream),
                duration: 1097);`

### Expected behavior
Voice is sent as any other voice message with actual soundwaves

![image](https://user-images.githubusercontent.com/84853777/213902093-e62a4b6f-da5f-4dd2-9962-4a774a7747ba.png)

### Actual behavior
sound spectrogram is flat

### Screenshots

![image](https://user-images.githubusercontent.com/84853777/213902013-4e6a4aeb-4870-4219-b024-30f04e50621c.png)

### Additional info
The voice message works properly except for the broken spectrogram. If clicked with right mouse key and Saved as, then after downloading the audio spectrogram refreshes and is visible. How to refresh it on upload to a chat?

### Environment data

*NuGet Package Version:* 18.0.0

*.NET Version:* .NET 6.0

*IDE:* VS2022

*App:* iOS, Win10

**Comment by magrega** [comment]
Why?--Всего хорошего. 22.01.2023, 12:32, "karb0f0s" ***@***.***>:
Closed #1198 as not planned.

**Comment by karb0f0s** [comment]
We do not control this behaviour. Our library is barely a thin layer over HTTP REST Bot API. You might have better luck with this issue in official [Bot API repo](https://github.com/tdlib/telegram-bot-api/issues?q=is%3Aissue+premium) or failing a bug inside your Telegram application.
