### ISSUE TITLE
Bot API Block User

### ISSUE THREAD

**Issue by hsn-github** [TelegramBots/Telegram.Bot#1203]
## I would like to request/propose a feature

Need a feature to block a user to sending message to bot, it will help to reduce spam and server load

**Comment by karb0f0s** [comment]
Please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)
If you want to chat, feel free to join our [group](https://t.me/tgbots_dotnet).
