### ISSUE TITLE
Escape markup tokens

### ISSUE THREAD

**Issue by gijsbertpieterbrouwer** [TelegramBots/Telegram.Bot#1213]
## I would like to send markupv2 and dont have to worry about escaping markup tokens like;

String escapedMsg = toEscapeMsg
    .replace("_", "\\_")
    .replace("*", "\\*")
    .replace("[", "\\[")
    .replace("`", "\\`");

Without this I get bad requests back ;)

**Comment by karb0f0s** [comment]
Duplicate #1176
