### ISSUE TITLE
Add method GetMessagesAsync

### ISSUE THREAD

**Issue by YakovenkoArtem** [TelegramBots/Telegram.Bot#1230]
## I would like to request/propose a feature

Please add wrap to method https://core.telegram.org/method/channels.getMessages

**Comment by karb0f0s** [comment]
Please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)
If you want to chat, feel free to join our [group](https://t.me/tgbots_dotnet).

**Comment by karb0f0s** [comment]
List of available methods and object for Bot API is available [here](https://core.telegram.org/bots/api).
