### ISSUE TITLE
SendTextMessageAsync entities parameter ignored

### ISSUE THREAD

**Issue by starkdm** [TelegramBots/Telegram.Bot#1236]
Try sending a message with entities parameter. For example like this:

`await BotClient.SendTextMessageAsync(chatId, "Bold Normal", entities: new[] { new MessageEntity() { Length = 4, Offset = 0, Type = Telegram.Bot.Types.Enums.MessageEntityType.Bold } });`

I don't understand if this is a bug or I'm doing something wrong. I'm know about `parseMode` parameter, but I need to resend the user's message keeping the original formatting. It is more convenient to take all entities from the incoming message and simply specify them when sending.

Target framework: .NET Framework 4.8
Telegram.Bot version: 18.0.0

**Comment by tuscen** [comment]
Does it work if you use raw HTTP requests (e.g. using a browser or Postman)?

**Comment by starkdm** [comment]
I looked at the raw request using Fiddler. [Entities field is present there](https://ibb.co/L52cbLW)

**Comment by tuscen** [comment]
That's strange. Its null by default
