### ISSUE TITLE
Can't delete forum topic

### ISSUE THREAD

**Issue by oleksii-mykhniak** [TelegramBots/Telegram.Bot#1252]
# I found a bug to report

### Steps to reproduce

`awaite _telegramBotClient.DeleteForumTopicAsync(ChatId, messageThreadId, cancellationToken);
`
result:
`Bad Request: TOPIC_NOT_MODIFIED
`
*NuGet Package Version:* v19.0.0-preview.4

problem in DeleteForumTopicRequest
```
public DeleteForumTopicRequest(ChatId chatId, int messageThreadId) : base("reopenForumTopic")
    {
        ChatId = chatId;
        MessageThreadId = messageThreadId;
    }
```

**Comment by karb0f0s** [comment]
@oleksii-mykhniak nice one
