### ISSUE TITLE
HandlePollingErrorAsync stop bot

### ISSUE THREAD

**Issue by MansoorJafari9** [TelegramBots/Telegram.Bot#1268]
Hi
When My bot got exception and it catch into HandlePollingErrorAsync my application stopped and I have to re open application
can you help me how can I change my code

`async Task HandlePollingErrorAsync(ITelegramBotClient botClient, Exception exception, CancellationToken cancellationToken)
{
    // Get the line number of the exception
    var lineNumber = new StackTrace(exception, true).GetFrame(0).GetFileLineNumber();

    if (exception is ApiRequestException apiException)
    {
        await botClient.SendTextMessageAsync(3, apiException.Message + $" on line {lineNumber}");
        // handle Telegram API errors
        Console.WriteLine($"Telegram API error occurred: {apiException.Message} on line {lineNumber}");
    }
    else
    {
        await botClient.SendTextMessageAsync(53608103, exception.Message + $" on line {lineNumber}");
        // handle all other errors
        Console.WriteLine($"Error occurred: {exception.Message} on line {lineNumber}");
    }

    // continue polling
    await Task.Delay(1000);
}`

**Comment by tuscen** [comment]
The poller doesn't catch exceptions from your own code. So if you have an exception inside your `HandlePollingErrorAsync` method it won't catch it, you need to ensure that your own code is exception safe. Try using `try/catch` clause.

**Comment by karb0f0s** [comment]
Duplicate for #1106
