### ISSUE TITLE
SendMediaGroup

### ISSUE THREAD

**Issue by zokirjanov** [TelegramBots/Telegram.Bot#1281]
#hello. I have a question
Im using Telegram..Bot lib in my C# WPF app.  everything is ok. i can send messages, photos etc.

But.  I can not send media goup with  url button.  is it possible ??

**Comment by karb0f0s** [comment]
Please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)
If you want to chat, feel free to join our [group](https://t.me/tgbots_dotnet).
