### ISSUE TITLE
ChatMemberLeft works, but join event not works

### ISSUE THREAD

**Issue by UnrealKaraulov** [TelegramBots/Telegram.Bot#1292]
NewChatMembers not working!

only ChatMemberLeft works

please fix it

sorry if english is bad

latest stable nuget .net 7.0 package

**Comment by UnrealKaraulov** [comment]
in 80% times works only ChatMemberLeft event, bot can't handle join event in 80% cases...

**Comment by UnrealKaraulov** [comment]
```
    ReceiverOptions receiverOptions = new()
        {
            AllowedUpdates = new UpdateType[55] 
        };
```

Now works ChatMembersAdded event :)

but with default example (empty array, not working)

please fix it!

**Comment by UnrealKaraulov** [comment]
Keyboard with buttons not showing in 50% times, IsPersistent not working in 100% times

**Comment by Fedorus** [comment]
> ```
> 
>     ReceiverOptions receiverOptions = new()
> 
>         {
> 
>             AllowedUpdates = new UpdateType[55] 
> 
>         };
> 
> ```
> 
> 
> 
> Now works ChatMembersAdded event :)
> 
> 
> 
> but with default example (empty array, not working)
> 
> 
> 
> please fix it!

Thats intentional as per api description this type should be added explicitly. Probably due to the fact that you can get same info as message

**Comment by Fedorus** [comment]
> Keyboard with buttons not showing in 50% times, IsPersistent not working in 100% times

Provide code that reproduces error.

**Comment by UnrealKaraulov** [comment]
> Thats intentional as per api description this type should be added explicitly. Probably due to the fact that you can get same info as message

Please share example with MemberAdded working code, what is need to be added to receiverOptions for MemberAdded works in 100% cases?

**Comment by UnrealKaraulov** [comment]
> > Keyboard with buttons not showing in 50% times, IsPersistent not working in 100% times
> 
> Provide code that reproduces error.

```
  if (update.Message != null && update.Message.NewChatMembers != null)
        {
            foreach (var member in update.Message.NewChatMembers)
            {
                if (member != null)
                {
                        ReplyKeyboardMarkup replyKeyboardMarkup = new(
                            new KeyboardButton[] { TRUE_ANSFER, "This group for spam" })
                        {
                            Selective = true,
                            ResizeKeyboard = true,
                            IsPersistent = true
                        };

                        Message sentMessage = await botClient.SendTextMessageAsync(
                            chatId: update.Message.Chat,
                            text: "For join this channel, enter true ansfer \"" + TRUE_ANSFER + "\" in 30 seconds.",
                            replyMarkup: replyKeyboardMarkup,
                            replyToMessageId: update.Message.MessageId);
```

**Comment by Fedorus** [comment]
why you trying to set reply keyboard to all chat members? )
That event is not reliable in big groups. use:
![image](https://github.com/TelegramBots/Telegram.Bot/assets/4276164/22cd77e3-cc3a-49b5-99a7-7da273663cb4)

**Comment by UnrealKaraulov** [comment]
> why you trying to set reply keyboard to all chat members? ) That event is not reliable in big groups. use: ![image](https://user-images.githubusercontent.com/4276164/258631531-22cd77e3-cc3a-49b5-99a7-7da273663cb4.png)

I don't understand 😭

I used Selective option to add keyboard to every joined user, this is error?

**Comment by Fedorus** [comment]
Let Rider/VS help you =) 
Thats enum, so all values are already there. I think its ChatMember, but I'm too lazy to check

**Comment by UnrealKaraulov** [comment]
@karb0f0s какие несколько месяцев, если не работало три недели назад то как сейчас заработает если не было обновлений?)))

**Comment by karb0f0s** [comment]
We, as authors of REST API wrapper written in C#, do not have any control over Telegram Bot API server behaviour. You can open an issue in official [Telegram Bot API Server repo](https://github.com/tdlib/telegram-bot-api/issues?q=is%3Aissue+multiple+is%3Aopen) or try to add more events by this code snippet:
```csharp
UpdateType[] AllUpdateTypes = Enum.GetValues<UpdateType>()[1..];
```
For further discussions you are welcome to join our [discussion group](https://t.me/+RBst95OLC8JawO2d).
