### ISSUE TITLE
updateHandler is not invoked asynchronously

### ISSUE THREAD

**Issue by dimasik2001** [TelegramBots/Telegram.Bot#1294]
### Steps to reproduce

1. Create `TelegramBotClient` object and call `StartReceiving` 
 `_client.StartReceiving(HandleRequest, Error);`
2. Ensure that the HandleRequest method is declared as asynchronous (`async`).
3. Implement the HandleRequest method to simulate a long asynchronous action:
 ```
 private async Task HandleRequest(ITelegramBotClient botclient, Update update, CancellationToken token)
 {
   var message = update.Message;
   if (message?.Text != null)
     {
        await botclient.SendTextMessageAsync(message.Chat.Id, "processing...");
        await Task.Delay(120000);
        await botclient.SendTextMessageAsync(message.Chat.Id, "completed");
      }
  }
```
4. Send messages to your bot from two different users
### Expected  behavior
I expect to receive the "processing..." message in both users simultaneously  
### Actual behavior
In reality, one of the users receives the "processing..." message only after the other user receives the "completed" message.

### Screenshots
**First user:**
![image](https://github.com/TelegramBots/Telegram.Bot/assets/86479418/184848e2-2e1f-499e-bc7f-446ac12c28fe)
**Second user** (pay attention to time)
![image](https://github.com/TelegramBots/Telegram.Bot/assets/86479418/f144525d-94e2-4cac-a33a-a3f91c17c065)

*NuGet Package Version:* 19.0.0

*.NET Version:* .NET 7

*IDE:* VS2022

*App:* Desktop

**Comment by Fedorus** [comment]
async does not mean parallel. 
Paralleling should be on your side, so you can handle not thread safe operations.

**Comment by ZhangYiQiu** [comment]
Hello, do you have a solution?
I'm having this problem too.
