### ISSUE TITLE
Could we have InputMediaBase inherit from IAlbumInputMedia?

### ISSUE THREAD

**Issue by wiz0u** [TelegramBots/Telegram.Bot#1319]
Only InputMediaAnimation is currently a InputMediaBase that does not inherit IAlbumInputMedia. The other 4 InputMedia* inherit already.

I'm not sure why InputMediaAnimation does not, as GIF can also be added to albums (media group).

![image](https://github.com/TelegramBots/Telegram.Bot/assets/11647984/eeba0681-2e39-4912-9d05-6c3bce2c6f02)

**Comment by tuscen** [comment]
This is probably historical artifact when not every media could be sent in a group

**Comment by tuscen** [comment]
@wiz0u Are you sure you can send an animation in a media group? The documentation say that you can't.

https://core.telegram.org/bots/api#sendmediagroup

**Comment by wiz0u** [comment]
indeed we can't
