### ISSUE TITLE
Release 19.0.1

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#1327]
Is there a way to publish a fix for v19 without a PR from [this branch](https://github.com/TelegramBots/Telegram.Bot/tree/release/19)?

**Comment by karb0f0s** [comment]
Yes. It's our latest stable release and it is reasonable to publish a fixed version. Or go with v20 release.

**Comment by tuscen** [comment]
Right now it’s not possible to do that automatically. I’ll need to change the release pipeline to make it possible
