### ISSUE TITLE
Calling MakeRequestAsync with Stream content more then once results in error

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#1336]
Calling `MakeRequestAsync` with `Stream` content more then once results in error.

`MakeRequestAsync` generates an HttpContent content each time it's called:

https://github.com/TelegramBots/Telegram.Bot/blob/843756aeb5cc8d8b94e30835d8c55ee5e98f2a7b/src/Telegram.Bot/TelegramBotClient.cs#L96

Some reqests contain `InputFileStream` content that forms a multi-part HttpContent with `ToMultipartFormDataContent`. Unerneath it `StreamContent` adds to the `MultipartFormDataContent` which rewinds `Stream` and next call tries to add content from the end of the `Stream`, resulting in empty content.

https://github.com/TelegramBots/Telegram.Bot/blob/843756aeb5cc8d8b94e30835d8c55ee5e98f2a7b/src/Telegram.Bot/Extensions/HttpContentExtensions.cs#L24-L31

**Comment by tuscen** [comment]
Can you make a repro project so I can look into it, please?

**Comment by karb0f0s** [comment]
@tuscen 
https://github.com/karb0f0s/BotClientContentCacheTest

**Comment by wiz0u** [comment]
That was an issue with RetryTelegramBotClient in our Integ test. It's been fixed.

I don't consider this an issue from a user perspective. It's the user's responsibility to rewind their stream if for some reason they want to reuse the same Stream after a request and issue a request again.

They already have the same problem of rewinding their stream when filling a MemoryStream anyway.

It's not our responsibility to consider whether it's adequate to rewind to position 0 (in some case it's not adequate)
