### ISSUE TITLE
Telegram.Bot.dll PUA classification with ESET problem

### ISSUE THREAD

**Issue by bestByteCode** [TelegramBots/Telegram.Bot#1354]
Hi,

I recently encountered an issue where the Telegram.Bot.dll is being flagged as a Potential Unwanted Application (PUA) by ESET's security software. This flagging may affect the user experience and trust in the Telegram.Bot library.

You can see details here.
https://www.virustotal.com/gui/file/e1238a1eb84e0b3f3ed3a7bcc01c90aeec44fa8f1790d02aa1b6cad5383c295e

Could you please look into this matter? It might involve reaching out to ESET for clarification or resolving any security concerns that led to this classification. Your attention to this issue would be greatly appreciated, as it could help ensure the library remains a trusted tool for developers.

**Comment by tuscen** [comment]
@bestByteCode Thanks for your report. I've sent an email to ESET.

**Comment by tuscen** [comment]
Still no answer from ESET, unfortunately

**Comment by tuscen** [comment]
I guess public backlash on social media can push this further like it always does with large companies, but I don't have large social media profiles

**Comment by fbhp** [comment]
Have the same problem with Bitdefender and Telegram.Bot.dll

**Comment by tuscen** [comment]
There's still not much progress, unfortunately. We're working with the Nuget team to find a solution

**Comment by keksikq09** [comment]
Have the same promlem , using .net library for tg bots
![image](https://github.com/TelegramBots/Telegram.Bot/assets/59124816/0ea185f7-0a90-48f4-9901-0534e4d9d813)

**Comment by bairog** [comment]
@tuscen Is there any progress from ESET or Nuget team side?

**Comment by tuscen** [comment]
@bairog No, the issue is still not resolved and we don't know when it will be resolved.

**Comment by bairog** [comment]
@tuscen Do I understand correctly that nugets from alternative feed (https://nuget.voids.site/packages/Telegram.Bot) supports latest API but can be classified as malware by ESET/Bitdefender/etc?

**Comment by tuscen** [comment]
@bairog yes, correct. This feed is currently our main one. I'm trying to create a separate public azure feed for release packages to replace it

**Comment by bairog** [comment]
> I'm trying to create a separate public azure feed for release packages to replace it

But that will not solve the problem of antiviruses false positives . Ok, now I better understand the current situation, thank you.

**Comment by wiz0u** [comment]
No need to keep this issue opened. We're still working on resolving this issue of course, you'll be all informed once PUA classification has been lifted.

See also pinned issue #1375
