### ISSUE TITLE
Receiving messages on azure web job.

### ISSUE THREAD

**Issue by GabrielTK** [TelegramBots/telegram.bot#137]
Good Evening,
In the issue #78, you used the following code as an example for a console app, but how can i do this in a Azure WebJob??

``` c#
static void Main(string[] args)
{
    var Bot = new Api("<Token>");
    Bot.MessageReceived += BotOnMessageReceived;

    // Maybe you like Bot.InlineQueryReceived and Bot.ChosenInlineResultReceived
    // Or receive all events on Bot.UpdateReceived

    Bot.StartReceiving();

    // Press any key to exit
    Console.ReadLine();

    Bot.StopReceiving();
}

private static async void BotOnMessageReceived(object sender, MessageEventArgs messageEventArgs)
{
    var message = messageEventArgs.Message;
    var Bot = (Api)sender;

    // reply to message
}
```

Thank you,
Gabriel

**Comment by MrRoundRobin** [comment]
I have not yet used WebJobs in Azure, so I don't know how they work.

But I would build an Azure API App and use the WebHook method, that's much more performant

**Comment by GeARCraft1** [comment]
Matar a thread or infinito loop can keep the app running

**Comment by eaba** [comment]
StartRecieving calls a method that loops as long as IsRecieving is true

**Comment by mhverbakel** [comment]
If you have the console application, it will run as an Azure WebJob. For more information: https://azure.microsoft.com/en-us/documentation/articles/websites-dotnet-deploy-webjobs/#convert

**Comment by afficionaddo** [comment]
I recently hosted my bot as Azure WebJob using MrRoundRobin library.

Works just fine!

To keep it as a continuous runningjob:
1. You need to either make use of an infinite loop to keep the job running.
2. Change your azure service plan to something else but not 'free'.
