### ISSUE TITLE
GetStickerSetAsync() fails: Required property 'is_animated' not found in JSON

### ISSUE THREAD

**Issue by Majura-fi** [TelegramBots/Telegram.Bot#1376]
# I found a bug to report

Please use the following template to ensure maintainers can reproduce the bug and solve it quickly.

> Bug reports that do not follow this template will be kept closed because [_not-reproducible_](https://github.com/TelegramBots/telegram.bot/labels/not-reproducible) until the creator edits the post properly.

### Steps to reproduce
1. Initialize bot normally.
2. Call `GetStickerSetAsync` to download information about a sticker set.
Example: `StickerSet stickerSet = await _bot.GetStickerSetAsync("rauski", cancellationToken);`
3. An exception should pop up:
```
Telegram.Bot.Exceptions.RequestException: Required properties not found in response
 ---> Newtonsoft.Json.JsonSerializationException: Required property 'is_animated' not found in JSON. Path 'result', line 1, position 34950.
```

### Expected  behavior
The function should return `StickerSet` object that contains Telegram server's response about the sticker set. Worked fine couple months ago.

### Actual behavior
The function cannot find expected/required `is_animated` field from the server's response and fails to parse the answer, causing an JSON parsing exception.

### Screenshots
None

### Environment data

*NuGet Package Version:* v19.0.0 (I guess this means Telegram.Bot package?)
*.NET Version:* .NET 8.0
*IDE:* VS2022 64-bit - v17.8.5
*App:* Windows Console Application

**Comment by t12elveoclock** [comment]
v19.0.0 is not compatible with the latest version of the Telegram bot API. Check out issue #1375 for more info.

**Comment by Majura-fi** [comment]
Alright. I managed to get the latest version via the alternative nuget feed and everything is working again. Thanks for the help. 👍
