### ISSUE TITLE
Required property 'is_animated' not found in JSON

### ISSUE THREAD

**Issue by kzhur** [TelegramBots/Telegram.Bot#1378]
# I found a bug to report
If you try to get a Sticker Set into the variable, then the specified in the title error occurs.
Earlier it worked correctly.

### Steps to reproduce
Just use some code like this:
Task&lt;StickerSet&gt; stickerSet = telegramBotClient.GetStickerSetAsync("RickAndMorty");
stickerSet.Wait();

### Expected  behavior
I was expecting to receive a list of stickers in stickerSet.Result.Stickers

### Actual behavior
System.AggregateException: 'One or more errors occurred. (Required properties not found in response)'
JsonSerializationException: Required property 'is_animated' not found in JSON. Path 'result', line 1, position 18931.

### Screenshots
Not needed

### Environment data
*NuGet Package Version:* 20.0.0-alpha.1 (I tried the nearest others, the problem remains)
*.NET Version:* 6.0
*IDE:* Visual Studio Version 17
*App:* Desktop Windows Forms

**Comment by tuscen** [comment]
This is a breaking change from Bot API, you need to install the latest release, read more on this here https://github.com/TelegramBots/Telegram.Bot/issues/1375

**Comment by kzhur** [comment]
> This is a breaking change from Bot API, you need to install the latest release of the library. Read more on this here #1375.

Oh yes, it worked. Thank you so much!
