### ISSUE TITLE
Error When Sending Video by File ID : "Bad Request: there is no video in the request"

### ISSUE THREAD

**Issue by mehranrasa** [TelegramBots/Telegram.Bot#1380]
**Steps to reproduce**
Send a video using `SendVideoAsync` and capture the `FileId`.

```
var message = await _bot.SendVideoAsync(
    chatId: chatId,
    thumbnail: InputFile.FromStream(thumbnailStream),
    video: InputFile.FromStream(mediaStream, mediaFileName),
    disableNotification: true,
    supportsStreaming: true,
    parseMode: Telegram.Bot.Types.Enums.ParseMode.Html);
```

Attempt to resend the same video using the captured `FileId`.

```
if (!string.IsNullOrEmpty(message.Video?.FileId))
{
  await _bot.SendVideoAsync(
      chatId: chatId,
      video: InputFile.FromFileId(message.Video?.FileId),
      supportsStreaming: true,
      parseMode: Telegram.Bot.Types.Enums.ParseMode.Html);
}
```

**Expected behavior**
The video should be sent successfully using the previously captured `FileId`.

**Actual behavior**
The following error is encountered:

```
Exception: Bad Request: there is no video in the request
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at Telegram.Bot.TelegramBotClientExtensions.SendVideoAsync(ITelegramBotClient botClient, ChatId chatId, InputFile video, Nullable`1 messageThreadId, Nullable`1 duration, Nullable`1 width, Nullable`1 height, InputFile thumbnail, String caption, Nullable`1 parseMode, IEnumerable`1 captionEntities, Nullable`1 hasSpoiler, Nullable`1 supportsStreaming, Nullable`1 disableNotification, Nullable`1 protectContent, Nullable`1 replyToMessageId, Nullable`1 allowSendingWithoutReply, IReplyMarkup replyMarkup, CancellationToken cancellationToken)
```

**Environment data**

- NuGet Package: 19.0.0
- .NET Core: 8.0
- Running on Docker
- Webhooks used
- Communicates with a [Telegram Local Bot API Server](https://core.telegram.org/bots/api#using-a-local-bot-api-server) by passing `baseUrl` to `TelegramBotClientOptions` constructor.

**Comment by tuscen** [comment]
Please, follow the issue template when filling bug reports. What version of the library are you using, which runtime, etc.

**Comment by mehranrasa** [comment]
> Please, follow the issue template when filling bug reports. What version of the library you are using, which runtime, etc.

I've edited my issue to include the required information following the issue template. Please review it now. Thank you!

**Comment by tuscen** [comment]
Do you have the same issue without using local bot server?

**Comment by mehranrasa** [comment]
> Do you have the same issue without using local bot server?

Yes, the problem still exists even without using local api server.

**Comment by mehranrasa** [comment]
I was wondering if there will be any updates soon? this part of my project is currently on hold as I prefer not to use alternative solutions.

**Comment by tuscen** [comment]
@mehranrasa Sorry, I'm a bit bussy currently. I'll try to look this weekend. Could you attach both thumbnail and video file if you can so I can debug it?

**Comment by mehranrasa** [comment]
> @mehranrasa Sorry, I'm a bit bussy currently. I'll try to look this weekend. Could you attach both thumbnail and video file if you can so I can debug it?

I hope you're doing well. I wanted to add that this issue affects all methods involving `InputFile`, including `SendAudioAsync`. For now, I've managed to fix it with the following solution:

```
public async Task<(string? fileId, string errorDetails)> SendAudioAsync(
    long chatId,
    FileStream stream,
    string fileName,
    string title,
    string performer,
    string caption,
    Stream? thumbnailStream = null)
{
    var url = $"{TelegramBaseUrl}/bot{token}/sendAudio";
    if (localMode)
        url = $"{LocalBaseUrl}/bot{token}/sendAudio";

    var content = new MultipartFormDataContent
    {
        { new StringContent(chatId.ToString()), "chat_id" },
        { new StreamContent(stream), "audio", fileName },
        { new StringContent(title), "title" },
        { new StringContent(performer), "performer" },
        { new StringContent(caption), "caption" },
        { new StringContent("HTML"), "parse_mode" }
    };

    if (thumbnailStream != null)
    {
        var thumbnailContent = new StreamContent(thumbnailStream);
        content.Add(thumbnailContent, "thumb", "thumbnail.jpg");
    }

    try
    {
        var response = await _httpClient.PostAsync(url, content);
        var responseString = await response.Content.ReadAsStringAsync();
        var responseJson = JObject.Parse(responseString);

        var fileId = responseJson["ok"]?.Value<bool>() == true
            ? responseJson["result"]?["audio"]?["file_id"]?.ToString()
            : null;
        var errorDetails = responseJson["description"]?.Value<string>() ?? string.Empty;

        return (fileId, errorDetails);
    }
    catch (Exception e)
    {
        return (null, e.Message);
    }
}
```

**Comment by wiz0u** [comment]
I tested your exact code (without Local Bot API server).
Cannot reproduce. The second video is sent correctly.

So likely a problem on your side, not in the library.

If you want to reopen this issue, please provide a minimal Console project, based on recent version of the library (v21.*)
