### ISSUE TITLE
Does the SendGameAsync function support seamless Telegram login?

### ISSUE THREAD

**Issue by bianandgan** [TelegramBots/Telegram.Bot#1396]
When I call ‘SendGameAsync’, I am unable to use seamless telegram login. The Url in loginUrl in the replyMarkup parameter cannot receive user information. However, it works if I use ‘SendTextMessageAsync’. Is this a bug?

var loginUrl = new LoginUrl()
{
    Url = "https://temple.index.html",
    ForwardText = "We need you access",
    BotUsername = "@bot",
    RequestWriteAccess = true,
};
var playButton = InlineKeyboardButton.WithLoginUrl("Play", loginUrl);
playButton.CallbackGame = new CallbackGame();
await bot.SendGameAsync(msg.Chat.Id, "gameshortname", replyMarkup: markUp);

**Comment by wiz0u** [comment]
I think your question is more about the usage of Telegram Bot API, rather than a bug in the library (we just implement the Bot API methods as they are designed by Telegram teams)

I recommend you ask this question in the https://t.me/BotTalk group

**Comment by bianandgan** [comment]
Thank you
