### ISSUE TITLE
getupdates missing message

### ISSUE THREAD

**Issue by sanwuping** [TelegramBots/Telegram.Bot#1415]
# I have a question or need help
Hello, I used your framework to write a program to get group messages, but the program will lose a certain message in rare cases. Although the probability of this happening is very small, I can't find the reason. Can you help me? ?
![photo_2024-08-29_13-33-27](https://github.com/user-attachments/assets/b341fb68-ee27-434f-8070-aceebe4260e6)

**Comment by wiz0u** [comment]
Likely a bug in your code. And you're using a very old version of the library.

Github issue is not for providing support on your own code.
And I see you asked the same question in our support group already 🙄

**Comment by sanwuping** [comment]
thank you
