### ISSUE TITLE
Missing Classes and Serialization Issues with SendPaidMediaRequest in Telegram.Bot v19.0.0

### ISSUE THREAD

**Issue by bencharpit** [TelegramBots/Telegram.Bot#1416]
Hi,

I've encountered a issue while working with the SendPaidMediaRequest class in the Telegram.Bot library, specifically version 19.0.0 from NuGet. (using .NET 8)

The main problem arises from the absence of the InputPaidMediaTypeConverter class, which is referenced in the InputPaidMediaType enum. This missing converter seems crucial for the proper serialization of InputPaidMediaType, and its absence is causing requests to be sent with an empty body. Consequently, this leads to a "Bad Request: parameter 'media' is required" error from the Telegram API.

In addition to this, several other essential classes, such as CustomJsonDerivedTypeAttribute, CustomJsonPolymorphicAttribute, IBusinessConnectable, InputPaidMedia, and others required for the proper functioning of SendPaidMediaRequest, are also missing from the NuGet package. I had to manually add these classes to my project to even attempt to use the feature.

Given these issues, it seems that either the implementation of SendPaidMediaRequest is incomplete in the current package, or some crucial components were omitted from the release.

Could you please look into this and provide the missing classes or offer guidance on how to properly implement SendPaidMediaRequest?

**Comment by wiz0u** [comment]
Migrate to v21.*
https://telegrambots.github.io/book/migrate/Version-21.x.html
Read it all and carefully.
