### ISSUE TITLE
When I install version 21.2.0 or newer I get Error NETSDK1082 then the project crashes.

### ISSUE THREAD

**Issue by ru-talion** [TelegramBots/Telegram.Bot#1417]
# I found a bug to report

1) I created a project using a standard template BlazorWebAssembly. I use Raider.

`<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="7.0.17"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="7.0.17" PrivateAssets="all"/>
        <PackageReference Include="Telegram.Bot" Version="21.10.1" />
    </ItemGroup>

</Project>
`

2) Installed Telegram.Bot Version="21.10.1".

3) The project is broken.

![image](https://github.com/user-attachments/assets/50c5314c-50bf-4f68-895c-a06bd9208dd1)

JetBrains Rider 2024.1.1
Build #RD-241.14494.325, built on April 16, 2024
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
.NET Core v8.0.1 x64 (Server GC)

Windows 11 Pro 23H2 29.‎12.‎2023 22631.4112
Windows Feature Experience Pack 1000.22700.1034.0

**Comment by wiz0u** [comment]
Have you even searched about that error NETSDK1082 before opening this issue, or you're just lazy and expecting us to do that for you?
A quick Google search brings up this page:
https://stackoverflow.com/questions/70220739/blazor-client-error-netsdk1082-browser-wasm
which is exactly what you describe.

The answer gives you the explanation: Telegram.Bot package is likely incompatible with WebAssembly

And indeed, if you had looked at our open issues (it's not like we have hundred of these 😏) before opening this one, you would see we have currently an open issue for AOT/Trimming compatibility (#1322), which is a prerequisite for a package to be compatible with Blazor WebAssembly
