### ISSUE TITLE
message_id bind as 0

### ISSUE THREAD

**Issue by uranio-235** [TelegramBots/Telegram.Bot#1419]
While binding the update body, message_id is set to 0. Allways

![image](https://github.com/user-attachments/assets/96bd3b11-916d-4acb-be24-c482ab1bb746)

![image](https://github.com/user-attachments/assets/c6263aac-962c-49d1-8e03-7c390f7ab77a)

**Comment by wiz0u** [comment]
did you configure your webapp according to https://telegrambots.github.io/book/3/updates/webhook.html ?

**Comment by sajjadmilani** [comment]
I have the same issue, and it seems that **[JsonPropertyName("message_id")]**  is missing from the **MessageId** property, causing deserialization problems.

**Comment by wiz0u** [comment]
did you configure your webapp according to https://telegrambots.github.io/book/3/updates/webhook.html ?

**Comment by sajjadmilani** [comment]
Here is how I get the POST request:

![image](https://github.com/user-attachments/assets/3cc0a14a-8a99-40c0-ab33-3523d0f7fc13)

All other values are correct except for MessageId

**Comment by wiz0u** [comment]
did you configure your webapp according to https://telegrambots.github.io/book/3/updates/webhook.html ?

**Comment by sajjadmilani** [comment]
Yes

**Comment by wiz0u** [comment]
Which version of the library are you using ?

**Comment by sajjadmilani** [comment]
Latest stable 19.0.0

**Comment by wiz0u** [comment]
Documentation is for stable versions v21.* (not available on Nuget)
You need to upgrade. See https://telegrambots.github.io/book/index.html#-installation for more info

**Comment by uranio-235** [comment]
> did you configure your webapp according to https://telegrambots.github.io/book/3/updates/webhook.html ?

has you tried the example code?

**Comment by uranio-235** [comment]
> I have the same issue, and it seems that **[JsonPropertyName("message_id")]** is missing from the **MessageId** property, causing deserialization problems.

good catch!
