### ISSUE TITLE
V21.6.0 and higher doesn't work

### ISSUE THREAD

**Issue by Simplifier** [TelegramBots/Telegram.Bot#1420]
This library doesn't work at all since v21.6.0 for some reason. Rider just shows all the library classes and namespaces in red.

![Monosnap StepikTelegramBots – Program cs 2024-09-0](https://github.com/user-attachments/assets/c58a700f-509f-4eb3-b7e8-a6add6a14987)

And when I'm trying to run it I get the error: 
Program.cs(1, 7): [CS0246] The type or namespace name 'Telegram' could not be found (are you missing a using directive or an assembly reference?)

But when I install version 21.5.0, for example, the same program runs perfectly fine

**Comment by wiz0u** [comment]
Weird. Can you share your csproj ?

**Comment by wiz0u** [comment]
Make sure to "`dotnet restore`" nuget packages for 21.6 so your IDE can analyze the downloaded package

**Comment by Simplifier** [comment]
> Make sure to "`dotnet restore`" your solution in order to download nuget package 21.6 so your IDE can analyze/build correctly

No, it doesn't help, unfortunately =(

**Comment by wiz0u** [comment]
try with latest v21.11 ?

**Comment by Simplifier** [comment]
Yes, I've tried many versions, including 21.11. And all higher than 21.5 don't work =\

**Comment by wiz0u** [comment]
make sure you have a nuget.config file in the project folder [as shown here](https://telegrambots.github.io/book/index.html#-installation)
and try ```dotnet build . -v d > build.log```
if you can't see what's the problem from the build.log file, you can post it here for analysis.

**Comment by Simplifier** [comment]
Oops, wait, it seems I got something mixed up, and v21.11, unlike the previous ones, actually works. Thanks!

**Comment by wiz0u** [comment]
Still weird, but if it solves your problem, you may close the issue
