### ISSUE TITLE
AllowSendingWithoutReply isn't being sent when set to `false`

### ISSUE THREAD

**Issue by Dubzer** [TelegramBots/Telegram.Bot#1421]
# I found a bug to report

### Steps to reproduce

```cs
client.OnMessage += async (message, _) =>
{
    await Task.Delay(TimeSpan.FromSeconds(3));
    await client.SendTextMessageAsync(message.Chat, "hi!", replyParameters: new()
    {
        MessageId = message.MessageId,
        AllowSendingWithoutReply = false
    });
};
```
Then send a message to any chat and remove it before 3 seconds delay. The message "hi!" will be sent without a reply

### Actual behavior
The request from the repro does not contain allow_sending_without_reply:

<img width="286" alt="image" src="https://github.com/user-attachments/assets/c6798431-c33e-4ffa-9721-2850bf749de9">

If you set parameter to `true`, then it will be passed in the request:

<img width="286" alt="image" src="https://github.com/user-attachments/assets/d959edb9-cbeb-4615-929b-d205ade07d2d">

I think this bug can be fixed by making the`AllowSendingWithoutReply` field a nullable type

### Environment data

*NuGet Package Version:* 21.10.1

*.NET Version:* .NET 8

**Comment by wiz0u** [comment]
That's normal. All optional boolean fields have a default meaning of `false` if unspecified for Bot API so they are not transmitted if false.
