### ISSUE TITLE
Callback query is null in webhook request body

### ISSUE THREAD

**Issue by vardasov-langate** [TelegramBots/Telegram.Bot#1424]
# Callback Query deserialisation problem

There is a problem during deserialisation Callback query param in Update.
Text messages and other message types work fine.

### Steps to reproduce

1. Setup Telegram bot with ASPNET Core webhook updates processing.
2. Make sure you configure `ConfigureTelegramBot<Microsoft.AspNetCore.Http.Json.JsonOptions>(opt => opt.SerializerOptions)` during app configuration.
3. Use InlineKeyboardMarkup as text input. 
`var inlineMarkup = new InlineKeyboardMarkup().AddButton("1.1", "11");`
`await client.SendTextMessageAsync(chatId, "A message with an inline keyboard markup", replyMarkup: inlineMarkup);`
4. Press on button item in Telegram client to generate Query callback.
5. Observe update request body.

### Expected  behavior

Callback Query is deserialised.

### Actual behavior

Callback Query is null.

### Screenshots

![image](https://github.com/user-attachments/assets/44d6dcfd-203c-4a4a-8802-84723849d5e3)

### Environment data

*NuGet Package Version:* 21.11.0

*.NET Version:* 8.0.101

*IDE:* Rider 2024.2.4

*App:* AspNet Core Web App

**Comment by wiz0u** [comment]
if you're using Controllers, you didn't use the correct line for configuring Json.
See https://telegrambots.github.io/book/3/updates/webhook.html#aspnet-core-with-controllers-mvc

**Comment by vardasov-langate** [comment]
I am silly. Sorry, the issue is resolved.
