### ISSUE TITLE
Username value should be Identifier or Username that starts with @

### ISSUE THREAD

**Issue by Skyseb** [TelegramBots/Telegram.Bot#1426]
I Need help. 

C# visual estudio Community v17.9.6
Telegram Bot version: 21.7.1.0 (lastest nuget package manager)

in this code:

var ReOpt = new ReceiverOptions { AllowedUpdates = { } };

while (true)
{
    try
    {
        await botClient.ReceiveAsync(OnMessage, ErrorMessage, ReOpt, canceltoken);
    }
    catch (Exception ex)
    {
        Console.WriteLine("Error StartReceiver: " + ex.ToString());
        await Task.Delay(1000);
    }

}

Sometimes:

Error StartReceiver: System.ArgumentException: Username value should be Identifier or Username that starts with @
Parameter name: username
   at Telegram.Bot.Types.ChatId..ctor(String username) in /_/src/Telegram.Bot/Types/ChatId.cs:line 54
   at Telegram.Bot.Types.ChatId.op_Implicit(String username) in /_/src/Telegram.Bot/Types/ChatId.cs:line 101

What could be generating this error?

Is it possible to replicate it by configuring a user's profile?

**Comment by wiz0u** [comment]
You're not showing the full stacktrace.
Error is likely in your code (OnMessage, ErrorMessage..)

Note: Last version is v21.11

**Comment by Skyseb** [comment]
OMG. how I didn't realize. It's in ErrorMessage.. 

 public async Task ErrorMessage(ITelegramBotClient botClient, Exception e, CancellationToken cancellation)
 {
     if (e is ApiRequestException apiRequestException) {
         await botClient.SendTextMessageAsync("", e.Message.ToString());
     }

 }

Sorry, and thanks for helpme.
