### ISSUE TITLE
Ability to use JsonStringEnumConverter included in System.Text.Json

### ISSUE THREAD

**Issue by saneks222** [TelegramBots/Telegram.Bot#1428]
I think the use of this:
 https://github.com/TelegramBots/Telegram.Bot/blob/master/src/Telegram.Bot/Serialization/EnumConverter.cs 
 seems redundant to me. 

Wouldn't this be a better solution ? 

`Public class JsonStringEnumSnakeCaseLowerConverter(): JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower);`

usage

`[JsonConverter(typeof(JsonStringEnumSnakeCaseLowerConverter))]`

**Comment by wiz0u** [comment]
In fact I did considered it, and wrote exactly that line.

But then I had to switch back to this EnumConverter code due to different behaviour in case of invalid/unrecognized value (ours returns 0, theirs throw an exception)

**Comment by wiz0u** [comment]
Note that our EnumConverter code is largely inspired by JsonStringEnumConverter implementation, in order to be short and efficient, and has been tested to be compatible with Native AOT/Trimming.
