### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by tbatabar** [TelegramBots/telegram.bot#143]
hi MrRoundRobin;

i found a problem in StartReceiving method.

when i create new instance of Api class and invoke the StartReceiving method, that is works correctly. but, when the internet connection broken for 1 second, my application was crashed. and that is Receive's method fault :D

i think u should to remove filter exception in try and catch blocks and change the ApiRequestException parameter to Exception in catch block.

thanks for u'r attention.

**Comment by mhverbakel** [comment]
Why don't you put the `StartReceiving` in a try-catch block, check that you indeed don't need to undertake action after the thrown exception and then retry by putting all of that in a while loop? There might be people out there that are using the exception thrown.

**Comment by MrRoundRobin** [comment]
@mhverbakel `StartReceiving` isn't throwing exceptions. the exceptions which occur during Receiving will be emit the [`OnReceiveError`](https://mrroundrobin.github.io/telegram.bot/html/E_Telegram_Bot_TelegramBotClient_OnReceiveError.htm) event

**Comment by mhverbakel** [comment]
Then how does this crash the application?

**Comment by irji** [comment]
I've got the same problem. Any ideas how to solve it?

**Comment by mhverbakel** [comment]
Hello all,

For me, it is still unclear what the problem is exactly. Could someone expand on what is going wrong, and how you notice the problem?

Kind regards,
Martijn

**Comment by irji** [comment]
Hi @mhverbakel 

The problem here is that bot is crashing if PC lost connection to internet.

I'm trying to run the bot example (Telegram.Bot.Examples.Echo). If my PC connected to internet then everything is fine. But if it's disconnected then bot is crashing with error System.Net.Http.HttpRequestException.

How to get it (step-by-step):
1) run example
2) check that bot is online
3) disconnect from internet
4) get exception

**Comment by CristianT** [comment]
The crash is normal with the current code as the general exceptions are not being catched in the receiving function.

I created a pull request with a possible solution:
https://github.com/MrRoundRobin/telegram.bot/pull/217

I hope it can be merged into the base code. In the meanwhile you have two options, either catch everything in [AppDomain.UnhandledException](https://msdn.microsoft.com/en-us/library/system.appdomain.unhandledexception(v=vs.110).aspx) or use the [branch I created](https://github.com/CristianT/telegram.bot/tree/OnReceiveGeneralErrorException).

**Comment by CristianT** [comment]
Actually after some investigation I concluded that it is not possible to catch exceptions that happen in a separate thread.
With AppDomain.UnhandledException you can just log it, so I guess the code has to be resolved in the library itself.

**Comment by irji** [comment]
@CristianT 
Thanks for your solution. But it still not work in my app. I've add aditional empty catch in ReceiveAsync method as a quik fix.

**Comment by Olfi01** [comment]
i believe this issue is solved with #217, is it not? it could be closed then
