### ISSUE TITLE
Add breaking change mention about ASP.NET Core Runtime to Migrate to v21.* guide

### ISSUE THREAD

**Issue by SoulsideJourney** [TelegramBots/Telegram.Bot#1433]
Since v21 it was added "Microsoft.Extensions.Options.ConfigurationsExtensions" dependency that requieres ASP.NET Core Runtime for work, and migration guides contains no mentions about it.
#1432 related

**Comment by wiz0u** [comment]
done.
https://telegrambots.github.io/book/migrate/Version-21.x.html
