### ISSUE TITLE
MessageId should be of type long

### ISSUE THREAD

**Issue by ddemarines** [TelegramBots/Telegram.Bot#1434]
[As per documentation](https://core.telegram.org/bots/api#animation), while the documentation always refers as integers everywhere, they really means to use longs (64 bits) instead of c# integers (32 bits).

![image](https://github.com/user-attachments/assets/aece9b17-899e-4cce-833f-b47444e4070e)

It would be nice if you can change the messageId from int to long.

Thanks in advance.

**Comment by wiz0u** [comment]
No. Message IDs are 32-bit integer.
https://core.telegram.org/constructor/message#parameters
