### ISSUE TITLE
I receive unexpected entities

### ISSUE THREAD

**Issue by LeeeJoe** [TelegramBots/Telegram.Bot#1438]
I found a bug to report

When I send large text messages (1500 characters or more) I get unexpected entities in the entity values ​​that are attached to the message.
Please check this situation.
Thank you.

Code is very simple:
```
            return await bot.SendMessage(
                chatId: message.Chat.Id,
                text: text,
                replyParameters: null,
                replyMarkup: null);
```
*NuGet Package Version:* 22.0.2
*.NET Version:* 9.0
*IDE:* VS2022
*App:* Desktop

**Comment by wiz0u** [comment]
Please send such large message to @JsonDumpBot and post the result here, and explain what's wrong.
Alternatively if you don't want to make it public, you can send me the result in private [@wiz0u](t.me/wiz0u)

**Comment by LeeeJoe** [comment]
Solved

**Comment by wiz0u** [comment]
as discussed, what you witness was Telegram automatically creating URL entities when your message text contains some URL links
