### ISSUE TITLE
<msg>.Text null when receiving a document.

### ISSUE THREAD

**Issue by TheHellTower** [TelegramBots/Telegram.Bot#1439]
# I found a bug to report

### Steps to reproduce
Handle any text message with a document

### Expected  behavior
Give the text if any along with the document

### Actual behavior
Text stays null

### Screenshots
![WindowsTerminal_MrFxT3IfLk](https://github.com/user-attachments/assets/171caacc-b202-4e82-b269-a14f491a2869)
![devenv_mwBWnLj2rP](https://github.com/user-attachments/assets/f7c96ad4-9204-4808-838f-b55b0f5329a6)

### Environment data

*NuGet Package Version*: 22.1.0

*.NET Version*: Core 9.0

*IDE*: VS 2022 Preview

*App*: Desktop

**Comment by wiz0u** [comment]
lol, your example code literally says "if msg.Text is null, print the type and an empty line"

anyway, to answer your question: `msg.Text` is only used when receiving a purely text message.
For any other media message, the text is in `msg.Caption`

**Comment by TheHellTower** [comment]
> lol, your example code literally says "if msg.Text is null, print the type and an empty line"
> 
> anyway, to answer your question: `msg.Text` is only used when receiving a purely text message. For any other media message, the text is in `msg.Caption`

Hello, this is based on [an official example](https://github.com/TelegramBots/Telegram.Bot.Examples/blob/master/Console/Program.cs#L32) but thank you it worked !
