### ISSUE TITLE
SavePreparedInlineMessage returns 404 due to incorrect methodName

### ISSUE THREAD

**Issue by mikko-tribo** [TelegramBots/Telegram.Bot#1441]
This code is wrong `RequestBase<PreparedInlineMessage>("savePreparedMessage")`

The parameter should be "savePreparedInlineMessage" as found here https://core.telegram.org/bots/api#savepreparedinlinemessage

### Steps to reproduce

Use the function botClient.SavePreparedInlineMessage

### Expected  behavior

Message is saved

### Actual behavior

Error 404

**Comment by wiz0u** [comment]
thx
