### ISSUE TITLE
Bot Webhook and JsonSerializerContext

### ISSUE THREAD

**Issue by rozamin-info** [TelegramBots/Telegram.Bot#1444]
## Not Sure if This is a Bug or Feature Request

I am using the `Telegram.Bot` NuGet package to create a bot with webhook support. To optimize serialization and deserialization, I implemented a `JsonSerializerContext` to generate the necessary source code. However, after updating to version `22.1.2`, I encountered the following errors:

```
The name 'PaidMedia' does not exist in the current context
The name 'ReactionType' does not exist in the current context
```

Previously, I was using version `19.0.0`, and I believe these fields are new additions to the `Telegram.Bot.Types.Update` class.

I noticed that these types (`PaidMedia` and `ReactionType`) are `abstract class` definitions and are configured with the `CustomJsonDerivedType` attribute. While I’m not entirely sure what the issue is, I suspect it could be related to the source generator for the `JsonSerializerContext`, which may not be able to handle these polymorphic types correctly.

As a result, I’m unable to upgrade to the latest version of `Telegram.Bot`.

Could you please advise on how to resolve this issue? Below are the relevant details about these classes:

### ReactionType:
```
[JsonConverter(typeof(PolymorphicJsonConverter<ReactionType>))]
[CustomJsonPolymorphic("type")]
[CustomJsonDerivedType(typeof(ReactionTypeEmoji), "emoji")]
[CustomJsonDerivedType(typeof(ReactionTypeCustomEmoji), "custom_emoji")]
[CustomJsonDerivedType(typeof(ReactionTypePaid), "paid")]
public abstract class ReactionType,...
```

### PaidMedia:
```
[JsonConverter(typeof(PolymorphicJsonConverter<PaidMedia>))]
[CustomJsonPolymorphic("type")]
[CustomJsonDerivedType(typeof(PaidMediaPreview), "preview")]
[CustomJsonDerivedType(typeof(PaidMediaPhoto), "photo")]
[CustomJsonDerivedType(typeof(PaidMediaVideo), "video")]
public abstract class PaidMedia,...
```

**Comment by wiz0u** [comment]
I don't see why PaidMedia and ReactionType would be any different from other abstract classes in the library like BackgroundFill for example.

In any case, you're trying to put the cart before the horse
We already have issue #1322 to support Json source generation for AOT/Trimming.
I will look at these problems when I'm working on that issue.

For now, Json serialization with reflection should work just fast enough already.
