### ISSUE TITLE
User join in group via Shareable Chat Folders

### ISSUE THREAD

**Issue by ImportVoid** [TelegramBots/Telegram.Bot#1445]
If group member join to group - i am get event "update"
if user join with **shareable Chat Folders**, group dont get anounce, bot does not receive any events(update) (breakpoint does not work on HandleUpdate)
Some bot developers solve this problem by receiving the connection event via https://core.telegram.org/bots/api#chatmemberupdated
Why "chatmemberupdated" is this necessary? because of this error telegram spammers using folders with chats enter chats and remain invisible, due to the lack of events
If it's possible, need support "ChatMemberUpdated" event

**Comment by wiz0u** [comment]
ChatMemberUpdated (update.ChatMember) is already supported.

https://telegrambots.github.io/book/FAQ.html#18-how-to-receive-chatmember-updates

**Comment by wiz0u** [comment]
(this library is independent from Telegram teams)

**Comment by wiz0u** [comment]
see also https://telegrambots.github.io/book/2/chats.html#detecting-new-group-members-and-changed-member-status

**Comment by ImportVoid** [comment]
> ChatMemberUpdated (update.ChatMember) is already supported.
> 
> https://telegrambots.github.io/book/FAQ.html#18-how-to-receive-chatmember-updates

Thank you
I am a newbie and tried to read your documentation first but was not attentive enough
Sorry for wasting your time, thanks for the links
