### ISSUE TITLE
Api.SendWebRequest on mono

### ISSUE THREAD

**Issue by agamanyuk** [TelegramBots/telegram.bot#145]
Get the following error when call _GetMe_ method on mono.

System.MissingFieldException: Field 'Telegram.Bot.Api/<SendWebRequest>d__78`1<T_REF>.<>4__this' not found.
  at Telegram.Bot.Api.GetMe () <0x4109b260 + 0x00023> in <filename unknown>:0

Maybe we should get duplicate the methods and have not async ones for mono comparability?

**Comment by MrRoundRobin** [comment]
according to the [mono docs](http://www.mono-project.com/docs/about-mono/compatibility/) it's supports async. is this not the case?

**Comment by agamanyuk** [comment]
It should. It'd be great if you try to run it with mono

**Comment by dedo1911** [comment]
Works perfectly on mono for me.

**Comment by mhverbakel** [comment]
Unable to reproduce. Close?

**Comment by dedo1911** [comment]
I've used both async and not methods, and both works on my mono installation.

@agamanyuk if you could specify framework target version and mono version that would be helpful. thanks

**Comment by pouladpld** [comment]
@agamanyuk If the problem is not fixed, tell us more and please use [issue template](https://github.com/TelegramBots/telegram.bot/blob/develop/ISSUE_TEMPLATE.md).
