### ISSUE TITLE
Voice calls

### ISSUE THREAD

**Issue by Ldanel** [TelegramBots/Telegram.Bot#1450]
I would like to check the option to have api for voice calls (not recorded voice message).

Same voice calls like in the app.

![image](https://github.com/user-attachments/assets/78ae20ae-1ca8-4101-a815-ff1c7f0edbd1)

**Comment by wiz0u** [comment]
This feature is not available in [Bot API](https://core.telegram.org/bots/api)
(and we are not from Telegram teams so we can't add features)
