### ISSUE TITLE
Message_text error in inline mode

### ISSUE THREAD

**Issue by koroteeww** [TelegramBots/telegram.bot#182]
Hello! I've tried to realise inline mode to my bot, but Telegram sends me an error, something like "no message_text field". I assume it is that I am sending InlineQueryResultArticle with some text and urls for user, so InlineQueryResultNew should have field message_text.
see https://core.telegram.org/bots/api#inputtextmessagecontent
and after I added it in InlineQueryResultNew like this:
[JsonProperty("message_text", Required = Required.Always)]
public string MessageText { get; set; }

Inline mode works perfectly and no more errors. 
so consider changing InlineQueryResultNew.cs
if you need detailed error text, i think i can provide it...

**Comment by MrRoundRobin** [comment]
have you used the [`InputMessageContent`](https://mrroundrobin.github.io/telegram.bot/html/P_Telegram_Bot_Types_InlineQueryResults_InlineQueryResult_InputMessageContent.htm) property on [`InlineQueryResultArticle`](https://mrroundrobin.github.io/telegram.bot/html/T_Telegram_Bot_Types_InlineQueryResults_InlineQueryResultArticle.htm)?

**Comment by MrRoundRobin** [comment]
you can also look at the comments [here](https://github.com/MrRoundRobin/telegram.bot.examples/blob/master/Telegram.Bot.Examples.Echo/Program.cs#L51-L62)

**Comment by koroteeww** [comment]
I used InlineQueryResultArticle

**Comment by MrRoundRobin** [comment]
the important part is that you need to specify `InputMessageContent`, that is what is send by the user, if he selects a result
