### ISSUE TITLE
Can't get profile photo of the group

### ISSUE THREAD

**Issue by armanforghani** [TelegramBots/telegram.bot#201]
I am wondering that how can I get the profile photo for a group?

**Comment by Olfi01** [comment]
That hasn't been possible for a long time, but now, using the newest beta version of Telegram.Bot you can call
```c#
var task = bot.GetChatAsync(chatId);
task.Wait()
```
and from the result get thechat photo's file ids, for example
```c#
task.Result.Photo.BigFileId
```
or
```c#
task.Result.Photo.SmallFileId
```
