### ISSUE TITLE
Non ASCII file name

### ISSUE THREAD

**Issue by armanforghani** [TelegramBots/telegram.bot#204]
Sending a file with a non-ascii filename is successful, but the filename displayed on the recipient's app is not human-readable stuff, e.g. '%EA%B0%80%EB%82%98%EB%8B%A4.txt.

Please see https://github.com/nickoala/telepot/issues/32

**Comment by wizzard2010** [comment]
I join to this issue. When I send file with russian filename on telegram I see something like this:
=?utf8?B?0JLQsNGIINCx0LjQu9C10Ylg0L3QsCDQv9C0LnBkZg==?=
I guess it is uft-8 encoding for email attachment.
With FileName and FileNameMask fields. One in Base64 encoding and one in utf-8.
Can you help with this error?

**Comment by pouladpld** [comment]
@armanforghani 
I have fixed this issue and included the fix in `.Core` package for the time being.
<https://www.nuget.org/packages/Telegram.Bot.Core/13.2.1>
