### ISSUE TITLE
is it posible use switch_inline_query for sharing in channel

### ISSUE THREAD

**Issue by javadmjt** [TelegramBots/telegram.bot#210]
Can switch_inline_query option use to  send messaging in  channel for sharing?

tnx

**Comment by Olfi01** [comment]
of course, why didn't you just try lol?

**Comment by van4oza** [comment]
since bot api 3.0 - no

Inline keyboards with switch_inline_query and switch_inline_query_current_chat can no longer be sent to channels because they are useless there.

https://core.telegram.org/bots/apiajsdfkadjsfkadjsfkjadsl
