### ISSUE TITLE
send photo in reply of pressing inline keyboard button

### ISSUE THREAD

**Issue by soheilrt** [TelegramBots/telegram.bot#221]
@MrRoundRobin Hi 
How can I send a photo in reply of pressing inline keyboard button?

**Comment by Olfi01** [comment]
you have to subscribe to the OnCallbackQueryReceived event.
your button should be created like this:
`var button = new InlineKeyboardButton(message, callbackData)`
keep in mind you will need the string you use for yourCallbackData (literally anything you want) in the event method, like this:
`public void Client_OnCallbackQueryReceived(object sender, CallbackQueryReceivedEventArgs e)
{
if (e.CallbackQuery.Data == yourCallbackData) Client.SendPhotoAsync(/*parameter stuff*/);
}`
