### ISSUE TITLE
inlineKeyboardButton that takes full width of the row

### ISSUE THREAD

**Issue by navidsharif** [TelegramBots/telegram.bot#222]
I've been trying to work out how to use InlineKeyboardMarkup[]  instead of InlineKeyboardMarkup[][] in the given example, but it throws exception, can anyone provide me an example of how to use it ?
or rather, what i want to do is create a inlineKeyboardButton that takes full width of the row not just a portion of it.

**Comment by MohammadKhani** [comment]
hi 
Navid
you can use this code for show inline KeyBoard(telegram.bot version 9.0.0.0 )
            InlineKeyboardButton[][] testInlinekeyBoard = new InlineKeyboardButton[2][];
            testInlinekeyBoard[0] = new InlineKeyboardButton[1];
            testInlinekeyBoard[0][0] = new InlineKeyboardButton("View Text", "Call Back data");

            testInlinekeyBoard[1] = new InlineKeyboardButton[2];
            testInlinekeyBoard[1][0] = new InlineKeyboardButton("View Text", "Call Back data");
            testInlinekeyBoard[1][1] = new InlineKeyboardButton("View Text", "Call Back data");

            InlineKeyboardMarkup keyboardInlineMarkUp = new InlineKeyboardMarkup();
           keyboardInlineMarkUp.InlineKeyboard = testInlinekeyBoard;

await bot.SendTextMessage(chatid, "test Inline KeyBoard", false, false, 0, keyboardInlineMarkUp, ParseMode.Default);

**Comment by cave25** [comment]
hi
can you show me how to get the callback data from the inline keyboard?

**Comment by pouladpld** [comment]
@cave25 
<https://github.com/TelegramBots/telegram.bot/blob/develop/test/Telegram.Bot.Tests.Integ/CallbackQuery/CallbackQueryTests.cs#L35-L49>
