### ISSUE TITLE
System.Net.Http.UnsupportedMediaTypeException

### ISSUE THREAD

**Issue by SeregaSpaceApp** [TelegramBots/telegram.bot#231]
Sometimes bot stops to response, and in log is the error:

```
Telegram.Bot.Exceptions.ApiRequestException: Invalid response received ---> System.Net.Http.UnsupportedMediaTypeException: No MediaTypeFormatter is available to read an object of type 'ApiResponse`1' from content with media type 'text/html'.
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, Type type, IEnumerable`1 formatters, IFormatterLogger formatterLogger, CancellationToken cancellationToken)
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, IEnumerable`1 formatters, CancellationToken cancellationToken)
   at System.Net.Http.HttpContentExtensions.ReadAsAsync[T](HttpContent content, CancellationToken cancellationToken)
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__139`1.MoveNext()
   --- End of inner exception stack trace ---
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Telegram.Bot.TelegramBotClient.<ReceiveAsync>d__68.MoveNext()
```

So it seems that Telegram server returns the answer that library can not parse. Is it possible to output the server response that causes this problem?

**Comment by a-a-k** [comment]
Very actually! I have this problem too.

**Comment by CristianT** [comment]
Errors happen sometimes while waiting a reply from the server, it would be good to log the data sent by the server when that happens to reproduce it for your specific case.

In my code I do a stop, a delay and a start. As far as I know I've never lost a message send by the user:

```
this.bot.OnReceiveError += (sender, args) => this.HandleError(args.ApiRequestException, args.ApiRequestException.ErrorCode);

private async void HandleError(Exception ex, int error)
{
            if (error != 408)
            {
                // Only delay if there was no timeout
                await Task.Delay(this.retryConnectionTime);
            }

            this.bot.StartReceiving();
}

```

Notice that if there is a network disconnection probably your application crashes, as described here #143 
And solved here #217 waiting for a merge to master.

**Comment by mhverbakel** [comment]
Are there steps to reproduce this issue?

Kind regards,
Martijn Verbakel

**Comment by SeregaSpaceApp** [comment]
CristianT, yes, it would be good to log the response from server, bur question was how to do that. Where are located these data in ApiRequestException? What property if the exception object should I log?

**Comment by CristianT** [comment]
If you can compile and use the binaries from this branch:
https://github.com/CristianT/telegram.bot/tree/ParametersLog

Or use the binary I compiled: https://www.dropbox.com/s/6ah1r59qardwbgk/Telegram.Bot.zip?dl=0

When you run it, a file "telegramBot.log" will be written in the working directory with information about parameters where I think is the issue. That may help finding the problem.

**Comment by SeregaSpaceApp** [comment]
CristianT, bot that uses this compiled version of library crashes with exception "Object reference not set to an instance of an object." at line
`var me = Bot.GetMeAsync().Result;`

**Comment by CristianT** [comment]
If you could debug the code to know what is happening it would be great.
Otherwise we need some defined steps to reproduce the issue (the original one) more accurately so we can know what is happening.

**Comment by SeregaSpaceApp** [comment]
The original issue happens seldom (and in release version published on server). And to understand its cause I must to see response of server.
About your branch. I can't compile the code on my computer because of C# versions diffrence. But as I can see, there are no null-checks for 'parameters', and I think there is the cause of "Object reference not set to an instance of an object." exception.

**Comment by CristianT** [comment]
OK, I tried to correct the binary, haven't tested it though:
https://www.dropbox.com/s/37u86x4bcuewll5/Telegram.Bot.zip?dl=0

**Comment by SeregaSpaceApp** [comment]
In each send request log is created anew. Old info will be lost :(
Also, has it sense to log parameters at begin of each request process? As I said, the original error happens seldom (one time in several days) and log will be very long.

**Comment by CristianT** [comment]
ok this time I had some time to test it:
https://www.dropbox.com/s/x1b1v27h3cnmnqm/Telegram.Bot.zip?dl=0

if you want to catch the error there are not a lot of options, at least I don't know where the problem is.
The file should only log data sent so depending on the volume of your bot it may not be that much.
If you catch the error and post the relevant lines of the file here, may be someone could help you

**Comment by SeregaSpaceApp** [comment]
I've recompiled the library from source with my logging and now i'm waiting that error happens in log. When I have new information, I'll post it here.
