### ISSUE TITLE
Error system.net.httprequestexception after a while!

### ISSUE THREAD

**Issue by soheilrt** [TelegramBots/telegram.bot#236]
![2016-09-23 1](https://cloud.githubusercontent.com/assets/17524113/18797780/79f6b3ea-81dc-11e6-88fc-8243c4cecc53.png)
👆👆👆
a got this error after couple hour?
How can I fix this?

@MrRoundRobin

**Comment by MrRoundRobin** [comment]
@soheilrt This looks like an DNS error. Can you check that? 
Does this error occur regularly?

**Comment by spoofi** [comment]
Hello! Your server can't resolve host api.telegram.org.
Problem on the side of your server (looks like DNS problem). You need to check your network settings and make sure that the server will resolve the host.

**Comment by soheilrt** [comment]
@MrRoundRobin yes it occurs at least once a day!

I'm running Bot on VPS and my DNS server set to 
213.186.33.99
and 
4.2.2.4

is there any way to handle this error?

**Comment by spoofi** [comment]
@soheilrt you primary dns can't resolve api.telegram.org, but secondary works fine. Try this command on you VPS:
``` nslookup api.telegram.org ```

**Comment by MrRoundRobin** [comment]
@soheilrt The root cause with the DNS is out of scope of the library. You could add the host name to your hosts file but I wouldn't suggest this. 

On the library side there could help an retry algorithm. This is on my road map but currently I have no time to implement it.

**Comment by soheilrt** [comment]
@spoofi
![ca2pture](https://cloud.githubusercontent.com/assets/17524113/18798731/c3e7ed44-81e0-11e6-8a09-750cffa8af88.PNG)
its ok!
this error occurs after a couple hour of running program!

**Comment by CristianT** [comment]
What version of the library are you using?

In 9.0 the problem was that the error was crashing the hosting application and there was no way to catch the exception.
In the current version of the library 10.4 you can get the exceptions with the event OnReceiveGeneralError and decide what to do with it, typically retry after a delay if it was a connection loss.

**Comment by soheilrt** [comment]
@CristianT I'm sorry.Which library do you mean?
