### ISSUE TITLE
Game Support

### ISSUE THREAD

**Issue by MrRoundRobin** [TelegramBots/telegram.bot#240]
See https://core.telegram.org/bots/api#games

**Comment by MHaendel** [comment]
Could you add sample code?

**Comment by MrRoundRobin** [comment]
@MHaendel not at the moment, maybe later today, sorry

**Comment by MHaendel** [comment]
Its not that urgent, but as its lacking documentations it would be nice to have some code. For example, how to set the game url.

**Comment by Arrow891** [comment]
Hey , could you at least tell us how to set the game url?
