### ISSUE TITLE
getUpdates is good for develop?

### ISSUE THREAD

**Issue by nabeghe** [TelegramBots/telegram.bot#245]
Hi
if i using `getUpdates` method for develop a windows software is good or bad?
and then running app on vps

**Comment by matiuspico** [comment]
hi,
By using getUpdates, you will use more resources from your server (Hots, vps,...). Also you should setup and configure your IIS and write lots of algorithms to handle your code. I will suggest you to use WebHook if you want to have a real-time and professional bot with high performance.

**Comment by mhverbakel** [comment]
Hello nabeghe,

This mostly depends on personal preference. I prefer building my bot
against webhooks, and then deploying them to a (free) Azure website, which
will automatically be booted (in ~10 seconds) when someone talks to the bot.

Kind regards,
Martijn Verbakel

**Comment by LightVolk** [comment]
@mhverbakel , my question about hosting on Azure: if i use webhook at bot: the CPU time utilized only when bot calculate answer?

**Comment by mhverbakel** [comment]
You pay for the time that the VM behind the website is up, which is as long as your application is deployed. So even when the website goes to sleep, you are still paying for it.
