### ISSUE TITLE
Upload File and Video with Large Size

### ISSUE THREAD

**Issue by mostafahtsm** [TelegramBots/telegram.bot#247]
Hi,
I try to upload large video or file but fail after 100 seconds. why this happen? 
because I want send large video or file to Telegram Channel.
Thanks,

**Comment by MrRoundRobin** [comment]
Default [`UploadTimeout`](https://mrroundrobin.github.io/telegram.bot/html/P_Telegram_Bot_ITelegramBotClient_UploadTimeout.htm) is 1 minute. you can increase this.

i'll increase the default this when i release a new version. planed this earlier but forgot it

**Comment by mostafahtsm** [comment]
Hi,
I set  UploadTimeout  to 1 hour but my problem is still.
here my code:

     void Main()
    {
     Task.Run(() => PollMessage());
    }

   public async Task<bool> PollMessage()
   {
     TimeSpan ts = new TimeSpan(1,1,1);
            
     Telegram.Bot.TelegramBotClient TelCh = new Telegram.Bot.TelegramBotClient("MyToken");
     TelCh.UploadTimeout = ts;

     await TelCh.SendPhotoAsync("@kanazspid", new Telegram.Bot.Types.FileToSend("C:\\nahaei.png", File.OpenRead("C:\\nahaei.png")), "", false, 0, null);
            return true;
        }

**Comment by MrRoundRobin** [comment]
so how does it fail? is there an exception?

**Comment by mostafahtsm** [comment]
Yes. it fail after 60 seconds or 100 seconds even I set UploadTimeout to 1 hour. in fact I cannot upload large video or file to channel.

**Comment by MrRoundRobin** [comment]
so **how** does it fail? is there an exception?

**Comment by mostafahtsm** [comment]
it fail after 60 seconds or 100 seconds even I set UploadTimeout to 1 hour. Why does happen this?

**Comment by MrRoundRobin** [comment]
please, can you provide an exception if there is any?

**Comment by mostafahtsm** [comment]
Unfortunately, the program remains in the run mode, and it will not be uploaded. I do not even have time to give a message.
Consider this line of code:

     Telegram.Bot.Types.Message xxx=  await TelCh.SendPhotoAsync("@kanazspid", new  Telegram.Bot.Types.FileToSend("C:\\nahaei.png", File.OpenRead("C:\\nahaei.png")), "", false, 0, null);

xxx variable is never returned.

**Comment by MrRoundRobin** [comment]
okay, so this helps.

it could be because you set the file **path** note the **name** in `FileToSend`.

can you test this:

```csharp
Telegram.Bot.Types.Message xxx=  await TelCh.SendPhotoAsync("@kanazspid", new  Telegram.Bot.Types.FileToSend("nahaei.png", File.OpenRead("C:\\nahaei.png")));
```

**Comment by mostafahtsm** [comment]
Yes. Now Test it.

**Comment by mostafahtsm** [comment]
I test your solution but again after 1 min 40 sec fail.
Please help.

**Comment by MrRoundRobin** [comment]
you can try to look 'on the wire' if the request is successful send an what answer comes back from telegram. to do this you cloud use [Fiddler](http://www.telerik.com/fiddler) for example.

at the moment i can't test it by myself. so if fiddler is to complicated you need to wait a bit

**Comment by mhverbakel** [comment]
Can you share the file you are trying to send? I might find some time to figure this out.

Kind regards,

Martijn Verbakel

**Comment by mostafahtsm** [comment]
Yes. My file is here. of course Due to the speed of the Internet, it fail after 100 seconds and Upload remains incomplete.
[bimesarbazi.pdf](https://github.com/MrRoundRobin/telegram.bot/files/541977/bimesarbazi.pdf)

**Comment by farazp** [comment]
Hi I used new ver but I don't find Telegram.Bot.Types.FileToSend any body can help me?
How to send larg size file more then 100MB?

**Comment by poulad** [comment]
@farazp 

Telegram Bot API has a limit on the file size.

https://core.telegram.org/bots/api#sending-files

Please join our group chat on Telegram if you have any questions.
