### ISSUE TITLE
How to send emoji in SendPhotoAsync()

### ISSUE THREAD

**Issue by A-Programmer** [TelegramBots/telegram.bot#248]
Hello.
I want to send emoji in SendPhotoAsync() can you help me?
please give me this code, i tested anything but i can not send still.

**Comment by matiuspico** [comment]
Hi, 
To send Emoji no need that you use SendPhotoAsync().  you can use SendTextMessageAsync() and pass the Unicode of Emoji as message text. 
Also you can fine the complete Emoji Unicode Table here -> 
http://apps.timwhitlock.info/emoji/tables/unicode

**Comment by A-Programmer** [comment]
Thank you but doesn work.
this is my code : 
token.SendTextMessageAsync("MyChanell Id",
                "U+1F601", true, true, 0, null, ParseMode.Html);

**Comment by a-a-k** [comment]
Try to use "U0001F601" instead of your emoji's code. IntelliSense will remark it to you.

**Comment by mhverbakel** [comment]
Hello,

Search for "C# escape unicode", that should help. It's something like `\u1060`.

Kind regards,
Martijn Verbakel

**Comment by a-a-k** [comment]
Try to use "\U0001F601" instead of your emoji's code. IntelliSense will remark it to you.

**Comment by A-Programmer** [comment]
I used your suggestions but dont work!
For changing unicodes to emoji i use this function :
static string DecodeEncodedNonAsciiCharacters(string value)
        {
            return Regex.Replace(
                value,
                @"\\u(?<Value>[a-zA-Z0-9]{4})",
                m =>
                {
                    return ((char)int.Parse(m.Groups["Value"].Value, NumberStyles.HexNumber)).ToString();
                });
        }
But still no result.
Here is a list of emoji codes : http://apps.timwhitlock.info/emoji/tables/unicode

**Comment by A-Programmer** [comment]
It worked, first list is wrong as i see, because second list works fine with this function.

**Comment by MTare** [comment]
Hi,
you said second list worked,
but i can't find out which list worked?
can you send an example?
thanks in advance

**Comment by mhverbakel** [comment]
I think he is referring to this list: http://apps.timwhitlock.info/emoji/tables/unicode

Which are then used as "My message \U000**1F601**" for sending.

**Comment by MTare** [comment]
Thanks for your help,
but when i send "My message \U0001F601" as input to DecodeEncodedNonAsciiCharacters method, 
I receive Parsing Error so I've change the method like this:
static string DecodeEncodedNonAsciiCharacters2(string value)
        {
            return Regex.Replace(
            value,
            @"\\u(?<Value>[a-zA-Z0-9]{4})",
            m =>
            {
                return ((char)int.Parse(m.Groups["Value"].Value, NumberStyles.HexNumber )).ToString();
            });
        }
So this worked with that input,
Any way Thank you.

**Comment by majid23** [comment]
You can find emoji code point list in https://emojipedia.org/telegram
for example for Grinning Face With Smiling Eyes we use code point "U+1F601" this is "0x1F601"
now for send text use below code:
await Api.SendTextMessageAsync(message.Chat.Id, char.ConvertFromUtf32(0x1F601));

**Comment by pouladpld** [comment]
You can just write emojis in a string.

```c#
client.SendTextMessageAsync(chatId, "😄");
```

If you are running Windows 10, [enable its _touch keyboard_](http://www.techradar.com/how-to/software/operating-systems/how-to-make-the-most-out-of-the-windows-10-touch-keyboard-1307508) and type emojis using that.

**Comment by Coderwill** [comment]
That's amazing answer it's work for me i want to send emoji on telegram bot using c# and i am visit this page i got my answer thanks a lot..
