### ISSUE TITLE
ArgumentOutOfRangeException Error in GetUpdate handler

### ISSUE THREAD

**Issue by Ramin-Bateni** [TelegramBots/telegram.bot#264]
I wrote a desktop app for a bot and it use **`GetUpdate`** but recently i see the bellow error in my `GetUpdate` handler method:

**`e.Update.Type' threw an exception of type 'System.ArgumentOutOfRangeException`**

![image](https://cloud.githubusercontent.com/assets/9051320/20561947/63624dbc-b196-11e6-9201-e582731105bd.png)
**What do you think about this?**

### Environment data

*NuGet Package Version:* (Telegram.Bot 10.4.0)
*.NET Version:* (4.5)
*IDE:* (VS2015)
*App:* (Desktop)

**Comment by mhverbakel** [comment]
I think this issue was caused by channel updates, which is resolved in #261. If you need it, consider to update to the beta package using `Install-Package Telegram.Bot -Pre`.

Kind regards,
Martijn Verbakel

**Comment by Ramin-Bateni** [comment]
Thank you @mhverbakel for your reply. It solved the problem. Do you know any way to prevent receive this update type from the channels that the bot is one of its admins?
