### ISSUE TITLE
Unable to connect to remote server

### ISSUE THREAD

**Issue by Ramin-Bateni** [TelegramBots/telegram.bot#265]
My bot desktop app **works** on my windows (8.1 64bit) but it **dose not work** on another window (8.1 64bit) !! When it want to send any message to a user (for example sending a simple text message to a chat id).

For example my app give me the error for each bellow lines of code:

```
await Bot.SetWebhookAsync("");
await bot.SendTextMessageAsync(chat_id, messageText);
```

**Error message:**

![image](https://cloud.githubusercontent.com/assets/9051320/20569108/2401e394-b1b4-11e6-872e-b490232891f9.png)

**I tried:**

- Check the internet
- Create a telegram bot API command as a link and test it in Firefox on the target windows and it works fine (i get correct message to the expected chatId)

- Run the app as administrator

### Environment data

*NuGet Package Version:* (10.3.1  or 11.1.0)

*.NET Version:* (4.5)

*IDE:* (VS2015)

*App:* (Desktop)

**Comment by matiuspico** [comment]
hi, 
would you please explain more? Do you want use webhook? do you want to set your pc as the webhook's server? or you want to use a host as your server? also please provide complete code. 
thanks

**Comment by Ramin-Bateni** [comment]
Hi, 
No i just want send a simple text by my app to reply a meeasge to the bot user after he/she send me a message and i get it in `GetUpdate` handler method
and
**My app work well on my PC!**

**But** when i test it on **another windows (my laptop),** it give me the error. I confused because i checked internet and used Run as administrator but it give me the error every where in my app that i wrote a line of code to send a request to telegram server!!

**For example** it works until inside the `GetUpdate `handler method and it receive the bot messages well! but when it want fire a line of code like this: `await bot.SendTextMessageAsync(chat_id, messageText);`
to replay to the user, it raise an error with this message:  **Unable to connect to remote server**.

I emphasize that my windows application work very well on my pc but it give me error when i run it on my laptop (another window).

Also i coped every files and `DLL`s (include `Telegram.Bot.dll`) in the bin project to the target window.
