### ISSUE TITLE
 InlineKeyboardButton.SwitchInlineQuery 

### ISSUE THREAD

**Issue by haniehnaseri** [TelegramBots/telegram.bot#271]
hi
example to use InlineKeyboardButton.SwitchInlineQuery for open chat and insert the bot's username in input  field similar @sticker

**Comment by Olfi01** [comment]
```c#
InlineKeyboardButton button = new InlineKeyboardButton("Press this")
            {
                SwitchInlineQuery = "yourquery",
                CallbackData = null
            };
            bot.SendTextMessageAsync(chatId, "Your message here", 
                replyMarkup: new InlineKeyboardMarkup(new InlineKeyboardButton[] { button })).Wait();
```

**Comment by Olfi01** [comment]
for some reason or another, you have to set CallbackData to null right now, I'm gonna look into that

**Comment by Olfi01** [comment]
Okay, seems like in the current version it won't be possible to fix that but for the newer versions I have created #391
