### ISSUE TITLE
My console app is running, but BotOnMessageReceived is not triggered and there is no error.

### ISSUE THREAD

**Issue by arlennav** [TelegramBots/telegram.bot#279]
### Steps to reproduce
The console app is running with no error but seems my client bot does not talk to my console bot application. It was working before. I did not make any changes.

### Environment data

*IDE:* (e.g. VS2015, VS Code, etc.)
VS2015

**Comment by matiuspico** [comment]
HI, 
Please provide your question with your code.

**Comment by 0xCA** [comment]
Got same problem after adding bot as administrator to the channel and publishing a post.
Current version of this lib **does not support channel_post and crash at it**.
What you can do is manually set *MessageOffset* to value of *update_id* (Get updates json with curl, for example) **after channel message**. After that everything will work as it did before.

Devs, please, fix this.

I'm new to GitHub, should I open a new issue?..

**Comment by MrRoundRobin** [comment]
@0xCA you cen try the beta, should be fixed there

**Comment by 0xCA** [comment]
@MrRoundRobin It's definitely fixed, it handles private messages after channel posts and vice versa.

**Comment by codehaks** [comment]
It's not possible to read channel posts yet?

I tried pre-release version and it works when there is a channel post but you can not see the message.
