### ISSUE TITLE
System.ArgumentOutOfRangeException on Post Method WebHook

### ISSUE THREAD

**Issue by oshinyil** [TelegramBots/telegram.bot#289]
### Steps to reproduce
Call Post method in WebHook controller.

### Expected  behavior
JSON request is serialized to Update object.

### Actual behavior
I got this error:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Telegram.Bot.Types.Update.get_Type()

### Environment data
`{
"update_id": 539698167,
"message": {
"message_id": 18,
"from": {
"id": 187812218,
"first_name": "Tane Yoroshi",
"username": "oshinyil"
},
"chat": {
"id": 187812218,
"first_name": "Tane Yoroshi",
"username": "oshinyil",
"type": "private"
},
"date": 1484231648,
"text": "test"
}
}`

*NuGet Package Version:* 10.4.0

*.NET Version:* .NET Core 1.0.1

*IDE:* VS2015

*App:* Desktop

**Comment by mhverbakel** [comment]
Should have parsed a `Message` property, and therefore [Update.get_Type()](https://github.com/MrRoundRobin/telegram.bot/blob/master/src/Telegram.Bot/Types/Update.cs#L78) should have responded with the correct type. Can you check if the `Message` property is not null?

**Comment by khashei** [comment]
The is the main issue with the 10.0.4. Is there any solution to that?

**Comment by DmitryZubelevich** [comment]
WebHook is not working for asp.net core 1.1 for bot version 10.4.0

**Comment by DmitryZubelevich** [comment]
As I can see from history, this bug was fixed in this commit: https://github.com/MrRoundRobin/telegram.bot/commit/a55f7dd66e0fa2be0edb5adeedbaa93ba60d31e9#diff-7221efa4e959074d92f89c74261dcc1a

But there is no Nuget package update. Does anyone knows when there will be new nugget package version release?
