### ISSUE TITLE
Member Status

### ISSUE THREAD

**Issue by Nazari76** [TelegramBots/telegram.bot#291]
Hi
Plase Help me For  Status Member Join Or Left in SuperGroup
 if (msg.Type == MessageType.ServiceMessage)
                {
                if(ChatMemberStatus.Left ==?????)
                }
Help me
i need Send message  welcome or left for members
tnx much

**Comment by mhverbakel** [comment]
@MrRoundRobin This is a question. Can you give me rights to add labels to an issue?

**Comment by MrRoundRobin** [comment]
@mhverbakel i think that's not possible with my private account?

**Comment by mhverbakel** [comment]
I think that this guide shows how to do this: https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/

**Comment by kogalino** [comment]
Hi @Nazari76,
please see my answer here https://github.com/MrRoundRobin/telegram.bot/issues/308#issuecomment-303453280, it explains how to check for member join or left.

If a user joins, the property `new_chat_member` of the ServiceMessage is available. Same for leaving members, the property `left_chat_member` is filled. You get one message for each joining or leaving member.

Hope that helps.
