### ISSUE TITLE
How to get EntityValues from EntityType in Entities in Message Class

### ISSUE THREAD

**Issue by behiunforgiven** [TelegramBots/telegram.bot#298]
I want to handle data in OnCallbackQueryReceived event with more than one data passed (e.g one hashtag and one emeil) in a query and some data in another querey (e.g a code).

Now this is the question: how can I get EntityValues of Message via it's type (EntityType) ?

*NuGet Package Version:* (10.4.0.0)

*.NET Version:* (4.6)

*IDE:* (VS2015)

*App:* (Android)

**Comment by Olfi01** [comment]
In a callback query, the only thing returned is the `e.CallbackQuery`. The message you can get from it is just the message with the buttons your bot sent, so I doubt that you'd want to use any entities from that to begin with.
If you really want that though, go find out `e.CallbackQuery.Message.Entities.IndexOf(yourEntity)` of the entity you determined via `e.CallbackQuery.Message.Entities[index].Type == EntityType.YourType` and get `e.CallbackQuery.Message.EntityValues[indexYouFound]`. There you have its value.
