### ISSUE TITLE
 asp.net webforms Reciever Page

### ISSUE THREAD

**Issue by keyvanarasteh** [TelegramBots/telegram.bot#300]
is there any sample for webhook reciever page in asp.net webforms ?

i cant do that, help plzz

**Comment by deril** [comment]
#39

**Comment by keyvanarasteh** [comment]
@deril my friend i dont have problem with setting webhook address.

i cant handle updates recieved in webhook webpage, it doesn't have any POST or GET parameteres & i dont know how to implement API's function because example is written in ConsoleApplication not a web application.

help plzzz

**Comment by keyvanarasteh** [comment]
what i need to write exactly on my asp.net web form like "hook.aspx" ?

i have this class now but i think i have to change somewhere ?

`using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Http;
using Microsoft.Owin.Hosting;
using Owin;
using Telegram.Bot.Types;
using File = System.IO.File;
using Telegram.Bot;

namespace HookHandler
{
    static class Bot
    {
        public static readonly Api Api = new Api("Your Api Key");
    }

    public class HookRecieverHelper
    {
        public HookRecieverHelper()
        {
            using (WebApp.Start<Startup>("https://+:8443"))
            {
                // Register WebHook
                Bot.Api.SetWebhook("https://YourHostname:8443/WebHook").Wait();

                Console.WriteLine("Server Started");

                // Stop Server after <Enter>
                Console.ReadLine();

                // Unregister WebHook
                Bot.Api.SetWebhook().Wait();
            }
        }
    }
        

    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            var configuration = new HttpConfiguration();

            configuration.Routes.MapHttpRoute("WebHook", "{controller}");

            app.UseWebApi(configuration);
        }
    }

    public class WebHookController : ApiController
    {
        public async Task<IHttpActionResult> Post(Update update)
        {
            var message = update.Message;

            Console.WriteLine("Received Message from {0}", message.Chat.Id);

            if (message.Type == MessageType.TextMessage)
            {
                // Echo each Message
                await Bot.Api.SendTextMessage(message.Chat.Id, message.Text);
            }
            else if (message.Type == MessageType.PhotoMessage)
            {
                // Download Photo
                var file = await Bot.Api.GetFile(message.Photo.LastOrDefault()?.FileId);

                var filename = file.FileId + "." + file.FilePath.Split('.').Last();

                using (var saveImageStream = File.Open(filename, FileMode.Create))
                {
                    await file.FileStream.CopyToAsync(saveImageStream);
                }

                await Bot.Api.SendTextMessage(message.Chat.Id, "Thx for the Pics");
            }

            return Ok();
        }
    }

   
}`

**Comment by keyvanarasteh** [comment]
how can i parse json to Update Object in API , this solves my problem too ;-)

**Comment by keyvanarasteh** [comment]
`Telegram.Bot.Types.Update.FromString`

**Comment by MrRoundRobin** [comment]
@keyvanarastehcan i close this?

**Comment by kamzara** [comment]
[https://mrroundrobin.github.io/telegram.bot/html/M_Telegram_Bot_TelegramBotClient_SetWebhookAsync.htm](https://mrroundrobin.github.io/telegram.bot/html/M_Telegram_Bot_TelegramBotClient_SetWebhookAsync.htm) says ' We currently do not support self-signed certificates. ' , is the document true ?

**Comment by deril** [comment]
@kamzara I'm using this lib with self-signed certificate with no problem.

**Comment by deril** [comment]
@keyvanarasteh If it can help you, take a look on my implementation of [telegram bot using webhooks](https://github.com/deril/jewish-bot-c )
