### ISSUE TITLE
Send Large File

### ISSUE THREAD

**Issue by mostafahtsm** [TelegramBots/telegram.bot#302]
Hi,
I want send large file using Telegram.Bot but it fails. it fails after 60 seconds and I set Uploadtime to 1 hour but it dose not send file.
I used 11.1.0-beta-3.

**Comment by Olfi01** [comment]
how big is the file?

**Comment by farazp** [comment]
Hi,
I want send large file using Telegram.Bot but it fails.
my file is between 100MB to 800MB, I used Telegram.Bot  in asp.net core 2.2 webapi.
how can send large file?

**Comment by poulad** [comment]
Telegram Bot API has a limit on the file size.

https://core.telegram.org/bots/api#sending-files

Please join our group chat on Telegram if you have any questions.

**Comment by arashsoftco** [comment]
> Telegram Bot API has a limit on the file size.
> 
> https://core.telegram.org/bots/api#sending-files
> 
> Please join our group chat on Telegram if you have any questions.
 hi poulad
what is your chat group link
