### ISSUE TITLE
Why i get Request timed out error in Bot.GetUpdatesAsync ?

### ISSUE THREAD

**Issue by behzad27** [TelegramBots/telegram.bot#304]
I'm write this code:
```
 while (true)
            {
                var updates = await Bot.GetUpdatesAsync(offset);
                foreach (var update in updates)
                {
                     ...
```
but in this line:
`var updates = await Bot.GetUpdatesAsync(offset);`
get this error:
`Request timed out`
What happen?How can i solve that problem?

**Comment by Olfi01** [comment]
It seems your internet is slow or something, the request wasnt able to finish before the timeout went off. Consider using the additional parameters of `Bot.GetUpdatesAsync` to add your own, longer timeout.
```c#
client.GetUpdatesAsync(offset, timeout: yourTimeout);
```
