### ISSUE TITLE
"No response received"

### ISSUE THREAD

**Issue by jcmag** [TelegramBots/telegram.bot#306]
Hi,
From time to time I see the error "No response received" in my log.
I see it comes from:
`if (responseObject == null)
       responseObject = new ApiResponse<T> { Ok = false, Message = "No response received" };`

and I checked that responseString is empty:
`responseString = await response.Content.ReadAsStringAsync().ConfigureAwait(false);`

my question is: do we know why no response is received?
Is the problem from my side or Telegram?

**Comment by jcmag** [comment]
I've contacted Telegram support and they said calling sendMessage should always return a Message object or error... any idea of why I'm receiving an empty response?

**Comment by jcmag** [comment]
I think it's because there is a timeout of 10 sec. If sendMessage doesn't reply before this period, then responseString will be empty, right?

**Comment by MrRoundRobin** [comment]
Hi,

i observed this in cobination with a bug in sending files (fixed in 9a09320a631893c4bda2e08b7872a56e0781a392)

if the request timesout, there should be an Exception (i think a `TaskCanceledException`)

cann you ty the v12 beta?
