### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by mhdmhdpor** [TelegramBots/telegram.bot#307]
Hi there...
I added my robot as administrator into my channel and i want to get channel posts by robot then resend it to other people that Previously get their telegram id's.
I apologize if i had bad dictation
English is not my first language 

Code:
`#region Properties
    private Api bot;
    string botToken = "Bot Token";
#endregion

#region Constructor
/// <summary>
/// Basic constructor for the api controller
/// </summary>
public WebhookController()
{
    bot = new Api(botToken);
}

#endregion
 
public async Task<IHttpActionResult> Post(Update update)
{
    var text = update.Message.Text;
    var chatType = update.Message.Chat.Type;

    if (chatType == ChatType.Channel)
    {

        // Send Text message to users that previusly we gathered their telegram id and saved them in our DB
        // ******Problem is here******
    }

    else if (chatType == ChatType.Private)

    {
        if (text != null && text.Contains("/start") || text.Contains("start"))
        {
            await bot.SendTextMessage(chatId: update.Message.Chat.Id, text: "START");
        }
    }
    else
    {
        await bot.SendTextMessage(chatId: update.Message.Chat.Id, text: "ERROR!!!");
    }

    return Ok();
}
`
`"Message": "An error has occurred.",
"ExceptionMessage": "Object reference not set to an instance of an object.",
"ExceptionType": "System.NullReferenceException",
"StackTrace": "   at CodeBlock.Bot.Engine.Controllers.webhookController.<Post>d__11.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"`

**Comment by Olfi01** [comment]
First, you shouldn't assume that every update is a message update, if you want to call update.Message, it will sometimes fire the very exception you described.
Second, a channel post will not be in the update.Message property, but in the update.ChannelPost property, so channel posts will fire the very exception you described once again.
I hope I was able to help you :)
