### ISSUE TITLE
A way to catch if user enter or leave chat

### ISSUE THREAD

**Issue by ebadola** [TelegramBots/telegram.bot#308]
Is possibile to know when a user enter/leave a chat and so what event is fired?
I can't find anything on README in main page.

I'm sorry if this problem is already solved time ago.

Thanks!

**Comment by DoomAngels** [comment]
On the top mf my mind I think you have to check what type of message is received because there is one type of message that tells you an user join, cannot check this right now because i'm far away from any computer.

**Comment by kogalino** [comment]
Hi @ebadola,
if a user enters or leaves a chat, you will receive a message of type `Telegram.Bot.Types.Enums.MessageType.ServiceMessage`.

You get this type of message for a couple of events, like

- your bot is added to a channel, group or super group
- a new user is added
- a user left
- the chat title was changed
- the chat image was changed
- etc.

Depending on the event, certain properties of that message are filled.

If a user enters a chat, you will get a message with the property `new_chat_member` filled. Like so:
```
{
  "message_id": 123,
 
  .. // removed for brevity
  
  "new_chat_member": {
    "id": 123456,
    "first_name": "Mr.",
    "last_name": "Burns",
    "username": "mrburns"
  },

  .. // removed for brevity
}
```

If a user leaves `left_chat_member` is filled. 

If you add multiple users at once, you will receive one message for each added user. 

Hope that answers your question.

**Comment by pouladpld** [comment]
@ebadola Check for these when receiving a message:

```c#
msg.Type == MessageType.ServiceMessage
msg.NewChatMember
msg.LeftChatMember
```

More info: <https://core.telegram.org/bots/api#message>

**Comment by ghettopoly** [comment]
Does it work for channels too?

**Comment by ayubxan** [comment]
> Does it work for channels too?

no it doesn't

**Comment by scriptPHPonit** [comment]
How to check the id of the link, by which our new member enter to our channel or group
