### ISSUE TITLE
HttpRequestException

### ISSUE THREAD

**Issue by Ozymandy** [TelegramBots/telegram.bot#309]
### Steps to reproduce
Just SendTextMessageAsync(user, message);

### Expected  behavior
Sending message to user

### Actual behavior
![c2e199f08e0943bdaa92187ed46a0123f5dde36bd17b4ac98a pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/3194888/23056209/58c147de-f4fb-11e6-888f-6cbcb5c8a231.png)

### Environment data

*NuGet Package Version:* (e.g. 10.3.0)

*.NET Version:* (e.g. 4.6, Core RTM, Mono, etc.)
4.5
*IDE:* (e.g. VS2015, VS Code, etc.)
VS2012, but it doesn't matter.
*App:* (e.g. Desktop, iOS, Android, etc.)
Desktop

**Comment by mhverbakel** [comment]
Can you translate the message?

And, other things you should try:
- can you access the bot directly from your browser? (Using the api docs over at telegram)
- can you run other methods with success?
- can you run the sample on your pc with your own bot token?

**Comment by Ozymandy** [comment]
@mhverbakel 

>Can you translate the message?

"error occures when sending request"

>can you access the bot directly from your browser? (Using the api docs over at telegram)

Yes, I can access from the browser.

>can you run the sample on your pcwith your own bot token?

And it's doens't work

>can you run other methods with success?

No.

**Comment by mhverbakel** [comment]
Put a try-catch around your statement and look at the inner exception.

**Comment by Ozymandy** [comment]
@mhverbakel  this have no inner exception(it's null)

**Comment by Ozymandy** [comment]
Can it happens because of wrong time on pc?

**Comment by Ozymandy** [comment]
@mhverbakel but in browser works fine.

**Comment by Ozymandy** [comment]
@mhverbakel and time differs in about 4 hours

**Comment by Ozymandy** [comment]
So can anyone help me with this problem?
