### ISSUE TITLE
on-the-fly-update message update example

### ISSUE THREAD

**Issue by MortiTotti** [TelegramBots/telegram.bot#314]
hi
I want to make a bot with inline keyboards and on-the-fly updating.
There are times when you'd prefer to do things without sending any messages to the chat. For example, when your user is changing settings or flipping through search results. In such cases, we need to use Inline Keyboards that are integrated directly into the messages they belong to.

in this link, there is a good example of what I want to do
https://core.telegram.org/bots#inline-keyboards-and-on-the-fly-updating

example bots are @music , @vote and @like

I read your examples and tried to make that, but I couldn't. could you help me with that?
thanks in advance

**Comment by DoomAngels** [comment]
Hello I'm trying to do the same, for now I know that you have to use the event OnCallBack which reads the inline button that you push, what I don't know is how to get the message ID so you can change the text and buttons with EditMessageCaptionAsync(chatID, MsgID, "New Msg", replyMarkup);
