### ISSUE TITLE
GetUpdate dosen't work in Xamarin.Android

### ISSUE THREAD

**Issue by MohammadHadi2031** [TelegramBots/telegram.bot#320]
### Steps to reproduce
I wrote this code to get updates from bot:
```

 protected override  void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);
            // Set our view from the "main" layout resource
             SetContentView (Resource.Layout.Main);
            bt = FindViewById<Button>(Resource.Id.button1);
            bt.Click += Bt_Click;
          bot.OnUpdate += Bot_OnUpdate;
            bot.StartReceiving();
        }
 private void Bot_OnUpdate(object sender, Telegram.Bot.Args.UpdateEventArgs e)
        {
           bot.SendTextMessageAsync(e.Update.Message.Chat.Id, "hello");
        }
```
but nothing happen when I send message to bot.

however  "SendTextMessageAsync" method works when I call it in "Bt_Click":

```
private  void Bt_Click(object sender, System.EventArgs e)
        {
             bot.SendTextMessageAsync(9116xxx3, "hello");
        }
```

I tried to get updates manually with this code:
`var updates = bot.GetUpdatesAsync().Result;`
but "updates" is null

in Application properties I chose "Sdk and User Assemblies" in linker properties and I tried with "Shared Runtime" and without it but result was same

NuGet Package Version: 10.4.0

Mono Android 7.1

IDE: VS2017

App: Android

**Comment by Olfi01** [comment]
Try this:
```c#
var task = bot.GetUpdatesAsync();
task.Wait();
var updates = task.Result;
```
if this is still null, try to check if there are any updates at all (enter "api.telegram.org/bot[TokenHere]/getUpdates" in your browser)
