### ISSUE TITLE
Never fired events

### ISSUE THREAD

**Issue by SkyQuant** [TelegramBots/telegram.bot#322]
What _BotOnInlineQueryReceived_ and _BotOnChosenInlineResultReceived_ methods for? They are never been called with subscription
```Bot.OnInlineQuery += BotOnInlineQueryReceived;
Bot.OnInlineResultChosen += BotOnChosenInlineResultReceived;
```

**Comment by MrRoundRobin** [comment]
have you called `StartReceiving()`?

**Comment by SkyQuant** [comment]
Yes, sure. I receive all incomes by this event Bot.OnMessage. I simply don't understand what other events for, they are **never** firing.

**Comment by mhverbakel** [comment]
See https://core.telegram.org/bots/api#update for the different update types.

**Comment by opewix** [comment]
I had the same problem in Echo example. Subscribe to Bot.OnReceiveGeneralError event, to see errors.

**Comment by Olfi01** [comment]
@SkyQuant do you know what those events are used for? they basically are fired once a user sends an inline query to your bot. For this, your bot should have inline mode activated at [@BotFather](t.me/BotFather) and you should keep in mind that the api only fires the query every few seconds to not overload your bot
