### ISSUE TITLE
StartReceiving Method Issue

### ISSUE THREAD

**Issue by MrShaghaghi** [TelegramBots/telegram.bot#323]
Hi,
my "BotOnMessageReceived" event doe's not fired when i used StartReceiving method of bot (console app. & background polling used).
so, when changed my code and used simple long polling with GetUpdatesAsync() method and give offset number parameter, receiving operation was OK.
Please help me about this issue.

**Comment by Olfi01** [comment]
Can you give the code you tried to use?
