### ISSUE TITLE
Message Entity with Mention Entity Type doesnt return user?

### ISSUE THREAD

**Issue by mclucario** [TelegramBots/telegram.bot#328]
### Steps to reproduce
Create a callback where the Message Entities contains a MessageEntityType.Mention

### Expected  behavior
The MessageEntity.User should contain an user when the MessageEntity.Type is MessageEntityType.Mention

### Actual behavior
It doesnt contain an user when you try to use it.

### Environment data

*NuGet Package Version:* (e.g. 10.3.0)
3.5.0.1996
*.NET Version:* (e.g. 4.6, Core RTM, Mono, etc.)
NetCore App 1.0.1
*IDE:* (e.g. VS2015, VS Code, etc.)
Visual Studio 14.0.25431.01 Update 3
*App:* (e.g. Desktop, iOS, Android, etc.)
NetCore App (Desktop)

**Comment by Olfi01** [comment]
The user does only exist for users who don't have a username, otherwise you'll have to use the EntityValue and find out their username and process that

**Comment by Olfi01** [comment]
It's a shame there's no MessageEntity.Value field, but it's the telegram.bot API at fault and not this .NET API
