### ISSUE TITLE
Show line number in ApiRequestException handling

### ISSUE THREAD

**Issue by shahinesi** [TelegramBots/telegram.bot#340]
How would one display what line number caused the error and is this even possible with the way that .NET compiles its .exes?

If not is there an automated way for Exception.Message to display the sub that crapped out?

```
try
{
                    await bot.SendTextMessageAsync(chatId: ChatID, text: AnswerClass.Start, replyMarkup: kb_main);
// All Code
}
catch(ApiRequestException ex)
{
}
```

**Comment by MrRoundRobin** [comment]
The `ApiRequestException` will always be thrown in this line: https://github.com/MrRoundRobin/telegram.bot/blob/dc3d63fbce7563f393b46437b36fc1c52a46309a/src/Telegram.Bot/TelegramBotClient.cs#L1644
