### ISSUE TITLE
SendInvoiceAsync dont works

### ISSUE THREAD

**Issue by ace37** [TelegramBots/telegram.bot#342]
Telegram.Bot.Exceptions.ApiRequestException: Request timed out ---> System.Threading.Tasks.TaskCanceledException: Task cancelled.
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   в Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__93`1.MoveNext()
   ---  ---
   в Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__93`1.MoveNext()
---  ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   в Telegram.Bot.TelegramBotClient.<ReceiveAsync>d__46.MoveNext()

*NuGet Package Version:* 12.0.0 beta3

*.NET Version:*  4.7

*IDE:* VS2017

*App:* Console

**Comment by MrRoundRobin** [comment]
Its a "Request timed out" exception, maybe related to the DNS issue yesterday?

**Comment by smartcontracteam** [comment]
But SendText works perfectly.

**Comment by a-a-k** [comment]
It doesn't work for me too, however was worked at friday. Could you test it yourself, Robin?

**Comment by pouladpld** [comment]
@ace37 Try newer versions and let us know if you still have this problem. All `sendInvoice` tests are passing at the moment.
