### ISSUE TITLE
ThumbHeight and Width should be int

### ISSUE THREAD

**Issue by FrayxRulez** [TelegramBots/telegram.bot#343]
### Steps to reproduce
Try to `AnswerInlineQueryAsync` with any `InlineQueryResultNew` with `ThumbWidth` or `ThumbHeight` set

### Actual behavior
The request will end in an exception:
"Bad Request: field "thumb_width" must be of type Number`

*NuGet Package Version:* 12.0.0.0

**Comment by Olfi01** [comment]
Can you give the code where you initialize the InlineQueryResultNew ?

**Comment by MrRoundRobin** [comment]
@Olfi01 already fixed in a local branch that's why there is a wip label

**Comment by Olfi01** [comment]
oops xD
