### ISSUE TITLE
send message with channel name doesn't work 

### ISSUE THREAD

**Issue by patachi** [TelegramBots/telegram.bot#345]
hi 
when i try to send a message to a channel by its name, got invalid chat error
(bot is administrator member in channel)

`bot.SendPhotoAsync("@ChannelName", ....);`

**Comment by khashei** [comment]
This is similar to #346 which I posted.

**Comment by patachi** [comment]
hmm.... welp if its not still fixed you can use channel Id instead of channel name 
`bot.SendPhotoAsync(-1234567890L, ....);`

**Comment by pouladpld** [comment]
I am using `12.0.0-beta-04` version in an ASP.NET Core app and it works fine for me.

```c#
await Client.SendPhotoAsync("@my-public-channel-id",
                    new FileToSend("http://dracul.kill.pl/%7Ebielu/astronomia/ksiezyc/00189.jpg"));
```

**Comment by patachi** [comment]
@pouladpld its public channel , well private channels doesn't have channel id that starts with "@" sign .

**Comment by pouladpld** [comment]
@patachi I'm pretty sure this is fixed. Feel free to reopen this issue if you still have the problem.
