### ISSUE TITLE
Bad Request: chat not found when sending image

### ISSUE THREAD

**Issue by khashei** [TelegramBots/telegram.bot#346]
### Steps to reproduce
Trying to send an image from an online source (e.g. path == "http://dracul.kill.pl/~bielu/astronomia/ksiezyc/00189.jpg") but receive bad request error.       

Here is the source code:
WebRequest request = WebRequest.Create(path);
using (Stream stream = request.GetResponse().GetResponseStream())
            {
                FileToSend fileToSend = new FileToSend(path, stream);
                _bot.SendPhotoAsync(new ChatId(to), fileToSend, caption).Wait();
            }

### Expected  behavior
Send photo with no exception

### Actual behavior
Telegram.Bot.Exceptions.ApiRequestException: Bad Request: chat not found

### Environment data
IIS on windows 10

*NuGet Package Version:* (e.g. 10.3.0)
12.0.0-beta-03

*.NET Version:* (e.g. 4.6, Core RTM, Mono, etc.)
4.5

*IDE:* (e.g. VS2015, VS Code, etc.)
VS2017

*App:* (e.g. Desktop, iOS, Android, etc.)
desktop

**Comment by khashei** [comment]
I downgraded the bot to latest stable version 10.0.4 and it works.

**Comment by MrRoundRobin** [comment]
Does this error only occure when you're sending images? `chat not found ` indecates an other reason

**Comment by khashei** [comment]
Yes this is only for images. Using the same bot on the same channel I post using SendTextMessageAsync with problem. Again when I downgraded the version send photo also works but I have other issues which I dont want to mix with this one with 10.0.4.

**Comment by khashei** [comment]
I tried this with 12.0.0-beta 4 and still receive "Bad Request: chat not found". With 10.0.4 it works fine

**Comment by khashei** [comment]
I found the root cause for this issue. When I try this it works:
FileToSend fileToSend = new FileToSend(new Uri(path));
_bot.SendPhotoAsync(new ChatId(to), fileToSend, caption).Wait();

The down side of using this is that telegram will compress the file when downloading directly and also allow smaller size. Is there anything we can do to fix the multipart upload?

**Comment by khashei** [comment]
Hi,
I started debugging the code and found that an exception is thrown at this line (#1603 - TelegramBotClient.cs): 

> response = await _httpClient.PostAsync(uri, form, cancellationToken).ConfigureAwait(false);

  InnerException: 
       HResult=-2146233088
       Message=Error while copying content to a stream.
       Source=mscorlib
       StackTrace:
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
            at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__93`1.MoveNext()
       InnerException: 
            HResult=-2146232800
            Message=Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
            Source=System
            StackTrace:
                 at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
                 at System.Net.Http.StreamToStreamCopy.BufferReadCallback(IAsyncResult ar)
            InnerException: 
                 ErrorCode=10054
                 HResult=-2147467259
                 Message=An existing connection was forcibly closed by the remote host
                 NativeErrorCode=10054
                 Source=System
                 StackTrace:
                      at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
                      at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
                 InnerException: 


Please note that this is the master/head version. Also bot access and everything is okay as just changing the bot to version 10 an everything works.

**Comment by khashei** [comment]
How can I find the last commit that was included in 10.0.4 to at least compare the stream upload code?

**Comment by khashei** [comment]
Hi,
I added latest compiled version from head. When tracing the code into the library on line 1602 TelegramBotClient.cs I get following response:

>  response = await _httpClient.PostAsync(uri, form, cancellationToken).ConfigureAwait(false);

response	{StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Connection: keep-alive
  Access-Control-Allow-Origin: *
  Access-Control-Expose-Headers: Content-Length,Content-Type,Date,Server,Connection
  Date: Sat, 10 Jun 2017 16:04:07 GMT
  Server: nginx/1.10.0
  Content-Length: 73
  Content-Type: application/json
}}	System.Net.Http.HttpResponseMessage


the request looks like this:
Request header: {Content-Type: multipart/form-data; boundary="5cdwcc37-107f-4781-b274-0b4f64eaa26c"
Content-Length: 1270224
}

**Comment by khashei** [comment]
Same post works with no problem on postman

**Comment by pouladpld** [comment]
@khashei Have your tried this with newer versions?

**Comment by Olfi01** [comment]
@khashei @MrRoundRobin @pouladpld isnt this the same thing with the channels and multipart data again? Where the string channelname was parsed with the Quote? Maybe the fix is not Ort was not at that time in master

**Comment by pouladpld** [comment]
@Olfi01 Ya. I believe so.

@MrRoundRobin Looks like it's about the time for a new minor version release. We have some (rather severe) bugs fixed now.

**Comment by khashei** [comment]
I believe the issue is related to multi-part data. I made direct call to telegram REST endpoints to solve my problem.  I can switch back to test the latest version of the library to see if it works. @MrRoundRobin

**Comment by Olfi01** [comment]
@khashei yes it is related to multi-part data, the headers were parsed wrongly

**Comment by pouladpld** [comment]
@khashei I have updated this package for the time being:
<https://nuget.org/packages/Telegram.Bot.Core/>

Get version 13.2.0.
