### ISSUE TITLE
Bot.SendDocumentAsync(tgId, streamFile, "file sended!", false);  throw exception Additional information: Error while copying content to a stream

### ISSUE THREAD

**Issue by nasserfet** [TelegramBots/telegram.bot#348]
public static async void sendFileToUser(long tgId, int fileId)
        {
            ExceptionDispatchInfo capturedException = null;
            String occuredException = "";
            try
            {
                string pathPhysical1 = (string)myHT[fileId];

    using (
var fs = new FileStream(pathPhysical1, FileMode.Open, FileAccess.Read, FileShare.Read, 1000, false))
                    {

                        string fileName = fileId + ".pdf";
                        FileToSend streamFile = new FileToSend(fileName, fs);
                        
                        await Bot.SendDocumentAsync(tgId, streamFile, "فایل pdf ارسال شد!", false);
                        await Bot.SendChatActionAsync(tgId, ChatAction.UploadDocument);

                    }
                }
            }
            catch (System.Net.Http.HttpRequestException ex)
            {
                capturedException = ExceptionDispatchInfo.Capture(ex);
                occuredException = "System.Net.Http.HttpRequestException";
                //                printExceptionINConsole(ex);
            }
            catch (ApiRequestException ex)
            {
                capturedException = ExceptionDispatchInfo.Capture(ex);
                occuredException = "ApiRequestException";

                //                printExceptionINConsole(ex);
            }
            catch (TaskCanceledException ex)
            {
                capturedException = ExceptionDispatchInfo.Capture(ex);
                occuredException = "TaskCanceledException";

                //printExceptionINConsole(ex);
            }
            catch (Exception ex)
            {
                occuredException = "Exception";

                capturedException = ExceptionDispatchInfo.Capture(ex);

                //  printExceptionINConsole(ex);
            }

            if (capturedException != null)
            {

                printExceptionINConsole(capturedException.SourceException, "capturedException-" + occuredException);

                //  await ExceptionHandler();

                //  capturedException.Throw();
            }
        }

### Steps to reproduce
after a few time using above method ,even getting same file , telegram stop 

### Expected  behavior
i expected this method send file to user , when user request 

### Actual behavior
send for a few times then throw exception 
Additional information: Error while copying content to a stream 
### Environment data

*NuGet Package Version:* (e.g. 10.3.0)
Telegram.Bot
version 10.3.0.0
*.NET Version:* (e.g. 4.6, Core RTM, Mono, etc.)
.net framework 4.5
*IDE:* (e.g. VS2015, VS Code, etc.)
vs 2015
*App:* (e.g. Desktop, iOS, Android, etc.)
console application - telegram bot

**Comment by Olfi01** [comment]
I tried your code, it sent me the document over and over...
Maybe your file system can't handle the amount of pressure you deal to it?

**Comment by pouladpld** [comment]
@nasserfet  Did you fix it?
