### ISSUE TITLE
Everyday repeated error "Unexpected character encountered while parsing value: <. Path '', line 0, position 0.  in Newtonsoft.Json.JsonTextReader.ParseValue()"

### ISSUE THREAD

**Issue by a-a-k** [TelegramBots/telegram.bot#357]
### Most often this error happens at the morning, may be not every day but about so. I have several errors (quantity is mutable from day to day) such as: 

> Unexpected character encountered while parsing value: <. Path '', line 0, position 0. [   in Newtonsoft.Json.JsonTextReader.ParseValue()
>    in Newtonsoft.Json.JsonTextReader.Read()
>    in Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
>    in Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    in Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    in Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    in Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>    in Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
>    in Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__93`1.MoveNext()
> --- End of stack trace ---
>    in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    in Program.GettingUpdatesAsync.d__6.MoveNext()

### Environment data

*NuGet Package Version: 12.0.4 beta*

*.NET Version: 4.5.2* 

*IDE: VS2015* 

*App: Desktop (Windows service)*

**Comment by Olfi01** [comment]
i have no clue where this comes from, but instead of looping getUpdatesAsync, why don't you just use `Client.OnUpdate` ?

**Comment by pouladpld** [comment]
@a-a-k This is weird! Does this still happen with newer versions?

**Comment by a-a-k** [comment]
@pouladpld yes

**Comment by pouladpld** [comment]
@a-a-k I can't tell. So could you share a sample of the code you are running? and what is the timezone of your server?

**Comment by a-a-k** [comment]
@pouladpld thanks for your response
> what is the timezone of your server?
GMT +7

> Could you share a sample of the code you are running? 

> Is there any delay between loop iterations?

```
internal static partial class Program
    {
        public static async void Run()
        {
            Bot.StartReceiving();
            Log.Info("Bot.StartReceiving()");
            await GettingUpdatesAsync();
        }

        public static void Stop()
        {
            Bot.StopReceiving();
            Log.Info("Bot.StopReceiving()");
        }

        private static async Task GettingUpdatesAsync()
        {
            var offset = 0;
            while (true)
            {
                var updates = new Update[0];
                try
                {
                    updates = await Bot.GetUpdatesAsync(offset);
                }
                catch (TaskCanceledException ex)
                {
                    Log.Error($"*TaskCanceledException* - {ex.Message} [{ex.StackTrace}]");
                }
                catch (Exception ex)
                {
                    Log.Error($"*Common* - {ex.Message} [{ex.StackTrace}]");
                }

                foreach (var update in updates)
                {
                    offset = ++update.Id;

                    try
                    {
                        await ParseMain(update);
                    }
                    catch (NullReferenceException ex)
                    {
                        Log.Error($"*NullReferenceException*, Type - {update.Type}, {ex.Message} [{ex.StackTrace}]");
                    }
                    catch (Exception ex)
                    {
                        Log.Error($"*Common*, Type - {update.Type}, {ex.Message} [{ex.StackTrace}]");
                    }

                    await Task.Delay(500);
                }
            }
        }
    }
```

**Comment by Olfi01** [comment]
i just received this too... i guess since its at the first position of the string to be parsed, maybe the telegram api is returning some gibberish from time to time? maybe whenever the server restarts or something?

**Comment by pouladpld** [comment]
I'll try to add and raise an event(or something similar) containing raw json payload from tg update, before parsing it, so it could be logged and analyzed.

**Comment by a-a-k** [comment]
Hi guys. Have any progress?

**Comment by a-a-k** [comment]
> why don't you just use Client.OnUpdate ?
@Olfi01 could you please provide any example?

**Comment by a-a-k** [comment]
I still have that. What is the reason to close this issue?

**Comment by pouladpld** [comment]
@a-a-k What version are you using?
This is already fixed.
Also, the reason is labeled as _inactive_ .

**Comment by a-a-k** [comment]
@pouladpld thanks, will try
