### ISSUE TITLE
Why i can not get update message in Bot.GetUpdatesAsync(offset)?

### ISSUE THREAD

**Issue by behzad27** [TelegramBots/telegram.bot#359]
I use telegram bot in c# and every thing work correctly,but now when i send message to server i dont have any response from bot,debug my program and i realized in this line of code:
`updates = await Bot.GetUpdatesAsync(offset);`
dont have any update message get,i change my api and that line of my code get update,but previous of the api not work ,what happen?thanks

**Comment by Olfi01** [comment]
did you use google translate? anyway, if you would send your code, it would help figure out the problem perhaps.

**Comment by pouladpld** [comment]
@behzad27 Did you fix it?
If you still need help, please tell us more and follow [issue template](https://github.com/TelegramBots/telegram.bot/blob/develop/ISSUE_TEMPLATE.md).

**Comment by Pooriairoop** [comment]
@behzad27 
@pouladpld 
I have the same problem at the same line. how should we fix it if we don't want to change bot token?

**Comment by pouladpld** [comment]
@Pooriairoop we cannot reproduce the issue. He didn't follow the issue template.

**Comment by Pooriairoop** [comment]
@pouladpld 
so how can I get my answer? I really can not understand what the problem is. if you can help me please send me a solution.
in.pooria@gmail.com

**Comment by Tuscen** [comment]
@Pooriairoop can you describe the problem in more detail? What's the version of the library you are using, what you want to achieve, what you expect and the actual result. There's too little info to help you. Look at [one](https://github.com/TelegramBots/Telegram.Bot/issues/462) of my issues for example.  Ideally you should open a new issue and follow the issue template.

**Comment by Pooriairoop** [comment]
I just run my code and sometimes it works and another time it doesn't!!!
to be clear, my code stops at this line
`Update[] updates = await bot.GetUpdatesAsync(offset);`
and nothing happens, it doesn't move on even when I just send many updates to bot.
and another time when I run it again it will work and answer the updates but it rarely happens and I should run it about 5 times to get the updates in one of them!! :)

I am using getUpdate method
and Version 13.4.0 of this library.
