### ISSUE TITLE
Not getting any response when i run your Api in my console application

### ISSUE THREAD

**Issue by yadav-ankit** [TelegramBots/telegram.bot#363]
When i send 
https://api.telegram.org/"my private key"/getupdates
 
I am not getting as follows : instead i  getting an empty response. Actually when i send any message from my phone, and run getupdate url i get the response as expected, but when i run the appication(i have just copied your whole API code) then the whole response get erased. and i get {"ok":true,"result":[]}

### {"ok":true,"result":[{"update_id":684384651,
"message":{"message_id":419,"from":{"id":320531910,"first_name":"Ankit","last_name":"Yadav","language_code":"en-US"},"chat":{"id":320531910,"first_name":"Ankit","last_name":"Yadav","type":"private"},"date":1498633136,"text":"Hi"}}]}

Unexpected Behaviour
###{"ok":true,"result":[]}

**Comment by Olfi01** [comment]
can you maybe attach the critical part of your code (or the code you copied, whatever)?

**Comment by pouladpld** [comment]
@yadav-ankit Do you still have the problem? Please either close this issue or provide us more info on it following [issue template](https://github.com/TelegramBots/telegram.bot/blob/develop/ISSUE_TEMPLATE.md).
