### ISSUE TITLE
Make SendWebRequestAsync public

### ISSUE THREAD

**Issue by Olfi01** [TelegramBots/telegram.bot#365]
It would be very convenient to be able to call the Client.SendWebRequestAsync method from outside, so one could even send requests for methods that are new and thus not implemented yet. What do you think?

**Comment by Olfi01** [comment]
@MrRoundRobin ?

**Comment by pouladpld** [comment]
@Olfi01 Let's say we make a `public` general purpose method for that. In that case, caller should know so much about the implementation details of this project. Well, he could just make a PR and help all of us. Just imagine he should know the right parameters to send a file, a json payload, and ... .

Doing this would also introduce more complexity to the code for a feature that only a few (probably only contributors) can use.

**Comment by Olfi01** [comment]
Point is, caller still needs Tod wait for the PR to be merged and nuget package to be published. I'd write the PR anyway, but I'd like that as a solution for the meantime. I mean, I could also just compile my own Version of the API, but thats not really what i want

**Comment by pouladpld** [comment]
@Olfi01 But everyone is free to fork this repo, add some new methods to it and publish their own temporary package or add it as a project to their own solution.

I also did that when Robin's package wasn't ready. It took just a few minutes.

**Comment by Olfi01** [comment]
I See your point, okay.
