### ISSUE TITLE
ChatId type isn't comparable

### ISSUE THREAD

**Issue by a-a-k** [TelegramBots/telegram.bot#369]
### Steps to reproduce
```
ChatId __chatId = new ChatId(12345);
bool e1 = update.Message.Chat.Id.Equals(_chatId);
bool e2 = update.Message.Chat.Id == _chatId;
bool e3 = update.Message.Chat.Id.Equals((ChatId)12345);
bool e4 = update.Message.Chat.Id == (ChatId)12345;
```

### Expected  behavior
Getting true as result.

### Actual behavior
Getting false. Always.

### Environment data

*Nuget: 12.0.0-beta04*

*.NET Version: 4.6*

*IDE: VS 2017*

*App: all*

**Comment by pouladpld** [comment]
This will be resolved after merging PR #362.

For the time being, use string comparison:
```c#
bool result = string.Equals(chatid, 12345 + "")
// result == true
```

**Comment by a-a-k** [comment]
@pouladpld got your idea and solve this issue by follow
`bool e1 = update.Message.Chat.Id.Equals(_chatId.ToString());`

**Comment by pouladpld** [comment]
@a-a-k Since we now using `ChatId` for method parameters only, do you think anyone would need to compare `ChatId`s?
