### ISSUE TITLE
SetGameScore response is not always a Message

### ISSUE THREAD

**Issue by pouladpld** [TelegramBots/telegram.bot#372]
### Steps to reproduce
As a user, not bot, share bot's game to a chat. This means message is not sent by bot itself using SendGame method.
User starts playing the game in that chat and the following code sets user score:

```c#
int userid = 900000000;
string inlineMessageId = "27abCdEFGHIJkLMNOPQRSTuVWX";
int score = 1;
Message response = await botClient.SetGameScoreAsync(userid, score, inlineMessageId);
```

### Expected  behavior
Response should not be a `Message` but rather just a `bool` with value of `true`. The reason is that this game message that user clicked on to play is not sent by bot itself.
In any other situation, the response contains edited `Message`.
More info at <https://core.telegram.org/bots/api#setgamescore>.

### Actual behavior
Throws exception in `TelegramBotClient.cs` at _line 1621_ while trying to deserialize response payload into a `Message`.

```c#
/*
Type of T is Message.
Value of responseString is:
   {"ok":true,"result":true}
*/
responseObject = JsonConvert.DeserializeObject<ApiResponse<T>>(responseString);
```

#### NuGet Package Version
12.0.0-beta-04

#### .NET Version
.NET Core 1.1

#### IDE
VS 2017

**Comment by pouladpld** [comment]
I can resolve this by one of the two ways below:

#### Tuple
```c#
/// <remarks>
/// If the message was sent by the bot, EditedMessage contains the edited message,
/// otherwise Success will be to true.
/// </remarks>
Task<(Message EditedMessage, bool Success)> SetGameScoreAsync(int userId, int score ...);
```

#### Throwing exception
```c#
/// <remarks>
/// On success, If the message was sent by the bot, returns the edited message,
/// otherwise API returns true and the message will be null.
/// If API does not return either message or true, throws Exception
/// </remarks>
Task<Message> SetGameScoreAsync(int userId, int score ...);
```

I prefer using the Tuple because it makes more sense. Any other ideas?

**Comment by MrRoundRobin** [comment]
I don't know how to identify if the message was sent by the bot. in the current design i need to know this before calling `SendWebRequestAsync`

as temporary workaround we can do something like this:

```csharp
var response = await SendWebRequestAsync<object>("setGameScore", parameters, cancellationToken).ConfigureAwait(false);

return (response is Boolean && (bool)response == true);
```

**Comment by pouladpld** [comment]
@MrRoundRobin Ok. Let me check this fix in both scenarios and make a PR.
