### ISSUE TITLE
Making a fork of this project with multiple active maintainers

### ISSUE THREAD

**Issue by pouladpld** [TelegramBots/telegram.bot#373]
Hi
First of all, I know this is not a good place to discuss this but, to me, it looks like an issue.

@MrRoundRobin has put a lot of time and effort in this great project and that's remarkable. However, I don't see any need to keep waiting for him as he might be busy with something else.

This repo currently has 70 issues and 10 pull requests open. Many of them look like quick fixes and shouldn't take much time.

I would suggest that active contributors make a new organization and fork this project. This will help to:

- Divide the work between multiple people
- Getting updates faster to clients
- Peer review each others' work more often
- Have more freedom to try new designs (might end up being good or bad)
- @MrRoundRobin can merge the new updated code back as well if he wants to

This process also happened before with the Telegram Client you find on f-droid. When the original maintainer was not interested enough to work on the project(https://github.com/slp/Telegram), a new fork of the repo,<https://github.com/Telegram-FOSS-Team/Telegram-FOSS>, continued the work.

So, what do you guys think?

**Comment by MrRoundRobin** [comment]
Hi @pouladpld 

recently I thought about adding collaborators, so I'm open for such discussions 👍 

Maybe we can find someone who is intrested in this?

I don't know if it's better to fork this or do it directly in this project.

**Comment by pouladpld** [comment]
@MrRoundRobin 
Good to hear from you. I'd love to be part of this as I currently am working on developing a [framework for Telegram bots](https://github.com/pouladpld/Telegram.Bot.Framework).

Do you have a list of DOs and DON'Ts you would like to discuss with collaborators?

One thing I don't like about this repo is I only see a `master` branch. How about creating a `dev` branch for people to just merge code in(after PR review) and then further test and approve it for `master`(NuGet package)?

**Comment by MrRoundRobin** [comment]
I like dev breanches but as the only contributor, I thought this is over kill. I'll just create one

**Comment by a-a-k** [comment]
Good news!

**Comment by paulkrupin** [comment]
First, I want to say **big thank you** for your work @MrRoundRobin! 👍 
I think that branching and then merging code after review will be best of all.
If you will have enough time for it. ;)

**Comment by pouladpld** [comment]
My understanding of `dev` branch is that it should always be equal to or ahead of `master`.

We can allow many collaborators to branch off `dev` and add their work. Then they make a PR to `dev` branch where others review their work. Finally, another PR could be made from `dev` to `master` and @MrRoundRobin holds that gate.

**Comment by Olfi01** [comment]
As I already said in #381 , I'd love to be a part of the structure :)
