### ISSUE TITLE
Keyboardbutton Event not fire

### ISSUE THREAD

**Issue by cRUSHER-ScriptBase** [TelegramBots/telegram.bot#374]
Hallo Robin, 
Deine Lib die durch bereitstellst ist wirklich sehr gut. 
Ich habe eine Frage/Problem welches ich dennoch nicht verstehe. Wenn ich einem KeyboardButton ein Command zuweise mit button = new KeyboardButton("/test");  und dann dem Button den Text zuweise button.Text = "Auswahl"; kann ich nicht durch die Methode BotOnMessageReceived() an den Button mit dem "/test" kommen. Sprich man drückt drauf aber es passiert nichts. Der einzige Weg auf dem es funktioniert ist das ich es nach dem Text filtere was ich aber absolut blöde finde, da ich meinen Spielebot auf mehrsprachigkeit aufgebaut habe. 
Für die InlineKeyboardButtons habe ich es selbst herausgefunden. 
Ich hoffe das du mir mit diesem Problem bitte bitte weiterhelfen kannst.

**Comment by cRUSHER-ScriptBase** [comment]
RoundRobin do you can help me pls?

**Comment by Olfi01** [comment]
@cRUSHER-ScriptBase Wenn jemand auf einen KeyboardButton drückt, wird immer exakt das als Textnachricht gesendet, was darauf stehet. Demnach kommt als einziges beim Bot auch nur die Textnachricht als solche an. Du wirst also wohl oder übel auf eine Nachricht warten müssen, die genau das enthält. Denk außerdem dran, dass in einer Gruppe der Bot entweder den Privacy mode aus haben oder Admin sein muss, um Textnachrichten zu erhalten, die keine Befehle sind oder seinen Nutzernamen enthalten oder auf eine seiner Nachrichten antworten.

**Comment by Olfi01** [comment]
Beispiel-code:
`private static void Bot_OnMessageReceived(object sender, MessageEventArgs e)
{
if (e.Message.Text == "/test")
{
//your code here, do whatever you want
}
}`

**Comment by cRUSHER-ScriptBase** [comment]
Danke sehr für deine Antwort. Aber wenn man die Keyboardbuttons erstellt muss man als Parameter ja auch einen String übergeben und als Text nunmal .Text setzen. 

Aber wie sieht es mit den InnlinekeyboardButtons aus? Ich verstehe dort nicht was es mit den callbackdata zu tun hat und wie man das dann Filtern muss bzw. wo. Sprich wie filtert man es wenn man auf einen InlineKeyboardButton drückt?

**Comment by Olfi01** [comment]
ein InlineKeyboardButton ist ein Knopf unter einer Nachricht. Dann wird auf Knopfdruck keine Nachricht gesendet, sondern im Normalfall eine CallbackQuery (also bot.OnCallbackQuery).
Und die callback data ist dann eben ein string den du selbst bestimmst, an dem du den gedrückten Knopf erkennen kannst.
Wenn du diesen InlineKeyboardButton hast:
```c#
InlineKeyboardButton button = new InlineKeyboardButton("TextHier", "callbackDataHier");
```
dann wird sobald der gedrückt wird, bot.OnCallbackQuery ausgelöst.
Da kannst du dann folgendermaßen vorgehen:
```c#
private static void Bot_OnCallbackQuery(object sender, CallbackQueryEventArgs e)
{
    if (e.CallbackQuery.Data == "callbackDataHier")
    {
        //tu was du willst
    }
}
```

**Comment by pouladpld** [comment]
(hmmm... I should learn some German someday 😎 )

@cRUSHER-ScriptBase Is the issue resolved?
