### ISSUE TITLE
telegram bot InlineKeyboardButton  CallbackData

### ISSUE THREAD

**Issue by majidazn** [TelegramBots/telegram.bot#378]
hi 
I am using mvc controller and i set webhook with https. everythings is ok just i couldnot use InlineKeyboardButton  Callback, is there any way to do this?

  public async Task<ActionResult> Index()
        {
            try
            {
               var reader = new StreamReader(Request.InputStream);
                var json = reader.ReadToEnd();
                var myClass = JsonConvert.DeserializeObject<Update>(json);
               if (myClass != null)
                    await SendMessage(myClass);
.
.
.

**Comment by Olfi01** [comment]
I don't see what exactly your issue has got to do with Telegram.Bot...

**Comment by pouladpld** [comment]
@majidazn Could you provide more info about your issue? Please always follow [template issue](https://github.com/TelegramBots/telegram.bot/blob/develop/ISSUE_TEMPLATE.md).
