### ISSUE TITLE
runtime conflict

### ISSUE THREAD

**Issue by mostafa8026** [TelegramBots/telegram.bot#379]
### Steps to reproduce
Add nuget pre release 12.0.beta.4

### Actual behavior
Could not load file or assembly 'System.Runtime, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

### Environment data

*NuGet Package Version:* 12.0.beta.4

*.NET Version:* 4.6

*IDE:* vs 2017

*App:* Desktop

**Comment by MrRoundRobin** [comment]
can you try the newest beta?

**Comment by Olfi01** [comment]
This means your current project is missing the System.Runtime reference
Just add it to your project, that should fix it

**Comment by mostafa8026** [comment]
Thanks for your response, When does the stable version release?

**Comment by pouladpld** [comment]
@mostafa8026 Stable version is released. Check it on NuGet. Feel free to reopen this issue if you still have the same problem.
