### ISSUE TITLE
Move project to an GitHub Organisation

### ISSUE THREAD

**Issue by MrRoundRobin** [TelegramBots/telegram.bot#381]
As initiated by @pouladpld I like the idea to move this project to an GitHub Organisation to improve the commuity work and deliver updates faster!

Some points he suggested are the following:

- Have a few people who can push/merge to master 
- dev branch carries out all new work and is always equal to or ahead of master 
- Changes to master only are applied through a PR from dev(Approved by "the few people") 
- We need a CONTRIBUTING file 
- MyGet packages are built only from dev branch 
- NuGet packages are built only from master branch

There are a few things on the roadmap i would love to get some help as I am very bussy in my "real job" (like UnitTest and the latest API additions and ah helpfull documentation)

So if you have suggesteion add them here

**Comment by pouladpld** [comment]
Thank you @MrRoundRobin . While I was writing Integ tests, I made notes of the things that need changes. I put them as cards in [Projects](https://github.com/TelegramBots/Telegram.Bot.Core/projects) section of that repo. Have a look at them as well.

We also need to discuss Integ Tests. They are semi-automated and some test cases need tester interaction through telegram supergroup/private chat. Who is responsible for doing them and at what events they should be triggered?

You can find the updated wiki on [Integration Tests here](https://github.com/TelegramBots/Telegram.Bot.Core/blob/master/docs/wikis/tests/integ-tests.md).

**Comment by Olfi01** [comment]
I would be happy to help this repo in my spare time. Tell me what I can do :)

**Comment by Olfi01** [comment]
@pouladpld as for the tests, is it possible to integrate them in a way like appveyor?

**Comment by pouladpld** [comment]
@Olfi01 It needs .NET Core CLI installed. Not sure if that host has it.
Tests are interactive and if you build, run tests on CI and then not respond to messages(in some test cases like Payment), they will fail.
I think it's better to keep them on separate host like Travis-CI so we have a clear way to see whether build fails or tests.
We can further mandate that only when both of CIs mark a commit/PR as successful build, we merge

**Comment by Olfi01** [comment]
@pouladpld i didnt mean we'd have to use appveyor 😆 i just meant that for every PR a test should be triggered
maybe you could even add unit tests for new methods, giving them example parameters for ids and strings and random parameters for bools

**Comment by pouladpld** [comment]
That's possible but tbh, there is not much to unit test. We are just passing values serialized into json to API in 90% of the code.

Integ tests first appeared as my playground to try out API methods and I then made a framework around it to automate calls and make sure all works end to end.

**Comment by Olfi01** [comment]
yeah xD i still think adding unit tests automated would be fun, even with new methods, maybe even asking the tester if everything went alright and if not, what didn't

**Comment by pouladpld** [comment]
Ok. It seems @MrRoundRobin also had ideas of changes to the library. If we have big refactorings on the roadmap, I'd say we:

1. Complete Integ Tests(High level, checking end-to-end)
2. Refactor lib
3. Write unit tests for newly refactored design

I'm kinda scared of ending up with putting a lot of efforts in unit testing parts that you can simply check by rolling your eyes on the code(in a simple `git diff`).

**Comment by MrRoundRobin** [comment]
That's why there are no Tests at the Moment ;) implementing tests would Take a lot longer than making the actual Implementation

**Comment by Olfi01** [comment]
oh, @MrRoundRobin, if you're here rn, mind to take a look at #382 ?

**Comment by pouladpld** [comment]
Have you guys checked Integ Tests yet? They have pretty good advantages at this stage.

Easy to write and maintain. Good examples of how to use this lib. Self-documented. Fun and interactive. It is easy to ask community to help with writing them.

@Olfi01 I understand your concern but the thing is this is not anyone's full time job so we cannot really follow all the practices we do in our real full time jobs.

**Comment by Olfi01** [comment]
yes, you're right @pouladpld , i'm sorry. sometimes i'm getting a bit too excited about this :)
And I have read your wiki about integ test, sounds good, i'm not sure i understood everything tho

**Comment by pouladpld** [comment]
Give it a try. Open an issue there if anything is not clear in docs. I try to explain and edit the wiki.

Simply put, stick your bot's token and your tg username into the `appsettings.json` and run the tests.

**Comment by pouladpld** [comment]
@MrRoundRobin How do we want to start moving the repo?
I sent you an invitation to join as an owner to org.

**Comment by MrRoundRobin** [comment]
I'll Check that

Starting on Monday i have more time dir this
