### ISSUE TITLE
error upload

### ISSUE THREAD

**Issue by shahinesi** [TelegramBots/telegram.bot#385]
```
public static async Task Upload(string ChatIDU, string url, string filename, string caption)
        {
            //await bot.SendChatActionAsync(ChatIDU, ChatAction.UploadVideo);
            // await bot.SendTextMessageAsync(ChatID, GetAppUrl().Replace("http", "https"));

            var request = WebRequest.Create(url);
            //TimeSpan ts = new TimeSpan(1, 1, 1);
            //bot.Timeout = ts;
            await bot.SendTextMessageAsync(ChatIDU, "URL : " + url + "\n ChatIDU : " + ChatIDU);

            using (var response = request.GetResponse())
            {
                var responseStream = response.GetResponseStream();
                await bot.SendDocumentAsync(ChatIDU, document: new FileToSend(filename, responseStream), caption: caption);
            }
        }
```

ErrorCode : 400
Message : Bad Request: chat not found

help me tnx

This is the correct code and the message 👍 

`            await bot.SendTextMessageAsync(ChatIDU, "URL : " + url + "\n ChatIDU : " + ChatIDU);
`
but this code error 400
`                await bot.SendDocumentAsync(ChatIDU, document: new FileToSend(filename, responseStream), caption: caption);
`

output :
URL : https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/718smiley.png/220px-718smiley.png
 ChatIDU : @friends_series_en
ErrorCode : 400
Message : Bad Request: chat not found

**Comment by Olfi01** [comment]
what is the value of `filename` and `responseStream`?

**Comment by Olfi01** [comment]
I found the error too, currently working on a solution

**Comment by Olfi01** [comment]
@shahinesi anyway, if you want to send the file as a photo, try SendPhotoAsync instead (though the issue will be present there too)

**Comment by shahinesi** [comment]
@Olfi01 TNX
NOW .... Fixed?

**Comment by shahinesi** [comment]
Version | Downloads | Last updated
-- | -- | --
Telegram Bot API 13.0.0-beta-01 (this version) | 41 | Thursday, July 13, 2017

this is still an error 
ErrorCode : 400
Message : Bad Request: chat not found

**Comment by Olfi01** [comment]
@shahinesi yes, unfortunately the fix is not included in that release yet.

**Comment by Olfi01** [comment]
If I understood it correctly, you could search myGet for the correct build (i didn't really get that myget stuff)

**Comment by pouladpld** [comment]
@shahinesi  I have updated this package for the time being:
<https://nuget.org/packages/Telegram.Bot.Core/>

Get version 13.2.0.
