### ISSUE TITLE
Edit Message remove reply markup

### ISSUE THREAD

**Issue by majid23** [TelegramBots/telegram.bot#402]
When I use edit EditMessageTextAsync in telegram message changed but reply markup removed why?
I want change just message and my reply_markup stay in before state.

**Comment by pouladpld** [comment]
Try assigning old message's reply markup to new edited message.

**Comment by pouladpld** [comment]
@majid23 I just checked that in postman and it turns out _removing reply_markup while editing just the text_ is the default behavior of tg API!

You can report this to [BotSupport](https://t.me/BotSupport)

**Comment by Olfi01** [comment]
@pouladpld  @majid23 this is totally intended, as you might as well want to edit the markup to vanish. EditMessageText is for editing the whole message anyway.

**Comment by pouladpld** [comment]
@Olfi01 I wouldn't like this type of behavior. They have `reply_markup` as an optional parameter.

What makes sense to me is if I tell API to only change `text`, it shouldn't implicitly change other stuff.
Nevertheless, there is another method for changing `reply_markup`.

**Comment by Olfi01** [comment]
@pouladpld point is, how do you tell the api to not have any markup at all then? does null even exist in http, and if yes, wouldn't it maybe be automatically assigned to all parameters not supplied?

**Comment by pouladpld** [comment]
@Olfi01 It is just a contract so we could pass any value such as a string of `null`, an empty array, or `false` to API for removing the `reply_markup`. 

That's in fact what API is already doing. For example, there are two different types possible for response of [editmessagetext](https://core.telegram.org/bots/api#editmessagetext).

**Comment by Olfi01** [comment]
@pouladpld get it, carry it to botsupport then

**Comment by pouladpld** [comment]
@Olfi01 I already did. They do not reply often though! The only time they replied me(after about 2 days), was about a problem in docs about `sendInvoice` method.

**Comment by pouladpld** [comment]
This is what BotSupport replied:

> Sending the empty keyboard is used to remove the keyboard, if you don't want to change it, you can always send the same. The main idea is that inline_keyboard are most commonly related to the message content itself (it provides actions according to that). So editing the message will change the keyboard in most of the cases, that's why the method works that way.

**Comment by majid23** [comment]
Thanks pouladpld.
