### ISSUE TITLE
GetUpdatesAsync() not throwing exceptions

### ISSUE THREAD

**Issue by Newgel** [TelegramBots/telegram.bot#403]
### Steps to reproduce
While running bellow code, disconnect Internet and wait for a timeout;

public async void Start()
        {
            while (true)
            {
                try
                {
                    var updates = await Bot.GetUpdatesAsync(offset);
                    foreach (var update in updates)
                    {
                        var message = update.Message;
                        {
                            if (message.Type == MessageType.TextMessage)
                            {
                                if (message.Chat.Id == tladmin_chat_id && message.Text.StartsWith("/test")) // broadcast admin command
                                {
                                    await Bot.SendTextMessageAsync(message.Chat.Id, "Test received");
                                }                                
                            }
                        }
                    }
                }
                catch (System.Net.Http.HttpRequestException ex)
                {
                    throw (ex);
                }
                catch (ApiRequestException ex)
                {
                    throw (ex);
                }
                catch (Exception ex)
                {
                    throw (ex);
                }
	    }
	}

### Expected  behavior
An exception should be catched and thrown.

### Actual behavior
Application crashes with message "An unhandled exception of type 'System.Net.Http.HttpRequestException' occurred in mscorlib.dll"

### Environment data
*NuGet Package Version:* 10.4.0
*.NET Version:* 4.6.01586
*IDE:* VS20175 Community
*App:* Windows 10 Home Desktop Application

**Comment by pouladpld** [comment]
TelegramClient neither has anything to do with non-telegram errors, such as connection timeout, nor hides unrelated exceptions from its caller.

It is your responsibility to guard against such errors. Catching that ` Http.HttpRequestException` exception is a good idea.

**Comment by Newgel** [comment]
@pouladpld Yes and catching Http.HttpRequestException is EXACTLY what I´m trying above and it is not working! So, can you help me finding whats wrong with my code?

**Comment by pouladpld** [comment]
I am trying this code and I catch the expected exception.

```c#
static void Main(string[] args) => Start().Wait();

public static async Task Start()
{
    ITelegramBotClient client = new TelegramBotClient("token");
    do
    {
        try
        {
            var updates = await client.GetUpdatesAsync();
            Console.WriteLine($"Received {updates.Length} updates.");
        }
        catch (System.Net.Http.HttpRequestException ex)
        {
            Console.WriteLine(ex.Message);
        }

        Console.Write("Disable network and press enter to simulate connection timeout...");
        Console.ReadLine();
    } while (true);
}
```

You can drill down into inner exception and see `SocketErrorCode` is of type `TimedOut`.

**Comment by Newgel** [comment]
Thanks for your code. While checking your version against my own I notice I was actually catching and throwing exceptions, instead of doing something with it. I was under the impression it was enough to catch an exception and it would not be considered an "unhandled exception"  anymore, preventing application to crash. Looks like I was wrong,

**Comment by Newgel** [comment]
This issue can be closed now.
