### ISSUE TITLE
Send Photo

### ISSUE THREAD

**Issue by PurTahan** [TelegramBots/telegram.bot#404]
Hi
Is it Possible to Upload Photo (or File) one time and send it to others multiple times. and that Message **Not like** `Forwarded Message`?

**Comment by paulkrupin** [comment]
As far as I understand it. You have to implement your own storage for binary files. And each time get a file from it and send it as new copy.

**Comment by PurTahan** [comment]
Each File in Telegram Server has FileID, I need to send file with FileID without Upload it each time @paulkrupin

**Comment by paulkrupin** [comment]
@PurTahan As I see in package 13.0.1.0 struct FileToSend have FileID field. And it also has a constructor with override only to set FileID.  Maybe it is what you want?

**Comment by PurTahan** [comment]
Can you check it @paulkrupin ?

**Comment by paulkrupin** [comment]
@PurTahan Not right now. Maybe when I will be at home and will have free time.

**Comment by pouladpld** [comment]
@PurTahan Yes, you can do that. Here is an example:

```c#
Message msg, msg2;
using (var stream = new FileStream("path/to/photo.png", FileMode.Open))
{
    msg = await client.SendPhotoAsync(chatId, stream.ToFileToSend("photo.png"));
}

msg2 = await client.SendPhotoAsync(otherChatId, new FileToSend(msg.Photo.First().FileId));
```
