### ISSUE TITLE
Sending using a bot.SendVideoNoteAsync with an mp4 via url 

### ISSUE THREAD

**Issue by cosimochellini** [TelegramBots/telegram.bot#407]
### Steps to reproduce
 bot.SendVideoNoteAsync(message.Chat.Id, new FileToSend(new Uri("http://url.com/myVideoNote.mp4")));

### Expected  behavior
Should send a videoNote

### Actual behavior
Send a normal video

*NuGet Package Version:* (e.g. 13.0.1)
version : 13.0.1

**Comment by pouladpld** [comment]
@cosimochellini Telegram doesn't support this.

<https://core.telegram.org/bots/api#sendvideonote>

> Sending video notes by a URL is currently unsupported.

**Comment by pouladpld** [comment]
Having `FileToSend` with a `Url` property is wrong for this `SendVideoNoteAsync` method.

**Comment by pouladpld** [comment]
@MrRoundRobin What do you think about making `FileToSend` a class and subclass it for cases like sending video note that doesn't allow urls?

**Comment by Olfi01** [comment]
@pouladpld you mean like InputFile in the docs? and after all, this is not really a bug...

**Comment by pouladpld** [comment]
We should remove `FileToSend` struct and use `InputFileBase`  abstract class. Here are the only 3 ways input files are used:

- `setWebhook` accepts a file Stream only
- many methods accepts all 3: Stream, url, file_id
- `sendVideoNote` accepts Stream and file_id

so this could be our hierarchy:

```
InputFileBase --> InputFile1(stream) --> InputFile2(stream & file_id) --> InputFile3(all 3 kinds of input)
````

**Comment by pouladpld** [comment]
Fixed in v14
