### ISSUE TITLE
New Line problem in PhotoMessages

### ISSUE THREAD

**Issue by emran17** [TelegramBots/telegram.bot#409]
I think , It's a problem in new update .
"\n" or Environment.NewLine dont affect the caption of photo messages.
It shows \n in the caption.
------------------------------
I dont changed my codes ! but after update ! this problem happend .
NuGet Package Version: (13.1.0)

**Comment by pouladpld** [comment]
@emran17 Thanks for the report. Here is the fix: <https://github.com/TelegramBots/telegram.bot/commit/cc8da5ff9c3daa001fd54a265534128c30143417>

**Comment by pouladpld** [comment]
@Olfi01 Regarding this issue, could you reapond my commemts on your commit here: <https://github.com/TelegramBots/telegram.bot/commit/b1924b92e543f9b51642706dfe96a05edef0ec98>

**Comment by Olfi01** [comment]
i guess this will work, but you should try uploading anything via multipart in a channel to see if the error reocurrs
shouldn't though

**Comment by pouladpld** [comment]
@Olfi01 Got it. I'll test that.

**Comment by pouladpld** [comment]
@Olfi01 I tested my fix <https://github.com/TelegramBots/telegram.bot/commit/cc8da5ff9c3daa001fd54a265534128c30143417> with posting messages to a public channel. It works fine.

**Comment by Olfi01** [comment]
Well done then, its fixed ;)

**Comment by emran17** [comment]
I dont use githum ! I installed it , from nuget ! when you will update nuget for fixing bugs ?

**Comment by pouladpld** [comment]
@emran17 Fixes are ready to be merged. Just waiting for @MrRoundRobin to reply.

**Comment by pouladpld** [comment]
@emran17 I have updated this package for the time being:
<https://nuget.org/packages/Telegram.Bot.Core/>

Get version 13.2.0.

**Comment by pouladpld** [comment]
If any one wonders why I put this fix in another package (`.Core`), have a look at #425
