### ISSUE TITLE
Apply as a member of TelegramBots

### ISSUE THREAD

**Issue by Olfi01** [TelegramBots/telegram.bot#410]
Is there any way to apply as a member of the TelegramBots organization? I'd love to be one :wink:

**Comment by pouladpld** [comment]
@MrRoundRobin What do you think about adding @Olfi01 ?
He has done good contributions to the project and I'd like to have him as a member.
If you don't reply in the next few days, I'll add him.

**Comment by MrRoundRobin** [comment]
sorry for the delay, now I have more time for this, i promise ;) 

i'll add him

I try to add a contributing file with some Code style and such...

**Comment by pouladpld** [comment]
@MrRoundRobin Alright. I'll start writing it.
