### ISSUE TITLE
InlineKeyboardButton in 13.1.0

### ISSUE THREAD

**Issue by aliarak** [TelegramBots/telegram.bot#412]
hi
How to use InlineKeyboard in new update 13.1.0
thanks

**Comment by pouladpld** [comment]
```c#
var replyMarkup = new InlineKeyboardMarkup(new InlineKeyboardButton[]
{
    new InlineKeyboardCallbackButton("Notify", "Show Notification"),
});

Message message = await BotClient.SendTextMessageAsync(
    myChatId,
    "Please click on *Notify* button.",
    ParseMode.Markdown,
    replyMarkup: replyMarkup);
```

**Comment by majid23** [comment]
I create helper method for that. I hope help you.

[https://stackoverflow.com/a/46648523/1920975](url)

**Comment by pouladpld** [comment]
@majid23 That's interesting. I have made [a similar implementation](https://github.com/pouladpld/BusVbot/blob/master/src/BusVbot/Services/Agency/AgencyMessageFormatterBase.cs#L25-L42).

Feel free to make a PR for such as extension methods.

**Comment by majid23** [comment]
@pouladpld thanks for your suggestion i changed [function](https://stackoverflow.com/a/46648523/1920975) as your code.
that's fantastic.
thanks.
