### ISSUE TITLE
waiting for user reply and validate it

### ISSUE THREAD

**Issue by irghost** [TelegramBots/telegram.bot#414]
is that possible?
keep waiting for each user reply and validate it?

**Comment by pouladpld** [comment]
I also looked into that but couldn't find a nice way.

What kind of project is that(console, asp.net,...)?

If you look at some of the tests on `dev` branch, you can see how I implemented a 2 minute wait for user to reply.

**Comment by pouladpld** [comment]
Here, for example, bot sends a message with inline button, **waits for user to click on it**, and answers _Got it!_

<https://github.com/TelegramBots/telegram.bot/blob/dev/test/Telegram.Bot.Tests.Integ/CallbackQuery/CallbackQueryTests.cs#L56-L79>

This isn't a really good solution but code reads just like a synchronous method.

**Comment by irghost** [comment]
windows service  C#
robot should get some info from user and register the user in database

**Comment by pouladpld** [comment]
OK. Look at that example, it might help.

Anyways, Bot API calls are async HTTP messages so I don't see a clean reliable way for writing such codes.
