### ISSUE TITLE
update.Message.MessageId is always 0 on webhook

### ISSUE THREAD

**Issue by sijav** [TelegramBots/telegram.bot#422]
### Steps to reproduce
install update 13
1. start a webhook
2. receive any messages and check for messageId (it's 0)

### Expected  behavior
parse the correct message_id

### Actual behavior
probably cannot parse message_id to MessageId?

### Environment data

*NuGet Package Version:* 4.2.0
*.NET Version:* 4.6.2
*IDE:* VS2017
*App:* Desktop

### More Info
Got this update as Json
```
{"update_id":969****25,
"message":{"message_id":68,"from":{"id":964***14,"first_name":"***","username":"***","language_code":"en-US"},"chat":{"id":-1001******332,"title":"***","type":"supergroup"},"date":1502169772,"text":"1"}}
```
And then this had been parsed
```
ParsedUpdate:{"Id":0,"Message":{"MessageId":0,"From":{"Id":964***14,"FirstName":null,"LastName":null,"Username":"***","LanguageCode":null},"Date":"\/Date(-62135596800000)\/","Chat":{"Id":-1001******332,"Type":3,"Title":"***","Username":null,"FirstName":null,"LastName":null,"AllMembersAreAdministrators":false,"Photo":null,"Description":null,"InviteLink":null},"ForwardFrom":null,"ForwardFromChat":null,"ForwardFromMessageId":0,"ForwardDate":null,"ReplyToMessage":null,"EditDate":null,"Text":"1","Entities":[],"EntityValues":[],"Audio":null,"Document":null,"Game":null,"Photo":null,"Sticker":null,"Video":null,"Voice":null,"VideoNote":null,"Caption":null,"Contact":null,"Location":null,"Venue":null,"NewChatMember":null,"NewChatMembers":null,"LeftChatMember":null,"NewChatTitle":null,"NewChatPhoto":null,"DeleteChatPhoto":false,"GroupChatCreated":false,"SupergroupChatCreated":false,"ChannelChatCreated":false,"MigrateToChatId":0,"MigrateFromChatId":0,"PinnedMessage":null,"Invoice":null,"SuccessfulPayment":null,"Type":1},"EditedMessage":null,"InlineQuery":null,"ChosenInlineResult":null,"CallbackQuery":null,"ChannelPost":null,"EditedChannelPost":null,"ShippingQuery":null,"PreCheckoutQuery":null,"Type":1}
```

**Comment by sijav** [comment]
It looks like every underline can't be parse correctly? but why? am I missing something here? this thing was working perfectly before...

**Comment by sijav** [comment]
***WorkAround***
I could make it by doing this at the start of the Post controller:
```
var req = Request.InputStream;
req.Seek(0, SeekOrigin.Begin);
string json = new StreamReader(req).ReadToEnd();
var update = JsonConvert.DeserializeObject<Update>(json);
```
now update has been bind perfectly

**Comment by Olfi01** [comment]
How did you parse the update before you used Newtonsoft.Json?

**Comment by sijav** [comment]
@Olfi01 Sorry I couldn't understand what are you trying to say,
I've added `using Newtonsoft.Json;` to the top of the file and then trying to deserialize it after getting the value manually with `Request.InputStream`. Then I read from 0 to the end of the Input and it'll give me a string that telegram would send me on update, so I just parse it with `JsonConvert.DeserializeObject<Update>` Command to `Update` class

**Comment by Olfi01** [comment]
I mean, how was the input handled before you used that workaround?

**Comment by sijav** [comment]
@Olfi01 Oh the ASP.NET MVC would automatically bind the form data into action's method arguments (which in this case `Update` class) however It won't bind the first_name into FirstName if our Update class name had first_name property instead of FirstName telegram it could be bind automatically to Update class and so on...

**Comment by Olfi01** [comment]
that seems to be a problem in your asp.net config, can you show the file with the url mapping to me?

**Comment by sijav** [comment]
@Olfi01 
Well I don't have a url mapping I'm using Asp.Net MVC and I have a Controller named `Bot` and an Action named `Post` so ...
```
public class BotController : Controller
{
    [HttpPost]
    public async Task Post(Update update)
    {
    ....
    }
    ....
}
```
I use webhook so I already run this command
`await Bot.SetWebhookAsync("https://domain.net/Bot/Post", new FileToSend("FileName.pem", System.IO.File.OpenRead(Server.MapPath("~/Path/To/File.pem"))), 100, new Telegram.Bot.Types.Enums.UpdateType[] { Telegram.Bot.Types.Enums.UpdateType.All });`
And the `RouteConfig` is
```
	public class RouteConfig
	{
		public static void RegisterRoutes(RouteCollection routes)
		{
			routes.IgnoreRoute("{resource}.axd/{*pathInfo}");

			routes.MapRoute(
				name: "Default",
				url: "{controller}/{action}/{id}",
				defaults: new { controller = "Home", action = "Index", id = UrlParameter.Optional }
			);
		}
	}
```
Which is the default route config of an ASP.NET MVC application default routing config, everything is basically a default config... 
Web.Config is the default one of course with my database connection inside added.
And that's it.

**Comment by Olfi01** [comment]
wait, let me research how asp.net handles json data...

**Comment by Olfi01** [comment]
okay, found it. apparently the serialization is done by a class that does not recognize jsonObject attributes. that means you should just change the argument of the controller to `string input` and then call `Update u = JsonConvert.DeserializeObject<Update>(input);`

**Comment by VahidNaderi** [comment]
> okay, found it. apparently the serialization is done by a class that does not recognize jsonObject attributes. that means you should just change the argument of the controller to `string input` and then call `Update u = JsonConvert.DeserializeObject<Update>(input);`

It does not work like that. I had to use @sijav 's workaround. That means reading the input stream from the beginning and deserialize it.

**Comment by JEnriqueZS** [comment]
Even until now with Nuget version 16.0.2, I still need to use @sijav's code and a custom DTO class to make it work properly.

**Comment by karb0f0s** [comment]
> Even until now with Nuget version 16.0.2, I still need to use @sijav's code and a custom DTO class to make it work properly.

read this https://github.com/TelegramBots/Telegram.Bot/issues/835
