### ISSUE TITLE
System.Net.Http.HttpRequestException

### ISSUE THREAD

**Issue by HellScre4m** [TelegramBots/telegram.bot#424]
### Steps to reproduce
Ran [Werewolf](https://github.com/GreyWolfDev/Werewolf) Node inside a windows server 2008 x86 machine.

### Expected  behavior
GetMe should work and the rest lines should be executed.

### Actual behavior
```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---
> System.Net.Http.HttpRequestException: An error occurred while sending the requ
est. ---> System.Net.Http.WinHttpException: The parameter is incorrect
   at System.Net.Http.WinHttpHandler.SetSessionHandleTlsOptions(SafeWinHttpHandl
e sessionHandle)
   at System.Net.Http.WinHttpHandler.SetSessionHandleOptions(SafeWinHttpHandle s
essionHandle)
   at System.Net.Http.WinHttpHandler.EnsureSessionHandleExists(WinHttpRequestSta
te state)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__103.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__109`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifica
tion)
   at System.Threading.Tasks.Task`1.get_Result()
   at Werewolf_Node.Program.Main(String[] args) in G:\Test\Werewolf\Werewolf for
 Telegram\Werewolf Node\Program.cs:line 102

```
Werewolf Node\Program.cs: 101-2: 
```
Bot = new TelegramBotClient(APIToken);
Me = Bot.GetMeAsync().Result;
```
### Environment data
Mentioned

*NuGet Package Version:* (e.g. 13.0.1)
13.2.0
*.NET Version:* (e.g. 4.7, Core RTM, Mono, etc.)
4.6
*IDE:* (e.g. VS2017, VS Code, etc.)
VS2017
*App:* (e.g. Desktop, iOS, Android, etc.)

Don't have much ability to debug as I'm running on a windows server 2008 without VS (Supports only VS2010 and before), I just moved compiled code from my PC (both Any CPU and x86 configs) and I get this error.

**Comment by pouladpld** [comment]
@HellScre4m I know this is not helpful, but what is Werewolf? What users can do with it?

**Comment by Olfi01** [comment]
@pouladpld its a game.

**Comment by HellScre4m** [comment]
@pouladpld yes @Olfi01 is right. It's a game bot which is popular these days.

**Comment by Olfi01** [comment]
@HellScre4m did you possibly not set the bot API token right?

**Comment by Olfi01** [comment]
you need to put it in the registry yk

**Comment by HellScre4m** [comment]
@Olfi01 I know it should be in the registry. Well due to some bug (really strange) OpenSubKey() returns null while keys are present (subkey names can be printed).
So I embedded token in the program code, it's not null nor empty.
`APIToken = "354413390:AAECAMwFJVn1D8p3wNAltQyH4xhe6XnRMA0";
`this line is just before
`Bot = new TelegramBotClient(APIToken);
`

**Comment by Olfi01** [comment]
1. maybe edit your token out of the comment
2. please look at the inner exception of the one fired and send ot here

**Comment by Olfi01** [comment]
*it

**Comment by HellScre4m** [comment]
I can put prints in whatever code line (including Telegram.Bot.TelegramBotClient.cs) you ask for test.
And about inner exception I have no ideas, this is the full stack trace I pasted in the first comment.

**Comment by Olfi01** [comment]
maybe try
```c#
var t = Bot.GetMeAsync();
t.Wait()
Me = t.Result;

**Comment by Olfi01** [comment]
that could work, or fire a more detailed error

**Comment by HellScre4m** [comment]
```

Unhandled Exception: System.AggregateException: One or more errors occurred. ---
> System.Net.Http.HttpRequestException: An error occurred while sending the requ
est. ---> System.Net.Http.WinHttpException: The parameter is incorrect
   at System.Net.Http.WinHttpHandler.SetSessionHandleTlsOptions(SafeWinHttpHandl
e sessionHandle)
   at System.Net.Http.WinHttpHandler.SetSessionHandleOptions(SafeWinHttpHandle s
essionHandle)
   at System.Net.Http.WinHttpHandler.EnsureSessionHandleExists(WinHttpRequestSta
te state)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__103.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__109`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at Werewolf_Node.Program.Main(String[] args) in G:\Test\Werewolf\Werewolf for
 Telegram\Werewolf Node\Program.cs:line 103

```
Line 103:  ` var t = Bot.GetMeAsync();`

**Comment by Olfi01** [comment]
what. the exception should normally be fired at .Wait()

**Comment by HellScre4m** [comment]
I double checked. The exception occurs at line 103 means GetMeAsync throws it.

**Comment by Olfi01** [comment]
hm... have you tried to debug step-by-step and look into `Bot` right before that line?

**Comment by Olfi01** [comment]
Your stacktrace says the parameter is incorrect, but GetMe doesn't send any parameters at all... strange.

**Comment by HellScre4m** [comment]
I'm not sure if I can put debugging prints in Telegram.Bot itself cause two days ago project switched to use NuGet, but I will give it a try. Thanks

**Comment by Olfi01** [comment]
i meant you should only debug your werewolf app step by step and look at the `Bot`object whether you see anything strange

**Comment by HellScre4m** [comment]
I understand, but the machine which seems exception (probably bug) occurs at is not capable of running VS. I try installing VS2010 and see what I can do.

**Comment by Olfi01** [comment]
if that doesnt help you can also try
```c#
try
{
var t = Bot.GetMeAsync();
t.Wait()
Me = t.Result;
}
catch (Exception x)
{
Console.WriteLine(x.Message + "\n" + x.StackTrace);
if (x.InnerException != null) Console.WriteLine(x.InnerException.Message + "\n" + x.InnerException.Stacktrace);
}
```

**Comment by HellScre4m** [comment]
I'm sorry but that's what I get:
```
One or more errors occurred.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at Werewolf_Node.Program.Main(String[] args) in G:\Test\Werewolf\Werewolf for
 Telegram\Werewolf Node\Program.cs:line 105
An error occurred while sending the request.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__109`1.MoveNext()
UpdateNodeInfo
UpdateNodeInfo

```
I also ensured that token is not null. Also because of catching exception Node goes on but does nothing.

**Comment by HellScre4m** [comment]
I highly suspect this is because of incompatibility between OS and library cause in my own PC this error doesn't occur. (Other errors occur which are not related to Telegram.Bot library)
As you see HttpClient can't handle whatever it is. Don't know how can I help through finding out more details, please tell me.

**Comment by Olfi01** [comment]
I'm sorry to tell you, but OS incompatibility problems are where my knowledge ends. Maybe @pouladpld knows something about that...

**Comment by HellScre4m** [comment]
I found this. Don't know if it helps or not (too much detailed, couldn't fully understand):
https://stackoverflow.com/questions/41700869/bug-when-using-await-async-for-system-net-http-with-net-core-net-standard-1-4

**Comment by Olfi01** [comment]
I believe I understand what it says, which version of visual studio do you use? (the way of fixing it differs)

**Comment by HellScre4m** [comment]
I use VS2017 to compile the code

**Comment by Olfi01** [comment]
then you should add this into your app.config (if i understood stackoverflow correctly):
```
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.0.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by HellScre4m** [comment]
I'm sorry but seems app.config of "Werewolf Node" project already contains these lines.

**Comment by Olfi01** [comment]
are they exactly the same? cause then I have no idea at all. Stackoverflow only suggested this.

**Comment by armanforghani** [comment]
I have a same problem.

**Comment by HellScre4m** [comment]
I suggest you debug with @armanforghani as maybe he doesn't suffer my limitations. 
Regards

**Comment by parabola949** [comment]
Couple things to throw out there:
 - I've modified the Telegram.Bot library again in the werewolf source.  Please try the latest commit.
 - @pouladpld Sorry, this issue is for Werewolf, you can close this issue
 - @HellScre4m if you are using the NuGet package, please make sure you are using Telegram.Bot.Core, the newer package.  There was an odd bug in `13.1.0` (Telegram.Bot), moving to Telegram.Bot.Core fixes it.

**Comment by pouladpld** [comment]
@parabola949 Thank you for the reply. If you have any suggestions to make this project more flexible and convenient to use, feel free to let us know.

**Comment by speekflayder** [comment]
Still have the same problem. Did anyone solve this issue?
