### ISSUE TITLE
Where is newest version (13.2.0)?!

### ISSUE THREAD

**Issue by Ramin-Bateni** [TelegramBots/telegram.bot#425]
I have [this problem](https://github.com/TelegramBots/telegram.bot/issues/334) and @pouladpld finally forwarded us to version **13.2.0** but its linked Nuget address is different with Nuget address of homepage of this project. It gose to https://www.nuget.org/packages/Telegram.Bot.Core/

I want resolve this problem in my bot and i should fix it fast but I confused!
Should I uninstall Telegram.Bot package from my project and continue this project by Telegram.Bot.Core from today? Or ...

**Comment by pouladpld** [comment]
@Ramin-Bateni It's been a while that @MrRoundRobin isn't active here so I fixed some bugs (see [milestone v13.2.0](https://github.com/TelegramBots/telegram.bot/milestone/3)) and updated `.Core` package.

Using that package shouldn't introduce any breaking change into your app and you can continue using the original package whenever @MrRoundRobin updates that.
