### ISSUE TITLE
EditInlineMessageReplyMarkupAsync Not Worked in Bot Chat 

### ISSUE THREAD

**Issue by PurTahan** [TelegramBots/telegram.bot#426]
Hi , `EditInlineMessageReplyMarkupAsync` with `inlineMessageID` work fine in `any chat` , **but** not work in `Bot Chat`

**Comment by pouladpld** [comment]
I'm pretty sure this is due to the same reason as #372

**Comment by pouladpld** [comment]
@PurTahan 
I tested this method and it works fine. Are you sure you passed a inlineMessageId properly to it?

**Comment by pouladpld** [comment]
@PurTahan Check the tests I wrote for this here: <https://github.com/TelegramBots/telegram.bot/commit/83313783c9204df77b4fd8bbde5c73d838359fbf>
