### ISSUE TITLE
Send InLine message to channel with bot

### ISSUE THREAD

**Issue by PurTahan** [TelegramBots/telegram.bot#430]
Is it possible to Send `InlineMessage` to **Channel** with Bot **Automatically** ?  

in `InlineMessage` after trying **user** to use Inline method Telegram sends `InlineQueryUpdate`, after that Bot should `AnswerInlineQuery` with `InlineQueryResults`. and then, User after select any of `InlineQueryResults` , Result is Send to user.  

In **channel** because no body there to select any of Results, `InlineKeyboardSwitchInlineQueryButton` is **removed** from Markup.

So, What we can do?

**Comment by pouladpld** [comment]
@PurTahan Not sure if I got your question but only channel admins can post an inline message from bot to channel. After message is posted to channel, any member can click on its inline buttons.

**Comment by pouladpld** [comment]
@PurTahan Did you get your answer? I close this but feel free to continue the discussion.
