### ISSUE TITLE
Readme.md example is not correct.

### ISSUE THREAD

**Issue by miladamirzadeh** [TelegramBots/telegram.bot#437]
### Steps to reproduce
In readme.md example section tells about usage `var Bot = new Telegram.Bot.Api("your API access Token");` but the correct way with latest version is: `var bot = new Telegram.Bot.TelegramBotClient("your API access Token");`

### Environment data

*NuGet Package Version:* 13.1.0

*.NET Version:* 4.6 & dotnet core 2.0.0

*IDE:* Both VS2017 on windows and VS Code on Ubuntu 16.04

**Comment by parabola949** [comment]
Created PR #438
