### ISSUE TITLE
Next steps to take

### ISSUE THREAD

**Issue by poulad** [TelegramBots/Telegram.Bot#439]
What do you think would be good to implement here?

Let's discuss and prioritize them to see what is going to be in the next release.

**Comment by pouladpld** [comment]
I'm thinking of more exception types that inherit from `ApiException`.

Almost all of the 404 responses have a reason in the format of `Bad Request: EXCEPTION_TYPE`.

Using integ tests, we can find them all. [example here](https://github.com/TelegramBots/telegram.bot/blob/develop/test/Telegram.Bot.Tests.Integ/AdminBots/AdminBotTests.cs#L129-L137)

**Comment by pouladpld** [comment]
I created `@tgbots_dotnet` chat on Telegram. Feel free to join.

**Comment by pouladpld** [comment]
Overriding `ToString()` on Update, Message, and other types helps a lot with creating meaningful logs.

```c#
// when update.Type == MessageUpdate
"MessageUpdate from 1234567 in chat -987654 on Aug 27, 2017 12:34."
```

**Comment by MasihAkbari** [comment]
@tgbots_dotnet chat is not available and nowhere to be seen

**Comment by pouladpld** [comment]
@MasihAkbari A few users (or their tg clients) have issues joining our public supergroup. We don't know why. Try contacting tg support to resolve it.

(Your message is unrelated to this issue. please remove it from here)

**Comment by poulad** [comment]
We might be able to use Selenium for e2e testing. It can be used on the tg web client to perform the actions required for interactive testing.

It can add a huge benefit to our build and release process.

**Comment by poulad** [comment]
We might be able to use Selenium for e2e testing. It can be used on the Telegram web client to perform the actions required for interactive testing.

That would add a huge benefit to our automated build and release process.

**Comment by rafacc87** [comment]
Add [messages.getAllChats](https://core.telegram.org/method/messages.getAllChats) and [API channel](https://core.telegram.org/api/channel)

**Comment by Fedorus** [comment]
> Add [messages.getAllChats](https://core.telegram.org/method/messages.getAllChats) and [API channel](https://core.telegram.org/api/channel)

That is not part of bot api...

**Comment by wiz0u** [comment]
I don't see any good suggestion in here, and we have a chat group to discuss anyway. Closing this.
