### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by Olfi01** [TelegramBots/Telegram.Bot#442]
What would you think about some useful extensions right inside the lib? For exampe, `User.IsSameAs(User u)` or `User.FullName{ get => $"{this.FirstName} {this.LastName}".Trim() }`

**Comment by pouladpld** [comment]
Sounds good. we could put the extension methods in `Telegram.Bot.Types` namespace for convenience.

Here are the suggestions I had:

```c#
bool isSameUser = someUser.IdEquals(otherUser);
bool hasSameSender = someUpdate.IsFromSameUserId(otherUser); // for messages, channel posts, callback query,...
int? msgId = someUpdate.TryGetMessageId(); // for messages, channel posts, callback query,...
long? chatId = someUpdate.TryGetChatId(); // for messages, channel posts, callback query,...
string queryIdOrNull = someUpdate.TryGetCallbackQueryId();
```

I hope users of the project participate here and share what they need to be added here.

**Comment by Olfi01** [comment]
I'd also suggest EditMessageTextAsync(Message msg, string text) and similar ;)

**Comment by pouladpld** [comment]
Hmm. That could be handy. As an extension method, that could be

```c#
await someCallbackQueryUpdate.CallbackQuery.Message
   .EditMessageTextAsync("Edited message");
```

**Comment by karb0f0s** [comment]
Closed due to inactivity. Due to recent decision this can be implemented in extension package rather than in the library. Library stays as close to pure API as possible.
