### ISSUE TITLE
Stickers api not work

### ISSUE THREAD

**Issue by KungA** [TelegramBots/telegram.bot#444]
`await bot.GetStickerSetAsync("EvilMinds")` returns 404.

I use fiddler and see, that sticker name not included in uri.

Also `AddStickerToSetAsync` and `CreateNewStickerSetAsnyc` not working.

### Environment data
*NuGet Package Version:*  13.1.0

*.NET Version:* 4.5.2

*IDE:* VS2017

*App:* Windows

**Comment by KungA** [comment]
Seems it fixed in current version of git, so please update nuget package to `13.2.1`.

**Comment by pouladpld** [comment]
@KungA That is fixed now. Use the latest version instead.
<https://www.nuget.org/packages/Telegram.Bot.Core/13.2.2-rc> 

Check project's readme file as well (just updated).

**Comment by KungA** [comment]
Before I used https://www.nuget.org/packages/Telegram.Bot/.
Now I use Telegram.Bot.Core/13.2.2-rc.

GetStickerSetAsync is working now, but AddStickerToSetAsync still none.
`ERROR Telegram.Bot.Exceptions.ApiRequestException: Bad Request: STICKERSET_INVALID`.

**Comment by pouladpld** [comment]
@KungA make sure that `name` parameter you pass belongs to a sticker set you own.
See tg docs: <https://core.telegram.org/bots/api#addstickertoset>

**Comment by pouladpld** [comment]
Unfortunately, we don't have tests for this API method and since you are working on stickers, it would be great if you could take some time to write 1 or 2 methods to test that in this class:

<https://github.com/TelegramBots/telegram.bot/blob/develop/test/Telegram.Bot.Tests.Integ/Stickers/StickersTests.cs>

**Comment by KungA** [comment]
Finally I understand:
1. Use `bot.CreateNewStickerSetAsnyc` to create set owned by your bot
2. Use `bot.AddStickerToSetAsync` with your new sticker set
Note: Short name of sticker set, to be used in t.me/addstickers/ URLs (e.g., animals). Can contain only english letters, digits and underscores. Must begin with a letter, can't contain consecutive underscores and must end in “_by_<bot username>”. <bot_username> is case insensitive. 1-64 characters.

**Comment by KungA** [comment]
Ok, I'll try to write some tests here.

**Comment by pouladpld** [comment]
Great. Here are some info about our testing framework:

<https://github.com/TelegramBots/telegram.bot/blob/develop/docs/wikis/tests/sys-integ-tests.md>
