### ISSUE TITLE
Updating Nuget package

### ISSUE THREAD

**Issue by armanforghani** [TelegramBots/telegram.bot#446]
@pouladpld 
Is there any plan to update Nuget package? I have some problems (#424) with the last stable release on Nuget.

**Comment by MrRoundRobin** [comment]
I'll Try to do this this week

**Comment by pouladpld** [comment]
@armanforghani use `.Core` package till @MrRoundRobin updates the original one. As @parabola949 mentioned there, the bug is fixed but not updated in original package yet.

<https://www.nuget.org/packages/Telegram.Bot.Core>
