### ISSUE TITLE
ChatId comparation bug

### ISSUE THREAD

**Issue by ImoutoChan** [TelegramBots/telegram.bot#447]
### Steps to reproduce
There is strange behavior in comparing two ChatId objects, that were received form GetMeAsync and from message.ReplyToMEssage.From.Id

Here is a log from immediate window:

```
_me.Id
{307109576}
message.ReplyToMessage.From.Id
{307109576}
message.ReplyToMessage.From.Id == _me.Id
false
Equals(message.ReplyToMessage.From.Id, _me.Id)
false
_me.Id.Equals(message.ReplyToMessage.From.Id)
false
message.ReplyToMessage.From.Id.Equals(_me.Id)
false
Equals(message.ReplyToMessage.From.Id, _me.Id)
false
(string)message.ReplyToMessage.From.Id == (string)_me.Id
true
(string)message.ReplyToMessage.From.Id == _me.Id
true
message.ReplyToMessage.From.Id == (string)_me.Id
true
message.ReplyToMessage.From.Id == _me.Id
false
```

### Expected  behavior
Comparing two ChatId objects should compare their values. Or at least ChatId should has public properties with identifier/username.

### Actual behavior
I'm not sure, how it works now. Probably this:
`public override bool Equals(object obj) => ((string)this).Equals((string)obj);`
could fix it. Or since we have already overridden GetHashCode method, we should use in Equals method too.

### Environment data

NuGet Package Version:* 13.1.0

.NET Version: .net core 1.1

IDE: VS2017

**Comment by pouladpld** [comment]
@ImoutoChan type of `User.Id` is now `Int32`. Please use `.Core` package till @MrRoundRobin updates the original package.(see project's README)

<https://www.nuget.org/packages/Telegram.Bot.Core>
