### ISSUE TITLE
Sending Message with Disable Notification : true Not Work

### ISSUE THREAD

**Issue by emran17** [TelegramBots/telegram.bot#449]
Hi ,
sending messages  methods like : SendPhotoAsync , SendTextMessageAsync , ... 
with parameter -> disableNotification: true 
have notification sound !!!
I'm Sure it is an problem , it was correct in previous versions . 
please check it , and tell me if I'm wrong ! 
thank you !

Telegram.Bot.Core 
Nuget Package 13.2.2-rc

**Comment by Olfi01** [comment]
Can you please specify which method you were using, what client and and what version, and which IDE... We don't have an issue template for nothing.

**Comment by armanforghani** [comment]
I can confirm there is this bug. I have the same problem.

**Comment by pouladpld** [comment]
@emran17 @armanforghani 
It works fine for me. This is something as simple as `{ "disable_notification": true }` to pass to tg API and this library does send it.

If this is a bug, I can't reproduce it so I suspect this might be related to your phone settings or the tg client app installed.

**Comment by pouladpld** [comment]
Something else to consider is the number of messages the client is receiving at the moment of getting updates. I guess if tg client gets 3 message updates in a row, first message having notification sound and the other 2 disabling it, client plays sound anyways.

**Comment by heine-it-yh** [comment]
@Olfi01 I have the same probem.
Method: direct call of URL (https://api.telegram.org/botXXXX:XXXX/sendMessage?chat_id=XXXX&disable_notification=true&text=Test3)
Client: Telegram web and desktop. Both play a notification sound regardless of the disable flag.

Unfortunately I did not find your mentioned issue template, if you could point it out to me, I'll fill out everything as needed!

**Comment by heine-it-yh** [comment]
This seems to be a telegram bug in the web version. Even on direct api call via https web version still plays notifocation sound, whereas desktop and android version don't.
