### ISSUE TITLE
Message box

### ISSUE THREAD

**Issue by sorankurds** [TelegramBots/telegram.bot#450]
Hello, is there any way to build a message box in telegram.bot?

**Comment by Olfi01** [comment]
I suppose you want to answer a callback query with `bot.AnswerCallbackQueryAsync(callbackQuery.Id, "some text", showAlert: true);`

**Comment by sorankurds** [comment]
> Thank you

**Comment by Olfi01** [comment]
i will close this issue then, if you need any further information, feel free to reopen it :)
