### ISSUE TITLE
Delete Message in Supergroups

### ISSUE THREAD

**Issue by cRUSHER-ScriptBase** [TelegramBots/telegram.bot#452]
Hi, 
I have a question how i can remove messages in a super group. I have currently a super group and the bot is also admin. One of the problems is that the bot is dont receiving any messages from the c# api but if i make it with https://api.telegram.org/bot.../getUpdates i get all messages from the chat. Pls help me i dont know what i can do from here on. I have tried every event like here: https://github.com/TelegramBots/telegram.bot.examples/blob/master/Telegram.Bot.Examples.Echo/Program.cs 
Good Regards,
cRUSHER

**Comment by Olfi01** [comment]
could you supply us with the code you are using?

**Comment by pouladpld** [comment]
@cRUSHER-ScriptBase follow this template please.

<https://github.com/TelegramBots/telegram.bot/blob/develop/ISSUE_TEMPLATE.md>

**Comment by cRUSHER-ScriptBase** [comment]
this code i am using for this situation: 

class Program	
{
	private static readonly TelegramBotClient Bot = new TelegramBotClient("");

	private static async void BotOnMessageReceived(object sender, MessageEventArgs messageEventArgs)
    {
        var message = messageEventArgs.Message;

        await Bot.DeleteMessageAsync(message.Chat.Id, message.MessageId);
    }

    static void Main(string[] args)
    {
        Bot.OnMessage += BotOnMessageReceived;
        Bot.OnMessageEdited += BotOnMessageReceived;

        Bot.StartReceiving();
        Console.ReadLine();
        Bot.StopReceiving();
    }
}

**Comment by cRUSHER-ScriptBase** [comment]
The "" by TelegramBotClient ist not empty.

**Comment by Olfi01** [comment]
The bot will only receive the message if it's admin or the message is a reply to a message from the bot or there's a command in the message. Or, of cause, if you turned privacy mode off at [@BotFather](t.me/BotFather)

**Comment by cRUSHER-ScriptBase** [comment]
The Bot is a Admin and the privacy mode is off. The group is a supergroup

**Comment by pouladpld** [comment]
@cRUSHER-ScriptBase I'm closing this because you don't [follow issue template](https://github.com/TelegramBots/telegram.bot/blob/develop/ISSUE_TEMPLATE.md) and we can't help you further without that. Feel free to open it and complete the template.
