### ISSUE TITLE
why only Updat.Message.Contact.UserId is filled when user shares contact ?

### ISSUE THREAD

**Issue by mz1368** [TelegramBots/telegram.bot#453]
I use a keyboard that  RequestContact=true but when user shares your contact to bot i get updatemessage that include null value and only userid is filled.

I get contact object from this way  update.message.contact and when i get location i can get location object from same way correctly .

*NuGet Package Version:* (e.g. 13.0.1)

*.NET Version:* (e.g. 4.7, Core RTM, Mono, etc.)

*IDE:* (e.g. VS2017, VS Code, etc.)

*App:* (e.g. Desktop, iOS, Android, etc.)

**Comment by pouladpld** [comment]
@mz1368 I haven't checked that version but try updating your NuGet package reference to the latest version.

Have a look at its test as well:
<https://github.com/TelegramBots/telegram.bot/blob/more-tests/test/Telegram.Bot.Tests.Integ/SendingMessages/MessageReplyMarkupTests.cs#L34-L51>
