### ISSUE TITLE
Telegram API

### ISSUE THREAD

**Issue by ThomasCarlyle** [TelegramBots/telegram.bot#454]
Are you planning to add new **[Telegram API](https://core.telegram.org/#telegram-api)**

**Comment by Olfi01** [comment]
1. This API is not new
2. No, this is the Telegram Bot API, not the client API, which is much more complicated and something completely different. AFAIK there is no complete implementation of that API in .NET yet.

**Comment by gmardok** [comment]
@Olfi01 How about [TLSharp](https://github.com/sochix/TLSharp)?

**Comment by Olfi01** [comment]
@gmardok that one exists, but it does not include all features and it's kinda bugged

**Comment by ThomasCarlyle** [comment]
@Olfi01,@gmardok  thanks for the answer.
