### ISSUE TITLE
how can create dynamically KeyboardButtons for ReplyKeyboardMarkup:"help wanted" 

### ISSUE THREAD

**Issue by djary** [TelegramBots/telegram.bot#455]
How do I define the buttons dynamically? In other words, read the text of the buttons from the database?

I mean, instead of manually defining the "KeyboardButton[][]" ,Like the example below:

`_mainKey = new ReplyKeyboardMarkup()
        {
            Keyboard = new KeyboardButton[][] { new KeyboardButton[] { "BlogPost Category" }, new KeyboardButton[] { "skills", "about me" } },
            OneTimeKeyboard = true,
            ResizeKeyboard = true
        };`
Read the information from the database,for example the keyboard for the "BlogPost Category" must be dynamically created.It is not fixed due to the number of categories and can be added at any time
`_categoriesKey = new ReplyKeyboardMarkup()
        {
            Keyboard = new KeyboardButton[][] { new KeyboardButton[] { "Category1" }, new KeyboardButton[] { "category2", "category2-2" } ,... },
            OneTimeKeyboard = true,
            ResizeKeyboard = true
        };`

can anyone help me ?

**Comment by Tuscen** [comment]
You can make `List<List<KeyboardButton>>`, add all needed buttons to each inner list and then convert this structure to array `KeyboardButton[][]`. For example:
```c#
var categories = new [] { "skills", "about me" };
var rows = new List<List<KeyboardButton>>();

foreach (var category in categories)
{
    var row = new List<KeyboardButton>();
    var button = new KeyboardButton(name);
    row.Add(button);
}

var buttons = rows.Select(row => row.ToArray).ToArray();
var replyMarkup = new ReplyKeyboardMarkup(buttons);// add buttons to as many rows as you want

var buttons = rows.Select(row => row.ToArray).ToArray();
var replyMarkup = new ReplyKeyboardMarkup(buttons);
```

Or you can use Linq:

```c#
var categories = new [] { "skills", "about me" };
var buttons = categories.Select(category => new [] { new KeyboardButton(category) })
    .ToArray();
var replyMarkup = new ReplyKeyboardMarkup(buttons);
```

**Comment by djary** [comment]
tan Q man , very code and  nice worked
but how can create  dynamic inline keyboard?
it seems different way to achieve this goal
