### ISSUE TITLE
Preupload file(question)

### ISSUE THREAD

**Issue by surgerer** [TelegramBots/telegram.bot#463]
HI,
Is there a way upload file, to get FileId or Url, and then use in different chats with one bot?
something like this: 

FileToSend fileToSend = new FileToSend(...);  
await client.UploadFileAsync(fileToSend));

FileToSend fts = new FileToSend(fileToSend.FileId);
await client.SendDocumentAsync(chatId, fts, caption);

**Comment by Olfi01** [comment]
Afaik there is no method for that in the telegram api. Gonna check in a minute.

**Comment by Olfi01** [comment]
Nope, that's impossible. You have to send it to a channel or other chat for that. Sorry.
