### ISSUE TITLE
[ParseMode.Html] Bad Request: can't parse entities in message text: Unexpected end tag at byte offset 0 

### ISSUE THREAD

**Issue by ayazzali** [TelegramBots/telegram.bot#465]
### Steps to reproduce
`"</p>\n<h4>Радио-Т (<a href=\"https://twitter.com/search?q=%23radiot\">#radiot</a>) <a href=\"http://www.radio-t.com/\">site</a>, <a href=\"http://vk.cc/1Fad2N\">itunes</a>, <a href=\"http://pirates.radio-t.com/\">pirates version</a></h4>\n<p>Разговоры на темы хайтек, высоких компьютерных технологий, гаджетов, облаков, программирования и прочего интересного из мира ИТ.</p>\n<p>| Ведущие             | github                                 | twitter                                 |\n| :------------------ | -------------------------------------- | --------------------------------------- |\n| Григорий Бакунов    | <a href=\"https://github.com/bobuk\">@bobuk</a>     | <a href=\"https://twitter.com/bobuk\">@bobuk</a>     |\n| Евгений Борт        | <a href=\"https://github.com/umputun\">@umputun</a> | <a href=\"https://twitter.com/umputun\">@umputun</a> |\n| Сергей Петренко     | <a href=\"https://github.com/grayru\">@grayru</a>   | <a href=\"https://twitter.com/gray_ru\">@gray_ru</a> |\n| Ксения              | <a href=\"https://github.com/ksenks\">@ksenks</a>   | <a href=\"https://twitter.com/ksenks\">@ksenks</a>   |</p>\n<p>"`

i call Bot.SendTextMessageAsync(123123123, %text above%[1],parseMode:ParseMode.Markdown).Wait();
            

### Expected  behavior
just send

### Actual behavior
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PodCastBot.Program.Main(String[] args) in c:\Logs\netcoreapps\PodCastBot\src\PodCastBot\Program.cs:line 69
---> (Inner Exception #0) Telegram.Bot.Exceptions.ApiRequestException: Bad Request: can't parse entities in message text: Unexpected end tag at byte offset 0
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__109`1.MoveNext()<---

### Environment data
netcoreapp2.0

*NuGet Package Version:* (e.g. 13.0.1 and 10 too)

*.NET Version:* (e.g. 4.7, Core RTM, Mono, etc.)

*IDE:* (e.g. VS2017, VS Code, etc.)

*App:* (e.g. Desktop, iOS, Android, etc.)

**Comment by ayazzali** [comment]
or if i have <br> in start like:

> 2017-09-19 21:31:26.1679|ERROR|my name|System.AggregateException: One or more errors occurred. (Bad Request: can't parse entities in message text: Unsupported start tag "br" at byte offset 0) ---> Telegram.Bot.Exceptions.ApiRequestException: Bad Request: can't parse entities in message text: Unsupported start tag "br" at byte offset 0
>    at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__109`1.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Task.Wait()


then:
```
2017-09-19 21:31:26.1679|ERROR|my name|System.AggregateException: One or more errors occurred. (Bad Request: can't parse entities in message text: Unsupported start tag "br" at byte offset 0) ---> Telegram.Bot.Exceptions.ApiRequestException: Bad Request: can't parse entities in message text: Unsupported start tag "br" at byte offset 0
   at Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__109`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
```

**Comment by Olfi01** [comment]
well, at first glance it seems you have not escaped the quotes properly, but i suppose in your code that's fine. but if you use parseMode.markdown, you cannot expect html markdown to be formatted correctly

**Comment by Tuscen** [comment]
I've ran into the same problem. Only a small part of markdown is supported by Telegram. [Supported](https://core.telegram.org/bots/api#markdown-style) subset include links, mentions (Telegram's own thing, just a link with different protocol), italic and bold text, blocks of preformated text (triple backticks) and inline preformated text (single backticks). That's it. No HTML, no table markup like in Github flavored markdown and so on. And no nesting. E.g. you can't make text both bold and italic.
