### ISSUE TITLE
Get UserID of username Custom

### ISSUE THREAD

**Issue by alish123456** [TelegramBots/telegram.bot#466]
hi
How can I import my custom username and Get it UserID??
I follow this code:
But it gives me a zero number

`User user = new User();
user.Username = "userSearch";
int userid = user.Id;

MessageBox.Show(userid.ToString());`

Please help me

**Comment by Olfi01** [comment]
You can't. A bot can get a users id only if they messaged them or are in the same group with them.

**Comment by alish123456** [comment]
@Olfi01 Thankful
One more question
Is it possible Search a username from within the group?
And get that info username?
(There are bot in the group)

**Comment by Olfi01** [comment]
You can GetChatMembersAsync and then search by yourself
