### ISSUE TITLE
only receive messages from me

### ISSUE THREAD

**Issue by arminblack** [TelegramBots/telegram.bot#469]
*NuGet Package Version: 13.2.2-rc *
*.NET Version : 4.5.1*

hey,
i've been using this api for quite a while now but this new version is giving me some problems, one of them is the bot can only recive messages from me, i know it doesn't make sense but i used one of your samples and simply added a handler to my sub to recive messages , and it receives fine for me, but for everyone else the sub doesn't get even called

**Comment by pouladpld** [comment]
@arminblack Ya. You are right. Doesn't make sense. Did you find the fix?
