### ISSUE TITLE
Delete messages

### ISSUE THREAD

**Issue by Sajgonisko** [TelegramBots/telegram.bot#471]
Is there any method to remove a message older than 48 hours using a bot?

**Comment by Dragonsangel** [comment]
There can be no method that can do that since the Telegram Bot API itself does not support it, as referenced here: https://core.telegram.org/bots/api#deletemessage

**Comment by TomaszKisielewski** [comment]
It's not good news :-( I know method #deletetemessage  from BOT API :-)  but I need to delete messages in private channels older then 48 h. But it is impossible - return json from Telegram:
{"ok":false,"error_code":400,"description":"Bad Request: message can't be deleted"}
