### ISSUE TITLE
My program runs without errors, but does not respond.

### ISSUE THREAD

**Issue by mahdibg** [TelegramBots/telegram.bot#472]
Hello
I copied the code in the following path. In VS 2015 Windows application (With a few minor changes)

"https://github.com/TelegramBots/telegram.bot.examples/tree/master/Telegram.Bot.Examples.Echo"

The program runs without errors, but does not respond to messages.

what is the problem?

tanks

**Comment by pouladpld** [comment]
@mahdibg You didn't follow the issue template and gave very little info. No wonder no body commented.
Feel free to edit your post according to the template and reopen this.
