### ISSUE TITLE
How can i use Inlinekeyboard in webhook method ?

### ISSUE THREAD

**Issue by djary** [TelegramBots/telegram.bot#473]
Who knows the answer?
https://stackoverflow.com/questions/46496636/how-can-i-use-inlinekeyboard-in-webhook-method-telegram-bot-c-sharp

**Comment by pouladpld** [comment]
I hope this helps:

https://github.com/TelegramBots/telegram.bot/blob/develop/test/Telegram.Bot.Tests.Integ/CallbackQuery/CallbackQueryTests.cs#L29-L48
