### ISSUE TITLE
restrict/unrestrict 

### ISSUE THREAD

**Issue by sorankurds** [TelegramBots/telegram.bot#474]
Hi
Sometimes I encounter this error:
Bad Request: not enough rights to restrict/unrestrict chat member
What is the reason?

*NuGet Package Version:* (e.g. 13.2.2)

*.NET Version:* (e.g. 4.7, Core RTM, Mono, etc.)

*IDE:* (e.g. VS2017, VS Code, etc.)

*App:* (e.g. Desktop, iOS, Android, etc.)

**Comment by pouladpld** [comment]
Error message is pretty clear. Just see what chat administration methods you are using that causes this.

I close this since it is not about .NET Client. Please ask such questions in our Telegram supergroup.

**Comment by pouladpld** [comment]
Error message is pretty clear. Just see what chat administration methods you are using that causes this.

I close this since it is not about .NET Client. Please ask such questions in our Telegram supergroup.
