### ISSUE TITLE
How to create new MessageEventArgs for Unit test purpose?

### ISSUE THREAD

**Issue by nimbusparis** [TelegramBots/telegram.bot#475]
### Steps to reproduce
new MessageEventArgs()

### Expected  behavior

A factory to instanciate a MessageEventArgs ?

### Actual behavior
constructors of MessageEventArgs are internal, Unit tests cannot instanciate it

### Environment data

*NuGet Package Version:* (13..2.1)

*.NET Version:* (Core 2.0.0)

*IDE:* (VS2017)

*App:* (Bot)

**Comment by Olfi01** [comment]
You are not supposed to create those yourself, so I suggest you maybe create a class extending that one (im not exactly sure if that would work tho)

**Comment by pouladpld** [comment]
@nimbusparis You probably are stubbing the wrong thing in the test. Make your own code to accept a mock object (maybe a mock of `ITelegramClient`)

**Comment by nimbusparis** [comment]
I'm using ITelegramClient interface mocked but the methods use concrete "EventArgs" classes. I was trying to test the message handling from the client by my concrete class.
The best option would be to inherit a dummy class from MessageEventArgs.
