### ISSUE TITLE
how can i get post Count ?

### ISSUE THREAD

**Issue by baiCoder** [TelegramBots/telegram.bot#477]
hi 
how can i get the post count like this ?https://docs.madelineproto.xyz/API_docs/constructors/updateNewChannelMessage.html

**Comment by Olfi01** [comment]
Can you please explain what you want to do? The link you gave there is not very useful

**Comment by baiCoder** [comment]
i want get the post view count of telegram channel

**Comment by pouladpld** [comment]
@baiCoder this is tg bot api not tg client. You can't do it using a bot.
