### ISSUE TITLE
JsonReaderException in SendWebRequestAsync

### ISSUE THREAD

**Issue by Tuscen** [TelegramBots/telegram.bot#478]
I've noticed recently that I get random `Newtonsoft.Json.JsonReaderException`'s during response deserialization from Telegram (I think it's [here](https://github.com/TelegramBots/telegram.bot/blob/develop/src/Telegram.Bot/TelegramBotClient.cs#L2031)). The exception is always the same: 

```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
```

It would be really handy if there was a catch clause in `SendWebRequestAsync` with `JsonReaderException` that throwed custom exception with a raw response from Telegram. Right now I can't even see what was the response that is causing this exception.

*NuGet Package Version:* 13.2.1
*.NET Version:* .NET Core 2.0

**Comment by pouladpld** [comment]
Oh! I guess it should be

```c#
// first make sure it was successful
response.EnsureSuccessStatusCode();

// then try to read the response
responseObject = JsonConvert.DeserializeObject<ApiResponse<T>>(responseString, SerializerSettings); 
```

**Comment by pouladpld** [comment]
Exception handling also doesn't seem ideal. Why looking for string when we can check status codes?!

https://github.com/TelegramBots/telegram.bot/blob/develop/src/Telegram.Bot/TelegramBotClient.cs#L2048
