### ISSUE TITLE
Error while copying content to a stream.

### ISSUE THREAD

**Issue by MahdiHad** [TelegramBots/telegram.bot#479]
Hello

### I wrote the following simple code to get information from the robot. But when the program is running, the following error occurs.

![123](https://user-images.githubusercontent.com/32649301/31352245-e9fe39bc-ad3a-11e7-812c-3af3c099c2bc.png)

### while without problems, I can read the information through the Telegram API.

![124](https://user-images.githubusercontent.com/32649301/31352703-982cc836-ad3c-11e7-8c6d-5fe034d05c0c.png)

What is the cause of the error?
Thankful

**Comment by pouladpld** [comment]
First, follow the issue template. Second, I don't see the bot client statements.
