### ISSUE TITLE
Error while copying content to a stream.

### ISSUE THREAD

**Issue by streppelchen** [TelegramBots/telegram.bot#480]
### Steps to reproduce
            botClient.StartReceiving();
            botClient.OnMessage +=  BotClientOnOnMessage;
---
 ```
private static async void BotClientOnOnMessage(object sender, MessageEventArgs messageEventArgs)
        {
            var message = messageEventArgs.Message;
            if (message.Type == MessageType.VoiceMessage)
            {
                var filePath = Path.Combine("./", message.Voice.FileId + ".ogg");

                using (var file2 = File.OpenWrite(filePath))
                {
                    await botClient.GetFileAsync(message.Voice.FileId, file2);
                    Console.WriteLine("Find Voice at {0}", filePath);
                }
            }
        }
```

### Expected  behavior
A File saved at the specified directory

### Actual behavior
HttpRequestException {"Error while copying content to a stream."}

### Environment data
Windows 7 x64

*NuGet Package Version:* (e.g. 13.0.1)
13.2.1

*.NET Version:* (e.g. 4.7, Core RTM, Mono, etc.)
4.6.1, tested also with 4.5 and 4.6.0 with the same result

*IDE:* (e.g. VS2017, VS Code, etc.)
VS2015 and VS2013, both same result

*App:* (e.g. Desktop, iOS, Android, etc.)
shouldn't matter, but sending voice from the iOS app to the bot.

**Comment by streppelchen** [comment]
A friend has the very same code running for him on W10 x64 with .net 4.6.1

**Comment by pouladpld** [comment]
Probably duplicate of #479
