### ISSUE TITLE
Invalid token format

### ISSUE THREAD

**Issue by samuelg78** [TelegramBots/telegram.bot#482]
### Steps to reproduce
var botClient = new Telegram.Bot.TelegramBotClient("461585999:AAF-5LthqW8mNVo-LEs14b9oV2z6PFCJRcA");

Why does it give "Invalid token format" error?

**Comment by paulkrupin** [comment]
Did you get your token from @Botfather on Telegram?

**Comment by samuelg78** [comment]
It's the confusion "1" with "l", thank you.
