### ISSUE TITLE
how can i use InlineKeyboard in webhook method ?

### ISSUE THREAD

**Issue by djary** [TelegramBots/telegram.bot#483]
my bot work in GetUpdates method but in webHook i have issues with inlineKeyboard

https://stackoverflow.com/questions/46496636/how-can-i-use-inlinekeyboard-in-webhook-method-telegram-bot-c-sharp

somebody have telegram.bot webhook method in mvc 5 example project and share it ?

**Comment by pouladpld** [comment]
@djary Ask such questions in our tg group. Issues are now only for bug report amd feature proposal.
