### ISSUE TITLE
I'm having multiple issues with getUpdates function 

### ISSUE THREAD

**Issue by Kannas24** [TelegramBots/telegram.bot#485]
1. Bot API is not returning new messages now(only callback_query messages are returned along with one old message with offset 53646521) after I set the offset to(53646521). This might be happening because new messages are having update_id less than 53646521 ? 
2. allowed_updates parameter is also not working, I tried it to filter/return callback_query messages only.
3. callback_query message disappears after 3-4min approx (api is not returning it)

**Comment by Olfi01** [comment]
3rd is on intent. I can't Research the other two rn sorry

**Comment by pouladpld** [comment]
Ask such questions in our tg group. Issues are now only for bug report amd feature proposal.
