### ISSUE TITLE
getting photo id of a recived message(solved)

### ISSUE THREAD

**Issue by alireza4474** [TelegramBots/telegram.bot#486]
Hi
I was trying to get photoID of the message I recived using OnMessage event and messageEventArgs but couldn't find any property representing it.

can you help me find it?
thank you

*NuGet Package Version:* (e.g. 13.0.1)

*.NET Version:* (e.g. 4.7, Core RTM, Mono, etc.)

*IDE:* (e.g. VS2017, VS Code, etc.)

*App:* (e.g. Desktop, iOS, Android, etc.)

**Comment by Olfi01** [comment]
MessageEvenArgs.Photo.FileId or sth
And I find it really funny that you used the issue template but didnt fill it xD
