### ISSUE TITLE
User List

### ISSUE THREAD

**Issue by sorankurds** [TelegramBots/telegram.bot#487]
Hi
How to access the list of users in the Telegram.Bot?

**Comment by Tuscen** [comment]
There is no such functionality in Bot API. You can only get number of users in a chat.

**Comment by sorankurds** [comment]
> There is no such functionality in Bot API. You can only get number of users in a chat.

So what should I do to see the block list or restricted list?

**Comment by Tuscen** [comment]
There is no bot api to retrieve a list of restricted users. You have to maintain such a list somewhere in your bot (e.g. store it in a database).

**Comment by sorankurds** [comment]
> There is no bot api to retrieve a list of restricted users. You have to maintain such a list somewhere in your bot (e.g. store it in a database).

tanks

**Comment by pouladpld** [comment]
@sorankurds Ask such questions in our tg group. Issues are now only for bug report amd feature proposal.
