### ISSUE TITLE
Error While Sending Audio With Uri

### ISSUE THREAD

**Issue by amirtvs** [TelegramBots/telegram.bot#490]
hi i use SendAudioAsync Method to send a track by url.
and its my code:
`await bot.SendAudioAsync(cid, new FileToSend(new Uri(music.Quality128)), "test",200,music.Artist.Name,music.Name,false,mid);`
and i get this error:
Bad Request: wrong file identifier/HTTP URL specified

**Comment by Tuscen** [comment]
I haven't been able to reproduce your error. Have you tried sending audio manually with the same url  (e.g. using postman)?

**Comment by pouladpld** [comment]
@amirtvs Ask such questions in our tg group. Issues are now only for bug report amd feature proposal.
