### ISSUE TITLE
BotOnReceiveError Event

### ISSUE THREAD

**Issue by samuelg78** [TelegramBots/telegram.bot#494]
private static void BotOnReceiveError(object sender, ReceiveErrorEventArgs receiveErrorEventArgs)
{
Debugger.Break();
}
When this event is fired, the console application crashed due to not in debugging mode, can i remove this event completely? Or is there any workaround?

**Comment by pouladpld** [comment]
@samuelg78 Ask such questions in our tg group. Issues are now only for bug report amd feature proposal.
