### ISSUE TITLE
Send video note problem

### ISSUE THREAD

**Issue by Ramin-Bateni** [TelegramBots/telegram.bot#496]
### Steps to reproduce
```
using (var fileStream = new FileStream(@"E:\path\video.mp4", FileMode.Open))
{
    var fileToSend = new FileToSend("MyVideoNote.mp4", fileStream);
    await Bot.SendVideoNoteAsync(chat_Id, fileToSend);
}
```
### Expected  behavior
Rounded Video
![image](https://user-images.githubusercontent.com/9051320/32136826-1796c92a-bc22-11e7-88c2-04c3a45a76bb.png)

### Actual behavior
Square Video with black thumb
![image](https://user-images.githubusercontent.com/9051320/32136813-b8d6318c-bc21-11e7-85a2-ad2a03429729.png)

### Environment data
*NuGet Package Version:* Telegram.Bot.Core.13.2.0

Where is my mistake? and how I should change my codes to send rounded videos?
Is there any problem in the library that I used (Telegram.Bot.Core.13.2.0) about sending video note messages?

**Comment by Tuscen** [comment]
I've not been able to reproduce your problem.
![2017-10-28 22 24 42](https://user-images.githubusercontent.com/1078199/32137776-fae9bfe6-bc2e-11e7-9acc-cde419d1f90a.png)

Have you tried to send video note manually to check if the problem isn't in the video file itself (e.g. using Postman or Insomnia rest clients)?

**Comment by pouladpld** [comment]
@Ramin-Bateni First, try this video that we use in our sys integ tests:

<https://github.com/TelegramBots/telegram.bot/blob/develop/test/Telegram.Bot.Tests.Integ/Files/Video/golden-ratio-240px.mp4>

Telegram decides about how to render the video. It should either be because of the resolution or length.

**Comment by Ramin-Bateni** [comment]
@pouladpld, It worked with the file that you linked to it.👍

Then now the question is why my video failed?
_In the other words:_
What are the **Video file requirements (require format)** to make a `VideoNote `successfully?

File info of my video (failed file):
```

Format                      : MPEG-4
Format profile              : Base Media
Codec ID                    : isom (isom/iso2/mp41)
File size                   : 1.28 MiB
Duration                    : 17s 189ms
Overall bit rate mode       : Variable
Overall bit rate            : 624 Kbps
Writing application         : Lavf56.15.100

Video
ID                          : 1
Format                      : MPEG-4 Visual
Format profile              : Simple@L1
Format settings, BVOP       : No
Format settings, QPel       : No
Format settings, GMC        : No warppoints
Format settings, Matrix     : Default (H.263)
Codec ID                    : 20
Duration                    : 17s 0ms
Bit rate mode               : Constant
Bit rate                    : 423 Kbps
Width                       : 358 pixels
Height                      : 536 pixels
Display aspect ratio        : 0.668
Frame rate                  : 14.647 fps
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Compression mode            : Lossy
Bits/(Pixel*Frame)          : 0.150
Stream size                 : 877 KiB (67%)
Writing library             : Lavc56.13.100

Audio
ID                          : 2
Format                      : MPEG Audio
Format version              : Version 1
Format profile              : Layer 3
Codec ID                    : 6B
Duration                    : 17s 189ms
Bit rate mode               : Variable
Bit rate                    : 201 Kbps
Channel(s)                  : 2 channels
Sampling rate               : 44.1 KHz
Compression mode            : Lossy
Stream size                 : 423 KiB (32%)
Default                     : Yes
Alternate group             : 1
```

**Comment by pouladpld** [comment]
I told you why. Convert your video to that format, resolution, and length. 

Ask `@botsupport` for more details and please let us know the answer.

**Comment by Ramin-Bateni** [comment]
**`@botsupport: `** They should be squared (same height and width) ;)

**Comment by Edgar-P-yan** [comment]
Right now i'm doing some experiments with telegram, and it looks like maximum video size is 639px. Even 640px gives an error, but up to 639 everything works fine.
So for now i can say that requirements for sending video note are:
1. Video shouldn't be longer than a minute.
2. It should be a square, meaning that width and height required to be equal
3. The size of it must be not bigger than 639px.

I'll edit this comment as i'll get some more information
