### ISSUE TITLE
v14 - Fluent API or DTO Types?

### ISSUE THREAD

**Issue by pouladpld** [TelegramBots/Telegram.Bot#498]
@MrRoundRobin initially proposed a _Fluent API_ for the client [here](https://github.com/TelegramBots/telegram.bot/pull/458#issuecomment-336494022).

Having a fluent API is nice and when implemented well, could instruct clients how to make the request properly without getting exception.

On the other hand, defining bot API request and respons types (DTOs), would help to implement the _request in response to webhook_ feature. @Olfi01 has already made a PR for it [here](https://github.com/TelegramBots/telegram.bot/pull/458).

In both of the cases, we could offer some validations before sending the request as well (maybe by using DataAnnotations api).

Which way should we go to? Either/or or Both? We also need to ensure we won't end up with duplicating ourselves.

**Comment by MrRoundRobin** [comment]
hi, don't know if it's already clear but "request in response to webhook" is also possible with the fluent api

**Comment by pouladpld** [comment]
That's fine. My concern is more about duplicating the field names when making requests. I'm not in favor of using the dictionary. A set of DTO classes with inheritance between them seems a better approach to me.

Maybe both features can go together but I'm not sure about how implementation might look like.

**Comment by pouladpld** [comment]
Matrix's API is very similar to Telegram. Here you can see how I tried my best to reuse code between DTOs.

> That project is in its early days so it's not perfect.

<https://github.com/pouladpld/PeykOn/tree/master/src/Matrix.NET.Client>
