### ISSUE TITLE
Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by TERMI80** [TelegramBots/telegram.bot#499]
Hello,
i got always this error:
Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
below my sub
Could you help me?

Async Sub PolBotFiglio()
    Dim retry As Boolean = True

    While retry = True
        Try
            Dim io = Await BtClient.GetMeAsync()
            Dim result = Await BtClient.GetUpdatesAsync(offset2)
            Dim noff As Integer
            Dim Messaggio As String
            For Each m In result

                If m.EditedMessage Is Nothing Then
                    If m.Message.Chat IsNot Nothing Then
                        Messaggio = m.Message.Text
                        If PrimoAvvio = False Then
                            HandleMessageFiglio(Messaggio)
                        End If
                        noff = m.Id
                        offset2 = noff + 1
                    End If
                End If
            Next
            PrimoAvvio = False
            Thread.Sleep(20)
        Catch ex As Exception
            LogInfo( ex.Message)         
  
            retry = True
        End Try
    End While

**Comment by pouladpld** [comment]
@TERMI80 First, Use issue template.
Second, consider trying latest package version before reopenning the issue.

**Comment by a-a-k** [comment]
This is same one?
https://github.com/TelegramBots/telegram.bot/issues/357

**Comment by pouladpld** [comment]
@a-a-k Already fixed. Update to latest version.
