### ISSUE TITLE
Target classic .NET (i.e. net462) in Nuget package.

### ISSUE THREAD

**Issue by maelgrove** [TelegramBots/telegram.bot#500]
The currently distributed nuget package @ [nuget.org](https://www.nuget.org/packages/Telegram.Bot/) is only published for the .NETStandard 1.1 framework, listing the NETStandard.Library package as its dependency. When installing the package within a classic .NET application (e.g. net462 console), this causes the entire .NETStandard.Libary and all associated dependencies to be downloaded and referenced.

### Steps to reproduce

1. Create a new .NET Console Application targeting net462.
2. Install Telegram.Bot nuget package.

### Expected  behavior

- Targets for the classic .NET framework exists, instructing the library to reference framework assemblies from the GAC.

### Actual behavior

- The entire NETStandard.Library is being referenced and downloaded.

*NuGet Package Version:* 13.3.0-rc1

*.NET Version:* 4.6.2

*IDE:* Visual Studio 2017 v15.3

*App:* Desktop

**Comment by pouladpld** [comment]
Project currently targets `netstandard1.1` only. If we consider this as an issue, we then should again support full .NET (probably 4.5) as well.

@MrRoundRobin what do you think?

**Comment by MrRoundRobin** [comment]
as this is only 4 lines of codes ill add this
