### ISSUE TITLE
Detect WebPagePreview (Link Preview) status of a message on MessageUpdate

### ISSUE THREAD

**Issue by Ramin-Bateni** [TelegramBots/telegram.bot#502]
I want detect the status (True/False) of `WebPagePreview `of the inserted message by user when the `MessageUpdate `occurre in my  webhook.
How can I do it?! Is there any property or method about this issue in Telegram Bot API?

**Comment by pouladpld** [comment]
@Ramin-Bateni we dont provide such support anymore. Ask in our group chat or on stack overfpow. Issues are now for bug report on feature request only.

**Comment by Ramin-Bateni** [comment]
@pouladpld, How can I join the group chat?
I get this error:
![image](https://user-images.githubusercontent.com/9051320/32414220-7fedefe2-c237-11e7-91f4-98abdd2ba04b.png)
