### ISSUE TITLE
bot.GetFileAsync  throws exception " Error while copying content to a stream "

### ISSUE THREAD

**Issue by newmamaly** [TelegramBots/telegram.bot#505]
### Steps to reproduce
call bot.GetFileAsync(message.Photo.LastOrDefault().FileId);
try
                    {
                        var file = await bot.GetFileAsync(message.Photo.LastOrDefault().FileId);

                        using (var saveImageStream = new FileStream(@"d:\4.jpg", FileMode.Create))
                        {
                            await file.FileStream.CopyToAsync(saveImageStream);
                        }
                    }
                    catch (Exception ex) { }

### Expected  behavior
GetFileAsync return uploaded file(photo)

### Actual behavior
GetFileAsync throws exception
**Message** : " Error while copying content to a stream. ".
**source**: System.Net.Http
**stacktrace**:    at System.Net.Http.HttpContent.<CopyToAsyncCore>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Telegram.Bot.TelegramBotClient.<GetFileAsync>d__74.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WConsole.Program.<BotOnMessageReceived>d__23.MoveNext() in E:\WConsole\Program.cs:line 1310

### Environment data

*NuGet Package Version:* (e.g. 13.2.1)
Version :13.2.1
*.NET Version:* (e.g. 4.7, Core RTM, Mono, etc.)
.NET 4.6 

*IDE:* (e.g. VS2017, VS Code, etc.)
VS2015  - os: W10 x64
*App:* (e.g. Desktop, iOS, Android, etc.)
Desktop

**Comment by Mahdi-Farhani** [comment]
About 2 weeks ago I had the same problem, after a while and looking lots of sources related to this issue and error I solve the problem by changing this line in the source.
```
using (var response = await _httpClient
                .GetAsync(fileUri, HttpCompletionOption.ResponseContentRead, cancellationToken)
                .ConfigureAwait(false))
```
In the latest version I found the HttpCompletation paramter set to **ResponseHeadersRead** so I've changed it to **ResponseContentRead** and my problem solved.

**Comment by Tuscen** [comment]
I couldn't reproduce it on my machine. I used `.NET Core 2.0` on `macOS 10.13` with `13.4.0` version of the library.
