### ISSUE TITLE
SendPhotoAsync

### ISSUE THREAD

**Issue by morph1** [TelegramBots/telegram.bot#508]
private bool pictureSend(string messagetosend)
        {
            bool success = true;
            string Token = Convert.ToString(txtToken.Text);
            string ChatIDChannel = Convert.ToString(txtChatID.Text);
            string phototosend = "C.\\image.jpg";
            var Bot = new Telegram.Bot.TelegramBotClient(Token);
            using (var stream = System.IO.File.Open(phototosend, FileMode.Open))
            {
                    FileToSend fts = new FileToSend();
                    fts.Content = stream;
                    fts.Filename = phototosend.Split('\\').Last();
                    Bot.SendTextMessageAsync(ChatIDChannel, messagetosend);
                    //Bot.SendPhotoAsync(ChatIDChannel, fts, messagetosend);
            }
        }

SendTextMessageAsync works but SendPhotoAsync don't work. Is something in my Code wrong or should it work like that?

**Comment by pouladpld** [comment]
@morph1 read <https://github.com/TelegramBots/telegram.bot/blob/develop/ISSUE_TEMPLATE.md>

**Comment by sadegh9999** [comment]
hi,

I think @tgbots_dotnet group not exists in telegram, is your group changed ?

I have to important question:
1- await bot.SendPhotoAsync(TargetChatId, F, Title); Freeze and "never" go do next line, but last week it work fine, but this days it freeze ! and even dont raise any error !
but when i make a url with query string and put in Web browser it work fine !

2- how can i get the command that your dll send to telegram bot?

thanks .
