### ISSUE TITLE
New field https://core.telegram.org/bots/api#october-11-2017

### ISSUE THREAD

**Issue by imixal** [TelegramBots/telegram.bot#510]
Can you add caption_entities field, please?

**Comment by Tuscen** [comment]
Bot API 3.4 had been implemented in `13.3.0-rc1` version. Although it's in prerelease state you can use it. I've been using it for a few weeks and haven't had problems.

**Comment by imixal** [comment]
I've using it and it's not working. It seems very strange, but I even get empty MessageId

**Comment by pouladpld** [comment]
@imixal read <https://github.com/TelegramBots/telegram.bot/blob/develop/ISSUE_TEMPLATE.md>

If you believe there is a bug, please open a bug report issue.
