### ISSUE TITLE
Update object doesn't populate all webhook post params,if the sent message contains file,voice,photo ,....

### ISSUE THREAD

**Issue by mehdimsv** [TelegramBots/telegram.bot#511]
### Steps to reproduce
these code throw and exception,we hove no way to retrieve sent photo,file,... 
`
```
public async Task<ActionResult> Index(Update update)
        {
 if (update.Message.Photo != null)
            {
                var file = await bot.GetFileAsync(update.Message.Photo.LastOrDefault()?.FileId);
                var filename = file.FileId + "." + file.FilePath.Split('.').Last();
               using (var saveImageStream = File.Open(filename, FileMode.Create))
               {
                   await file.FileStream.CopyToAsync(saveImageStream);
               }
}
}
```
`
 

### Expected  behavior
if we use update object for webhook method,
It seems that javascript deserializer doesn't populate fileid,filesize for sent photo and these fields are null,

### Environment data

*NuGet Package Version:* (e.g. 13.0.1)

*.NET Version:* (e.g. 4.7, Core RTM, Mono, etc.)

*IDE:* (e.g. VS2017, VS Code, etc.)

*App:* (e.g. Desktop, iOS, Android, etc.)

**Comment by Tuscen** [comment]
What version of the library are you using?
