### ISSUE TITLE
How to design inline message ?

### ISSUE THREAD

**Issue by arminblack** [TelegramBots/telegram.bot#512]
### Environment data

*NuGet Package Version:* (e.g. 13.0.1)

*.NET Version:* (e.g. 4.7, Core RTM, Mono, etc.)

*IDE:* (e.g. VS2017, VS Code, etc.)

*App:* (e.g. Desktop, iOS, Android, etc.)

**Comment by pouladpld** [comment]
@arminblack read <https://github.com/TelegramBots/telegram.bot/blob/develop/ISSUE_TEMPLATE.md>
