### ISSUE TITLE
Read configs from a json serialized env var

### ISSUE THREAD

**Issue by poulad** [TelegramBots/Telegram.Bot#515]
### Feature Request

In Sys Integ tests, configs could be loaded from a json serialized env var. Would be nice to have an extension method on `IConfiguartionBuilder` to read from env var and deserialize it into a POCO.

This helps with setting up test env such as in Travis CI when we need to worry about only about 1 env var.

**Comment by karb0f0s** [comment]
kind of workaround: https://gist.github.com/kr/6161118 converts json to env variables. you only have to change contents of json file. giving more thought to it - how is that different from using application.json?
Or you suggest using whole configuration in single env var?

**Comment by pouladpld** [comment]
@karb0f0s I am looking for a way to have settings in an env var. This might need some `IConfigurationBuilder` extensions to read that env var and convert back from JSON.

```bash
export CI_BUILD_SETTINGS='{ "Tests": { "Execute":true } }'
```

```c#
var testSettings = Configuration.GetSection("Tests").Get<TestSettings>();
```

**Comment by karb0f0s** [comment]
https://github.com/karb0f0s/EnvJson/tree/master
I've combined Microsoft.Extensions.Configuration.EnvironmentVariables - reads environment variables and Microsoft.Extensions.Configuration.Json - parses variable as JSON stream  (https://github.com/aspnet/Configuration/tree/dev/src). 
As a result you can write             
```
var config = new ConfigurationBuilder()
                .AddJsonEnvironmentVariables("CI_BUILD_SETTINGS")
                .Build();
var testSettings = config.GetSection("Tests").Get<TestSettings>();
```
