### ISSUE TITLE
How to get post in channel

### ISSUE THREAD

**Issue by mahdibg** [TelegramBots/telegram.bot#517]
Hello
I added the my Bot to the some public and private channels. but when the post is sent to these channels, OnMessage event dont fire.
What should I do?

thanks

**Comment by pouladpld** [comment]
@mahdibg Read issue template.

**Comment by mahdibg** [comment]
thanks for your reply.
Receiving text messages, videos, ...  was solved.
How can we get ServiceMessage messages for channels?
