### ISSUE TITLE
retry failed requests

### ISSUE THREAD

**Issue by poulad** [TelegramBots/Telegram.Bot#520]
### Feature Request

Proprty on IBotClient to retry requests that fail due to throttling on tg server (429 too many requests).

Could be
```c#
myrequest.RetryOptions = new RetryOptions(count: 3, everySecs: 7)
```

**Comment by Tuscen** [comment]
I think it should be a property on request base class to allow per request setting. And it means that we need to implement all Bot API methods in terms of requests and responses first.

**Comment by ch-asimakopoulos** [comment]
> I think it should be a property on request base class to allow per request setting. And it means that we need to implement all Bot API methods in terms of requests and responses first.

What about now? 🗻
