### ISSUE TITLE
SetWebhookAsync doesn't return true

### ISSUE THREAD

**Issue by Tuscen** [TelegramBots/telegram.bot#525]
`ITelegramBotClient.SetWebhookAsync` doesn’t return bool in the interface. According to Bot API docs it always returns `true`.

*NuGet Package Version:* 13.4.0-rc2

**Comment by pouladpld** [comment]
@Tuscen I don't think we really need to return a `bool`. Some requests like this either return `true` or have an error. In terms of a .NET method call, `SetWebhookAsync` either returns void(awaitable `Task`) or throws an exception.

**Comment by Tuscen** [comment]
Sounds reasonable. But `bool` type parameter must be present in `SetWebhookRequest` and other methods like it because it parameterizes `Result` field in `ApiResponse`.

**Comment by Tuscen** [comment]
Fixed this in #557
