### ISSUE TITLE
Manage error 429 (too many send)

### ISSUE THREAD

**Issue by mahdial** [TelegramBots/Telegram.Bot#540]
Hello,
I'm using sendasync...
But many time mybot got error 429.
Can u add a controller to check it and prevent this error?
I think you must prevent to send more than 30 message in a second.
Sorry for bad english...
Tnx

**Comment by Tuscen** [comment]
I don't think that this library is the appropriate place for such functionality. It's just a wrapper around HTTP API. There could be a framework around this library and thats where it fits better. Actually soon @pouladpld's framework can be moved to the repo's organization and there we can implement 429 error handling. Though it's just my opinion and the maintainers can have a different one.

**Comment by pouladpld** [comment]
@mahdial It might be implemented in v14 of Client. We will check this in coming weeks when Request types are in place.

here is a suggestion:

```c#
var req = new SendTextMessageRequest(chatId, "Hello, World!", cancellationToken)
{
  RetryCount = 3;
  RetryAfter = TimeSpan.FromSeconds(2)
};

try {
  await BotClient.MakeRequestAsync(req);
} catch(ApiRequestException e) {
  // log 
  throw;
}
```

**Comment by mahdial** [comment]
@pouladpld @Tuscen  Thank you.
I hope to see it in v14. 
For now, i want to write a code to prevent send more than 29 messages in a second. 
After that , i will send it here.
Tnx

**Comment by jcmag** [comment]
Any update on this feature?

**Comment by pouladpld** [comment]
@jcmag We'd probably implement such features in a framework package. For the time being, I'd suggest you using [Polly](https://github.com/App-vNext/Polly).

**Comment by jcmag** [comment]
I didn't know Polly, it seems very useful, thanks!

**Comment by karb0f0s** [comment]
@MihaZupan suggested this https://github.com/MihaZupan/TelegramBotClients - Telegram Bot Client with message queue, that prevents hitting rate limit

**Comment by matteocontrini** [comment]
Was the implementation of this discussed anywhere more recently?

I'm personally strongly against introducing such a drastic change in behaviour in a minor version. Developers that won't go through the commits to see what changed will have their existing retry implementation unexpectedly broken.

I and probably many others also assumed that the upgrade guide was a one-time guide to upgrade to the 21.x major version, and that there wouldn't be other breaking changes until 22.x. I'm sure people also appreciated that the project followed semantic versioning, at least until recently.

**Comment by wiz0u** [comment]
If it all depended to me, I would have added Release Notes to the release pipelines indicating this change, but it's not easily feasible the way the repository is configured.

I recon it is a notable change although not a "breaking" one in my view. Same with v21.3.

I have a much major breaking change in mind that will soon warrant a change to v22

**Comment by wiz0u** [comment]
Additionally, we are still currently waiting for the Nuget.org issue to be resolved, so I take the opportunity to apply all those change in the mean time, as we are "less public".
