### ISSUE TITLE
How Can Run Bot in Host ?

### ISSUE THREAD

**Issue by Hamed6380** [TelegramBots/telegram.bot#541]
# I have a question or need help
Hi 
How Can Create Bot For Run In Host Server (Create Bot In Web Api Project) ?
Thanks ....

**Comment by pouladpld** [comment]
@Hamed6380 read issue template.

**Comment by pouladpld** [comment]
@Hamed6380 
<https://github.com/TelegramBots/telegram.bot/blob/develop/ISSUE_TEMPLATE.md>
