### ISSUE TITLE
Is it possible to just Allow the members use the bot  that are in the specific GeoLocation

### ISSUE THREAD

**Issue by mahoor-bhr** [TelegramBots/telegram.bot#551]
Hi
I'm new to telegram bot.I create a bot with botFather and C# & telegramBot nuget package.
Two questions :
1-Is there anyway that allow users whom are in the specific location,use the bot?For example if the users are in the company ,they can use the bot.
Is it possible ??

2-Can i get from what channels or groups the user joined to the bot, when he pressed the start button of my bot?

**Comment by pouladpld** [comment]
@mahoor-bhr Read issue template. No support here.
