### ISSUE TITLE
EditInlineMessageReplyMarkupAsync with chatId and messageId parameters

### ISSUE THREAD

**Issue by Ramin-Bateni** [TelegramBots/telegram.bot#553]
Telegram documents show us that it is possible to change a MessageReplyMarkup with chatId and messageId of the message:

![image](https://user-images.githubusercontent.com/9051320/33864453-ed3ea546-df01-11e7-9d84-568d63c38e06.png)

But there is not a  method in the Telegram.Bot library that named `EditInlineMessageReplyMarkupAsync` with `chatId` and `messageId` parameters. Already it works just with `inline_message_id`.

**Is it possible to add a new method for  `EditInlineMessageReplyMarkupAsync` to support `chatId` and `messageId` ?**

--------------------------

I wrote my request here because when I open the [https://t.me/tgbots_dotnet](https://t.me/tgbots_dotnet) by Telegram desktop, it send me the following error! **Why?**
![image](https://user-images.githubusercontent.com/9051320/33864620-d8e37cb0-df02-11e7-8d6b-ae7212f1ecf8.png)

**Comment by pouladpld** [comment]
@Ramin-Bateni That's weird you cannot join. This is the invite link:

https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA

**Comment by Ramin-Bateni** [comment]
I solved it with `EditMessageReplyMarkupAsync`.

But @pouladpld when I try the link ([https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA)) that you write in your reply it show me another error:
![image](https://user-images.githubusercontent.com/9051320/33870819-f098cd0c-df24-11e7-81bf-29cb0ce291a9.png)
Is it a expired link? May you give me the alive link of the group?

**Comment by pouladpld** [comment]
@Ramin-Bateni Whatever tg client you have has a problem. Try something else.

**Comment by Ramin-Bateni** [comment]
@pouladpld, I checked it with 3 different Telegram Desktop (and 2 Different Account) and 2 Telegram Android (with 2 Different Account). All of them give me the same error: **Sorry, this group is not accessible.**
![image](https://user-images.githubusercontent.com/9051320/33909026-6eccdcf2-df9f-11e7-979a-12b57488b833.png)

**Comment by pouladpld** [comment]
@Ramin-Bateni 

It says you have left the group yourself and I cannot add you back.

Also check group privacy settings and allow everybody to add you.

**Comment by Ramin-Bateni** [comment]
@pouladpld, I did not leave the group manually! I just get the error after click on join chat. My telegram setting:
![image](https://user-images.githubusercontent.com/9051320/34171137-8a40e3d0-e502-11e7-9640-70b9e6502028.png)

**Comment by pouladpld** [comment]
@Ramin-Bateni This is a public group so anyone can join and you definitely are not in the black list.

Try asking a friend to join and then add you to group. 

Also if you contact tg support, let us know their answer.

**Comment by pouladpld** [comment]
@Ramin-Bateni It seems you can't join a public supergroup using Iran's filternet. Try a VPN.
