### ISSUE TITLE
Which version of visual studio is required to open Telegram Bot

### ISSUE THREAD

**Issue by GoldenLighter** [TelegramBots/telegram.bot#558]
I am using visual studio 2015.
But i could n't open https://github.com/TelegramBots/telegram.bot
Which version of visual studio is required to open Telegram Bot?
Also where can i get examples project?

**Comment by Tuscen** [comment]
I think you have to use VS 2017 because this library uses the latest `csproj` format, the same that is used in .NET Core. But I may be wrong because I don't use VS.

As for the examples you can find some [here](https://github.com/TelegramBots/telegram.bot.examples) but they are a bit outdated.

**Comment by pouladpld** [comment]
@GoldenLighter Read issue template.
