### ISSUE TITLE
Where is updated examples for TelegramBots?

### ISSUE THREAD

**Issue by GoldenLighter** [TelegramBots/telegram.bot#559]
Where is updated examples for TelegramBots?
There is an old link that does not work any more & has error.
https://github.com/TelegramBots/telegram.bot.examples
Also the old one does not work with new library.
Why the writer of this library did n't write an example for it?

**Comment by pouladpld** [comment]
True. Sample project needs to be upgraded accordingly.

I hope people understand this is a community-based project so anyone is free to make his own contribution such as upgrading the samples.

There are 4 maintainers here and we try our bests to make time to work on the project.

**Comment by GoldenLighter** [comment]
Hi dear manager,
Thanks for the library.
You wrote the library, But i really could n't understand how to use it without an example project!
Please update the upper link related to example project.

Thanks in advance

**Comment by karb0f0s** [comment]
For now updated examples available in my fork https://github.com/karb0f0s/telegram.bot.examples. Soon it will be merged to this branch

**Comment by pouladpld** [comment]
Thank you @karb0f0s
