### ISSUE TITLE
Send InLine message to channel with channel

### ISSUE THREAD

**Issue by Mohammad-Reza-Rahimi-Zade** [TelegramBots/telegram.bot#564]
hi
How to use the inline method to send a message from a channel to a robot ؟

**Comment by Tuscen** [comment]
@Mohammad-Reza-Rahimi-Zade Read issue template.

**Comment by Mohammad-Reza-Rahimi-Zade** [comment]
But I did not find anything

**Comment by Tuscen** [comment]
@thoemmi We use issues tracker only for bugs and development. Feel free to join [our group](https://t.me/tgbots_dotnet) in Telegram if you have questions about the library.

**Comment by Mohammad-Reza-Rahimi-Zade** [comment]
tgbots_dotnet found

**Comment by pouladpld** [comment]
@Mohammad-Reza-Rahimi-Zade 
This most likely is a bug with tg desktop client.
Type this in any tg chat and click on it to join:

`@tgbots_dotnet`

**Comment by pouladpld** [comment]
@Ramin-Bateni You might also want to try that.

**Comment by Ramin-Bateni** [comment]
@pouladpld, I tested both Telegram Desktop and Telegram Android with different Telegram Clients with no success to join the group!

![image](https://user-images.githubusercontent.com/9051320/34170888-c6053872-e501-11e7-9d9c-d343204b5400.png)

I did not hear about any bug to join a group in Telegram. I join to other groups easily by their join link... Is the group has some special settings and policy or .....?!!!

**Comment by pouladpld** [comment]
@Mohammad-Reza-Rahimi-Zade 
It seems you can't join a public supergroup using Iran's filternet. Try a VPN.
