### ISSUE TITLE
Allocated memory is not freed

### ISSUE THREAD

**Issue by ivmazurenko** [TelegramBots/Telegram.Bot#565]
# I have a question or need help

I have a simple program:

        internal static class Program {
            private static readonly TelegramBotClient _bot = new TelegramBotClient("SOME_KEY");

            public static void Main() {
                _bot.OnMessage += BotOnMessageReceived;
                _bot.StartReceiving();
                Console.ReadLine();
                _bot.StopReceiving();
            }

            private static void BotOnMessageReceived(object sender, MessageEventArgs messageEventArgs) {
                for (var i = 0; i < 1000; i++) {
                    Task.Run(() => {
                        Thread.Sleep(new Random().Next() % 100);
                        _bot.SendTextMessageAsync(
                            messageEventArgs.Message.Chat.Id,
                            Guid.NewGuid().ToString(),
                            replyMarkup: new ReplyKeyboardHide());
                    });
                }
            }
        }

After running this program, and send 3 or 4 messages to bot, allocated memory will be never cleared. What can i do?

**Comment by karb0f0s** [comment]
Have you tried to reproduce it with v14 library?

**Comment by karb0f0s** [comment]
Are you sure, that library uses memory?  You create 4000 Task objects and according to https://stackoverflow.com/questions/8293297/how-can-i-free-up-memory-used-by-a-parallel-task Task Manager will show high memory consumption, but in fact it is reserved not actually “in-use” memory

**Comment by ivmazurenko** [comment]
@karb0f0s , I think this behaviour is related with strings. You can check if you switch this line 

    Guid.NewGuid().ToString(),

to this:

    new Guid().ToString(),

In this case, all sending strings will be the same. Maybe strings are Interned

**Comment by ivmazurenko** [comment]
Nothing changed with version 14 of lib, situation still reproduced.

You say: **but in fact it is reserved not actually “in-use” memory**
And what? Any other application can not use this memory. 

Tou say: **You create 4000 Task objects ... **
Where? As i can see, ThreadPool works here
 
I tried to modify my example into something other to "притянуть за уши"  it to your answer, but i can't reproduce this scenario without calling this lib.

**Comment by karb0f0s** [comment]
I was not able to reproduce this behavior - well, yes 1000 object created with ~100 ms delay, and yes, they consume some memory, but after `SendTextMessageAsync` method finished with `429` error, this objects removed from heap by GC.
![image](https://user-images.githubusercontent.com/17474471/38311487-f3cd4532-3827-11e8-969e-a263962b02e9.png)
Tested with latest (for now) `Telegram.Bot v.14.2.0-rc-452` and slightly modified test case:
```csharp
private static void BotLeatTesk()
{
    for (var i = 0; i < 1000; i++)
    {
        Task.Run(async () =>
        {
            await Task.Delay((new Random().Next() % 1000) * 1_000);
            await _bot.SendTextMessageAsync(
                307811862,
                Guid.NewGuid().ToString(),
                replyMarkup: new ReplyKeyboardRemove()
            );
        });
    }
}
```
with async Tasks it almost does not consume memory at all
