### ISSUE TITLE
request/propose: create inline buttons and keyboard buttons at the same time

### ISSUE THREAD

**Issue by MasihAkbari** [TelegramBots/Telegram.Bot#589]
# I'd like to request/propose a feature
As far as i know you can create an inline button or normal keyboard button with sending a text but can you create a feature that with sending one text we can create inline buttons and normal keyboard button at the same time? is there a way to create such thing now that i'm missing?
thanks for this awesome work

**Comment by pouladpld** [comment]
@MasihAkbari We are not in charge of such changes. Talk to telegram support.
