### ISSUE TITLE
How to show progress while downling a file using GetFileAsync?

### ISSUE THREAD

**Issue by mostafa8026** [TelegramBots/Telegram.Bot#590]
How to show progress while downling a file using GetFileAsync?

**Comment by pouladpld** [comment]
@mostafa8026 First, please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/ISSUE_TEMPLATE.md). I am considering this a feature request.

You can't do that using our implementation. It is a simple GET request you can make on your own. These might help: 

<https://core.telegram.org/bots/api#getfile>
<https://stackoverflow.com/questions/20661652/progress-bar-with-httpclient#20665200>

**Comment by mostafa8026** [comment]
Excuse me for not putting your issue template into effect.
And Thanks for your response and your useful links. It takes me some time to implement that. Maybe I can add this feature to your repository.

**Comment by pouladpld** [comment]
That's not in our scope. What you want is a very simple HTTP call. Consult the docs.
