### ISSUE TITLE
Message with type SuccessfulPayment never catched

### ISSUE THREAD

**Issue by a-a-k** [TelegramBots/Telegram.Bot#592]
I don't sure is it a library bug or API directly so take a look.

### Steps to reproduce
Run your bot and make any successful payment. Then try to catch info about this payment.
```
switch (update.Message.Type) // Breakpoint is here
{
   case MessageType.TextMessage:
   {
      await ParseTextMessageAsync(update);
      break;
    }
// ... 
    case MessageType.SuccessfulPayment: // Another breakpoint here too
    {
       await ParseSuccessfulPaymentAsync(update);
       break;
     }
}
```
### Expected  behavior
Message with type `SuccessfulPayment` must be catched.
### Actual behavior
Running flow doesn't enter even into the switch clause.
### Environment data
*NuGet Package Version: 13.4.0*

*.NET Version: Core 2.0*

*IDE: VS2017, Rider 2017.3*

*App: Android*

**Comment by pouladpld** [comment]
@a-a-k I cannot reproduce this. Our tests already check that option and it looks fine.

You can debug this test to learn more.

<https://github.com/TelegramBots/Telegram.Bot/blob/master/test/Telegram.Bot.Tests.Integ/Payments/PaymentTests.cs#L166>

**Comment by a-a-k** [comment]
@pouladpld there I see the `Should_Receive_Successful_Payment_With_Shipment_Option` test. Its name tells that `shipment_option` should be switched on. Isn't it? I have orders with `shipment_option` switched off.

**Comment by pouladpld** [comment]
It's not about shipment info or anything else. When any payment is done, I can see type has proper value.

**Comment by a-a-k** [comment]
@pouladpld I don't know what it's about but when I've added `needShippingAddress = true` into `sendInvoice` the `successfulPayment` were catched on my breakpoints.
