### ISSUE TITLE
Link to docs isn't valid

### ISSUE THREAD

**Issue by nikkonrom** [TelegramBots/Telegram.Bot#593]
Link in README.md to Library Docs unexpectedly gets 404 error. Can you fix it, pls?

**Comment by pouladpld** [comment]
We should remove that docs link. A _getting started_ wiki should be enough since all API is already documented by tg.

**Comment by findusl** [comment]
Maybe you could put up a generated HTML documentation of the code based on the comments? From what I saw there are quite a few. The library may be based on the API of tg, but it is not the same.
