### ISSUE TITLE
Bot not receive from channel

### ISSUE THREAD

**Issue by hanigamini** [TelegramBots/Telegram.Bot#595]
Hi,
My bot not receive message from channel that bot is added to channel and admin.
in bot father i /setprivacy to DISABLED, my code.

 public static void Main(string[] args)
        {

            Bot.OnMessage += BotOnMessageReceived;
            Bot.OnMessageEdited += BotOnMessageReceived;
            Bot.OnCallbackQuery += BotOnCallbackQueryReceived;
            Bot.OnInlineQuery += BotOnInlineQueryReceived;
            Bot.OnInlineResultChosen += BotOnChosenInlineResultReceived;
            Bot.OnReceiveError += BotOnReceiveError;
            //Bot.OnUpdate += BotOnMessageReceived;

            var me = Bot.GetMeAsync().Result;

            Console.Title = me.Username;     

            Bot.StartReceiving();
            Console.WriteLine($"Start listening for @{me.Username}");
            Console.ReadLine();
            Bot.StopReceiving();
        }

 private static async void BotOnMessageReceived(object sender, MessageEventArgs messageEventArgs)
        {
            var message = messageEventArgs.Message;
....
}

i also add this code on main , but not worked.

 UpdateType[] updateType = new UpdateType[1];
            updateType[0] = UpdateType.ChannelPost;

            Bot.StartReceiving(updateType);

**Comment by pouladpld** [comment]
@hanigamini Follow issue template properly. This is not reproducible.

**Comment by AskoldMakaruk** [comment]
same

**Comment by MihaZupan** [comment]
@AskoldMakaruk Channel messages come in under `Update.ChannelPost`, not on the OnMessage event. Join the group chat linked in the readme if you have any questions.
