### ISSUE TITLE
Feature Request: Telegram Client Support

### ISSUE THREAD

**Issue by aarian93p** [TelegramBots/Telegram.Bot#599]
Well, this package and library is awesome. But the point is it only works with Bots. I think it it isn't that much hard to make it possible to also implement a Telegram Client that can log into my own personal account and do some automated tasks for me. We already have a lot of models needed to work with Telegram API. Why not implement the remaining ones and make this library even more powerful?

**Comment by pouladpld** [comment]
Not in our scope. Although, the code here is free and anyone can fork to make it better.
