### ISSUE TITLE
inline keyboard 

### ISSUE THREAD

**Issue by sajjadarash** [TelegramBots/Telegram.Bot#602]
Sorry mr Icant Create inline keyboards And Using That Plz Help me For this 
```
InlineKeyboardButton n = new InlineKeyboardButton();
            ikb = new InlineKeyboardMarkup().InlineKeyboard =
               new[]
                    {
                      new[]
                         {
                          n ,
                          }
                 };
```
this my code

**Comment by pouladpld** [comment]
@sajjadarash No support from gh issues. Read [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/ISSUE_TEMPLATE.md).

**Comment by AppleAssistant** [comment]
Hi @sajjadarash ,
Please See https://github.com/TelegramBots/Telegram.Bot/blob/master/test/Telegram.Bot.Tests.Integ/Inline%20Keyboard/CallbackQueryTests.cs


Good Louck.
