### ISSUE TITLE
Login Widget Utilities

### ISSUE THREAD

**Issue by pouladpld** [TelegramBots/Telegram.Bot#603]
### Feature Request: Login Widget Utilities

Telegram recently added a [Login Widget](https://core.telegram.org/widgets/login) to authorize users.

We could have a few utilities to help with Login Widget authorization such as calculating [this hash](https://core.telegram.org/widgets/login#checking-authorization) to check data integrity.

Example:

```c#
if (Utilities.IsLoginWidgetDataValid(authData)) {
  // save user info...
}
```

**Comment by Tuscen** [comment]
[System.Security.Cryptography.Algorithms](https://www.nuget.org/packages/System.Security.Cryptography.Algorithms/4.3.1) requires `netstandard1.3` as a minimal build target. We will have to rise our build target if we are going to provide this helper.

**Comment by pouladpld** [comment]
That might not be a big issue since we release a version for NET 4.5 as well.

**Comment by MihaZupan** [comment]
https://gist.github.com/MihaZupan/0d0a836c1fdb1c2dd983c88b8736ea5d

**Comment by karb0f0s** [comment]
new "home" for `LoginWidget` extension https://github.com/TelegramBots/Telegram.Bot.Extensions.LoginWidget
