### ISSUE TITLE
host bot on shared host as asp.net project

### ISSUE THREAD

**Issue by AminMhmdi** [TelegramBots/Telegram.Bot#616]
I have a question or need help
i create simple app using c# console app
but i want to host it in shared host 
how can i do it?

**Comment by pouladpld** [comment]
@AminMhmdi Support is provided in our group chat. Read issue template for more info.

**Comment by AminMhmdi** [comment]
where is it??

**Comment by pouladpld** [comment]
@AminMhmdi some users have that issue. Try contacting telegram support for that.

**Comment by AminMhmdi** [comment]
i solved my problem by putting  my code in  application_start on global.asax

**Comment by pouladpld** [comment]
@AminMhmdi 
It seems you can't join a public supergroup using Iran's filternet. Try a VPN.
