### ISSUE TITLE
How to send a message to the user who logged in through the telegram in website?

### ISSUE THREAD

**Issue by MJ-Vakili** [TelegramBots/Telegram.Bot#620]
I have need help

How to send a message to the user who logged in through the telegram in website?

[Telegram Login for Websites
](https://telegram.org/blog/login)

> Telegram bots are a powerful communication tool, but until today they couldn't start a conversation. Even if you wanted them to reach out to you, you had to chat them up first.

and

[Bot API 3.6
](https://core.telegram.org/bots/api#february-13-2018)
> Added the new field connected_website to Message. The bot will receive a message with this field in a private chat when a user logs in on the bot's connected website using the Login Widget and allows sending messages from your bot.

After login user,my bot can not send message with use user_id,Even the OnMessage event is not fired.

How start a conversation by bot?

Thankful.

NuGet Package Version: 14.2.0-rc-452

.NET Version: 4.6.1

IDE:VS2013

**Comment by pouladpld** [comment]
@MJ-Vakili We don't provide support on gh issues. Read issue template.

<https://github.com/TelegramBots/Telegram.Bot/blob/master/ISSUE_TEMPLATE.md>
