### ISSUE TITLE
How get newMember join in channel?

### ISSUE THREAD

**Issue by abbasi1356** [TelegramBots/Telegram.Bot#624]

**Comment by AppleAssistant** [comment]
salam . bebinid bastegi dare az koja bekhay in qaziye ro chek koni , age to event OnMessage mikhay chek koni bayad in roydad ro shart bezari

Message.Type == MessageType.ChatMembersAdded

va ye method dige ham dare be esme  GetChatMemberAsync  ke chek mikone aya in user to channel hast ya kheyr.  moafaq bashid.

**Comment by abbasi1356** [comment]
دوست عزیز ممنون از پاسخی که دادین. اصلا ایونت onmessageفراخونی نمیشه 
فقط ایونت onupdate فراخونی میشه که اونم ممبر رو نشون نمیده

**Comment by Tuscen** [comment]
@abbasi1356 please, read issue template.

**Comment by AppleAssistant** [comment]
Hello my friend, for this you have two solutions:
1. The first is where you want to check if the new user has entered the channel.
If you plan to attend an event OnMessage  check the following code:

`Message.Type == MessageType.ChatMembersAdded`

Or, if you want to check whether a user is in the member channel, you should use the following method:

`GetChatMemberAsync`

Good Luck.

**Comment by abbasi1356** [comment]
event onmessage didn't raise. only onupdate raised and cant get newmember on this event

**Comment by pouladpld** [comment]
@abbasi1356 Post in English only. If you need to chat, join our group chat.

<https://github.com/TelegramBots/Telegram.Bot/blob/master/ISSUE_TEMPLATE.md>
