### ISSUE TITLE
Add exception type for too many requests

### ISSUE THREAD

**Issue by tuscen** [TelegramBots/Telegram.Bot#628]
HTTP Code: `429`
Error message: `Too Many Requests: retry after [0-9]+`

**Comment by pouladpld** [comment]
What's HTTP status code?

**Comment by karb0f0s** [comment]
429?

**Comment by Tuscen** [comment]
@karb0f0s I added it after @pouladpld had asked :) Forgot about status code when I opened the issue.

**Comment by pouladpld** [comment]
![image](https://user-images.githubusercontent.com/14295804/38101161-87287c00-334d-11e8-8174-7bbe9791cff9.png)

**Comment by karb0f0s** [comment]
https://github.com/TelegramBots/Telegram.Bot/pull/657/commits/48fe2a57f0783f5cdb42c7b356d1bb89b1cdb4b9

**Comment by karb0f0s** [comment]
wow https://github.com/dotnet/corefx/issues/4382

**Comment by karb0f0s** [comment]
BTW I think constants should be replaced with HttpStatusCode - either exception class accept HttpStatusCode, or error code will be cast to int?
https://github.com/TelegramBots/Telegram.Bot/blob/ce94da88aecb870b7e7a263d2f0e50da82beaba0/src/Telegram.Bot/TelegramBotClient.cs#L222-L225
https://github.com/TelegramBots/Telegram.Bot/blob/ce94da88aecb870b7e7a263d2f0e50da82beaba0/src/Telegram.Bot/TelegramBotClient.cs#L243-L245
https://github.com/TelegramBots/Telegram.Bot/blob/ce94da88aecb870b7e7a263d2f0e50da82beaba0/src/Telegram.Bot/TelegramBotClient.cs#L198
https://github.com/TelegramBots/Telegram.Bot/blob/ce94da88aecb870b7e7a263d2f0e50da82beaba0/src/Telegram.Bot/TelegramBotClient.cs#L297

Maybe the same should be made here
https://github.com/TelegramBots/Telegram.Bot/blob/ce94da88aecb870b7e7a263d2f0e50da82beaba0/src/Telegram.Bot/Exceptions/BadRequestException.cs#L10
and here
https://github.com/TelegramBots/Telegram.Bot/blob/ce94da88aecb870b7e7a263d2f0e50da82beaba0/src/Telegram.Bot/Exceptions/ForbiddenException.cs#L10
bcs at first there is a check for HttpStatusCode and after comes some constants

**Comment by matteocontrini** [comment]
@karb0f0s is that integration test working? Last time I asked to BotSupport they said that when sending messages to groups the 429 reply could actually never come because they `wait for small flood delays` and then handle the request. Here is a part of my conversation with them. This was in September.

Me:

> 1) it seems that when reaching the limit of 20 messages per minute per group, the Bot API starts rejecting the requests instead of sending back 429. I'm getting ESOCKETTIMEDOUT in a Node.js app when I go over that limit. I expect 429 to be returned so that I can filter the type of response and decide what to do
> 2) when I reach the limit above and I start getting ESOCKETTIMEDOUT, it seems that I should not retry the requests anymore because they're queued on your end? Is that correct? I've seen messages being sent to a group I was testing with in batches of 5 for some time after I killed the script that was sending the messages

Support:

>I can confirm it, requests are waiting for small flood delays on our side. Socket timeout should be set to at least 65 seconds to always receive an answer and don't receive ESOCKETTIMEDOUT ;)

**Comment by Tuscen** [comment]
@matteocontrini I tried to get 429 in tests but I couldn't. Now I know why :)

**Comment by karb0f0s** [comment]
@matteocontrini it worked yesterday. i send request in parallel, it breaks flood protection i guess

**Comment by karb0f0s** [comment]
should this exception have parameter reflecting retry delay?

**Comment by Tuscen** [comment]
@karb0f0s retry delay should be inside `ApiException.ResponseParameters. RetryAfter` property.

**Comment by karb0f0s** [comment]
[throw TooManyRequestsException with with apiResponse.Parameters](https://github.com/TelegramBots/Telegram.Bot/commit/41fafb449560a6084949ee27c5ec7d13cf9783db)
