### ISSUE TITLE
SetWebhookAsync in v14.2.0-rc-455 

### ISSUE THREAD

**Issue by jcmag** [TelegramBots/Telegram.Bot#633]
Hi,
I've updated my code to use the latest version of your API (14.2.0-rc-455 ), so I've changed SetWebhook() with SetWebhookAsync. I got no exception, but then my bot doesn't receive any message...
Do you have an idea of what could be the problem?

**Comment by jcmag** [comment]
I've found the issue, I had this method in my webhook controller:
 public async void DownloadFileAsync(File fileInfo, Stream s)

and it causes an error for asp.net ("multiple actions were found that match the request: 
Post on type ....WebhookController
DownloadFileAsync on type ...WebhookController")

I've added the [NonAction] attribute in front of DownloadFileAsync, and now it works :-)

**Comment by pouladpld** [comment]
@jcmag Read issue template. No support is provided on gh issues.
