### ISSUE TITLE
Send Voice Message

### ISSUE THREAD

**Issue by AppleAssistant** [TelegramBots/Telegram.Bot#637]
# I have a question

Hi, i want send audio as voice, but i can't ! please give me a example for this.

Sorry I can't use this group chat [TGBots_DotNet](https://t.me/tgbots_dotnet) !

![11](https://user-images.githubusercontent.com/12428325/37243577-0ba6b2ba-2491-11e8-87ab-da74414520c5.jpg)

Help Me. Thanks ♥.

*NuGet Package Version:* (14.2.0-rc-452)

*.NET Version:* (4.5)

*IDE:* (VS2017)

*App:* (Desktop Convert MP3 To Voice)

**Comment by pouladpld** [comment]
@AppleAssistant As you know, we don't provide support via gh issues. 

Please contact tg support and ask them why you cannot join a public supergroup that has no restrictions!

**Comment by AppleAssistant** [comment]
### I did not want to resolve my telegram problem!
I said i can not log in to chat and i have to ask a question here!
**But I've been asking you to give me a sample code to send voice by the robot!**
I do not know how to tell my problem! Whatever we ask you to get out!

**Comment by matteocontrini** [comment]
What have you tried? What problems are you facing? Have you looked at the example code in the integration tests?

**Comment by AppleAssistant** [comment]
Yes Sir,
**I now understand my problem**, but this friend did not help or guide me until I find the solution !!
I found the answer in: [Send Voice](https://github.com/TelegramBots/Telegram.Bot/pull/626/commits/430c24abd8b34b4af5617d04bf9e75de9c856463)
**My problem was: i must convert mp3 to ogg format and send ogg file as voice!**
I tried to send the mp3 file with voice send method and I was in trouble.
Thank you my friend for your attention.

**Comment by karb0f0s** [comment]
Dear Sir. 
There is no point to hold a grudge on developers here. 
The Telegram Bot API is pretty much language-agnostic, so if you provide some code that you failed to translate to C#, or you have some C# code that does not work the way you expect - it would be easier to help you. 
Issue tracker here mostly supposed to document missing functions, or incorrect library behavior, or suggestions on what would this library be in the future. It is not supposed to track issues on Telegram side, neither hold discussions about Telegram Client and such. And we do not yet have community big enough to expect some real discussions or code suggestions. 
Regarding problems with our Telegram discussion group - we submitted this issue to Telegram Support and I would recommend you to make such request too.
I hope the issue with the group will be resolved soon, hope to see you there.

**Comment by AppleAssistant** [comment]
**Thank you very much for your follow up and response.**

I'm looking for this and looking for it.
I have seen various solutions and methods. I am looking for a very simple method and solution.

I got this now:
**Use a program called Sox.exe. Very comfortable and accurate.**

I'm going to tell you how to use it and explain the rest of my friends that they were looking for.

1. First, download the Sox program. (I will attach the file at the end of the post)

2. Copy this app with its folder to your app's **bin** folder.

3. Use the following method in your application:

```
public void SoxConvertMethod()
    {
        var startInfo = new ProcessStartInfo();
        startInfo.FileName = "sox-folder/sox.exe";
        startInfo.Arguments = "sox-folder/[INPUT_AUDIO_ADDRESS] -r 16000 [OUTPUT_FILE_ADDRESS_AND_FORMAT]";
        //EX.  startInfo.Arguments = "sox-folder/D:\\MyAudio.mp3 -r 16000 D:\\OutAudio.ogg";
        //EX.  startInfo.Arguments = "sox-folder/D:\\MyAudio.mp3 D:\\OutAudio.ogg";
        startInfo.WindowStyle = ProcessWindowStyle.Hidden;
        startInfo.UseShellExecute = false;
        startInfo.CreateNoWindow = false;
        startInfo.WorkingDirectory = AppDomain.CurrentDomain.BaseDirectory; // this is bin folder address ;)
        using (Process soxProc = Process.Start(startInfo))
        {
            soxProc.WaitForExit();
        }
    }
```

Hope my little help is good for friends :)

Good Luck.

[Download -->  SOX_AppleAssistant.zip](https://github.com/TelegramBots/Telegram.Bot/files/1799835/SOX_AppleAssistant.zip)

**Comment by AppleAssistant** [comment]
My friends have another good news!

I found the easiest way to convert each audio to another audio format !

The easiest way is to use a **SoxSharp.dll** 

This Library is availabe in Nuget :  [SoxSharp.dll in Nuget](https://www.nuget.org/packages/SoxSharp)

Learn this library at :  [SoxSharp Tutorial](https://github.com/igece/SoxSharp)

Good Luck.

**Comment by Olfi01** [comment]
Are you from the Philippines perhaps? Telegram is blocking users from certain countries from joining public groups

**Comment by pouladpld** [comment]
Guys, many people are watching this repository and they keep getting unrelated notifications from threds like this one. What @AppleAssistant is doing seems interesting but here is not the right place.

P.S. I am still waiting for tg support to investigate the issue some users have with joining the group

**Comment by pouladpld** [comment]
@AppleAssistant 
It seems you can't join a public supergroup using Iran's filternet. Try a VPN.
