### ISSUE TITLE
Is it possible to copy members from one group to another?

### ISSUE THREAD

**Issue by mia0x75** [TelegramBots/Telegram.Bot#638]
Just wonder if bot API has such method to copy members between groups, thanks.

**Comment by matteocontrini** [comment]
You can find out by yourself 😉  https://core.telegram.org/bots/api#available-methods
It's not possible

**Comment by karb0f0s** [comment]
@mia0x75 please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/ISSUE_TEMPLATE.md)
If you need to chat, join our [group chat](https://t.me/tgbots_dotnet).
