### ISSUE TITLE
BotBlockedException tests

### ISSUE THREAD

**Issue by pouladpld** [TelegramBots/Telegram.Bot#639]
There are currently no tests for `BotBlockedException`.

@karb0f0s suggests having the id of a user who blocked the bot in test configs.

In that case, related tests should go into a separate collection with its class fixture. This ensures such config is optional for a tester unless he wants to test that exception.

**Comment by karb0f0s** [comment]
This issue was moved to TelegramBots/Telegram.Bot.Extensions.Exceptions#4
