### ISSUE TITLE
Force commit message format

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#641]
We could use commitlint to check commit message.

There are possible options to configure linting:
- [setup local commitmsg hook](https://jaketrent.com/post/enforce-git-commit-message-format/)
- [setup travis-ci integration](https://github.com/marionebl/commitlint/blob/master/docs/guides-ci-setup.md)
- setup github bot: [commitlint-bot](https://github.com/ahmed-taj/commitlint-bot/blob/master/README.md) or [commitlintbot](https://github.com/paulirish/commitlintbot/blob/master/README.md)

**Comment by wiz0u** [comment]
Don't make our job more annoying. We work for free here.
