### ISSUE TITLE
All chat admins are authorized testers

### ISSUE THREAD

**Issue by pouladpld** [TelegramBots/Telegram.Bot#644]
In Sys Integ tests configs, we specify the usernames that can interact with the bot during the test execution. That is mandatory.

It could be optional and list of _authorized_ users could be retrieved from `getChatAdministrators` method.

**Comment by karb0f0s** [comment]
some tests require nonadmins as chat members, so this tests will fail [example](https://github.com/TelegramBots/Telegram.Bot/blob/5e41805e69c4cb3294a6c8d0175b1f029ea2557c/test/Telegram.Bot.Tests.Integ/Exceptions/ApiExceptionsTests.cs#L55)

**Comment by pouladpld** [comment]
@karb0f0s Those regular users in chat don't need to interact with bot at all.

**Comment by karb0f0s** [comment]
if regular use is not in authorized list, bot will ignore update message when user joins chat. i spent few hour debugging this behavior.

**Comment by pouladpld** [comment]
How about the following?

All admins in the supergroup are white-listed users and bot ignores updates from everybody else. This means removing `AllowedUserNames` from test settings.

The test collections like _chat member administration_ that need a _regular chat member_ should have a fixture that checks existence of such a setting. If value isn't set:
1. Send a message: "Reply to this message with the mention of a regular chat member"
1. Wait for reply to previous message
1. Set the value and start tests

Also `TestsFixture.AllowedUserNames` changes to an `ICollection<string>` to allow granting temporary access to a user for particular tests. for example:
```c#
class MyFixture : IDisposable {
  MyFixture(fixture) { fixture.AllowedUserName.Add("pouladpld") }
  void Dispose() { fixture.AllowedUserName.Remove("pouladpld") }
}
```
