### ISSUE TITLE
How can i Recieve Deleted Message Update ?

### ISSUE THREAD

**Issue by pesar368** [TelegramBots/Telegram.Bot#645]
Hi
In the GetUpdates Method i can Recieve Edited Message update
but
i want to Recieve Deleted Message Update .
How can i understand When Message Deleted ?

It Seems  [updates.getDifference](https://core.telegram.org/method/updates.getDifference) Method can do it. how can i use it ?

**Comment by Olfi01** [comment]
There is no such thing as a DeletedMessageUpdate afaik.

**Comment by karb0f0s** [comment]
@mia0x75 please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/ISSUE_TEMPLATE.md)
If you need to chat, join our [group chat](https://t.me/tgbots_dotnet).

updates.getDifference  method belongs to Telegram Client API, library only provide Telegram Bot API
