### ISSUE TITLE
Clean ApiException.cs

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#646]
We should clean this commented out part in 
[public static ApiRequestException FromApiResponse<T>(ApiResponse<T> apiResponse)](https://github.com/TelegramBots/Telegram.Bot/blob/d94d7e6f295e40eb1da504b38569a7c762c60807/src/Telegram.Bot/Exceptions/ApiException.cs#L85-L161)
some exceptions already implemented, and there is no need to keep dead code for them, some not implemented yet, like [case "bot was blocked by the user"](https://github.com/TelegramBots/Telegram.Bot/blob/d94d7e6f295e40eb1da504b38569a7c762c60807/src/Telegram.Bot/Exceptions/ApiException.cs#L137) but declared, which is misleading

**Comment by karb0f0s** [comment]
Should `BadRequestException` and `ForbiddenException` abstract classes be renamed to `BadRequestExceptionBase` and `ForbiddenExceptionBase`?
Could then `BadRequestException` and `ForbiddenException` classes be used to throw general 400 and 403 errors?

**Comment by Tuscen** [comment]
@karb0f0s Agree, it makes sense to throw general `BadRequestException` and `ForbiddenException`  when there is no particular exception type.

**Comment by karb0f0s** [comment]
https://github.com/TelegramBots/Telegram.Bot/pull/653

**Comment by karb0f0s** [comment]
Closed due to inactivity
