### ISSUE TITLE
Add "Forbidden: bot is not a member of the channel chat" exception

### ISSUE THREAD

**Issue by tuscen** [TelegramBots/Telegram.Bot#648]
HTTP code: `403`
Error message: ` Forbidden: bot is not a member of the channel chat`

**Comment by karb0f0s** [comment]
How do you get this? Send message to some public channel when you are not its member?

**Comment by Tuscen** [comment]
Either public or private, doesn't matter.

**Comment by karb0f0s** [comment]
I was able to test this exception in supergroup and channel, it is not thrown for regular group - ChatNotFoundException is thrown instead

**Comment by karb0f0s** [comment]
[Add BotIsNotMemberException](https://github.com/TelegramBots/Telegram.Bot/commit/0dd29b39496e3e88704932564af5cc69437030ca)

**Comment by karb0f0s** [comment]
anyone can think of better a name?

**Comment by Tuscen** [comment]
It should somehow include word "channel" because it is thrown only for channels.

**Comment by pouladpld** [comment]
If such errors happen for other chats, we could use general base and derived subclasses.

**Comment by karb0f0s** [comment]
@Tuscen actually not 'bot is not a member of the (supergroup|channel) chat'

**Comment by Tuscen** [comment]
@karb0f0s yeah, makes sense to have single type if it can be thrown with slightly different error message for other chats.

**Comment by karb0f0s** [comment]
This issue was moved to TelegramBots/Telegram.Bot.Extensions.Exceptions#3

**Comment by AngryBandera** [comment]
> This issue was moved to [TelegramBots/Telegram.Bot.Extensions.Exceptions#3](https://github.com/TelegramBots/Telegram.Bot.Extensions.Exceptions/issues/3)

Have you fixed this issue? I have bot, but one day he started throwing this error. I idk what to do.
