### ISSUE TITLE
get last user message

### ISSUE THREAD

**Issue by mattiusad** [TelegramBots/Telegram.Bot#654]
Hi .I have question
  i make bot in c# with telegram.bot,but i can't get text from user and process it,
  because i can't get the last message of user's message.
  please help me

**Comment by karb0f0s** [comment]
@mattiusad  please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/ISSUE_TEMPLATE.md)
If you need to chat, join our [group chat](https://t.me/tgbots_dotnet).
