### ISSUE TITLE
Use username instead of id

### ISSUE THREAD

**Issue by aliarabbasi5155** [TelegramBots/Telegram.Bot#655]
Hi MrRoundRobin;
How can I send a message to specific username instead of specific chat id?

**Comment by karb0f0s** [comment]
@aliarabbasi5155  please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/ISSUE_TEMPLATE.md)
If you need to chat, join our [group chat](https://t.me/tgbots_dotnet).

And no, you cannot send message to user by name, you can only send messages using username to public channels
