### ISSUE TITLE
External references can be updated

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#656]
Some external references could be updated:
![image](https://user-images.githubusercontent.com/17474471/38027868-c648e5dc-3299-11e8-99a5-62bc7784c759.png)

**Comment by karb0f0s** [comment]
@pouladpld @Tuscen any contraindications or suggestions? can we merge [this PR](https://github.com/TelegramBots/Telegram.Bot/pull/658)?

**Comment by karb0f0s** [comment]
https://github.com/JamesNK/Newtonsoft.Json/releases
we are here 
[10.0.3](https://github.com/JamesNK/Newtonsoft.Json/releases/tag/10.0.3)
updated 
[11.0.2](https://github.com/JamesNK/Newtonsoft.Json/releases/tag/11.0.2)
[11.0.1](https://github.com/JamesNK/Newtonsoft.Json/releases/tag/11.0.1)

**Comment by Tuscen** [comment]
@karb0f0s what will happen if my app uses Newtonsoft.Json v10?

**Comment by pouladpld** [comment]
Json and Tests are fine. If others are for same netstandard version, all is good.

**Comment by karb0f0s** [comment]
well, Newtonsoft.Json changelog is pretty impressive, and it has .NETStandard 1.3 in dependencies (same as 10.0.3).
other references only apply to tests, we have .netcore 2.0 project there

**Comment by karb0f0s** [comment]
I did a research:
If user reference in his code `Newtonsoft.Json` version `10.0.3` and library reference higher version `Newtonsoft.Json` version `11.0.2`, then package installation fails with error `NU1605: Detected package downgrade: Newtonsoft.Json from 11.0.2 to 10.0.3. Reference the package directly from the project to select a different version.`
If user reference newer version `Newtonsoft.Json` version `11.0.2`, and library reference older version `Newtonsoft.Json` version `10.0.3` then `Newtonsoft.Json` version `11.0.2` used globally.
So this mean, that if we upgrade `Newtonsoft.Json` to version `10.0.3`, client will be forced to upgrade too. 
On the other side, we have to be aware of `Newtonsoft.Json` updates, because if it will contain some breaking changes, our code could break in updated user environment.
