### ISSUE TITLE
Problem WithSwitchInlineQuery in channel

### ISSUE THREAD

**Issue by Ramin-Bateni** [TelegramBots/Telegram.Bot#660]
### Why `SwitchInlineQuery` buttons in a `ReplyMarkup` dose not appear under a **channel** post with the following code?

```
// It just show the btn4 button!

new InlineKeyboardButton[]
{
      InlineKeyboardButton.WithSwitchInlineQuery( "btn1", "aaaaa"),
      InlineKeyboardButton.WithSwitchInlineQuery( "btn2", ""),
      InlineKeyboardButton.WithSwitchInlineQuery( "btn3", "None"),
      InlineKeyboardButton.WithUrl("btn4", "http://www.google.com"),
}
```

**Is it a Telegram limit or a bug in `Telegram.Bot` library?**

**Note1:** If it is a Telegram limit why when I use `WithSwitchInlineQueryCurrentChat`, Telegram return me an error that say "You can not have a switch_inline_query_current_chat in a channel" but when I use `WithSwitchInlineQuery `Telegram dose not return any error and just dose not show the `SwitchInline` buttons and just show the above defined `Url Button `(`btn4`)?

**Note2:** It show all the buttons in the `bot`.  
_________________________________________________________
*NuGet Package Version:* 14.2.0-rc-452
*.NET Version:* 4.5

**Comment by karb0f0s** [comment]
[Inline keyboards with switch_inline_query and switch_inline_query_current_chat can no longer be sent to channels because they are useless there](https://github.com/yagop/node-telegram-bot-api/issues/268#issuecomment-302696051)

**Comment by Ramin-Bateni** [comment]
@karb0f0s Thank you for your reply and the reference.

I think Telegram has made a mistake about `switch_inline_query`. It is useful for my bot! It seems they should just prevent sending `switch_inline_query_current_chat ` inline keyboard. I hope they allow sending `switch_inline_query` inline keyboard again in channels.
