### ISSUE TITLE
Chat.Id is negative because of long overflow

### ISSUE THREAD

**Issue by interpol-kun** [TelegramBots/Telegram.Bot#661]
Hey! The Chat.Id returns negative values.

This is the output with the default value type -- **long** (first number is chat ID):

![image](https://user-images.githubusercontent.com/7690603/38275051-4f4a515a-3799-11e8-9374-638a72ec8e59.png)

This is the output for the **ulong**:
![image](https://user-images.githubusercontent.com/7690603/38275100-707a89c6-3799-11e8-9ec8-ed07b7a7579e.png)

NuGet Package Version: 13.4.0

.NET Version: 4.7.2

IDE: VS2017

App: Desktop console app

**Comment by matteocontrini** [comment]
Groups and supergroups have negative IDs, this is correct

**Comment by karb0f0s** [comment]
@interpol-kun  it's due to the specification. you can check this by making api requests yourself in browser or rest test app like Insomnia
