### ISSUE TITLE
Add "Forbidden: bot was kicked from the group chat" exception

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#662]
HTTP code: `403`
Error message: 
- `Forbidden: bot was kicked from the group chat exception`
- `Forbidden: bot was kicked from the group channel exception`
- `Forbidden: bot was kicked from the group supergroup exception`

You receive this error if you add bot to group, remove it, and try to send message to that group afterwards

**Comment by karb0f0s** [comment]
I see two possible test runs for this exception:
- user should remove bot from test chat before excecution (and add back after)
- create some BotBlockedChat and add/remove bot from there (i created two chats, deleted them, but I still receive this error when send messages)

**Comment by karb0f0s** [comment]
For my test case I created 3 groups in which I added and then removed my testbot:
```csharp
long[] groups =
{
  -1001100532129, // BotBlockedSupergroup
  -1001298749133, // BotBlockedGroup
  -262679471, // BotBlockedChannel
};
```
after upgrading BotBlockedSupergroup from regular group to supergroup i caught a [Bad Request: group chat was upgraded to a supergroup chat](#663) error

**Comment by karb0f0s** [comment]
I'd like to commit the tests with fixed `chatId`s, and maybe move them to settings/class fixture later. Is it appropriate?

**Comment by Tuscen** [comment]
I'm okay with more interactivity during integ tests because some of them couldn't really be done either without more configs (several group chats and channels for different tests, etc) or without user interaction. But @pouladpld have different opinion on this.

**Comment by karb0f0s** [comment]
@Tuscen [Sergey Khabibullin](https://github.com/x2bool) unofficially created a wrapper classes for [TDLib](https://github.com/x2bool/tdsharp) and published them as NuGet package [TDLib](https://www.nuget.org/packages/TDLib/). 
I'm planning to add Telegram client features to tests, so we do not have to wait for user interactions, but send actions through TDLib.

**Comment by Tuscen** [comment]
@karb0f0s Nice. It would be super helpful 👍

**Comment by karb0f0s** [comment]
This issue was moved to TelegramBots/Telegram.Bot.Extensions.Exceptions#2

**Comment by sid-khullar** [comment]
Hi. I'm not sure if this is the right place, but I'm at a loss for options. My bot receives the "bot was kicked from the supergroup chat" when it tries to send a message to a group it used to be a part of, was removed and then added again as an admin. Now the desktop client shows it has access to messages, but the mobile client shows it does not have access.

**Comment by PM84** [comment]
> Hi. I'm not sure if this is the right place, but I'm at a loss for options. My bot receives the "bot was kicked from the supergroup chat" when it tries to send a message to a group it used to be a part of, was removed and then added again as an admin. Privacy mode is disabled.

Same here...

Bot was removed from Group and re-added. After that, i got these error when trying to send messages to the group.

**Comment by sid-khullar** [comment]
I ended up having to create a new bot for the purpose.

**Comment by mihailmariusiondev** [comment]
Any news on this?

**Comment by him-v** [comment]
Here is what worked for me:
1. After the bot tried to send message to group chat via python, the chat got upgraded to supergroup chat.
`Starting
Sending message...
Failed to send message: 400 {"ok":false,"error_code":400,"description":"Bad Request: group chat was upgraded to a supergroup chat","parameters":{"migrate_to_chat_id":-xxxxxxxx0}}
Response: {'ok': False, 'error_code': 400, 'description': 'Bad Request: group chat was upgraded to a supergroup chat', 'parameters': {'migrate_to_chat_id': -xxxxxxxx0}}
Ending`
2. After this I used the migrate_to_chat_id provided in the message and then the python was able to send messages.
