### ISSUE TITLE
Consider deprecating Message.IsForwarded property in v14 and removing in v15

### ISSUE THREAD

**Issue by tuscen** [TelegramBots/Telegram.Bot#667]
Forwarding a message from a channel produces different message object than from a group/private chat due to missing `User` object. This makes `IsForwarded` prop confusing to users. Splitting it in two different props will make the problem worse because it's yet another adhoc check that can be made by users. Consider deprecating it in v14 and removing in v15.

![2018-04-08 18 46 06](https://user-images.githubusercontent.com/1078199/38469473-fe74db42-3b5d-11e8-9dd7-b84c460ad41f.jpg)

**Comment by pouladpld** [comment]
@tuscen That's right. make a PR please
