### ISSUE TITLE
Fix description for LivePeriod property in InlineQueryResultLocation class

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#668]
https://github.com/TelegramBots/Telegram.Bot/blob/16facadc1c27eaf23ffe8edcdb80382ea037648e/src/Telegram.Bot/Types/InlineQueryResults/InlineQueryResultLocation.cs#L32-L36

Summary for `LivePeriod` should be
```csharp
        /// <summary>
        /// Period in seconds for which the location can be updated, should be between 60 and 86400.
        /// </summary>
```

**Comment by pouladpld** [comment]
@karb0f0s Make a PR instead please
