### ISSUE TITLE
Disable InlineQueryResult caching in Should_Delete_Message_From_InlineQuery

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#669]
https://github.com/TelegramBots/Telegram.Bot/blob/16facadc1c27eaf23ffe8edcdb80382ea037648e/test/Telegram.Bot.Tests.Integ/Update%20Messages/DeleteMessageTests.cs#L52-L61
Add `cacheTime: 0` to AnswerInlineQueryAsync call to avoid result caching
```csharp
await BotClient.AnswerInlineQueryAsync(
    inlineQueryId: queryUpdate.InlineQuery.Id,
    cacheTime: 0,  // <==
    results: new[]
    {
        new InlineQueryResultArticle(
            id: "article-to-delete",
            title: "Telegram Bot API",
            inputMessageContent: new InputTextMessageContent("https://www.telegram.org/")
        )
    }
);
```

**Comment by pouladpld** [comment]
@karb0f0s 
Yes. It's better to have it even though that isn't an issue now. Feel free to make a PR.

**Comment by karb0f0s** [comment]
done https://github.com/TelegramBots/Telegram.Bot/commit/4f88277c4c8f1bff04bfd3fdebd6f3e87e46ce99
