### ISSUE TITLE
Add "DebugType Full" to project to enable Code Coverage Report

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#670]
As per issue in Microsoft/vstest issue [Code coverage requires DebugType full #800](https://github.com/Microsoft/vstest/issues/800) adding `<DebugType>Full</DebugType>` to Telegram.Bot.csproj makes it possible to generate Code Coverage Report in Visual Studio (don't know about 3rd party editors) for .Net Core projects.
```
 <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework> 
    <DebugType>Full</DebugType>
  </PropertyGroup>
```

![image](https://user-images.githubusercontent.com/17474471/38471179-30880efc-3b76-11e8-97e8-17c22832438c.png)

**Comment by pouladpld** [comment]
@karb0f0s 
This is neat. Can we use this in CI? or use another service available?
