### ISSUE TITLE
Should_Edit_Message_Markup test failing

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#671]
[`Should_Edit_Message_Markup`](https://github.com/TelegramBots/Telegram.Bot/blob/16facadc1c27eaf23ffe8edcdb80382ea037648e/test/Telegram.Bot.Tests.Integ/Update%20Messages/EditMessageContentTests.cs#L92-L116) test is failing because edited message contains `edit_date` property:
Original message:
```json
{
  "message_id": 4608,
  "from": {
    "id": 464646464,
    "is_bot": true,
    "first_name": "mytestbot",
    "username": "mytestbot"
  },
  "date": 1523271033,
  "chat": {
    "id": -1001165656565,
    "type": "supergroup",
    "title": "Test Chat Title",
    "username": "mytestbot"
  },
  "text": "Inline keyboard will be updated shortly"
}
```
Edited message:
```json
{
  "message_id": 4608,
  "from": {
    "id": 464646464,
    "is_bot": true,
    "first_name": "mytestbot",
    "username": "mytestbot"
  },
  "date": 1523271033,
  "chat": {
    "id": -1001165656565,
    "type": "supergroup",
    "title": "Test Chat Title",
    "username": "mytestbot"
  },
  **"edit_date": 1523271034,**
  "text": "Inline keyboard will be updated shortly"
}
```

**Comment by pouladpld** [comment]
This test used to pass before. Tg team must have fixed that now.

**Comment by pouladpld** [comment]
Oh. I now remember that I reported this issue to BotSupport earlier.

https://github.com/TelegramBots/Telegram.Bot/blob/16facadc1c27eaf23ffe8edcdb80382ea037648e/test/Telegram.Bot.Tests.Integ/Update%20Messages/EditMessageContentTests.cs#L49
