### ISSUE TITLE
find groups administrators

### ISSUE THREAD

**Issue by shahryarse** [TelegramBots/Telegram.Bot#672]
how can i find out that the person who have sent a message in group is admin or not?
please send an example
thanks

**Comment by karb0f0s** [comment]
@shahryarse we do not provide help on GitHub. If you have trouble with library please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/ISSUE_TEMPLATE.md)
If you need to chat, join our [group chat](https://t.me/tgbots_dotnet).
