### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by SkyQuant** [TelegramBots/Telegram.Bot#673]
Can we add proxy configuration (with a link to .pac file, for example) in bot communication to avoid some contries blocking policy?

**Comment by Tuscen** [comment]
@SkyQuant we do not provide help on GitHub. If you have trouble with library please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/ISSUE_TEMPLATE.md)
If you need to chat, join our [group chat](https://t.me/tgbots_dotnet).
