### ISSUE TITLE
how to share InlineKeyboardButton ?

### ISSUE THREAD

**Issue by Hamed6380** [TelegramBots/Telegram.Bot#674]
hi;
how to share InlineKeyboardButton to other chat “private”, “group”, “supergroup” or “channel”
so that show completely?

**Comment by pouladpld** [comment]
Read [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/ISSUE_TEMPLATE.md) and join our group [@tgbots_dotnet](https://t.me/tgbots_dotnet) if you have any questions.
