### ISSUE TITLE
OnMessage event not contain the value of MessageEventArgs.Message.Chat.Description 

### ISSUE THREAD

**Issue by hzexe** [TelegramBots/Telegram.Bot#677]
In  void BotOnMessageReceived(object sender, MessageEventArgs messageEventArgs) method ,the MessageEventArgs.Message.Chat.Description is null if a message is from a group that have the description.
May be a bug?

*NuGet Package Version:* (e.g. 13.0.1)
Include vs2017
*.NET Version:* (e.g. 4.7, Core 1.1, Mono, etc.)
.net core 2.0
*IDE:* (e.g. VS2017, VS Code, etc.)
vs2017
*App:* (e.g. Desktop, iOS, Android, etc.)
Desktop

**Comment by karb0f0s** [comment]
@hzexe, we recently released v14.3.0, could you reproduce this error after update?

**Comment by karb0f0s** [comment]
I was not able to reproduce, no new info was provided.
