### ISSUE TITLE
GetChatMemberAsync

### ISSUE THREAD

**Issue by SignCube** [TelegramBots/Telegram.Bot#689]
Hi i think GetChatMemberAsync Method  user_id  type   Should Be Long

**Comment by karb0f0s** [comment]
In official Telegram schema it declared as `user_id:int32`

https://github.com/tdlib/td/blob/be48e787bcc0bc3b10da60eb03fc77b513a7db9b/td/generate/scheme/td_api.tl#L2400-L2401
