### ISSUE TITLE
How wait new message from user?

### ISSUE THREAD

**Issue by AlexToxS** [TelegramBots/Telegram.Bot#698]
By dialog with bot?

case "/captcha":
 Bot: "Write Captcha code"
 User: "{captcha}"
 Bot: "Ok Captcha Succesed"

break;

**Comment by tuscen** [comment]
@AlexToxS 
Read [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/.github/ISSUE_TEMPLATE/Question.md) and join our group [@tgbots_dotnet](https://t.me/tgbots_dotnet) if you have any questions.
