### ISSUE TITLE
your group chat username is not found !

### ISSUE THREAD

**Issue by ParsaRt** [TelegramBots/Telegram.Bot#705]
I'm posting it just because you have either changed your username or removed the group totally ! 

I have questions about how to implement my c# bot on a server ! 

what i want to know is that do i have to get a Windows VPS and run my console application in it or is there any other/cheaper way ? 

thanks in advance.

**Comment by tuscen** [comment]
@ParsaRt Since you're from Iran try using VPN or a proxy. The group isn't removed. All users from Iran have issues with public channels and supergroups.
