### ISSUE TITLE
Using Proxy

### ISSUE THREAD

**Issue by dukesaeed** [TelegramBots/Telegram.Bot#721]
As you know these bot programs are executed on server in most cases, and due to filtering telegram in some countries the program won't work,
Is there a solution to use proxies for bot ?

**Comment by pouladpld** [comment]
@dukesaeed Please follow issue templates and we do not provide support via GitHub issues.

However, there are solutions for using proxy. Please ask that in our support chat:
<https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA> or [tgbots_dotnet](https://t.me/tgbots_dotnet)
