### ISSUE TITLE
Error converting value "phone_number" to type 'Telegram.Bot.Types.Enums.MessageEntityType'

### ISSUE THREAD

**Issue by fedderrico** [TelegramBots/Telegram.Bot#724]
# I found a bug to report

Hello,
Thanks for this project! It's great.

A couple of days ago i moved to version 14 and everythink was OK, but from today i'm getting error when trying to get updates.

### Steps to reproduce
var updates = await _client.GetUpdatesAsync(_client.MessageOffset)

### Expected  behavior
getting updates

### Actual behavior
018-06-06 10:34:30.1650|ERROR|MyBot|Newtonsoft.Json.JsonSerializationException: Error converting value "phone_number" to type 'Telegram.Bot.Types.Enums.MessageEntityType'. Path 'result[0].message.entities[0].type', line 2, position 483. ---> System.ArgumentException: Requested value 'phone_number' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---

### Environment data

*NuGet Package Version:* 14.3.0

*.NET Version:* 4.5

*IDE:*  VS2015

*App:* Desktop

**Comment by tuscen** [comment]
@fedderrico Thank you. We already have a fix for this bug and will soon release an update to Nuget.

**Comment by fuad86** [comment]
I also get the same error, there is an incoming message containing the phone number.
But strangely, if you create a new bot account, there is no error when sent a message in the form of a phone number.

the error : 
Error converting value "phone_number" to type 'Telegram.Bot.Types.Enums.MessageEntityType'. Path 'result[0].message.entities[0].type', line 2, position 369.

hopefully soon there are updates and solutions, thanks.

**Comment by mafaza86** [comment]
I also get the same error, there is an incoming message containing the phone number.
But strangely, if you create a new bot account, there is no error when sent a message in the form of a phone number.

the error : 
Error converting value "phone_number" to type 'Telegram.Bot.Types.Enums.MessageEntityType'. Path 'result[0].message.entities[0].type', line 2, position 369.

hopefully soon there are updates and solutions, thanks.

**Comment by pouladpld** [comment]
@mafaza86 This `phone_number` entity seems to be a new undocumented change. Fix will be available shortly.

**Comment by SaeedTuzande** [comment]
i am also have same problem
any fix or update?

**Comment by pouladpld** [comment]
<https://www.nuget.org/packages/Telegram.Bot/14.5.0>

**Comment by mafaza86** [comment]
thanks @pouladpld work perfect...

**Comment by fedderrico** [comment]
Thanks!

**Comment by karb0f0s** [comment]
@SaeedTuzande join our group [TelegramBots - .NET](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA) for discussion. Check out [examples](https://github.com/TelegramBots/Telegram.Bot.Examples) to see possible library use cases, like this one:
https://github.com/TelegramBots/Telegram.Bot.Examples/blob/f59ac9b2449b56947dd4795141dae85422696a4d/Telegram.Bot.Examples.Echo/Program.cs#L48-L60

**Comment by SaeedTuzande** [comment]
@karb0f0s  i want to make buttons online (read from sql or database) i was use old method .. but in update 14  i donot know how make it runtime

**Comment by pouladpld** [comment]
@SaeedTuzande It's unrelated to bug report. Please join the our group and ask there.
