### ISSUE TITLE
proxy 

### ISSUE THREAD

**Issue by erfan132** [TelegramBots/Telegram.Bot#729]
how can i set / use proxy in this freamwork??

**Comment by pouladpld** [comment]
@erfan132  Please follow issue templates. We do not provide support via GitHub issues.

However, there are solutions for using proxy. Please ask that in our support chat:
<https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA> or [tgbots_dotnet](https://t.me/tgbots_dotnet)
