### ISSUE TITLE
telegram.bots for freamwork v 4

### ISSUE THREAD

**Issue by erfan132** [TelegramBots/Telegram.Bot#732]
i want to use this in unity unity works with freamwork v 3.5 plz update it
for freamwork v 3.5 
tnx for great api

**Comment by karb0f0s** [comment]
@erfan132 Telegram.Bot supports .Net 4.5 and newer. We do not have plans to support older .Net versions.  Consider upgrade your environment ot .Net 4.5+ for windows or .Net Core for broader list of supported platforms.
