### ISSUE TITLE
Additional information: Error converting value "phone_number" to type 'Telegram.Bot.Types.Enums.MessageEntityType'.

### ISSUE THREAD

**Issue by 123SERGEY321** [TelegramBots/Telegram.Bot#735]
Hello,
Thanks for this project! It's great.

 I'm getting error when trying to get updates.

Steps to reproduce
var updates = await _client.GetUpdatesAsync(_client.MessageOffset)

Expected behavior
getting updates

Actual behavior
Newtonsoft.Json.JsonSerializationException occurred
  HResult=-2146233088
  Message=Error converting value "phone_number" to type 'Telegram.Bot.Types.Enums.MessageEntityType'. Path 'result[0].message.entities[0].type', line 2, position 327.
  Source=Newtonsoft.Json
  StackTrace:
       в Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
       в Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
       в System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, Encoding effectiveEncoding, IFormatterLogger formatterLogger)
       в System.Net.Http.Formatting.JsonMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, Encoding effectiveEncoding, IFormatterLogger formatterLogger)
       в System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)
       в System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.ReadFromStreamAsync(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)
    --- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
       в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       в System.Net.Http.HttpContentExtensions.<ReadAsAsyncCore>d__0`1.MoveNext()
    --- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
       в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       в System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
       в Telegram.Bot.TelegramBotClient.<SendWebRequestAsync>d__125`1.MoveNext()
    --- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
       в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       в CarlsbergUzBot.Form1.<bw_DoWork>d__46.MoveNext() в d:\Work\TelegramBot\CarlsbergUzBot\CarlsbergUzBot\Form1.cs:строка 113
  InnerException: 
       HResult=-2147024809
       Message=Запрошенное значение "phone_number" не найдено.
       Source=mscorlib
       StackTrace:
            в System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
            в System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
            в System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
            в Newtonsoft.Json.Utilities.EnumUtils.ParseEnumName(String enumText, Boolean isNullable, Type t)
            в Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
       InnerException: 

--- End of inner exception stack trace ---

Screenshots
Environment data
NuGet Package Version: **14.5.0**

.NET Version: 4.5

IDE: VS2015

App: Desktop

**Comment by 123SERGEY321** [comment]
entered value before error 998905660000

**Comment by tuscen** [comment]
Could you provide full json response that causes the exception?

You can log it using `ITelegramBotClient.ApiResponseReceived` event.

**Comment by 123SERGEY321** [comment]
can be more detailed how to use it?
Можно поподробнее как ITelegramBotClient.ApiResponseReceived можно использовать?

**Comment by tuscen** [comment]
Try this:
```c#
client.ApiResponseReceived += async (sender, eventArgs) => {
    var stringResponse = await eventArgs.ResponseMessage.Content.ReadAsStringAsync();
    Console.WriteLine(stringResponse);
};
```

**Comment by 123SERGEY321** [comment]
Error	CS0103	The name 'client' does not exist in the current context

**Comment by 123SERGEY321** [comment]
example of my variables
                Bot.OnCallbackQuery += async (object sc, Telegram.Bot.Args.CallbackQueryEventArgs ev) =>
                {
                    }

**Comment by tuscen** [comment]
`client` is an instance of `ITelegramBotClient`. Substitute it with the name you used.

**Comment by 123SERGEY321** [comment]
Telegram.Bot.ITelegramBotClient haven"t client

**Comment by tuscen** [comment]
Could you please join our group? It would be easier to chat there.

https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA

**Comment by ScottRFrost** [comment]
I'm having this same issue, what was the resolution?

It occurs at line 54 here: https://github.com/ScottRFrost/TrixieBot/blob/master/TelegramProtocol.cs

Telegram.Bot package version 14.4.0

**Comment by MihaZupan** [comment]
@ScottRFrost updating the library to 14.5 or newer fixes the issue.

**Comment by ScottRFrost** [comment]
That got it, thanks!

This issue can probably be closed 🛑
