### ISSUE TITLE
Ability to log and see the body of sent HTTP requests

### ISSUE THREAD

**Issue by Ramin-Bateni** [TelegramBots/Telegram.Bot#740]
## I would like to request/propose ability to log the final output HTTP request that the library send to the Telegram servers.

I know we can use a profiler to see our bot connections but I think for a library that has written for programmers in some cases it will be very useful that this feature be as embedded in the library and developers could check it when they need during developing their bots.
Then if it is possible please write a code like this at the final function of the library that send the request to the Telegram:

```
string bodyOfTheRequest;

try{
        //Send to Telegram codes here
}
catch{
       //.........
}
finally{
       #if (DEBUG && this.IsEnabledLog)
             Console.WriteLine(bodyOfTheRequest_AsFormated);
       #endif
}
```

- `IsEnabledLog` » Is a new `bool` property in `TelegramClient` class that its default value is `false`
- `bodyOfTheRequest_AsFormated` » Is the final body of the sent request.

-------------------------------------------------------------------------------------
Also you can add some other log information by this way in other sections of the app and also you can support some log systems like `nLog` and let the developer to set a path for it and log them in that file.

**Comment by MihaZupan** [comment]
There is already such functionality in the library.
`Bot.MakingApiRequest += (s, e) => { Console.WriteLine(e.HttpContent.ReadAsStringAsync().Result); };`

**Comment by Ramin-Bateni** [comment]
Thank you @MihaZupan , It is right what I wanted...
