### ISSUE TITLE
dll file do not contain some classes.

### ISSUE THREAD

**Issue by imkaka** [TelegramBots/Telegram.Bot#741]
# I found a bug to report
There is no **`InlineKeyboardCallBackButton`** and many other classes available.

*NuGet Package Version:* 14.6.0

*.NET Version:*  4.7, Core 1.1, 

*IDE:* VS2015

*App:* Desktop

**Comment by MihaZupan** [comment]
There is no such thing as an `InlineKeyboardCallBackButton`. Where did you find a reference to any such classes?
Please join our [Group chat](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA) so that this can be more easily discussed.
