### ISSUE TITLE
FileTosend not found

### ISSUE THREAD

**Issue by hamidrezashahnazari** [TelegramBots/Telegram.Bot#743]
Hi, i want to choose a photo and send it to the user but c# can not Find  FileToSend !
here is my code for sending photo button :
        private void btnPhoto_Click(object sender, EventArgs e)
        {
           
            if (dgReport.CurrentRow != null)
            {
                int chatId = int.Parse(dgReport.CurrentRow.Cells[0].Value.ToString());

                FileStream imageFile = System.IO.File.Open(txtFilePath.Text, FileMode.Open);

                Bot.SendPhotoAsync(chatId, new FileToSend("1234.jpg", imageFile), txtMessage.Text);
            }

        }
and also i had System.IO but still do not recognize :(
.Net Version is 4.5.2

**Comment by MihaZupan** [comment]
FileToSend is no longer used by the library. Look at the migration guide: https://github.com/TelegramBots/Telegram.Bot/blob/master/docs/wikis/migration/v13-to-v14.md
