### ISSUE TITLE
Backwards Compatibility

### ISSUE THREAD

**Issue by Olfi01** [TelegramBots/Telegram.Bot#746]
I have had it. I just updated my version and it sucks. Have you ever heard of backwards compatibility? You don't just remove anything in a lib! If needed, add an [Obsolete] tag to it and make it reference the newer, right version. It SUCKS to have to update every single Reference of MessageType in my code! If you program a library, you should keep some consistency so I don't have to recode my whole project just because the library was updated!

**Comment by pouladpld** [comment]
@Olfi01 We noted that and try not to have breaking changes for a while.

**Comment by Olfi01** [comment]
So you refuse to keep backwards compatibility, but you say you won't change anything for a while? That's no help

**Comment by pouladpld** [comment]
Transition to v14 happened over months with preview packages and helping users to port their code in our support chat. It wasn't a sudden change.

It's great to keep the package versions backwards-compatible but after 13 major releases, maintenance was a challenge. Over the course of months, we re-wrote large parts of the project and fixed bugs. The result was a more consistent API for users, more maintainable code for developers, and a higher quality product.

I don't see any breaking changes needed for now unless up stream API forces us to do so. Unfortunately, tg bot API doesn't communicate upcoming changes with dependent teams like us.
