### ISSUE TITLE
OnMessage event is not firing

### ISSUE THREAD

**Issue by djeizan** [TelegramBots/Telegram.Bot#750]
# I found a bug to report

Hello friends, I have identified that when sending a certain text to my BOT the receiving event simply stops working

### Steps to reproduce

When you send text 10010290 to my bot the OnMessage event stops being fired

### Expected  behavior

OnMessage Event Fired.

### Actual behavior

OnMessage Event not Fired

### Screenshots
![image](https://user-images.githubusercontent.com/6104031/41753524-55a5a3ee-75a4-11e8-86d4-0cbc6d998188.png)

### Environment data

*NuGet Package Version:14.6.0.0

*.NET Version:* 4.6.1

*IDE:* e.g. VS2015

*App:* Desktop

**Comment by MihaZupan** [comment]
Are you sure you are using 14.6? The error regarding the phone_number type has been fixed in 14.5

**Comment by djeizan** [comment]
Hi, Yes my version is 14.6.

But i refresh the newtonsoft.json and work fine.

thanks
