### ISSUE TITLE
BaseUrl and BaseFileUrl

### ISSUE THREAD

**Issue by Maverick1983** [TelegramBots/Telegram.Bot#751]
it is possible to make the variables BaseUrl and BaseFileUrl public?

**Comment by tuscen** [comment]
@Maverick1983 Please follow issue templates. We do not provide support via GitHub issues.

If you have questions you can ask them in our support chat:
https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA or tgbots_dotnet
