### ISSUE TITLE
OnMessage is not triggered in some cases

### ISSUE THREAD

**Issue by TMaddox** [TelegramBots/Telegram.Bot#753]
# I found a bug to report

### Steps to reproduce
Send a msg to the bot in this format: /pwedit 123456 12345
F.e. with /pwedit 000 000 no problem occurs
The name of the command does not matter, numbers do
### Expected  behavior
when I send a Message containing "/pwedit 123456 12345" the onMessage event should be triggered
### Actual behavior
when I send a Message containing "/pwedit 123456 12345" the onMessage event is NOT triggered
### Screenshots
none
### Environment data

*NuGet Package Version:* (e.g. 13.4.0)

*.NET Version:* 4.6.1

*IDE:* VS2017

*App:* Desktop, C# Console Application

**Comment by MihaZupan** [comment]
I receive all messages, no matter the numbers used.
Do you use any additional logic to filter commands from messages that would drop a request of this form?

**Comment by TMaddox** [comment]
This is my start_bot logic:

```
public static void Start_bot()
        {
            Bot = new TelegramBotClient(Token);
            Bot.OnMessage += Bot_OnMessage;
            Bot.OnMessageEdited += Bot_OnMessage;
            Bot.StartReceiving();
        }
```

and this my Eventhandler:

```
private static void Bot_OnMessage(object sender, MessageEventArgs e)
        {
//something
}
```

I have done nothing else to filter anything. I can furthermore confirm via the browser that the msg I sent reached the telegram server.

**Comment by tuscen** [comment]
@TMaddox I also couldn't reproduce your problem.

**Comment by TMaddox** [comment]
Very strange, I will close this Issue and dig a bit deeper into it.
In case I find a solution I will let you know.

**Comment by TMaddox** [comment]
I found the issue.

It is only reproducible in version 13.4.0 and below.

/pwedit 123456 12345 is recognized as "phone number" by telegram which is obviously a new message type and produced an error in old versions of the Telegram.Bot package.

--> The bug does not persist in the newest version, so everything is fine.
