### ISSUE TITLE
How to send Original Photo?

### ISSUE THREAD

**Issue by includein** [TelegramBots/Telegram.Bot#754]
When the bot send photo, not send original photo.
Bot is send to compressed photo

What should I do?

Sorry for my bad english

**Comment by MihaZupan** [comment]
Use SendDocumentAsync instead to avoid compression

**Comment by includein** [comment]
I considered the method.
But I do not know how to set upload filename.

**Comment by MihaZupan** [comment]
```c#
using (FileStream fs = System.IO.File.OpenRead("photo.jpg"))
    await Bot.SendDocumentAsync(message.Chat.Id, new InputOnlineFile(fs, "name.jpg"));
```

**Comment by includein** [comment]
thanks for help 👍

**Comment by MihaZupan** [comment]
If you have any other questions feel free to join the group support chat for this project [on Telegram](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA)
