### ISSUE TITLE
inactive inline button after resetting the app

### ISSUE THREAD

**Issue by roic03** [TelegramBots/Telegram.Bot#755]
Hello!
I have a problem that i didn't figure how to fix. I'm writing a python code who run a telegram bot that handle a menu selection (inline keyboard that take send callback_query and make some function in accordance to the user select).
All this part working fine, until i closing the app (or resting the computer) and re-run the code. When i do so, the inline buttons of the old messages became inactive and press on them make nothing (new messages who sent after the reset work fine until the next code re-run).

Hope that i make my self clear enough, and wondering if there is a solution to solve this issue? I'll be grateful for any help!
Thanks.

**Comment by MihaZupan** [comment]
This is a repository for the C# implementation of the bot API. You will probably have more luck resolving any issues by reaching out to the community of the python library you are using.
With that out of the way, it sounds like your implementation's state does not persist across multiple runs. Consider using a database to store the state that will not change if you restart your bot.

**Comment by roic03** [comment]
Thanks!
I found how to save and load the state of user in the python's repository and it's just working fine right now.
I'm closing the issue.
