### ISSUE TITLE
how to make a telegram bot post wait for answer?

### ISSUE THREAD

**Issue by BLucky-gh** [TelegramBots/Telegram.Bot#756]
I have a bot which has to ask for a title of a post (this is a post-to-channel bot) and store the answer in a variable and then ask for some other information.

here's the code:  https://pastebin.com/ffsecq4y

**Comment by MihaZupan** [comment]
This is a repository for the C# implementation of the bot API. You will probably have more luck resolving any issues by reaching out to the community of the python library you are using.

If you want to delay an action you could look at the sleep command.

**Comment by MihaZupan** [comment]
You'd need to have some kind of state keeping track of what state every chat is in.
