### ISSUE TITLE
How Obtain progress in sendDocument or any file??

### ISSUE THREAD

**Issue by rigorvzla** [TelegramBots/Telegram.Bot#775]
Hello, my question is simple, how can obtain the progress in sendDocumentAsync ? im make a aplication is posible send anything but i cant see, his progress i cant see % in pc, please help me.

Im Sorry for my english,i hope can understandme

**Comment by pouladpld** [comment]
We don't have this functionality right now. I will include more info here after investigation.

**Comment by MihaZupan** [comment]
If you need such functionality right now, you can implement your own `MakeRequestAsync` and use it when sending files

**Comment by rigorvzla** [comment]
MihaZupan you can , make a example in code?

**Comment by MihaZupan** [comment]
There might even be a bit of a simpler version by wrapping the file stream, I'll write and test an example tomorrow.

**Comment by MihaZupan** [comment]
@rigorvzla Something like this might work for you: [custom InputOnlineFile class](https://gist.github.com/MihaZupan/3964479e5a303c699e5c9b510a92da38)

```csharp
using (FileStream fs = File.OpenRead("Book.pdf"))
{
        NotifyingInputOnlineFile onlineFile = new NotifyingInputOnlineFile(fs, fs.Length, "Lovely book.pdf");
        onlineFile.OnProgressUpdated += (s, progress)
            => Console.WriteLine($"Uploaded {progress.Uploaded} out of {progress.TotalSize} bytes. Progress: {progress.ProgressPercentage} %");
        await Bot.SendDocumentAsync(e.Message.Chat, onlineFile);
}
```

**Comment by rigorvzla** [comment]
thanks for the code but i have a problem
in this line have a error and i dont know hoy fix.

`   public NotifyingInputOnlineFile(Stream content, long size)
            : this (content, size, default)
{ }`

my code is in C#

**Comment by MihaZupan** [comment]
Without any other information I'd guess you need to use a higher c# version, to use 'default'. Or to use null instead of default.

Please provide more information than just 'have error'.

**Comment by rigorvzla** [comment]
@MihaZupan this is my problem in the class

![imagen](https://user-images.githubusercontent.com/41328887/43833044-64105980-9ad7-11e8-8369-4ae878a6a0c2.png)

i dont know , why.

**Comment by MihaZupan** [comment]
As I said, default literals were simplified in C# 7.1. You can fix this by replacing `default `with `default(string)` or with `null`.

**Comment by MihaZupan** [comment]
Leaving this issue open for discussion on whether such a class (`NotifyingInputOnlineFile`) should be included in an extension package of sorts.

**Comment by rigorvzla** [comment]
@Banane9  a question, whit this metod, i can obtain the progress in real time, when is uploading? 
I do not currently get the progress in real time as the file goes up

**Comment by poulad** [comment]
It's worth mentioning that [`HttpMessageHandler`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpmessagehandler?view=netstandard-2.0) could be used for this purpose as well.

**Comment by rigorvzla** [comment]
@pouland friend you can writter a example funtional please

**Comment by karb0f0s** [comment]
I suggest to close this discussion. Due to the limits (20-50MB) per file I personally don't think this feature could be useful. Anyway successful upload doesn't mean that user can immediately access or download this file as this process is not controlled on bot side rather then depend on Telegram infrastructure and Telegram Client specifics.

**Comment by karb0f0s** [comment]
Closed due to inactivity.
