### ISSUE TITLE
New Wiki

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#780]
## Wiki topics

- [x] [How to do proxy](https://github.com/TelegramBots/Telegram.Bot/wiki/Working-Behind-a-Proxy)
- [ ] Deployment options
- [ ] How to map from Bot API methods to our interface methods
- [ ] What is diff on our API (e.g. sending files)
- [x] [Login widget](https://github.com/TelegramBots/Telegram.Bot/wiki/Login-Widget)
- [ ] Passport
- [ ] Getting started with callback queries and maintaining chat context

**Comment by pouladpld** [comment]
Docs are now moved to <https://github.com/TelegramBots/book> .
