### ISSUE TITLE
how to use http proxy 

### ISSUE THREAD

**Issue by reza3vi** [TelegramBots/Telegram.Bot#781]
when use http proxy unable to connect. how to use?

**Comment by MihaZupan** [comment]
Take a look at the [wiki article](https://github.com/TelegramBots/Telegram.Bot/wiki/Working-Behind-a-Proxy).
If you have any other questions feel free to join [our group chat](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA).

**Comment by reza3vi** [comment]
I did the same, but it was filtered out of Iran and did not connect

**Comment by MihaZupan** [comment]
Yeah, http proxies will not work in Iran. You can still use a VPN or Tor to connect though. Or consider moving the hosting to the cloud.
