### ISSUE TITLE
Remove unnecessary EventArgs

### ISSUE THREAD

**Issue by MihaZupan** [TelegramBots/Telegram.Bot#782]
Event args for polling events aren't really needed.
If a time comes for a breaking release, essentially all `EventArgs` could be removed, since they only encapsulate a single object each, thus removing some bloat from all event consumer code.

For example:
```csharp
public event EventHandler<MessageEventArgs> OnMessage;
```
could easily be changed to
```csharp
public event EventHandler<Message> OnMessage;
```

**Comment by tuscen** [comment]
We even could make event handler with strongly typed sender param.

**Comment by MihaZupan** [comment]
Closing as not relevant anymore
