### ISSUE TITLE
Не работает бот установленный с NuGet

### ISSUE THREAD

**Issue by Alitrix** [TelegramBots/Telegram.Bot#783]
В место нулей подставлен нормальный ключ.
static async Task<string> TestApiAsync()
        {
            var botClient = new TelegramBotClient("00000000000000000000000000000000");
            var me = await botClient.GetMeAsync();
            return $"Hello! My name is {me.FirstName}";
        }

выдаёт ошибку :
Исключение типа "System.Net.Http.HttpRequestException" возникло в mscorlib.dll, но не было обработано в коде пользователя

Дополнительные сведения: Произошла ошибка при отправке запроса.

**Comment by sh2ezo** [comment]
Возможно, у тебя заблокирован доступ к серверам Телеграма. Учить обходить блокировки не буду. И лучше не задавай на подобных ресурсах вопросы на русском, если проект, которому посвящен репозиторий, не рассчитан, преимущественно, на использование людьми из России, иначе вероятность того, что ты получишь помощь, будет бесконечно близка к нулю.

**Comment by pouladpld** [comment]
Please write it in English so all of us can understand.
If any questions, join our support chat on Telegram: [public group chat](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA)
