### ISSUE TITLE
Editing Bot Messages

### ISSUE THREAD

**Issue by EmanueleS2** [TelegramBots/Telegram.Bot#786]
Hi everybody!
I'm trying to create a bot that answers to users just like @BotFather does.
Can just somebody help me figuring out why i can't just do so by using
`bot.EditTextMessageAsync([ID of the message i'm trying to edit], [new text], replyMarkup: [new InlineKeyboardMarkup]);`

Even though the async task gets completed the message won't just change!

Thank you in advance, and sorry for my possible mistakes in English!

**Comment by EmanueleS2** [comment]
I just performed what i wanted to do by using:
`bot.DeleteMessageAsync()`

**Comment by pouladpld** [comment]
We don't provide general support in gh issues. Join our group for a chat:

https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA
