### ISSUE TITLE
Markdown error

### ISSUE THREAD

**Issue by 4egod** [TelegramBots/Telegram.Bot#787]
Hi. I think I found the bug with markdown formatting.
It's very simple to reproduce it:
```
await BotClient.SendTextMessageAsync(chatId, "**SHOULD BE BOLD**", ParseMode.Markdown);
await BotClient.SendTextMessageAsync(chatId, "*IS BOLD*", ParseMode.Markdown);
```

Correct me if i'm wrong... Thank you!

**Comment by MihaZupan** [comment]
This is actually just Telegram being a special snowflake.
See here https://core.telegram.org/bots/api#markdown-style

**Comment by 4egod** [comment]
Ok. Thanks for a very quickly reply.
