### ISSUE TITLE
Get random username in group

### ISSUE THREAD

**Issue by BearBump** [TelegramBots/Telegram.Bot#789]
How I can get random username in group? I just want to make the random bot

**Comment by MihaZupan** [comment]
You get usernames (for users that have them) whenever you receive a message from them, or when they join the group in the `Message.NewChatMembers` field.
For random, take a look at the [Random](https://docs.microsoft.com/en-us/dotnet/api/system.random?view=netframework-4.7.2#examples) class.

Consider joining our [public group chat](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA) for questions like this, GitHub issues are not the place.
