### ISSUE TITLE
Async void method in library

### ISSUE THREAD

**Issue by Leonqn** [TelegramBots/Telegram.Bot#790]
Hello.
Method [ReceiveAsync](https://github.com/TelegramBots/Telegram.Bot/blob/master/src/Telegram.Bot/TelegramBotClient.cs#L294) is ``async void``, which means that if any exception occurred in [OnUpdateReceived](https://github.com/TelegramBots/Telegram.Bot/blob/master/src/Telegram.Bot/TelegramBotClient.cs#L329), program will exit, is this by design or not?
Making this method ``async Task`` will fix this problem.

**Comment by pouladpld** [comment]
Hi @Leonqn 
You are right.
We are keeping it that way for a while until we have the new updating handling pipeline ready.
