### ISSUE TITLE
mtproto proxy

### ISSUE THREAD

**Issue by MherX** [TelegramBots/Telegram.Bot#794]
Hi! 
Can you help? In the current version of the SDK can be used mtproto proxy or not? and if not please tell me if the plans to add such functionality and when it will be available.
Thanks!

**Comment by poulad** [comment]
Telegram bot API is HTTP-based and not on MTProto.

**Comment by poulad** [comment]
Join our support chat for further questions (see repo's readme).

Proxy docs:
https://telegrambots.github.io/book/4/proxy.html
