### ISSUE TITLE
An asynchronous module or handler completed while an asynchronous operation was still pending

### ISSUE THREAD

**Issue by JTrotta** [TelegramBots/Telegram.Bot#797]
# I found a bug to report

Please use the following template to ensure maintainers can reproduce the bug and solve it quickly.

> Bug reports that do not follow this template will be kept closed because [_not-reproducible_](https://github.com/TelegramBots/telegram.bot/labels/not-reproducible) until the creator edits the post properly.

### Steps to reproduce
Create a bot client (_botClient) inside a WEB Api project. Initialize it, and call `StartReceiving()`
Call `_botClient.SendTextMessageAsync(_chatId, message)` inside a web ApiController method (i.e. `public HttpResponseMessage Apimethod(ARequest request))` 

### Expected  behavior
Normal working

### Actual behavior
The Api controller, after return response, throw an exception:
`An asynchronous module or handler completed while an asynchronous operation was still pending`

I suspect the problem is caused by this method:
` private async void ReceiveAsync(
            UpdateType[] allowedUpdates,
            CancellationToken cancellationToken = default)`

If I do not call the method `StartReceiving()` (that calls ReceiveAsync) everything works fine, but I cannot receive anything anymore. I think the `ReceiveAsync` method should return a Task, while now return void and you add `#pragma warning disable AsyncFixer03` to avoid AsyncFixer warning.

### Environment data

*NuGet Package Version:* 14.10.0.0

*.NET Version:* 4.6.2

*IDE:* VS2017

*App:* AspNet.WebApi

**Comment by karb0f0s** [comment]
StartReceiving is only supposed to be used in console or standalone applications. In ASP NET MVC you have to use another solution to keep track of incoming updates: use controller to handle webhook, or manually check updates with 'HostingEnvironment' or 'BackgroundTaskManager'. Overwise you break AspNet mechanisms.

**Comment by karb0f0s** [comment]
StartReceiving is only supposed to be used in console or standalone applications. In ASP NET MVC you have to use another solution to keep track of incoming updates: use controller to handle webhook, or manually check updates with 'HostingEnvironment' or 'BackgroundTaskManager'. Overwise you break AspNet mechanisms.

**Comment by JTrotta** [comment]
Thank you.
But what you mean for **check updates with 'HostingEnvironment'** ?
