### ISSUE TITLE
SendTextMessageAsync: An error occurred while sending the request 

### ISSUE THREAD

**Issue by mooningnow** [TelegramBots/Telegram.Bot#798]
# While sending text messages using "SendTextMessageAsync" method, I get the following error very often like 1 in 10 messages I send.

### Steps to reproduce
Used the below code to reproduce the issue in debug mode with valid value for all the arguments:
            for(int i = 0; i<10; i++)
            {
                var sentMessage = await telegramBotClient.SendTextMessageAsync(channelName, "Text", parseMode, disableWebPagePreview,
                    disableNotifications, replyToMessageID, inlineKeyboardMarkup);
                Thread.Sleep(1000);
            }

### Expected  behavior
Expected all the messages to be sent without any error.

### Actual behavior
A few of the messages were not send and gets the below error.
{"Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}

### Screenshots
![image](https://user-images.githubusercontent.com/38512190/47357088-d5c82380-d693-11e8-9e87-8511a0615efa.png)

### Environment data

*NuGet Package Version:* (e.g. 13.0.1)

*.NET Version:* (e.g. 4.7, Core 1.1, Mono, etc.)

*IDE:* (e.g. VS2017, VS Code, etc.)

*App:* (e.g. Desktop, iOS, Android, etc.)

**Comment by poulad** [comment]
It's a networking issue between bot's device and tg servers. That's not really related to this project.

Feel free to ask others about their experiences in dealing with such issues in our support chat.
[![telegram chat](https://img.shields.io/badge/Support_Chat-Telegram-blue.svg?style=flat-square)](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA)
