### ISSUE TITLE
Integrate NLU provider

### ISSUE THREAD

**Issue by Oceania2018** [TelegramBots/Telegram.Bot#799]
## I would like to request/propose a feature

I'd like to know if it's possible to integrate an open source NLU provider SDK to Telegram.Bot. Then user will play around conversational UI locally and get more DIY interesting things.

**Comment by MihaZupan** [comment]
It's possible. Telegram.Bot simply wraps the rest API, so you get 'raw' access to messages; you can process them however you like.

**Comment by Oceania2018** [comment]
I mean something like NLU SDK, not exteranl NLU rest API.

**Comment by MihaZupan** [comment]
Ofc. When you receive a text message from the Telegram API, you are left with a string that you can process locally to your heart's desire.

For discussions, you may want to join our public group chat https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA

**Comment by poulad** [comment]
@Oceania2018 That's not a feature for the core package but we can have extension package and utilities to offer such a feature.
We would be glad to hear your input on it in the group chat.

**Comment by Oceania2018** [comment]
@poulad I'm coding a [telegram adapter ](https://github.com/Oceania2018/botsharp-channel-telegram) to intergate local NLU provider to TelegramBots. So developers could train and predict intent locally.
