### ISSUE TITLE
Incorrect type of field

### ISSUE THREAD

**Issue by otetsdiodor** [TelegramBots/Telegram.Bot#800]
Is any reason to make Id long type. Because in Telegram bot api type of Id is integer.
Chat.cs -> Id field

It is inconvenient to use long if in other methods accepting chatid
int is used :(
![image](https://user-images.githubusercontent.com/26055393/47517807-01186180-d892-11e8-9346-5c2a644d9cf8.png)

**Comment by MihaZupan** [comment]
You should read https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/integral-types-table

int is a 32bit integer while long is 64bit in c#.
In this case the possible range of values exceeds those of an int, so long is used.
Make sure you don't cast this back to int anywhere as it could overflow!
