### ISSUE TITLE
Property "update.callback_query.message.date" might not exist 

### ISSUE THREAD

**Issue by poulad** [TelegramBots/Telegram.Bot#801]
## Bug Report

Property `Message.Date` might not exist for the old callback query updates. [See the `update.callback_query.message` descriptions](
https://core.telegram.org/bots/api#callbackquery).

https://github.com/TelegramBots/Telegram.Bot/blob/85134a4b5f09de4bef4306aa44d708c202b31f31/src/Telegram.Bot/Types/Message.cs#L34-L36

> Note that I don't have a real old callback query update from Telegram to test this.

### Steps to reproduce

Try to deserialize this update.

```c#
string update = @"{
    update_id: 1,
    callback_query: {
        id: ""5399"",
        data: ""foo/bar"",
        from: {
            id: 1234,
            first_name: ""Poulad"",
            is_bot: false
        },
        message: {
            message_id: 2744,
            from: {
                id: 1234,
                first_name: ""Poulad"",
                is_bot: false
            },
            chat: {
                id: 1234,
                type: ""private""
            }
        },
        chat_instance: ""-9999"",
        date: 1100
    }
}";
Update u = JsonConvert.DeserializeObject<Update>(update);
```

### Expected  behavior

JSON is deserialized into `u` object.

### Actual behavior

Throws serialization exception:

```text
Unable to deserialize update payload. Required property 'date' not found in JSON. Path 'callback_query.message', line 22, position 2
```

### Environment data

*NuGet Package Version*: 14.10.0

**Comment by karb0f0s** [comment]
Is this still an issue? There is no signs of reproducing this behaviour for more than a year.

**Comment by tuscen** [comment]
I'd leave it open because there's still a probability of facing it.

**Comment by karb0f0s** [comment]
As of today [CallbackQuery](https://core.telegram.org/bots/api#callbackquery) has a really vague description of this behaviour:

Field | Type | Description
-- | -- | --
message | [Message](https://core.telegram.org/bots/api#message) | _Optional_. Message with the callback button that originated the query. Note that **message content** and **message date** will not be available if the message **is too old**

How old is _"too old"_? Which properties fit _"message content"_ description? To fix this we could either introduce `MessageInQuestion` class (where all properties are optional), or make all properties of `Message` class optional (and it won't look good).

**Comment by wiz0u** [comment]
Solved with v21.*
Undefined date will have `default` value as we are no longer enforcing JsonRequired fields.
