### ISSUE TITLE
Can't compile your code

### ISSUE THREAD

**Issue by aliDel** [TelegramBots/Telegram.Bot#804]
I want to see this project codes, and change some methods for use of myself
I've downloaded your project and imported it to visual studio, but i can't compile it, it has some errors!
is it possible to see your codes and make some changes on it?if yes, how can i do that?

**Comment by MihaZupan** [comment]
We can't help you if you don't tell us what errors you actually see. The code compiles fine, (maybe you have an outdated VS)?
You can download, modify, compile and use the source code.
