### ISSUE TITLE
mtproto proxy for bot api

### ISSUE THREAD

**Issue by ddadkhah** [TelegramBots/Telegram.Bot#805]
Hello.
Please add a feature that we can use mtproto proxy for telegram bots. For example convert http requests to mtproto protocol, send it to proxy server and then convert it to http request for sending to telegram servers.

**Comment by MihaZupan** [comment]
You misunderstand how MTProto works, you can read about it on Telegram's website. If you want to use the bot api over MTProto, you'll have to convince client api libraries to add this functionality, but I doubt they will.
You could always host the bot in the cloud if you can't do it from your local machine, or you could use a vpn/tor from your machine.
