### ISSUE TITLE
can't save downloaded photo 

### ISSUE THREAD

**Issue by aliDel** [TelegramBots/Telegram.Bot#806]
I am using the telegram bot API, and i want to download a photo that was sent to my bot, and save it to my disk.
ive used **GetInfoAndDownloadFileAsync** method for downloading file, and then i tried to save the downloaded photo, but after saving, i can not open the saved file
here is my code:

```
private static async Task<byte[]> downloadFileAsync(string fileId)
        {
            Stream fileDestination = new MemoryStream();
            await botClient.GetInfoAndDownloadFileAsync(fileId, fileDestination);
            fileDestination.Position = 0;
            saveToDisk(fileDestination);
            byte[] bytes = new byte[fileDestination.Length];
            fileDestination.Read(bytes, 0, bytes.Length);
            return bytes;
        }

private static void saveToDisk(Stream fileDestination)
        {
            string fileFullPath = "F:\\My Files\\Picture\\pic.jpg";
            FileStream fileStream = System.IO.File.Create(fileFullPath, (int)fileDestination.Length);
            byte[] bytesInStream = new byte[fileDestination.Length];
            fileDestination.Read(bytesInStream, 0, bytesInStream.Length);
            fileStream.Write(bytesInStream, 0, bytesInStream.Length);
            fileStream.Close();
        }
```
and saved photo is attached
![pic](https://user-images.githubusercontent.com/13185138/49063034-47fbcd00-f22b-11e8-84a4-4245347364ce.jpg)

**Comment by nimbusparis** [comment]
Hello, I think your problem is a `Seek` missing just after reading bytes from TG since the stream position is at the end:
```
using (var stream = new MemoryStream())
                                    {
                                        var fileInfo =
                                            await _telegramBotClient.GetInfoAndDownloadFileAsync(attachment.ContentUrl,
                                                stream);
                                        stream.Seek(0, SeekOrigin.Begin);
/// Other code
                                    }
```

**Comment by MihaZupan** [comment]
`stream.Seek(0, SeekOrigin.Begin);` has the same effect as `stream.Position = 0;`

**Comment by nimbusparis** [comment]
Yes, but after the call to `saveToDisk` the stream position is again at the end...
I don't know what this piece of code do, but GetInfoAndDownloadFileAsync worked perfectly well for me.

**Comment by karb0f0s** [comment]
If you found a bug in our library please follow [bug report](https://github.com/TelegramBots/Telegram.Bot/blob/master/.github/ISSUE_TEMPLATE/But_report.md) template and provide minimum reproducible example we can work on. If you have any other issues feel free to ask others about their experiences in dealing with such issues in our support chat.
[![telegram chat](https://img.shields.io/badge/Support_Chat-Telegram-blue.svg?style=flat-square)](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA)
