### ISSUE TITLE
Delete all messages from the bot and kick the bot

### ISSUE THREAD

**Issue by pourmand1376** [TelegramBots/Telegram.Bot#808]
# Delete All messages from the bot newly added to group and kick it

Hi, I've written a group moderator bot which restricts users from sending spam messages.
The problem I have encountered with, is that some malicious users add bots to the group and those bots send spam messages. I want to delete this messages.
My solution was "to kick bots out of the group immediately after being added" but that is not working sometimes.  (because It's kicked very soon It can't send spam messages but sometimes It can).
Thank you for answers.

**Comment by karb0f0s** [comment]
If you found a bug in our library please follow [bug report](https://github.com/TelegramBots/Telegram.Bot/blob/master/.github/ISSUE_TEMPLATE/But_report.md) template and provide minimum reproducible example we can work on. If you have any other issues feel free to ask others about their experiences in dealing with such issues in our support chat.
[![telegram chat](https://img.shields.io/badge/Support_Chat-Telegram-blue.svg?style=flat-square)](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA)

**Comment by igorbelikov** [comment]
@pourmand1376 Hi, do you find solution for this problem?

**Comment by Fedorus** [comment]
> @pourmand1376 Hi, do you find solution for this problem?

just save everything that comes to chat and then delete for deleted user...

**Comment by igorbelikov** [comment]
@pourmand1376 but messages from bots are not saving in webhook :-( or not?

**Comment by Fedorus** [comment]
> @pourmand1376 but messages from bots are not saving in webhook :-( or not?

no messages are saving by default.
You need to write some code and use DB/cache )

**Comment by igorbelikov** [comment]
I use https://github.com/php-telegram-bot/core and I configured, that all messages was saving in db, but messages from bots is not avaiable for check :-(

**Comment by Fedorus** [comment]
> @Fedorus I use https://github.com/php-telegram-bot/core and I configured, that all messages was saving in db, but messages from bots is not avaiable for check :-(

usually spam is not from bots )

**Comment by igorbelikov** [comment]
@Fedorus sure, but in my case I have problem with bots :-)
