### ISSUE TITLE
After  sometimes bot does not work via webhook

### ISSUE THREAD

**Issue by dreamevilgf** [TelegramBots/Telegram.Bot#811]
# Strange behavior after deploy on server 

Hi! 
I faced with issue when deploy my asp core mvc application on server. I use webhook approach

        public void ConfigureServices(IServiceCollection services)

        {

            services.AddMvc();

            var telegramToken = _configuration.GetSection("appSettings")
                .GetSection("TelegramBotToken")?.Value;

            TelegramBotClient telegramClient = new TelegramBotClient(telegramToken);

            var appUrls = _configuration.GetSection("appSettings").GetSection("AppUrl")?.Value;

            telegramClient.SetWebhookAsync(appUrls + "/WebHook").Wait();

            services.AddScoped<ITelegramBotClient>(client => telegramClient);
        }

### Steps to reproduce
1. Deploy to server
2. Chat with bot  (bot works), I see in IIS log requests from telegram
3. Wait some time, (20 min - 60 min may be more I don't know what it depends on) don't work with bot all this time, 
4 Chat again 
5 Bot does not work

I checked IIS log telegram does not send to my server any requests to WebHook controllers. 

### Expected  behavior
Bot has to work 24/7

### Actual behavior
After sometimes bot is not respoding and telegram does not send request to my application.
I have to redeploy application.

### Environment data
Windows Server 2016, IIS 10, Plesk Control Panel

Settings of application pool 
> **The maximum number of worker processes** 
> 1 Maximum number of worker processes permitted to service requests for IIS application pool. 
> **Idle timeout (minutes)** 
> 20 Amount of time a worker process will remain idle before it shuts down.
> Idle timeout action 
> Terminate What action to perform when the idle timeout duration has been reached.
> **Maximum CPU usage (%)** 
> 45
> **Limit action** 
> Shut Down The action that IIS performs when a worker process exceeds the configured maximum CPU usage.
> **Limit interval (minutes)** 
> 3 The reset period for monitoring of CPU usage on an application pool. When the specified number of minutes passes since the last reset, IIS resets CPU timers for the logging and for limit intervals.
> **Recycling at regular time intervals (minutes)** 
> 360 Period of time after which IIS application pool will recycle.
> **Recycling when the maximum number of requests is reached** 
> Unlimited Maximum number of requests IIS application pool can process before it is recycled.
> **Recycling when the maximum amount of virtual memory is used** 
> 2097152 KB Maximum amount of virtual memory a worker process can consume before causing IIS application pool to recycle.
> **Recycling when the maximum amount of private memory is used** 
> 1048576 KB Maximum amount of private memory a worker process can consume before causing IIS application pool to recycle.
> 

*NuGet Package Version:* (e.g. 14.10)

*.NET Version:* ( Core 2.1)

*IDE:* (e.g. VS2017)

*App:* (Asp Core MVC )

**Comment by MihaZupan** [comment]
I'd start by going to https://api.telegram.org/bot<token>/getWebhookInfo to see if any info is available on why telegram stops sending updates.

**Comment by dreamevilgf** [comment]
Thank you! 
I get additional information 
```
ok | true
-- | --
result |  
url | "someUrlHere"
has_custom_certificate | false
pending_update_count | 5
last_error_date | 1551097850
last_error_message | "Wrong response from the webhook: 402 Payment Required"
max_connections | 40

```
May be I don't know something, but about which payment this message?

**Comment by MihaZupan** [comment]
It means your server responded with a 402.
It must always respond with a 200 OK to webhook requests

**Comment by poulad** [comment]
@dreamevilgf
This behavior seems to be caused by your hosting service. I'm closing the issue due to inactivity.
