### ISSUE TITLE
Telegram.Bot.Types.Message.Date change to timestamp

### ISSUE THREAD

**Issue by wuball** [TelegramBots/Telegram.Bot#816]
https://core.telegram.org/bots/api#message

https://github.com/TelegramBots/Telegram.Bot/blob/master/src/Telegram.Bot/Types/Message.cs

`Telegram.Bot.Types.Message.Date` must change to int.

**Comment by MihaZupan** [comment]
The value is read as an integer and converted into DateTime with the UnixDateTimeConverter, as DateTime is what can easily be used in c#.
