### ISSUE TITLE
A couple Travis CI changes

### ISSUE THREAD

**Issue by poulad** [TelegramBots/Telegram.Bot#818]
I'm exploring a few different configurations on the [`travis-ci` branch].

It uses .NET Core 2.2 instead of 2.0 and `dotnet test` instead of `dotnet xunit`. In addition, test execution results are written to a `.trx` file. See [build #334].

There ~are 2~ is only 1 main issue with that:

- ~Test collection orders are not respected~
- Doesn't fail fast (no `-stoponfail`)

[`travis-ci` branch]: https://github.com/TelegramBots/Telegram.Bot/blob/travis-ci/.travis.yml
[build #334]: https://travis-ci.org/TelegramBots/Telegram.Bot/builds/522610681

**Comment by poulad** [comment]
might be useful:

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore21

https://github.com/Microsoft/vstest-docs/blob/master/docs/RunSettingsArguments.md

https://github.com/Microsoft/vstest-docs/blob/master/docs/report.md#2-trx-logger

**Comment by poulad** [comment]
Updated. test collection order is in effect and there was an unrelated issue that made me think otherwise.

**Comment by tuscen** [comment]
Superseded by #858.
