### ISSUE TITLE
 MissingMethodException when calling "await bot.SendTextMessageAsyn"

### ISSUE THREAD

**Issue by riccardiclaudio** [TelegramBots/Telegram.Bot#820]
# I found a bug to report

Please use the following template to ensure maintainers can reproduce the bug and solve it quickly.

> Bug reports that do not follow this template will be kept closed because [_not-reproducible_](https://github.com/TelegramBots/telegram.bot/labels/not-reproducible) until the creator edits the post properly.

### Steps to reproduce
When user creates a new ticket from a web application form, a notification is sent to Telegram using this method:

        public async Task SendTelegramNotification(List<string> idList, string notificationMsg)
        {
            var TELEGRAM_BOT_CLIENT_KEY = db.Settings.FirstOrDefault(c => c.SettingCode.Equals("TELEGRAM_BOT_CLIENT_KEY")).SettingVal;

            try
            {
                var bot = new Telegram.Bot.TelegramBotClient(TELEGRAM_BOT_CLIENT_KEY);
                foreach (var item in idList)
                {
                    await bot.SendTextMessageAsync(item, notificationMsg, parseMode: ParseMode.Markdown);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
        }

### Expected  behavior
The notification was correctly sent until last week.

### Actual behavior
The notification is correctly sent when I debug the web application on my local machine (Windows 10). When I deploy the web application dll on the server (Windows Server 2012 R2), the application shows the attached error page.

### Screenshots
![telegram-bot-error](https://user-images.githubusercontent.com/32217857/57507820-25083580-7300-11e9-8a41-98cea5b09379.jpg)

### Environment data
Windows Server 2012 R2

*NuGet Package Version:* (e.g. 13.0.1)
14.10.0

*.NET Version:* (e.g. 4.7, Core 1.1, Mono, etc.)
4.6

*IDE:* (e.g. VS2017, VS Code, etc.)
VS2019

*App:* (e.g. Desktop, iOS, Android, etc.)
Web Application ASP.NET

**Comment by MihaZupan** [comment]
This is not an issue with the library but with your deployment. Make sure you're deploying the correct versions, see https://stackoverflow.com/questions/8058832/system-missingmethodexception-method-not-found.

**Comment by manishbsg** [comment]
I
