### ISSUE TITLE
Expose BaseUrl and BaseFileUrl settings

### ISSUE THREAD

**Issue by MihaZupan** [TelegramBots/Telegram.Bot#829]
Did we reach a conclusion as to whether to implement this by just making the properties public, or by adding ctor parameters?

**Comment by tuscen** [comment]
I'm fine with making them instance properties with public setters.

**Comment by MihaZupan** [comment]
I've changed my mind - we shouldn't expose this as an API.

For anyone requiring such functionality, there is a workaround, see https://github.com/TelegramBots/Telegram.Bot/pull/857#issuecomment-657108726
