### ISSUE TITLE
An issue with InlineKeyboardMarkup

### ISSUE THREAD

**Issue by NickolayKabash** [TelegramBots/Telegram.Bot#832]
I have used the following code and nothing happened. A few days before that All was fine...

**Steps to reproduce**

        client = new TelegramBotClient(<token>);
        client.OnUpdate += Client_OnUpdate;
        client.OnCallbackQuery += Client_OnCallbackQuery;
        client.StartReceiving();

        private static async void Client_OnCallbackQuery(object sender, Telegram.Bot.Args.CallbackQueryEventArgs e)
        {
           // NEVER FIRES
        }

        private static async void Client_OnUpdate(object sender, Telegram.Bot.Args.UpdateEventArgs e)
        {
            var update = e.Update;

            if (update == null || update.Message == null)
            {
                return;
            }
            long chatId = update.Message.Chat.Id;
            string text = update.Message.Text;
            if (text.ToLowerInvariant().Contains("start"))
            {
                InlineKeyboardMarkup inline = new InlineKeyboardMarkup(new InlineKeyboardButton[] { new InlineKeyboardButton() { Text = "Click me", CallbackData = "CallbackData" } });
                await client.SendTextMessageAsync(new ChatId(chatId), "response:", replyMarkup: inline);
            }
        }

**Expected  behavior**

Should fire an event "OnCallbackQuery" after a click on a button

**Actual behavior**

![image](https://user-images.githubusercontent.com/14564729/63337461-ae8cc200-c349-11e9-981f-f97faa14077b.png)

**NuGet Package Version: 15.0.0**

**.NET Version: 4.7**

**IDE: VS2019**

**App: Desktop**

**Comment by tuscen** [comment]
The code you provided can't work at all in your scenario. It will always fail with `NullReferenceException` on any non-message update since OnUpdate event handler is always invoked if it is set.

**Comment by NickolayKabash** [comment]
@tuscen , I have simplified code and I don't think that this is matters now. What version of the library have you used?

**Comment by tuscen** [comment]
I used v15.

**Comment by NickolayKabash** [comment]
@tuscen , I don't know what to do now. As for settings, I have "Inline mode" disabled for my bot. After I click on the button the Telegram says: "Loading..." and that's all.

**Comment by tuscen** [comment]
Is the callback query update there if you try to go to `https://api.telegram.org/bot<token>/getUpdates`?

**Comment by NickolayKabash** [comment]
Got this:

{"ok":true,"result":[]}

**Comment by tuscen** [comment]
I mean after you press the button on inline keyeboard.

**Comment by NickolayKabash** [comment]
I clock on the button and then get this response:

{"ok":true,"result":[]}

**Comment by tuscen** [comment]
That's why calback query event handler isn't invoked: there is no callback query update. Maybe you have some connectivity problems with telegram servers on your client or from your current network.

**Comment by MihaZupan** [comment]
I think that the problem is `Client_OnUpdate` will always throw since you're assuming every update is a message (IT IS NOT).
If that method throws, `Client_OnCallbackQuery` will not be called.

Fix your `Client_OnUpdate`

**Comment by NickolayKabash** [comment]
@MihaZupan , I have this block of code:

    if (update == null || update.Message == null)
    {
        return;
    }

And OnUpdate won't fire on button click even if OnCallbackQuery is subscribed

**Comment by NickolayKabash** [comment]
Here is a test project that I've used:

https://github.com/NickolayKabash/ConsoleApp1/

I can create a video of that process if needed...
I've been using telegram bot for more than a year and everything was OK! That issue just blocked my dev process and I'm stucked

**Comment by NickolayKabash** [comment]
> That's why calback query event handler isn't invoked: there is no callback query update. Maybe you have some connectivity problems with telegram servers on your client or from your current network.

I have tried to host app with Azure and click on the button on my mobile phone, same issue

**Comment by MihaZupan** [comment]
@NickolayKabash Just fyi, in OnUpdate, the Update itself will never be null. But a Message doesn't have to be a text message (it could be an image for example), so your bot is still throwing uncought exceptions for all non-text messages. Add exception handling to your code

**Comment by Torvin** [comment]
I had exactly the same issue. Just deleting the bot and re-creating it helped. There's definitely something wrong with Telegram servers.
