### ISSUE TITLE
Google Links not working when sent by Telegram

### ISSUE THREAD

**Issue by Ephaltes** [TelegramBots/Telegram.Bot#833]
# I found a bug to report

Hello 

My problem is when I sent a google maps link through telegram I cant open the link in google Maps, but when i send the exact same link through whatsapp or email it is working.

### Steps to reproduce

I used this link, sent it through my bot and then clicked on it google maps error says that this link is not supported 

[Link](https://www.google.com/maps/dir/Ottakringer%20Stra%C3%9Fe,%20Vienna,%20Austria/Herbeckstra%C3%9Fe%2038,%20Vienna,%20Austria/D%C3%B6blinger%20Hauptstra%C3%9Fe,%20Vienna,%20Austria/FH%20Technikum%20Wien,%20H%C3%B6chst%C3%A4dtplatz,%20Vienna,%20Austria/Donauzentrum,%20Wagramer%20Stra%C3%9Fe,%20Vienna,%20Austria/Lobau,%20Vienna,%20Austria/Aspern,%20Vienna,%20Austria/Flughafen%20Wien%20(VIE),%20Wien-Flughafen,%20Schwechat,%20Austria/Erdberg,%20Vienna,%20Austria/Yip%20Hint%20Import-Export%20GmbH,%20Favoritenstra%C3%9Fe,%20Vienna,%20Austria
)

but when I press on the link in telegram and choose "copy link" and paste it in whatsapp or send it to me via mail and open it, then google maps is opening the map normal

I also checked the link both from whatsapp/email with the one from telegram ( "copy link address" )
and it is the exact same link not a single char is different

### Expected  behavior

open google maps map with route

### Actual behavior

Error : link not supported

### Environment data

Iphone 6

On the Desktop App it is working normal

**Comment by matteocontrini** [comment]
How is this related to this library?

**Comment by Ephaltes** [comment]
ah sorry my bad, thought that would be from telegram itself

**Comment by MihaZupan** [comment]
As this is working on the desktop, it's an issue with the mobile app. You should reach out to their support team and report the bug.

**Comment by Ephaltes** [comment]
> As this is working on the desktop, it's an issue with the mobile app. You should reach out to their support team and report the bug.

Ok Thanks, I contacted : https://github.com/TelegramMessenger/Telegram-iOS/
