### ISSUE TITLE
Support System.Text.Json (as well as Newtonsoft.Json)

### ISSUE THREAD

**Issue by poulad** [TelegramBots/Telegram.Bot#839]
We can use new and high performance JSON serialization `System.Text.Json` package. Faster serialization/deserialization of request and response data structures is the main reason for this suggestion.

There are a few things to consider:

`System.Text.Json` requires .NET Standard 2.0 and that's .NET 4.6.1+.

Snake case naming policy support won't come until .NET 5 (see dotnet/corefx#41354). Alternatives are using camel cased naming policy by default, e.g. for `username`, and overriding specific fields, e.g. for `first_name`, with the `[JsonPropertyName("first_name")]`.

Custom type converters such as for `DateTime` to Unix epoch time need to be implemented. This is very similar to the current implementation for `Newtonsoft.Json`.

##### References

[The future of JSON in .NET Core 3.0](https://github.com/dotnet/announcements/issues/90)

**Comment by poulad** [comment]
### Ignoring Default Values

As @tuscen pointed out on #838, default value of the value types should be ignored during serialization but it's not supported at the moment. Default `null` value of the reference types can be ignored using the `IgnoreNullValues` in serialization options.

```csharp
class Foo
{
    [JsonPropertyName("field_bar")]
    public bool FieldBar { get; set; }
    
    [JsonPropertyName("field_baz")]
    public string FieldBaz { get; set; }
}
```

```csharp
[Fact]
public void Test()
{
    var opts = new JsonSerializerOptions { IgnoreNullValues = true };
    string json = JsonSerializer.Serialize(new Foo(), opts);
    // JSON is {"field_bar":false}

    // assertion fails
    Assert.Equal("{}", json);
}
```

see more at dotnet/corefx#40922

**Comment by poulad** [comment]
@tuscen :

> ...webhook users will need to set custom JsonSerializerOptions specifically for Bot API, because these options are global for the entire middleware pipeline in ASP.NET Core. If I'd want to host telegram webhook in the same process as my web app options needed for the library might not be compatible with the app. With the current setup we don't even need custom serializer options.

https://github.com/TelegramBots/Telegram.Bot/pull/838#discussion_r332608326

**Comment by dumkin** [comment]
> ### Ignoring Default Values
> As @tuscen pointed out on #838, default value of the value types should be ignored during serialization but it's not supported at the moment. Default `null` value of the reference types can be ignored using the `IgnoreNullValues` in serialization options.
> 
> ```cs
> class Foo
> {
>     [JsonPropertyName("field_bar")]
>     public bool FieldBar { get; set; }
>     
>     [JsonPropertyName("field_baz")]
>     public string FieldBaz { get; set; }
> }
> ```
> 
> ```cs
> [Fact]
> public void Test()
> {
>     var opts = new JsonSerializerOptions { IgnoreNullValues = true };
>     string json = JsonSerializer.Serialize(new Foo(), opts);
>     // JSON is {"field_bar":false}
> 
>     // assertion fails
>     Assert.Equal("{}", json);
> }
> ```
> 
> see more at dotnet/corefx#40922

dotnet 5&6 can do that now
![image](https://user-images.githubusercontent.com/31487230/140509543-bba040f8-da38-4b1c-9881-3316cf2c655e.png)

**Comment by tuscen** [comment]
@dumkin unfortunately this is not a solution because if someone would use the library with a webhook they could need different json options compared to what we need. And as far as I know json options are global in ASP.NET Core.

**Comment by dumkin** [comment]
I don't really understand at all why it is necessary to create a controller with an action with parameters. Why not just ask to add an additional route. And get everything you need from the body. And here it doesn't matter. use system.text.json or newtonsoft.json. it will not affect other libraries and user code

example for webhook
![image](https://user-images.githubusercontent.com/31487230/140561167-3fefc72a-c345-4382-b3da-597517573636.png)

**Comment by dumkin** [comment]
It's just that now, in essence, the situation is the same. Only the other way around. now it is required
```
services.AddControllers()
                    .AddNewtonsoftJson();
```

Which forces us to use NewtonsoftJson exactly as globally

**Comment by tuscen** [comment]
You have a point 🤔 We'll think about it.

**Comment by sixpeteunder** [comment]
This is something I would very much like in this library. Is there anything I can help with that would get this done quicker?

**Comment by tuscen** [comment]
@sixpeteunder Unfortunately , there's not much you can do. We rely heavily on:
- completely attribute-based configuration (no custom `JsonSerializerSettings`), but that feature we might be ok with dropping
- opt-in property strategy, it's safer because probability of accidental adding of the json attribute on a property is lower than ensuring that all ignored properties are annotated with `[JsonIgnore]`
- built-in snake case property conversion
- Required properties validation during (de-)serialisation

All these features are still missing even in .NET 6.

**Comment by klinki** [comment]
This would be really great to have, it is a blocker for AOT.

**Comment by Fedorus** [comment]
> This would be really great to have, it is a blocker for AOT.

Well, usage in Unity or front end blazor is strongly not recommended, so its not big of a deal )

**Comment by klinki** [comment]
True, but AOT is not just about raw performance but also about memory footprint. Especially trimming is really great to reduce memory footprint. I'm experimenting with TelegramBot client used for forex trading running on very low spec VPS provided by my forex broker. It has just 1GB RAM available and it has to run MT4 platform + my telegram bot. Currently it works, but sometimes I'm getting near the memory limit.

**Comment by luizfbicalho** [comment]
Whats the status on this? looks like there is a lot of problems to migrate

**Comment by tuscen** [comment]
@luizfbicalho All the changes are in the branch [tuscen/stj-2](https://github.com/TelegramBots/Telegram.Bot/tree/tuscen/stj-2) and I'd say it's 80-90% ready. I just don't have enough free time to squash all the bugs and finish it. I want to release Bot API 7.0 and 7.1 updates first and then release STJ support.

The thing is that it ended up quite non-trivial in a lot of places and it probably won't be backwards compatible so it'll be release as a new major version. The current plan is to completely remove Newtonsoft from `net7.0` and newer targets and use built-in STJ from the runtime. All the targets below `net7.0` will stay on Newtonsoft because earlier versions of STJ don't have some features that we use from Newtonsoft.

**Comment by luizfbicalho** [comment]
I have the same issues with my projects, thanks for the answer and I'll see it if I can help in any way

**Comment by tuscen** [comment]
Also the first release with STJ will not be AOT compatible. I want to make implement it in a separate release, because otherwise it will take too much time.

**Comment by tuscen** [comment]
@luizfbicalho you can run unit tests from that branch and see which ones are failing. We also will need to add a few more hundreds of serialization tests :)

**Comment by wiz0u** [comment]
switch to STJ has been done.

issue #1322 will track AOT compatibility

**Comment by kacperpikacz** [comment]
If you don't want to use Newtonsoft in your project.

```
Builder.Services.AddControllers(options => { options.ModelBinderProviders.Insert(0, new TelegramBotUpdateTypeBinderProvider());});
```

`TelegramBinder.cs`
```
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.ModelBinding.Binders;
using Telegram.Bot.Types;

public class TelegramBotUpdateTypeBinderProvider : IModelBinderProvider
{
    public IModelBinder? GetBinder(ModelBinderProviderContext context) =>
        context.Metadata.ModelType == typeof(Update) 
            ? new BinderTypeModelBinder(typeof(TelegramBotUpdateTypeBinder)) 
            : null;
}

public class TelegramBotUpdateTypeBinder : IModelBinder
{
    public async Task BindModelAsync(ModelBindingContext bindingContext)
    {
        if (bindingContext == null) throw new ArgumentNullException(nameof(bindingContext));
        var request = bindingContext.HttpContext.Request;

        if (!request.Body.CanSeek)
        {
            var memoryStream = new MemoryStream();
            await request.Body.CopyToAsync(memoryStream);
            memoryStream.Position = 0;
            request.Body = memoryStream;
        }

        request.Body.Position = 0;

        using var reader = new StreamReader(request.Body);
        var json = await reader.ReadToEndAsync();

        using var jsonDoc = JsonDocument.Parse(json);
        var updatedJson = PreprocessDateProperty(jsonDoc.RootElement);

        var update = JsonSerializer.Deserialize<Update>(updatedJson, new JsonSerializerOptions
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            Converters = { new JsonStringEnumConverter(JsonNamingPolicy.CamelCase), new UpdateConverter() }
        });

        bindingContext.Result = update != null 
            ? ModelBindingResult.Success(update) 
            : ModelBindingResult.Failed();
    }

    private static string PreprocessDateProperty(JsonElement root)
    {
        using var memoryStream = new MemoryStream();
        using var writer = new Utf8JsonWriter(memoryStream);

        writer.WriteStartObject();

        foreach (var property in root.EnumerateObject())
        {
            if (property.Name == "message" && property.Value.ValueKind == JsonValueKind.Object)
            {
                writer.WritePropertyName("message");
                writer.WriteStartObject();

                foreach (var messageProp in property.Value.EnumerateObject())
                {
                    if (messageProp.Name == "date" && messageProp.Value.ValueKind == JsonValueKind.Number)
                    {
                        var dateTime = DateTimeOffset.FromUnixTimeSeconds(messageProp.Value.GetInt64()).UtcDateTime;
                        writer.WritePropertyName("date");
                        writer.WriteStringValue(dateTime.ToString("o"));
                    }
                    else
                    {
                        messageProp.WriteTo(writer);
                    }
                }

                writer.WriteEndObject();
            }
            else
            {
                property.WriteTo(writer);
            }
        }

        writer.WriteEndObject();
        writer.Flush();

        return Encoding.UTF8.GetString(memoryStream.ToArray());
    }
}

public class UpdateConverter : JsonConverter<Update>
{
    public override Update? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var document = JsonDocument.ParseValue(ref reader);
        var root = document.RootElement;

        var update = new Update
        {
            Id = root.TryGetProperty("update_id", out var updateId) ? updateId.GetInt32() : 0,
            Message = root.TryGetProperty("message", out var message) 
                ? JsonSerializer.Deserialize<Message>(message.GetRawText(), options) 
                : null
        };

        return update;
    }

    public override void Write(Utf8JsonWriter writer, Update value, JsonSerializerOptions options) =>
        throw new NotImplementedException();
}
```
