### ISSUE TITLE
Add missing pages to documentation

### ISSUE THREAD

**Issue by UAVXP** [TelegramBots/Telegram.Bot#841]
It's very frustrating that some of the pages are missing. I need to know some more info about those features

**Comment by Smartis2812** [comment]
Hello,
I guess this issue will be resolved in [the books repositiory](https://github.com/TelegramBots/book), or?
Any particular topic you want to be handled first?

**Comment by nicky-ernste** [comment]
Seems like the Getting updates chapter would be very important. I'm trying to work on a bot myself, but i dont think the telegram documentation about about getting updates isn't very clear either.
For example as far as i can read from the [telegram docs](https://core.telegram.org/bots/api#getting-updates) it should only return updates to you once when you call the getUpdates endpoint. But for me it just keeps returning the same updates even though the bot has already handled them or send a message in response (Not a reply though). So i would love some more information about it.

**Comment by Fedorus** [comment]
> Seems like the Getting updates chapter would be very important to get started with making bots. I'm trying to work on a bot myself, but i dont think the telegram documentation about about getting updates isn't very clear either.
> For example as far as i can read from the [telegram docs](https://core.telegram.org/bots/api#getting-updates) it should only return updates to you once when you call the getUpdates endpoint. But for me it just keeps returning the same updates even though the bot has already handled them or send a message in response (Not a reply though). So i would love some more information about it.
look at offset in https://core.telegram.org/bots/api#getupdates
