### ISSUE TITLE
Why i'm Member in my bot!

### ISSUE THREAD

**Issue by HaliAlduhoky** [TelegramBots/Telegram.Bot#844]
Hello.
I created new bot.
When i get my status from bot is ( Status:member)
When i get my status from group and channel is ( Status:creator)

My question is.
Why i'm member in my own bot and i'm that person that created it!

Thanks.

**Comment by tuscen** [comment]
If you have a question and not a but report please join our [group](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA), we don't provide support in github issues.
