### ISSUE TITLE
Implement Try pattern in a TelegramBotClient class

### ISSUE THREAD

**Issue by UselessToucan** [TelegramBots/Telegram.Bot#846]
Since Telegram is blocked in Russia, I expect that my requests may fail. The problem is that it is uncomfortable to me to handle these failures using current `TelegramBotClient`.
I have to wrap library calls in try/catch blocks. I would prefer not to have a ton of try/catch blocks in my application code.
As a solution, I suggest to implement Try pattern. I mean, I would like to have a set of methods  where `false` is returned instead of throwing an `Exception`.

**Comment by tuscen** [comment]
`Try*` methods with `out` parameters can't be async. And we don't plan to add sync versions of methods. Also even if that would be possible it's a very non-idiomatic way to write API clients in, that way all information from returned errors is lost.

**Comment by karb0f0s** [comment]
ASP.NET Core 2.1 introduced `IHttpClientFactory`. Following [this article](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly) you can configure resilient typed HttpClient and customize fail behaviour with custom policy.

**Comment by Fedorus** [comment]
if-else instead of try-catch... trade bad for worse
