### ISSUE TITLE
In Asp.net Mvc,after pressing callbackbutton ,CallbackQuery is null

### ISSUE THREAD

**Issue by mehdimsv** [TelegramBots/Telegram.Bot#850]
Hello
for webhook api works perfect until you send an inlinekeyboardbuttn(with callback data),after user presses the buttn, all parameters of the Update object is null.

the only way to get the json for CallbackQuery is by using :

`var stream = new StreamReader(Request.InputStream).ReadToEnd();`

the returnded json is like this:

{"update_id":xxxx,
"callback_query":{"id":"xxxx","from":{"id":xxx,"is_bot":false,"first_name":"Mehdi","last_name":"Mousavi","username":"xxx","language_code":"fa"},"message":{"message_id":xxx,"from":{"id":xxx,"is_bot":true,"first_name":"xxxx","username":"xxxx"},"chat":{"id":xxx,"first_name":"xxx","last_name":"xx","username":"xxx","type":"private"},"date":1575899738,"text":"xxx","reply_markup":{"inline_keyboard":[[{"text":"button 1","callback_data":"data-1"}]]}},"chat_instance":"xxxx","data":"data-1"}}

the problem is by using the update as an argument for Action, webhook works fine but when pressing the callbackbutton it returns null.
I think somewhere in binding model there is a problem.
I got the code working by casting json by newtonsoft but for begginers it may cause headache.

**Comment by karb0f0s** [comment]
We've made some changes under the hood. Could you please check if this is still an issue with the latest library version [Telegram.Bot 15.2.1](https://www.nuget.org/packages/Telegram.Bot/15.2.1)

**Comment by karb0f0s** [comment]
Fixed in #860
