### ISSUE TITLE
Telegram Bot C#

### ISSUE THREAD

**Issue by 49IME** [TelegramBots/Telegram.Bot#855]
Hello, I am writing a bot telegram. Telegram.Bot library, I need to make a greeting for my bot so that it welcomes every new member, who will help? (I need a sample code, I tried a lot like it through NewChatMembers too, but did not understand how to extract a list of participants from it)

**Comment by tuscen** [comment]
Please, read message template when creating new issues. For help you can join our support group. You can link to it in the readme.
