### ISSUE TITLE
Provide and consume custom Typed Client for Telegram Bot API

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#863]
I would like to summarize and suggest some improvements, based on these guides:
- [Use HttpClientFactory to implement resilient HTTP requests](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)
- [Make HTTP requests using IHttpClientFactory in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1)

[Typed Client](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#typed-clients) have some benefits:

- Provide a single location to configure and interact with a particular HttpClient.
- Work with DI and can be injected where required in the app.

This would give a safe way to customize Telegram Bot API endpoint without exposing `BaseUrl` property (and solve this issue #829). As a single configuration point this would also make obsolete proxy interfaces in library [`public TelegramBotClient(string token, IWebProxy webProxy)`](https://github.com/TelegramBots/Telegram.Bot/blob/3785abf53f0b810a4ede47fadc26fa2ee8fdcf30/src/Telegram.Bot/TelegramBotClient.cs#L187-L210)

In conjunction with DI injection and `IHttpClientFactory` it is possible to configure resilient client [Use Polly-based handlers](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#use-polly-based-handlers), [Implement HTTP call retries with exponential backoff with HttpClientFactory and Polly policies](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly). This would solve this issues #520, #540.

Another possible effect of explicit declaration and use of Typed Client is the ability to remove [`HttpClient`](https://github.com/TelegramBots/Telegram.Bot/blob/3785abf53f0b810a4ede47fadc26fa2ee8fdcf30/src/Telegram.Bot/TelegramBotClient.cs#L42) from the library and encourage users to manage `HttpClient` lifetime themselves or  let `HttpClientFactory` take care of this matter.

**Comment by tuscen** [comment]
I don't quite understand your proposal. What exactly are you suggesting? Could you add a bit of code to see how it would look like from an API standpoint?

**Comment by astorDev** [comment]
I believe the proposal is to make ctor like 
`public TelegramBotClient(HttpClient client)` which allows it to be injected like 
`services.AddHttpClient<ITelegramBotClient, TelegramBotClient>` like described [here](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)

**Comment by tuscen** [comment]
@astorDev There’s no need to change the client to achieve that. I have a prototype for DI integration that also allows to have more than one client in a container.

**Comment by astorDev** [comment]
@tuscen Well, I think the benefits of suggested approach is not only having DI integration and multiple clients. But to move HttpClient lifecycle management etc to Microsoft’s libraries

**Comment by tuscen** [comment]
@astorDev It can be achieved today with the following piece of code

```c#
var servicesCollection = new ServiceCollection();

servicesCollection.AddHttpClient("telegram")
    .AddTypedClient<ITelegramBotClient>(client =>
    {
        client.BaseAddress = new Uri("https://api.telegram.org");
        return new TelegramBotClient("<token>", client);
    });

var services = servicesCollection.BuildServiceProvider();

var scopeFactory = services.GetService<IServiceScopeFactory>();
var scope = scopeFactory.CreateScope();

var botClient = scope.ServiceProvider.GetService<ITelegramBotClient>();
```

**Comment by karb0f0s** [comment]
@tuscen what a  truly wonderful piece of code! I was scraping some code to demonstrate the same concept but started from another direction by removing hard coded BaseUrl from client.
your example totally covers HttpClient lifetime management in .Net Core DI and resiliency issues I mentioned earlier.
Still I’m not sure about exposing BaseUrl as read/write property, but placing it inside HttpClient constructor could give flexibility for some use cases (for example setting up a proxy endpoint to record certain interactions and than replaying them for test purposes without direct access to TG servers). With this changes simple HttpClient injection could lead to errors because BaseAddress is not set. With custom (typed) client as a constructor parameter this errors can be avoided.

**Comment by MihaZupan** [comment]
I think the issue with that was that some services may use different base uris for regular requests and file requests

**Comment by tuscen** [comment]
@MihaZupan I have a crazy idea: we could decouple request building logic and introduce something like this:

```csharp
// is used by anything that don't care about result type so consumers
// don't need to introduce needless generics
interface IRequest
{
    HttpMethod Method { get; }
    string MethodName { get; }
    HttpContent ToHttpContent();
    bool IsWebhookRequest { get; set; }
}

// is used by MakeRequestAsync to obtain result type
interface IRequest<TResult> : IRequest
{
}

// just an idea and not an actual API proposal
interface ITelegramRequestBuilder
{
    HttpRequestMessage BuildMethodRequest(string token, IRequest request);
    HttpRequestMessage BuildDownloadFileRequest(string token, string fileId);
}
```

So if you for some reason want to make your proxy expect requests in a slightly different format (e.g. token in a header instead of a part of path) you'd implement `ITelegramRequestBuilder`.

We'd have to our default implementation that knows how to construct requests to official bot api endpoint.

That way we can decouple request building logic and allow people to make proxies however they like.

**Comment by MihaZupan** [comment]
I'd be okay with exposing such logic, but only after there is an actual request/need for it

**Comment by karb0f0s** [comment]
and then it is possible to do something like this
```csharp
var bot1 = “token1”;
var bot2 = “token2”;

var message1 = await botClient().WithToken(bot1).With(BetaApiHttpClient).SendMessage(...);
var message2 = await BotClient().WithToken(bot2).WithDefaultClient().SendDocument(...);
```

**Comment by tuscen** [comment]
@MihaZupan yeap, until then having two optional `Uri`s in a ctor would suffice.

**Comment by tuscen** [comment]
@karb0f0s I guess all this `WithSomething` methods would return some kind of client or request executor builder? So `ITelegramBotClient` will serve as a facade for actual implementations. Though that will make it a bit overengineered 😄  Though the idea is interesting.

**Comment by karb0f0s** [comment]
So here is some research i've done for my [proposal](https://github.com/TelegramBots/Telegram.Bot/issues/863#issue-554653878).

### Customize `HttpClient`

It is possible to specify a base address for `HttpClient`. To avoid overriding modified `HttpClient` with default address I suggest to provide preconfigured instance of client with library. 

```csharp
public interface ITelegramApiHttpClient
{
    HttpClient Client { get; }
}

public class TelegramApiHttpClient : ITelegramApiHttpClient
{
    private const string BaseUrl = "https://api.telegram.org/";

    public readonly HttpClient Client { get; }

    public TelegramApiHttpClient(HttpClient client)
    {
        client.BaseAddress = new Uri(BaseUrl);
        Client = client;
    }
}
```

### Modified `TelegramBotClient`

```diff
public class TelegramBotClient : ITelegramBotClient
{
-   private const string BaseUrl = "https://api.telegram.org/bot";
    // ...
    public TelegramBotClient(BotToken botToken, ITelegramApiHttpClient apiClient)
    {
        _token = botToken ?? throw new ArgumentNullException(nameof(botToken));
        BotId = _token.BotId;
-       _baseRequestUrl = $"{BaseUrl}{_token}/";
+       _baseRequestUrl = WebUtility.UrlEncode($"bot{_token.Token}/");
        _httpClient = apiClient.Client;
    }
}
```

### Some usage examples

Default client usage example:

```csharp
var bot = new TelegramBotClient(botToken, new TelegramApiHttpClient());
```

Modified client example:

```csharp
public class TelegramCustomApiHttpClient : ITelegramApiHttpClient
{
    private const string BaseUrl = "https://myapi.bot/";

    public HttpClient Client { get; }

    public TelegramCustomApiHttpClient(HttpClient client)
    {
        client.BaseAddress = new Uri(BaseUrl);
        Client = client;
    }
}
// .....
var bot = new TelegramBotClient(botToken, new TelegramCustomApiHttpClient());
```

**Comment by karb0f0s** [comment]
And here is an example of creating resilient client utilizing `HttpClientFactory` in ASP.NET Core (maybe it's too complicated, [this comment](https://github.com/TelegramBots/Telegram.Bot/issues/863#issuecomment-578524438) covers this issue better):

```csharp
// Services.cs
public class BotService
{
    public ITelegramBotClient Bot { get; }

    public BotService(IOptions<BotOptions> botOptions, ITelegramApiHttpClient apiClient)
    {
        Bot = new TelegramBotClient(new BotToken(botOptions.Value.BotToken), apiClient);
    }
}

// Startup.cs
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddHttpClient<ITelegramApiHttpClient, TelegramCustomApiHttpClient>()
            .AddPolicyHandler(GetRetryPolicy());
        services.AddScoped<BotService>();
        // ...
    }

    private static IAsyncPolicy<HttpResponseMessage> GetRetryPolicy()
    {
        return HttpPolicyExtensions
            .HandleTransientHttpError()
            .OrResult(msg => msg.StatusCode == HttpStatusCode.NotFound)
            .WaitAndRetryAsync(6, retryAttempt => TimeSpan.FromSeconds(Math.Pow(2,
                                                                        retryAttempt)));
    }
}

// Controller.cs
public class GetMeController : ControllerBase
{
    private readonly ITelegramBotClient _bot;

    public GetMeController(BotService botService)
    {
        _bot = botService.Bot;
    }

    [HttpGet]
    public async Task<ActionResult<User>> GetMeAsync()
    {
        var me = await _bot.GetMeAsync();
        return Ok(me);
    }
}
```

**Comment by karb0f0s** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue with the [latest stable version](https://www.nuget.org/packages/Telegram.Bot) and then please use the [issue template](https://raw.githubusercontent.com/TelegramBots/Telegram.Bot/master/.github/ISSUE_TEMPLATE/bug_report.md).
