### ISSUE TITLE
BotToken entity type

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#864]
We can go full DDD and use `BotToken` entity type instead of checking it in ctor.

```csharp
public class BotToken
{
    public readonly string Token;
    public readonly int BotId;

    public BotToken(string token)
    {
        Token = token ?? throw new ArgumentNullException(nameof(token));

        var parts = Token.Split(':');
        if (parts.Length <= 1 || !int.TryParse(parts[0], out BotId))
        {
            throw new ArgumentException(
                "Invalid format. Please provide a valid token in format \"1234567:4TT8bAc8GHUspu3ERYn-KGcvsvGB9u_n4ddy\".",
                nameof(token)
            );
        }
    }
}
```

Much cleaner code:
```csharp
public TelegramBotClient(BotToken botToken, HttpClient httpClient = null)
{
    _token = botToken ?? throw new ArgumentNullException(nameof(botToken));
    _baseRequestUrl = $"{BaseUrl}{_token.Token}/";
    _httpClient = httpClient ?? new HttpClient();
}
```

**Comment by tuscen** [comment]
I think we're going to remove the second ctor with `IWebProxy` so there wouldn't be much benefit from wrapping token in another type

**Comment by karb0f0s** [comment]
Sorry, can’t leave it behind 🙃. My point is - either we accept token as it is and it mean we should check it’s existence or we accept specific kind of object and then this checks (its business logic) should be placed inside it.

**Comment by tuscen** [comment]
Yeah, I get it. From a purely DDD standpoint it makes sense. But do we really need it? What puppose will it serve other than putting one piece of code to another place?
