### ISSUE TITLE
JSON value could not be converted to Telegram.Bot.Types.Enums.ChatType

### ISSUE THREAD

**Issue by lvyyln** [TelegramBots/Telegram.Bot#865]
I found a bug to report
When i am trying to deserealize data from body json can't convert ChatType

Steps to reproduce:
1.Sending command 'start' 
2.Waiting while json will be deserealized
3.Then happend 'bad request'

![image](https://user-images.githubusercontent.com/52297465/73345897-94a6c200-428d-11ea-9cf5-a8acb32d0928.png)

NuGet Package Version: 15.2.0

.NET Version: Core 3.1

IDE: Rider

App: Desktop

**Comment by tuscen** [comment]
Are you using `System.Text.Json`? The error message looks like from it.

**Comment by lvyyln** [comment]
No, i am not using System.Text.Json

**Comment by tuscen** [comment]
Could you add more context? Is it a webhook on ASP.NET Core 3.1 or long polling mode? If it is webhook could you provide the code from startup and where you're deserializing webhook request?

**Comment by lvyyln** [comment]
So this is a webhook on ASP.NET Core 3.1 
Startup : public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            Bot.GetBotClientAsync().Wait();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints => { endpoints.MapControllers(); });
        }
    }

GetBotClientAsync :
 public static class Bot
    {
        private static TelegramBotClient botClient;
        private static List<Command> commandsList;

        public static IReadOnlyList<Command> Commands => commandsList.AsReadOnly();

        public static async Task<TelegramBotClient> GetBotClientAsync()
        {
            if (botClient != null)
            {
                return botClient;
            }

            commandsList = new List<Command>();
            commandsList.Add(new StartCommand());

            botClient = new TelegramBotClient(AppSettings.Key);
            
            string hook = string.Format(AppSettings.Url,"api/message/update"); 
            await botClient.SetWebhookAsync(hook);

            return botClient;
        }
    }

And for deserializing i'm using frombody attribute
![image](https://user-images.githubusercontent.com/52297465/73480176-14be4c00-43a2-11ea-9d9e-3c452bd7407a.png)

**Comment by tuscen** [comment]
Ok, so you do use `System.Text.Json`, you just didn't know it. ASP.NET Core 3.0+ replaced `Newtonsoft.Json` as the default json formatter with `STJ`. But the client still doesn't support it yet. What you need to do is to install [this](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.NewtonsoftJson) nuget package and add it as the default json formatter. This should solve the problem.

```csharp
services.AddControllers().AddNewtonsoftJson();
```

**Comment by lvyyln** [comment]
Thanks for help, everything is working, and maybe you write somewhere that for ASP.NET Core 3.0+ developers should use  
services.AddControllers().AddNewtonsoftJson();

**Comment by sergiycheck** [comment]
Thank you I had the same problem and it worked!
