### ISSUE TITLE
The request was canceled: A secure channel for SSL / TLS could not be created

### ISSUE THREAD

**Issue by tuscen** [TelegramBots/Telegram.Bot#868]
If you've recently started getting an exception with the following message `The request was canceled: A secure channel for SSL / TLS could not be created` it is due to Telegram disabling everything older than TLS v1.2 (which is not used as the default in .NET Framework 4.5 and earlier). The best way to mitigate this problem is to update to .NET Framework 4.6-4.8 or even to .NET Core 3.1 (this is preferrable if you can do that).

If you can't upgrade your system or .NET Framework to a newer one there might be a solution (though it's not guaranteed to work). One of the members in our group came up with a guide how it could be mitigated:

> So, this is the final instruction for those who faces the problem "The request was aborted: Could not create SSL / TLS secure channel"
> 
> Windows 7 / Server 2008 R2:
> 
> 1. Update your system.
> 
> 2. If you use .NET Framework 4.5, add this line somewhere before you initialize TelegramBotClient:
> 
> ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
> 
> or target .NET Framework 4.6 and higher to use TLS 1.2 as default.
> 
> 3. If the error is still here, try to follow these instructions to enable TLS 1.1 and TLS 1.2 as default secure protocols in WinHTTP in Windows (https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi) (but this didn't work for me until I updated my system).
> 
> 
> Windows 8.1/Server 2012 R2 and higher:
> - use step 2 of instructions above.

---

For additional information you can check this [comment](https://github.com/TelegramBots/Telegram.Bot/issues/867#issuecomment-583023201).

**Comment by wiz0u** [comment]
This might have been a good pinned issue at the time, but I don't think it's relevant nowadays. Maybe incorporate this better in our FAQ. Closing this for now.
