### ISSUE TITLE
How to make the bot read what user says after bot message

### ISSUE THREAD

**Issue by mynameismental** [TelegramBots/Telegram.Bot#877]
I want the bot to read and store what a user says after bot's message. Example:

Bot: Insert BTC Wallet Address
User: 489tyh34078fgh7g4q3t03y3

The 489tyh34078fgh7g4q3t03y3 needs to gets stored in a variable, but I have not Idea how can make the bot read that

**Comment by tuscen** [comment]
Please, don't use issue tracker for questions, we use it only for bug reports. Feel free to join our group for support https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA
