### ISSUE TITLE
System.ArgumentException: “"utf-8"”

### ISSUE THREAD

**Issue by mudebug77** [TelegramBots/Telegram.Bot#878]
await TGClient.GetMeAsync()；出现 error

System.AggregateException: 发生一个或多个错误。 ---> System.InvalidOperationException: The character set provided in ContentType is invalid. Cannot read content as string using an invalid character set. ---> System.ArgumentException: “"utf-8"”不是受支持的编码名。
参数名: name
   在 System.Globalization.EncodingTable.internalGetCodePageFromName(String name)
   在 System.Globalization.EncodingTable.GetCodePageFromName(String name)
   在 System.Text.Encoding.GetEncoding(String name)
   在 System.Net.Http.HttpContent.ReadBufferAsString(ArraySegment`1 buffer, HttpContentHeaders headers)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.Http.HttpContent.ReadBufferAsString(ArraySegment`1 buffer, HttpContentHeaders headers)
   在 System.Net.Http.HttpContent.ReadBufferedContentAsString()
   在 System.Net.Http.HttpContent.<>c.<ReadAsStringAsync>b__36_0(HttpContent s)
   在 System.Net.Http.HttpContent.<WaitAndReturnAsync>d__63`2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Telegram.Bot.TelegramBotClient.<MakeRequestAsync>d__54`1.MoveNext()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   在 System.Threading.Tasks.Task`1.get_Result()
   在 LHSystem.TelegramBotComponent.<Start>b__1_0(Task`1 x)
   在 System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 LHSystem.TelegramBotComponent.<Start>d__1.MoveNext()
---> (内部异常 #0) System.InvalidOperationException: The character set provided in ContentType is invalid. Cannot read content as string using an invalid character set. ---> System.ArgumentException: “"utf-8"”不是受支持的编码名。
参数名: name
   在 System.Globalization.EncodingTable.internalGetCodePageFromName(String name)
   在 System.Globalization.EncodingTable.GetCodePageFromName(String name)
   在 System.Text.Encoding.GetEncoding(String name)
   在 System.Net.Http.HttpContent.ReadBufferAsString(ArraySegment`1 buffer, HttpContentHeaders headers)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.Http.HttpContent.ReadBufferAsString(ArraySegment`1 buffer, HttpContentHeaders headers)
   在 System.Net.Http.HttpContent.ReadBufferedContentAsString()
   在 System.Net.Http.HttpContent.<>c.<ReadAsStringAsync>b__36_0(HttpContent s)
   在 System.Net.Http.HttpContent.<WaitAndReturnAsync>d__63`2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

----------------------------------------------------------------------------------------
此项目有解决方案
https://github.com/skazantsev/WebDavClient/issues/1

**Comment by tuscen** [comment]
Could you please write in English? I don't understand Chinese. Also could you add additional info about versions of the lib, runtime, etc? As it is in the issue template. Thanks.

**Comment by karb0f0s** [comment]
@mudebug77 please provide more info according to our issue template. We are unable to reproduce this error, would reopen this issue with more input from you.
