### ISSUE TITLE
unable to receive messages via webhook

### ISSUE THREAD

**Issue by eulphean** [TelegramBots/telegram.bot#88]
I'm using Telegram.Bot sdk and went through the steps to configure the webhook. I'm not receiving any messages from telegram. Here are some things I'm doing and some questions:

1: I'm configuring endpoint with port 443 and not 8443. Telegram's FAQ says that it's fine.

2: I call the setWebhook utility with a self-signed certificate and the endpoint url. This succeeds gracefully. Do I still need to configure the endpoint using the commands you mentioned? If so, why?

// Endpoint musst be configured with netsh:
            // netsh http add urlacl url=https://+:8443/ user=<username>
            // netsh http add sslcert ipport=0.0.0.0:8443 certhash=<cert thumbprint> appid=<random guid>

3: I'm deploying this on Azure website and it gives me a https endpoint by default. 

Thanks in advance for your help.

**Comment by ffalmeida** [comment]
Hi,
I'm having the same problem. Managed to solve ?

**Comment by mhverbakel** [comment]
I have no problem with this. How are you handling the webhook request?

**Comment by ddadkhah** [comment]
I have same problem. Is any one to help us?

**Comment by mhverbakel** [comment]
How do you deploy the application?

**Comment by ddadkhah** [comment]
My Problem resolved automatically. I don't know why. Thx

**Comment by pouladpld** [comment]
@eulphean Feel free to reopen this if the issue isn't resolved and please follow [issue template](https://github.com/TelegramBots/telegram.bot/blob/develop/ISSUE_TEMPLATE.md).
