### ISSUE TITLE
TelegramBotClient.SetWebhookAsync not working

### ISSUE THREAD

**Issue by YanivHakim** [TelegramBots/Telegram.Bot#880]
When calling SetWebhookASync I don't get any error and still do not recieve any webhook updates...
I read all the guidelines for verified certificates and tested them all (https://core.telegram.org/bots/webhooks) . I know have a valid verfied certificate and still cannot set any web hooks...
Does this works? Someone knows if this is a bug? anyone made webhooks works???

I tried with or without a pem/cer file:
```

InputFileStream certFile = new InputFileStream(File.OpenRead("c:\\data\\certs\\cert.cer"));

m_client.SetWebhookAsync("https://mydomain:443/telegram/realtimeupdates/", certificate: certFile, allowedUpdates: new UpdateType[0]).Wait();

```

`m_client.SetWebhookAsync("https://mydomain:443/telegram/realtimeupdates/, allowedUpdates: new UpdateType[0]).Wait();`

**Comment by tuscen** [comment]
Try making this request in the browser `https://api.telegram.org/botYOURTOKEN/getWebhookInfo`. What does it return?

**Comment by YanivHakim** [comment]
thanks @tuscen !
I tried it an got:
`{"ok":true,"result":{"url":"https://mydomain:443/telegram/realtimeupdates/Z3_bBAbmEdP3veUDHGv9HSg%3d%3d","has_custom_certificate":false,"pending_update_count":0,"max_connections":40,"allowed_updates":["message","channel_post"]}}`

which looks good, but, I still don't get ANY updates to this URL. What am I missing???

**Comment by tuscen** [comment]
You have `allowed_updates` set to only channel posts. Is that what you wanted?

**Comment by YanivHakim** [comment]
@tuscen channel post and messages. no? i want to receive user sent messages mainly

**Comment by tuscen** [comment]
I see, I missed the first entry in the array. Are you sure you're sending correct url and path? I couldn't reproduce the problem on my local machine with ngrok. Webhook worked correctly.

**Comment by YanivHakim** [comment]
@tuscen yes. the url and domain are good and also tested, but i don't seem to get a request from telegram to that url. It's just a regular request right? https/post with application/json content-type right?

**Comment by tuscen** [comment]
Correct, it's always a post request with json payload. What happens when you send some messages and then call `getWebhookInfo`? Does it return non-zero pending messages count?

**Comment by YanivHakim** [comment]
@tuscen No, I checked that... it's always 0... really frustrating

**Comment by tuscen** [comment]
That might mean two things: a bug in telegram bot api servers which for some reason not only prevents updates to be sent to your server, but also don't register new updates on their server (which is unlikely, too many problems at once, but who knows), or that messages are sent and your server acknowledges them with 200 OK. Maybe you configured something incorrectly? Could you show me your receiving code and your startup class (I assume you're using ASP.NET Core)? By the way, try testing your webhook locally with [ngrok](https://ngrok.com/).

**Comment by YanivHakim** [comment]
@tuscen I'm not using .net core, we're using .NET framework 4+.
And also I can't show you the code because it's complicated and part of a really big platform.
But, I'm testing post messages to the same URL from postman and I see them entering good, but from telegram i can't see them... thanks anyway for your help, is there a way to contact Telegram and ask for support?

**Comment by tuscen** [comment]
In that case check if TLS 1.2 is enabled on your server with appropriate ciphers. Telegram disabled everything older than TLS 1.2.

**Comment by YanivHakim** [comment]
@tuscen Just checked and it is tls 1.2 with a trusted certificate from telegram's list

**Comment by YanivHakim** [comment]
@tuscen this is the URL : https://devapi.commbox.xyz/telegram/realtimeupdates/Z3_bBAbmEdP3veUDHGv9HSg%3d%3d

and this is a monitor url:
https://devapi.commbox.xyz/status

if you have any idea i'll be very thankfull

**Comment by tuscen** [comment]
I've checked available ciphers on your domain and the required ones are seems to be enabled. I'm out of ideas what might be wrong.

**Comment by johmarjac** [comment]
I dont get updates too, i have following json payload from getWebhookInfo

```json
{
"ok": true,
"result": {
"url": "https://desktop.johmarjac.me:8443/api/update",
"has_custom_certificate": false,
"pending_update_count": 15,
"last_error_date": 1584115369,
"last_error_message": "Connection timed out",
"max_connections": 40
}
}
```

**Comment by karb0f0s** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue with the [latest stable version](https://www.nuget.org/packages/Telegram.Bot) and then please use the [issue template](https://raw.githubusercontent.com/TelegramBots/Telegram.Bot/master/.github/ISSUE_TEMPLATE/bug_report.md).
