### ISSUE TITLE
Animated GIFs are sent as videos

### ISSUE THREAD

**Issue by erraineon** [TelegramBots/Telegram.Bot#881]
# I found a bug to report

Please use the following template to ensure maintainers can reproduce the bug and solve it quickly.

> Bug reports that do not follow this template will be kept closed because [_not-reproducible_](https://github.com/TelegramBots/telegram.bot/labels/not-reproducible) until the creator edits the post properly.

### Steps to reproduce
With `_api` being a `TelegramBotClient`, `_chat` being the destination `Chat` and `stream` being a `MemoryStream` which contains an animated gif, the code below successfully uploads the gif to Telegram, but it's received from clients as a video and can't be saved to GIFs.
```
await _api.SendVideoAsync(_chat.Id, new InputOnlineFile(stream));
```

This started happening just a few months ago.
Uploading the same file manually through the official Telegram Desktop client works as expected. I'm attaching the file to this issue.

![result](https://user-images.githubusercontent.com/35406749/76472600-72e04500-63cc-11ea-93ab-2e7237705a44.gif)

### Expected  behavior
The received file loops without sound and can be saved to the GIFs.

### Actual behavior
The received file loops choppily, has a timer in the top left and can't be saved to GIFs.

### Screenshots
![image](https://user-images.githubusercontent.com/35406749/76472457-fa798400-63cb-11ea-9d2e-b9ea3ebfb8f7.png)

### Environment data

NuGet Package Version: 15.4.0 

.NET Version: Core 3.0 

IDE: VS2019

App: Console

**Comment by tuscen** [comment]
Are you sure that you started noticing this behaviour only recently? As far as I remember it has been like that for quite a while. It's not a bug in the library, but an undocumented behaviour of telegram servers: they convert all gifs to mp4 videos. It's probably due to saving bandwidth and space.

**Comment by erraineon** [comment]
That worked, thank you.
