### ISSUE TITLE
Client crashes upon new network reconnecion

### ISSUE THREAD

**Issue by jdahan91** [TelegramBots/Telegram.Bot#882]
Hi, I have this scenario where my bot client fires up with Windows and the thing is after it fires up the vpn client connects which means that the bot client raises an internal exception when receiving a message which causes the client to crash. I think this should be take into consideration.

What happens behind the hood is that the bot client establishes a connection under non-vpn and then when vpn connects it screws up the bot client connection.

**Comment by tuscen** [comment]
I don't think it's a client problem. In your case you have a dependency on another service and need to somehow satisfy it yourself. I'd check if window has an ability for services to have triggers on connections established and services running.
