### ISSUE TITLE
ArgumentException in GetAsync

### ISSUE THREAD

**Issue by Omid500** [TelegramBots/Telegram.Bot#883]
When the program runs GetMeAsync() this error is showed to me :
An unhandled exception of type 'System.AggregateException' occurred in mscorlib.dll

Additional information: One or more errors occurred.
------------------------------------------------------------------
I use Visual Studio2015 and .NET Freamwork 4.8

**Comment by tuscen** [comment]
What kind of error is thrown exactly? `AggregateException` is a container exception.

**Comment by Savenzip** [comment]
did you manage to solve this? I got the same error today and it was related to #868.
