### ISSUE TITLE
Event is not Raised when the bot is added to a channel

### ISSUE THREAD

**Issue by wasimjee** [TelegramBots/Telegram.Bot#890]
When I add the bot to a group, I get the update, but when I add the bot to the channel I don't get any update.

**Comment by Fedorus** [comment]
> When I add the bot to a group, I get the update, but when I add the bot to the channel I don't get any update.

You subscribed to wrong event.

**Comment by wasimjee** [comment]
i have subscribed to this event 

OnUpdate

**Comment by tuscen** [comment]
There are no updates for channels other than new or edited messages. It's a limitation of the bot api.

**Comment by wasimjee** [comment]
ok
