### ISSUE TITLE
Unable to Catch ApiRequestException for 429 (Too Many Requests)

### ISSUE THREAD

**Issue by aalejandrodiazs** [TelegramBots/Telegram.Bot#891]
# I found a bug to report

Please use the following template to ensure maintainers can reproduce the bug and solve it quickly.

> Bug reports that do not follow this template will be kept closed because [_not-reproducible_](https://github.com/TelegramBots/telegram.bot/labels/not-reproducible) until the creator edits the post properly.

### Steps to reproduce
```
try
{
    // Send 100 text messages to a group chat
    for (int i = 0; i < 100; i++)
        await Bot.SendTextMessageAsync(chatId, "Hello");
}

catch (ApiRequestException e)
{
    // Retry after the wait time
    await Task.Delay(e.Parameters.RetryAfter);
    await Bot.SendTextMessageAsync(chatId, "Hello");
}
```

### Expected  behavior
I expect to catch ApiRequestException so that I can get the retry_after ResponseParameter.

### Actual behavior
HttpRequestException is thrown, which doesn't include the retry_after ResponseParameter. So I have no way of knowing how long I should wait before retrying.

### Screenshots
<details>
<summary>Screenshot</summary>

![изображение](https://user-images.githubusercontent.com/1078199/79881037-6999bd80-83f9-11ea-86ae-471684c87ac1.png)  

</details>

### Environment data

*NuGet Package Version:* 15.5.1

*.NET Version:* 4.7.2

*IDE:* VS2019

*App:* Console

**Comment by kirsan31** [comment]
Any news? This is a pretty nasty bug :(

**Comment by tuscen** [comment]
@kirsan31 It will be fixed only in the next major release since fixing it is a breaking change in terms of runtime behaviour. You'll have to wait for it.

**Comment by karb0f0s** [comment]
@aalejandrodiazs @kirsan31 you can try [latest development builds](https://dev.azure.com/tgbots/Telegram.Bot/_packaging?_a=package&feed=Telegram.Bot%40Local&package=Telegram.Bot&protocolType=NuGet&version=15.7.1-ci.168%2Bgit.commit.91df3e7459bdf6335a08e0780093635371b20363) which handle 429 error appropriately.

**Comment by kirsan31** [comment]
@karb0f0s sorry I can't - have no bot yet. Was investigating this subject  before starting development...

**Comment by karb0f0s** [comment]
which version do you use? you should target development build and configure additional nuget feed following the instructions https://dev.azure.com/tgbots/Telegram.Bot/_packaging?_a=connect&feed=Telegram.Bot%40Local

Telegram.Bot build 15.7.1-ci.158 targets current v16 development brunch.

**Comment by aalejandrodiazs** [comment]
@karb0f0s My bad —I didn't properly configure Nuget.

I did now, but I'm unable to test because of the breaking changes. Do you have sample code for migrating a bot from v15 to v16?

**Comment by karb0f0s** [comment]
Well, as I recall, there are two major changes: removal of message-handling events and all derived from `ApiRequestException` exceptions.
The first one is somewhat covered by Telegram.Bot.Extensions.Polling. You can take a look at [Polling example](https://github.com/TelegramBots/Telegram.Bot.Examples/tree/master/Telegram.Bot.Examples.Polling)). 
And for the second one - either change specific `*Exception` to `ApiRequestException` or try to add[Telegram.Bot.Extensions.Exceptions](https://github.com/TelegramBots/Telegram.Bot.Extensions.Exceptions/tree/master) to your solution. It's in development and doesn't have CI yet, so you can't just grab nuget for it yet.

**Comment by derigel23** [comment]
@karb0f0s any plans to release Telegram.Bot.Extensions.Exceptions and Telegram.Bot package compatible with it?

**Comment by karb0f0s** [comment]
@derigel23 we do not have specific release dates, but you can already try our latest and full-featured release. It is based on [v15 branch](https://github.com/TelegramBots/Telegram.Bot/tree/v15) and can be added to your project via [Azure DevOps feed](https://dev.azure.com/tgbots/Telegram.Bot/_packaging?_a=connect&feed=Telegram.Bot%40Local).
Exceptions package doesn't have its CI pipeline configured yet, but you can clone it and add as a project reference in your solution.
@tuscen do you have any plans on releasing v16?

**Comment by Xilosof** [comment]
This problem occurs because an exception is thrown in the "TelegramBotClient. cs" file in the "MakeRequestAsync" method on line 269 if the response code is not OK. Line 269 is part of the switch block. 

`switch (actualResponseStatusCode)
            {
                case HttpStatusCode.OK:
                    break;
                case HttpStatusCode.Unauthorized:
                case HttpStatusCode.BadRequest when !string.IsNullOrWhiteSpace(responseJson):
                case HttpStatusCode.Forbidden when !string.IsNullOrWhiteSpace(responseJson):
                case HttpStatusCode.Conflict when !string.IsNullOrWhiteSpace(responseJson):
                    // Do NOT throw here, an ApiRequestException will be thrown next
                    break;
                default:
                    httpResponse.EnsureSuccessStatusCode();
                    break;
            }`
In the case of known errors, this exception is simply not generated. Therefore, you just need to add the 429 response code processing to the switch block, following the example of the other not-okay codes. 

Sample solution:
`switch (actualResponseStatusCode)
            {
                case HttpStatusCode.OK:
                    break;
                case HttpStatusCode.Unauthorized:
                case HttpStatusCode.BadRequest when !string.IsNullOrWhiteSpace(responseJson):
                case HttpStatusCode.Forbidden when !string.IsNullOrWhiteSpace(responseJson):
                case HttpStatusCode.Conflict when !string.IsNullOrWhiteSpace(responseJson):
                case HttpStatusCode.TooManyRequests when !string.IsNullOrWhiteSpace(responseJson):
                    // Do NOT throw here, an ApiRequestException will be thrown next
                    break;
                default:
                    httpResponse.EnsureSuccessStatusCode();
                    break;
            }`
           
I

**Comment by karb0f0s** [comment]
this issue is addressed in https://github.com/TelegramBots/Telegram.Bot/commit/bb50b5de3150553bc3dd801d3c4e2e9dc75f4c57
