### ISSUE TITLE
Response status code does not indicate success: 302 (Moved Temporarily).

### ISSUE THREAD

**Issue by CEBAnder** [TelegramBots/Telegram.Bot#894]
I have next code:
```
var clientHandler = new HttpClientHandler();
clientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };
var client = new HttpClient(clientHandler);
var token = "some_string";            
var botClient = new TelegramBotClient(token, client);                        
var me = await botClient.GetUpdatesAsync();
```
### Expected  behavior
Everything is OK and I get result.
### Actual behavior
System.Net.Http.HttpRequestException: 'Response status code does not indicate success: 302 (Moved Temporarily).'
### Environment data

*NuGet Package Version:* 15.5.1

*.NET Version:* Core 3.0

*IDE:* VS 2019 Community 16.3.0

*App:* Console application

**Comment by tuscen** [comment]
I couldn't replicate your problem in Ubuntu and Windows 10 with the provided example.

**Comment by CEBAnder** [comment]
May it be caused by internet provider or something like this?

**Comment by tuscen** [comment]
I’ve found this issue https://github.com/dotnet/runtime/issues/23801. Do you have some kind of proxy or anything that tries to redirect from https to http?

**Comment by MihaZupan** [comment]
```c#
clientHandler.ServerCertificateCustomValidationCallback =
    (sender, cert, chain, sslPolicyErrors) => { return true; };
```

Is very concerning

**Comment by CEBAnder** [comment]
@tuscen i do not use any proxy
@MihaZupan without this code i get
`HttpRequestException: 'The SSL connection could not be established, see inner exception.'
Inner exception: AuthenticationException: The remote certificate is invalid according to the validation procedure.`

**Comment by tuscen** [comment]
Then it looks like some kind of MITM in your network that tries to redirect requests from https to http.

**Comment by CEBAnder** [comment]
@tuscen seems you are right because i have just tried another provider and everything is ok
