### ISSUE TITLE
Newtonsoft.Json Version 11.0.0.0 not found

### ISSUE THREAD

**Issue by TheMulti0** [TelegramBots/Telegram.Bot#896]
# Newtonsoft.Json Version 11.0.0.0 not found

I found that when sending a message through `TelegramBotClient` (`_client.SendTextMessageAsync`), it will fail with an exception; it cannot find Newtonsoft.Json 11.0.0.

I am using the latest `Telegram.Bot` (`15.5.1`) package, which references Newtonsoft.Json 11.0.2.

`Newtonsoft.Json 11.0.0` does not exit, only 11.0.1, etc.

Strangest thing: All of this only happens while running my [app](https://github.com/TheMulti0/Iris/) on Docker for Linux. None of this occurs when debugging, or even when running my docker image on Docker for Windows (which virtualizes a Linux VM using HyperV behind the scenes).

I am targeting .NET Core 3.1.

### Steps to reproduce

Call `TelegramBotClient.SendMessageAsync` on a .NET Core 3.1 Docker on Linux container.

### Expected  behavior

The message will be sent with no error.

### Actual behavior

I get an exception:
```cs
 Failed to send update: Id: 1254481372787376128, ChatId: @yeminapar
System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyTo40)
File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Telegram.Bot.TelegramBotClient.MakeRequestAsync[TResponse](IRequest`1 request, CancellationToken cancellationToken)
   at Telegram.Bot.TelegramBotClient.SendTextMessageAsync(ChatId chatId, String text, ParseMode parseMode, Boolean disableWebellationToken)
   at Iris.Bot.Sender.SendAsync(Update update, Int64 chatId) in /source/Iris/Bot/Sender.cs:line 36
   at Iris.Bot.Bot.SendMessage(Update update, Int64 chatId) in /source/Iris/Bot/Bot.cs:line 141
```

### Screenshots

![image](https://user-images.githubusercontent.com/25365118/80320391-d14b7080-881e-11ea-9ddd-c047ff3eb59a.png)

### Environment data

*NuGet Package Version:* 15.5.1

*.NET Version:* .NET Core 3.1

*IDE:* Not relevant.

*App:* Console application (Desktop), as a container running on Docker for Linux.

Thank you all very much! <3

**Comment by TheMulti0** [comment]
Same without Docker (simply running `dotnet publish` and `dotnet run`)

**Comment by karb0f0s** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. 

Please reopen if you still encounter this issue with the [latest stable version](https://www.nuget.org/packages/Telegram.Bot) and then please use the [issue template](https://raw.githubusercontent.com/TelegramBots/Telegram.Bot/master/.github/ISSUE_TEMPLATE/bug_report.md).
