### ISSUE TITLE
Markup Title in documentation

### ISSUE THREAD

**Issue by yungstepik** [TelegramBots/Telegram.Bot#898]
I would like to request to add something in documentation in the title about Markups. 

That's great. Let us know what's on your mind and please try to be specific.

You also can chat with us on Telegram [![@tgbots_dotnet](https://img.shields.io/badge/@tgbots__dotnet-Telegram-blue.svg)](https://t.me/tgbots_dotnet)

**Comment by tuscen** [comment]
Please, open issues in the appropriate repositories. This issue applies to the [TelegramBots/book](https://github.com/TelegramBots/book) repository.
