### ISSUE TITLE
c# send a file image

### ISSUE THREAD

**Issue by ahron33** [TelegramBots/Telegram.Bot#899]
i am trying to get this working but i got an error on this filetosend thing

what is this?

`WebRequest req = WebRequest.Create("http://google.com");
            req.Method = "GET";

            using (var response = await req.GetResponseAsync())
            using (var stream = response.GetResponseStream())
            {
                await bot.SendDocumentAsync(e.Message.Chat.Id, new FileToSend("file.html", stream));
            }`

**Comment by tuscen** [comment]
Please, follow issue template. As I can see you're using pretty old version of the library. I couldn't replicate the problem with the latest version.

**Comment by ahron33** [comment]
so what could i do to fix it update to what version?

**Comment by ahron33** [comment]
> Please, follow issue template. As I can see you're using pretty old version of the library. I couldn't replicate the problem with the latest version.

so what could i do to fix it update to what version?

**Comment by tuscen** [comment]
The latest one: 15.5.1

**Comment by ahron33** [comment]
> The latest one: 15.5.1

its on this version..

**Comment by tuscen** [comment]
`FileToSend` type has long been removed. You can read migration guide about breaking changes https://telegrambots.github.io/book/Migration-Guide-to-Version-14.x.html.

**Comment by ahron33** [comment]
> `FileToSend` type has long been removed. You can read migration guide about breaking changes here https://telegrambots.github.io/book/Migration-Guide-to-Version-14.x.html.

thanks! i did it with this code

`Stream stream = System.IO.File.OpenRead("Screenshot_8.png");
            await bot.SendPhotoAsync(e.Message.Chat.Id, stream);`
