### ISSUE TITLE
after button clicked run code or display it inlinekeyboardbutton with callbackdata c#

### ISSUE THREAD

**Issue by ahron33** [TelegramBots/Telegram.Bot#900]
trying to click or display or do something after clicking on one of the buttons
code:
`await bot.SendTextMessageAsync("", "test", replyMarkup: new InlineKeyboardMarkup(
            new InlineKeyboardButton[][]
            {
            new [] {
                new InlineKeyboardButton()
                { Text = "btn 1",CallbackData="Somedata1"} }, // buttons in row 1
            new [] 
            { new InlineKeyboardButton() 
            { Text = "btn 2", CallbackData = "Some data2" } }, // buttons in row 2
            new [] 
            { new InlineKeyboardButton() 
            {Text =  "btn 3", CallbackData = "Some data3" } }// buttons in row 3
            }));`

![Screenshot_26](https://user-images.githubusercontent.com/63168357/81792641-fe7f6a80-9510-11ea-953f-7ccd99ce4960.png)

**Comment by tuscen** [comment]
Please, file issues only if you found a legitimate bug. If you have other questions feel free to join our group https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA.
