### ISSUE TITLE
Create implicit convertation between ChatId and Update

### ISSUE THREAD

**Issue by DmytroSH** [TelegramBots/Telegram.Bot#903]
## I would like to request/propose a feature
So usually i do stuff like that to send response
``` csharp
 public async Task Reply(TelegramBotClient client, Update hook)
 {
        await client.SendTextMessageAsync(
                hook.Message.Chat.Id, "Hello World");
 }
```
But I think it will be good to send message without hardcode chat id position because sometimes it can vary by message type, so i create extension method to retrieve ChatId from hook, but i think its better to have implicit convertion between Update and ChatId so i can use method like this:

``` csharp
 public async Task Reply(TelegramBotClient client, Update hook)
 {
        await client.SendTextMessageAsync(
                hook, "Hello World");
 }
```

**UPDT: or extension method**
That's great. Let us know what's on on your mind and please try to be specific.

You also can chat with us on Telegram [![@tgbots_dotnet](https://img.shields.io/badge/@tgbots__dotnet-Telegram-blue.svg)](https://t.me/tgbots_dotnet)

**Comment by Fedorus** [comment]
Main issue what you wanna do in case where update doesn`t have any chatId/FromId.

My suggestion - add extension methods: 
```
User? GetUser(this Update update); 
Chat? GetChat(this Update update);
```
Which will return corresponding objects if they exist (or sender != anonymous user) after that you can easily implement methods that you need with Reply if chat exists and handle situation when there is none.

Additionally those methods useful while logging/user authorization, etc.

**Comment by wiz0u** [comment]
> ```cs
> await client.SendTextMessageAsync(hook.Message.Chat.Id, "Hello World");
> ```
As a shortcut, you can already use hook.Message.Chat

I don't plan to make further such shortcuts because an Update object may reference many Chats (ex: forwarding from one chat to another, replying to a message from another group)
