### ISSUE TITLE
.NET Core 3.0/3.1, .NET 5 Preview and .NET Standard compatibility

### ISSUE THREAD

**Issue by simusr2** [TelegramBots/Telegram.Bot#904]
# .NET Core 3.0/3.1, .NET 5 Preview and .NET Standard compatibility
I'm trying to create new console app or worker with Telegram.Bot package.
When I try to install NuGet package many errors are throws.

```
Errore	NU1202	Il pacchetto System.IO.FileSystem.Primitives 4.3.0 non è compatibile con netstandard2.1 (.NETStandard,Version=v2.1). Il pacchetto System.IO.FileSystem.Primitives 4.3.0 supporta:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)
```
I don't know if this is a "missing feature" or a bug (or something that I'm doing wrong).
It seem that Telegram.Bot is not compatible with these versions of .NET (I personally tried with all of these versions).
I have same problem compiling example in [Telegram.Bot.Examples](https://github.com/TelegramBots/Telegram.Bot.Examples) (I tried with [Telegram.Bot.Examples.Polling](https://github.com/TelegramBots/Telegram.Bot.Examples/tree/master/Telegram.Bot.Examples.Polling)

**Comment by tuscen** [comment]
I think it's more likely that's a problem with your environment. All my bots worked on .NET Core starting from 1.X preview using this library. Right now I'm in the process of migrating my bot to .NET Core 3.1 and I don't compatibility problems. I also have checked the latest .NET 5 preview 4 and couldn't replicate your problem.

**Comment by simusr2** [comment]
Thanks for your response.
After your response i thought that problem could be caused by NuGet cache so I cleared it with
`dotnet nuget locals all -c`
Now I'm able to install Telegram.Bot package!
