### ISSUE TITLE
Beginner Issue

### ISSUE THREAD

**Issue by graudouin** [TelegramBots/Telegram.Bot#912]
I am new to Telegram Bots. I have created a bot but the Telegram.Bot is not receiving messages at all. I received one message before and one error event upon receive. The only thing that I see that could cause an issue is if the Bot Privacy is enabled but I disabled it. I checked the very simple Youtube videos and recreated the code according to simple instructions but to no avail. I know I am doing something stupid but I have no idea what. Any ideas? Am I setting up the API incorrectly.

My code is below:

[TelegramCode.txt](https://github.com/TelegramBots/Telegram.Bot/files/4867975/TelegramCode.txt)

**Comment by tuscen** [comment]
If you have questions regarding the library, feel free to join our [support group](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA). We don't use github issues to offer help.
