### ISSUE TITLE
Public constructor for UpdateEventArgs or public method that constructs it

### ISSUE THREAD

**Issue by nminaya** [TelegramBots/Telegram.Bot#926]
I'm trying to make unit tests for a project that uses Telegram.Bot... So I'm mocking **ITelegramBotClient** and I want to raise the **OnMessage** event, but this event needs **MessageEventArgs**, and this object needs **UpdateEventArgs** to be constructed and this object just has an internal constructor.

https://github.com/TelegramBots/Telegram.Bot/blob/e09ed3f20ba6a1f05ac0ea8c2e3dccc3550a641f/src/Telegram.Bot/Args/UpdateEventArgs.cs#L24

Is it possible to make a public constructor for **UpdateEventArgs**? 

Or a public method that internally construct a **UpdateEventArgs** with the given **Update**, or a **MessageEventArgs** with the given **Message**.

**Comment by Grepsy** [comment]
I'm struggling with exactly the same problem.
