### ISSUE TITLE
start void with events on onther void with different events

### ISSUE THREAD

**Issue by Ahron333** [TelegramBots/Telegram.Bot#934]
hi, i am trying to get this working. i trying evry thing and wont work, how could i make ti work?
thanks

`
public static async void BotOnCallbackQueryReceived(object sender, CallbackQueryEventArgs callbackQueryEventArgs)
{
   Start(sender, e);
}

public static async void Start(object sender, Telegram.Bot.Args.MessageEventArgs e)
{

}`

**Comment by Fedorus** [comment]
CallbackQueryEventArgs != MessageEventArgs

So just use OnUpdate event

**Comment by Ahron333** [comment]
> CallbackQueryEventArgs != MessageEventArgs
> 
> So just use OnUpdate event

how? can i use update event

**Comment by Fedorus** [comment]
> > CallbackQueryEventArgs != MessageEventArgs
> > So just use OnUpdate event
> 
> how? can i use update event

 I don`t have example, but there is this:
https://github.com/TelegramBots/Telegram.Bot.Examples/blob/master/Telegram.Bot.Examples.Polling/Program.cs

**Comment by Ahron333** [comment]
> > > CallbackQueryEventArgs != MessageEventArgs
> > > So just use OnUpdate event
> > 
> > 
> > how? can i use update event
> 
> I don`t have example, but there is this:
> https://github.com/TelegramBots/Telegram.Bot.Examples/blob/master/Telegram.Bot.Examples.Polling/Program.cs
> 
> Note that it needs additional Telegram.Bot.Extensions.Polling package!

i could not make this happed?
public static async void BotOnCallbackQueryReceived(object sender, CallbackQueryEventArgs callbackQueryEventArgs)
{
Start(sender, e);
}

public static async void Start(object sender, Telegram.Bot.Args.MessageEventArgs e)
{

}

**Comment by Fedorus** [comment]
> > > > CallbackQueryEventArgs != MessageEventArgs
> > > > So just use OnUpdate event
> > > 
> > > 
> > > how? can i use update event
> > 
> > 
> > I don`t have example, but there is this:
> > https://github.com/TelegramBots/Telegram.Bot.Examples/blob/master/Telegram.Bot.Examples.Polling/Program.cs
> > Note that it needs additional Telegram.Bot.Extensions.Polling package!
> 
> i could not make this happed?
> public static async void BotOnCallbackQueryReceived(object sender, CallbackQueryEventArgs callbackQueryEventArgs)
> {
> Start(sender, e);
> }
> 
> public static async void Start(object sender, Telegram.Bot.Args.MessageEventArgs e)
> {
> 
> }

Events will be deleted in next library version so do it like I`ve suggested in previous message )

**Comment by karb0f0s** [comment]
@Ahron333  please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/ISSUE_TEMPLATE.md)
If you need to chat, join our [group chat](https://t.me/tgbots_dotnet).
