### ISSUE TITLE
DeleteMessageAsync should return Task<bool> instead of Task

### ISSUE THREAD

**Issue by bpashkovskyi** [TelegramBots/Telegram.Bot#935]

**Comment by Fedorus** [comment]
And why we should pass useless variable on stack?

**Comment by bpashkovskyi** [comment]
To detect if message was deleted successfully

**Comment by Fedorus** [comment]
> To detect if message was deleted successfully

If you have no exception... then it is deleted )

**Comment by bpashkovskyi** [comment]
Exceptions should not be used for flow control

**Comment by tuscen** [comment]
Telegram never returns false as a result in such methods, it makes no sense to return anything there. It returns errors instead which are then thrown as exceptions in the library. Though in the vnext there will be additional method to make requests that do not throw exceptions for valid errors from Bot API.

**Comment by karb0f0s** [comment]
Please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/ISSUE_TEMPLATE.md)
If you want to chat, feel free to join our [group](https://t.me/tgbots_dotnet).
