### ISSUE TITLE
@Nhan2207

### ISSUE THREAD

**Issue by 779nhan** [TelegramBots/Telegram.Bot#941]
# I found a bug to report

Please use the following template to ensure maintainers can reproduce the bug and solve it quickly.

> Bug reports that do not follow this template will be kept closed because [_not-reproducible_](https://github.com/TelegramBots/telegram.bot/labels/not-reproducible) until the creator edits the post properly.

### Environment data

*NuGet Package Version:* (e.g. 13.0.1)

*.NET Version:* (e.g. 4.7, Core 1.1, Mono, etc.)

*IDE:* (e.g. VS2017, VS Code, etc.)

*App:* (e.g. Desktop, iOS, Android, etc.)

**Comment by karb0f0s** [comment]
please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/ISSUE_TEMPLATE.md)
If you need to chat, join our [group chat](https://t.me/tgbots_dotnet).
