### ISSUE TITLE
the EditMessageMediaAsync function removes the media instead of replacing it

### ISSUE THREAD

**Issue by AGitWanderer** [TelegramBots/Telegram.Bot#942]
### Steps to reproduce

using the following architecture:
```

Bot_OnInlineQuery

 new InlineQueryResultDocument(
                    id: "ccc",
                    documentUrl:PdfUrl,
                       title:"sddf",mimeType:"application/pdf"){
                           ReplyMarkup=k1,
                           InputMessageContent=new InputTextMessageContent(  messageText:"cccc"   ) 
                    {
                       
                    }
                       },
                    new InlineQueryResultArticle(
                    id: "ddd",
                    title: "ddd",
                    inputMessageContent: new InputTextMessageContent(  messageText:"dddd"   ) )
                    {
                        Description =  "...",
                        ThumbUrl = "",
                        ReplyMarkup = k1 ,
                    }


botClient.AnswerInlineQueryAsync

```
the bot show an inline menu
and in `Bot_OnInlineResultChosen`
I have

```
 var result= Program.botClient.EditMessageMediaAsync(
                                                    inlineMessageId: ChosenInlineResult. InlineMessageId,
                                                    
                                                     media:  new InputMediaDocument(pdfUrl2)
                                                     {
                                                             Caption = "**Audio** in `.mp3` format",
                                                             ParseMode = ParseMode.Markdown,
                                                     }
             
                                                    ,replyMarkup: null);
                                                    await result;
Console.WriteLine(result.Status+" "+result.Exception);


```

### Expected  behavior
the document should be replaced
### Actual behavior
this code won't replace the document it simply removes it and in the text shows "**Audio** in `.mp3` format"

### Screenshots
[https://ibb.co/r0YW3sS](url)
### Environment data

*NuGet Package Version:* (15.7.1)

*.NET Version:* (Core 3.1)

*IDE:* ( VS Code)

*App:* (Web)

**Comment by karb0f0s** [comment]
There is not much happening behind [EditMessageMediaAsync](https://github.com/TelegramBots/Telegram.Bot/blob/e09ed3f20ba6a1f05ac0ea8c2e3dccc3550a641f/src/Telegram.Bot/TelegramBotClient.cs#L1145-L1154) method.
You can try manually serialize [EditInlineMessageMediaRequest](https://github.com/TelegramBots/Telegram.Bot/blob/e09ed3f20ba6a1f05ac0ea8c2e3dccc3550a641f/src/Telegram.Bot/Requests/Update%20Messages/EditInlineMessageMediaRequest.cs#L14). If it is not serialized properly, we can fix it.
But if this behaviour is specific to Telegram Bot API servers there's nothing we can do about it.
