### ISSUE TITLE
pinChatMessage should return TRUE on Success

### ISSUE THREAD

**Issue by taha-ghadirian** [TelegramBots/Telegram.Bot#943]
# I found a bug to report

### Steps to reproduce

just use bot.PinMessageAsync!

### Expected  behavior

return TRUE on success or false when fails.

### Actual behavior

its only a Task not Task<bool>

### Screenshots

![image](https://user-images.githubusercontent.com/36773254/100196604-5b22ff80-2f0e-11eb-9e7e-124215b6fdc0.png)

**Comment by Fedorus** [comment]
#935 same answer as this ;)

**Comment by taha-ghadirian** [comment]
Same bot I Think should change? exceptions are bad happening in applications if developer forget using tryCatch!
