### ISSUE TITLE
Add Strong Name.

### ISSUE THREAD

**Issue by HavenDV** [TelegramBots/Telegram.Bot#944]
Add to .csproj
```xml
<SignAssembly>true</SignAssembly>
<AssemblyOriginatorKeyFile>key.snk</AssemblyOriginatorKeyFile>
```
and add key.snk in project properties.

like this:
![image](https://user-images.githubusercontent.com/3002068/102263848-94c0b680-3f60-11eb-8074-a39d06e7d92c.png)

The strong name makes your library more useful (sometimes required for modules or extensions).

**Comment by karb0f0s** [comment]
we are not planning to release a signed version. it doesn't add any benefit but has many downsides. you can sign it on your side in your ci/cd pipeline if you need to. 
generally signing is neither recommended nor needed for modern .NET applications.
