### ISSUE TITLE
SendTextMessageAsync error Chat not found

### ISSUE THREAD

**Issue by samperizal** [TelegramBots/Telegram.Bot#953]
regards

I have tried to send a text message (SendTextMessageAsync) to a telegram username and it gives the error "Chat not found"

SendTextMessageAsync (username, text, ...)

the telegram api

https://core.telegram.org/bots/api#sendmessage

> **Parameter**                                       
>      chat_id   

    

>  **Type**
>     Integer or String 

> **Required** 
>    Yes   

   

> **Description**
>    Unique identifier for the target chat or username of the target channel (in the format @channelusername)

 

it's possible ?

**Comment by karb0f0s** [comment]
> Unique identifier for the target chat or username **of the target channel** (in the format @channelusername)
you only can reference channels this way. groups, supergroups and private chats are only available via their chatId

**Comment by karb0f0s** [comment]
Please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/ISSUE_TEMPLATE.md)
If you want to chat, feel free to join our [group](https://t.me/tgbots_dotnet).
