### ISSUE TITLE
Force a reply 

### ISSUE THREAD

**Issue by samperizal** [TelegramBots/Telegram.Bot#954]
Greetings.

Is it possible to force a reply to a text message?

Thank you

**Comment by karb0f0s** [comment]
yes it is possible

**Comment by karb0f0s** [comment]
Please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/ISSUE_TEMPLATE.md)
If you want to chat, feel free to join our [group](https://t.me/tgbots_dotnet).
