### ISSUE TITLE
cannot convert from 'Telegram.Bot.Types.PollOption []' to 'System.Collections.Generic.IEnumerable

### ISSUE THREAD

**Issue by samperizal** [TelegramBots/Telegram.Bot#955]
Greetings.
I have created an object polloption that contains the answers

```
                    PollOption [] questions = new []
                    {
                        new PollOption () {
                          Text = "Yes",
                          VoterCount = 63
                        },

                        new PollOption () {
                          Text = "No",
                          VoterCount = 12
                        }
                    };
```

when passing it to the POLL object

```
                    var i = await botClient.SendPollAsync (
                           chatId: _Message.Id,
                           isAnonymous: false,
                           openPeriod: 15,
                           type: PollType.Regular,
                           question: "do you read?",
                           options: questions

                       );
```

gives the error

**Argument 6: cannot convert from 'Telegram.Bot.Types.PollOption []' to 'System.Collections.Generic.IEnumerable <string>'**

Does anyone know how to do it?

**Comment by karb0f0s** [comment]
You cannot use `PollOption` object to create new poll. 
According to official Telegram Bot API [`Poll`](https://core.telegram.org/bots/api#poll) and [`PollOption`](https://core.telegram.org/bots/api#polloption) are properties of [`Update`](https://core.telegram.org/bots/api#update) object - and represent result of the poll. [`SendPoll`](https://core.telegram.org/bots/api#sendpoll) options is an `Array of String` representing answers.
