### ISSUE TITLE
How to download voice file?

### ISSUE THREAD

**Issue by onurcansen** [TelegramBots/Telegram.Bot#959]
I Try this:

```
Telegram.Bot.Types.File file = await bot.GetFileAsync(e.Message.Voice.FileId);
file.
```
But im stuck here how save this file on my computer ?

**Comment by Fedorus** [comment]
https://github.com/TelegramBots/Telegram.Bot/blob/e09ed3f20ba6a1f05ac0ea8c2e3dccc3550a641f/src/Telegram.Bot/TelegramBotClient.cs#L854

**Comment by karb0f0s** [comment]
@onurcansen  take a look at [this code](https://github.com/TelegramBots/Telegram.Bot/blob/8103e2acb57fabafff53a3fc41a5e979059c9818/test/Telegram.Bot.Tests.Integ/Other/FileDownloadTests.cs#L92-L105) this should allow you to download file by `fileId` to a desired destination.
