### ISSUE TITLE
Bot API 5.1 (March 9, 2021)

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#962]
# [Bot API 5.1](https://core.telegram.org/bots/api-changelog#march-9-2021)

## Added two new update types

- Added updates about member status changes in chats, represented by the class `ChatMemberUpdated` and the fields `my_chat_member` and `chat_member` in the `Update` class. The bot must be an administrator in the chat to receive `chat_member` updates about other chat members. By default, only `my_chat_member` updates about the bot itself are received.

## Improved Invite Links

- Added the class `ChatInviteLink`, representing an invite link to a chat.
- Added the method `createChatInviteLink`, which can be used to create new invite links in addition to the primary invite link.
- Added the method `editChatInviteLink`, which can be used to edit non-primary invite links created by the bot.
- Added the method `revokeChatInviteLink`, which can be used to revoke invite links created by the bot.

## Voice Chat Info

- Added the type `VoiceChatStarted` and the field `voice_chat_started` to the class `Message`.
- Added the type `VoiceChatEnded` and the field `voice_chat_ended` to the class `Message`.
- Added the type `VoiceChatParticipantsInvited` and the field `voice_chat_participants_invited` to the class `Message`.
- Added the new administrator privilege `can_manage_voice_chats` to the class `ChatMember` and parameter `can_manage_voice_chats` to the method `promoteChatMember`. For now, bots can use this privilege only for passing to other administrators.

## And More

- Added the type `MessageAutoDeleteTimerChanged` and the field `message_auto_delete_timer_changed` to the class `Message`.
- Added the parameter `revoke_messages` to the method `kickChatMember`, allowing to delete all messages from a group for the user who is being removed.
- Added the new administrator privilege `can_manage_chat` to the class `ChatMember` and parameter `can_manage_chat` to the method `promoteChatMember`. This administrator right is implied by any other administrator privilege.
- Supported the new bowling animation for the random dice. Choose between different animations (dice, darts, basketball, football, bowling, slot machine) by specifying the _emoji_ parameter in the method `sendDice`.

>⚠️ WARNING! ⚠️
>
>After one of the upcoming Bot API updates, _some_ user identifiers will become bigger than 2^31 - 1 and it will be no longer possible to store them in a signed 32-bit integer type. User identifiers will have up to 52 significant bits, so a 64-bit integer or double-precision float type would still be safe for storing them. Please make sure that your code can correctly handle such user identifiers.

**Comment by derigel23** [comment]
It should be implemented ASAP because of user id will not fit in existing data type.
