### ISSUE TITLE
Create groups or supergroups

### ISSUE THREAD

**Issue by gsasch** [TelegramBots/Telegram.Bot#966]
Create groups or supergroups
https://core.telegram.org/method/channels.createChannel

**Comment by Fedorus** [comment]
That isn't part of bot api.

**Comment by karb0f0s** [comment]
Please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/ISSUE_TEMPLATE.md)
If you want to chat, feel free to join our [group](https://t.me/tgbots_dotnet).

**Comment by gsasch** [comment]
Hello, sorry but this is link is not working. I'll chat you thanks
[image: image.png]

Il giorno mer 17 mar 2021 alle ore 04:08 karb0f0s ***@***.***>
ha scritto:
