### ISSUE TITLE
get channel messages in array

### ISSUE THREAD

**Issue by graysuit** [TelegramBots/Telegram.Bot#971]
Respected developers,
is there any example to show 
how to get channel or group message with specific index ?

I also joined your group for support, but looks like i can't post anything there.
Regards

**Comment by Fedorus** [comment]
U can`t get any messages/posts unless telegram sent it. 
Bot are designed to react on something new, not something that was in the past

**Comment by graysuit** [comment]
@Fedorus 
Actually I'm new to telegram bot.
So what you recommend ? telegram api ?

please do guide me, if you know which can do better.
Thanks for quick reply.

**Comment by Fedorus** [comment]
If you really need old messages/posts you need client api, https://github.com/sochix/TLSharp
