### ISSUE TITLE
Please allow to specify custom (local) telegram server url

### ISSUE THREAD

**Issue by monster1025** [TelegramBots/Telegram.Bot#982]
## I would like to request/propose a feature
I want to use local telegram bot api server (https://core.telegram.org/bots/api#using-a-local-bot-api-server), but api.telegram.org urls are hardcoded in client. Also TelegramClient ignores baseUrl of HttpClient.
Please allow to specify custom server url.

**Comment by karb0f0s** [comment]
This feature is not yet available in official released package. It is available in preview through CI/CD feed: https://dev.azure.com/tgbots/Telegram.Bot/_packaging?_a=connect&feed=Telegram.Bot%40Local
API 5.1 support added in Telegram.Bot 16.0.0-ci.* packages.

**Comment by monster1025** [comment]
Thanks for fast feedback! Checked it and it works great!
