### ISSUE TITLE
YooKassa invoice more then one 

### ISSUE THREAD

**Issue by PixelGuy19** [TelegramBots/Telegram.Bot#987]
# Operator : incorrect information / invoice with 2+ parts

When in invoice have more than 1 part of cost everything fall apart.

### Steps to reproduce
1. Create project (console template) and add nuget package
2. Create bot in @BotFather
3. Add YooKassa(ЮKassa) paymant method (in my case - test variant).
4. Add this code somewhere in code
`List<LabeledPrice> Prices = new List<LabeledPrice>();`
`Prices.Add(new LabeledPrice("First", 1000*100));`
`await Bot.SendInvoiceAsync(e.Message.From.Id, "<title>", "<description>", "123", "<token>", "RUB", Prices, 500, null, string.Empty, null, "<link to image 1280x720>",0,1280,720, false,false,true,false,false,false,false,false,0);`

User information from boolean parameters don't mean much so they can be deleted without loss. Same thing i can say about image link and it sizes.

Another or addition case
`List<LabeledPrice> Prices = new List<LabeledPrice>();`
`Prices.Add(new LabeledPrice("First", 1000*100));`
`Prices.Add(new LabeledPrice("Second", 1000*100)); //this line also breaks invoice`

### Expected  behavior

Simple invoice with new payment 2.0 features.

### Actual behavior

On checkout operator throw error: incorrect information.

### Screenshots

[Error text in telegram](https://imgur.com/a/4cZX5le)
[More then one part price](https://imgur.com/a/lS2y1PF)

### Environment data

*NuGet Package Version: 16.0.0-alpha.2

*.NET Version: Core 3.1

*IDE: VS 2019

*App: Desctop-console (windows 10)

**Comment by tuscen** [comment]
Hi. I couldn't obtain a YouKassa account to get a test token to reproduce your issue. Could you maybe share yours in private in Telegram if you are comfortable with this?

**Comment by PixelGuy19** [comment]
You can get test token without account in telegram bot father (it takes link to another youkassa bot). Anyway, yes you can use my token below.

381764678:TEST:25467
test card data 1111 1111 1111 1026, 12/22, CVC 000

**Comment by karb0f0s** [comment]
@PixelGuy19 we were able to run tests for YooKassa provider and they're fine. You might take into account limitations for test account described [here](https://yookassa.ru/docs/support/payments/onboarding/integration/cms-module/telegram)
> Обратите внимание, что платежи для тестового магазина должны быть не более 1000 рублей.

As long as you keep total payment below 1000RUB your tests should be fine.
