### ISSUE TITLE
Add code coverage

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#990]
Consider adding code coverage in CI pipeline.

.Net Core is able to [produce cross-platform](https://github.com/microsoft/vstest/issues/981#issuecomment-839500012) code-coverage reports and Azure DevOps is able to [display coverage](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/review-code-coverage-results?view=azure-devops) information. This could help to identify "blind spots" in our test suite.

**Comment by wiz0u** [comment]
We don't have the manpower for now to add ourself more work. Closing this.
(our test suite already has lots of blind spots due to not keeping up with new version of Bot APIs anyway)
