### ISSUE TITLE
Reduce time and memory usage during instantiation

### ISSUE THREAD

**Issue by karb0f0s** [TelegramBots/Telegram.Bot#992]
It is possible to reduce overhead during instantiation of `TelegramBotClient`:

1.  `BotId` extraction via `RegEx` could be replaced with `Span` manipulations:

| [Original](https://github.com/TelegramBots/Telegram.Bot/blob/c6c0aec42665327ce5b68d086ed1143473192ec4/src/Telegram.Bot/TelegramBotClient.cs#L199-L207) | [Optimized](https://github.com/karb0f0s/BotClientConstructorBenchmark/blob/dc182d22f55060a05f3238b4631b9d776c8f8212/src/BotClient/FatClient.cs#L98-L110) |
|-|-|

|                    Method |              Runtime |      Mean | Ratio |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------- |--------------------- |----------:|------:|-------:|------:|------:|----------:|
|                Bench_Orig |             .NET 5.0 | 311.52 ns |  1.00 | 0.1450 |     - |     - |     456 B |
|          Bench_Orig_BadId |             .NET 5.0 |  85.04 ns |  0.27 | 0.0100 |     - |     - |      32 B |
|       Bench_SpanLocalFunc |             .NET 5.0 |  33.62 ns |  0.11 | 0.0101 |     - |     - |      32 B |
| Bench_SpanLocalFunc_BadId |             .NET 5.0 |  34.14 ns |  0.11 | 0.0101 |     - |     - |      32 B |
|                           |                      |           |       |        |       |       |           |
|                Bench_Orig | .NET Framework 4.6.1 | 580.52 ns |  1.00 | 0.1450 |     - |     - |     457 B |
|          Bench_Orig_BadId | .NET Framework 4.6.1 | 336.42 ns |  0.58 | 0.0100 |     - |     - |      32 B |
|       Bench_SpanLocalFunc | .NET Framework 4.6.1 | 161.20 ns |  0.28 | 0.0229 |     - |     - |      72 B |
| Bench_SpanLocalFunc_BadId | .NET Framework 4.6.1 | 140.51 ns |  0.24 | 0.0229 |     - |     - |      72 B |

2.  Avoid parsing `baseUrl` via `TrySetBaseUrl` for default `BaseTelegramUrl`. Current implementation tries to parse `BaseTelegramUrl` even though it will return same address:

| [Original](https://github.com/TelegramBots/Telegram.Bot/blob/c6c0aec42665327ce5b68d086ed1143473192ec4/src/Telegram.Bot/TelegramBotClient.cs#L209-L212) | [Optimized](https://github.com/karb0f0s/BotClientConstructorBenchmark/blob/dc182d22f55060a05f3238b4631b9d776c8f8212/src/BotClient/FatClient.cs#L88-L91) |
|-|-|

|                   Method |              Runtime |        Mean | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------- |--------------------- |------------:|------:|--------:|-------:|------:|------:|----------:|
|               Bench_Orig |             .NET 5.0 | 1,085.07 ns |  1.00 |    0.00 | 0.4883 |     - |     - |   1,536 B |
| Bench_Orig_CustomBaseUrl |             .NET 5.0 | 1,190.47 ns |  1.09 |    0.03 | 0.6294 |     - |     - |   1,976 B |
|               Bench_Span |             .NET 5.0 |    99.69 ns |  0.09 |    0.00 | 0.1274 |     - |     - |     400 B |
| Bench_Span_CustomBaseUrl |             .NET 5.0 |   882.73 ns |  0.81 |    0.02 | 0.4940 |     - |     - |   1,552 B |
|                          |                      |             |       |         |        |       |       |           |
|               Bench_Orig |             .NET 6.0 |   983.56 ns |  1.00 |    0.00 | 0.3414 |     - |     - |   1,072 B |
| Bench_Orig_CustomBaseUrl |             .NET 6.0 | 1,060.93 ns |  1.08 |    0.04 | 0.3738 |     - |     - |   1,176 B |
|               Bench_Span |             .NET 6.0 |   102.18 ns |  0.10 |    0.00 | 0.1274 |     - |     - |     400 B |
| Bench_Span_CustomBaseUrl |             .NET 6.0 |   715.57 ns |  0.73 |    0.02 | 0.2394 |     - |     - |     752 B |
|                          |                      |             |       |         |        |       |       |           |
|               Bench_Orig | .NET Framework 4.6.1 | 1,563.14 ns |  1.00 |    0.00 | 0.5341 |     - |     - |   1,685 B |
| Bench_Orig_CustomBaseUrl | .NET Framework 4.6.1 | 1,728.23 ns |  1.11 |    0.03 | 0.6733 |     - |     - |   2,118 B |
|               Bench_Span | .NET Framework 4.6.1 |   246.37 ns |  0.16 |    0.01 | 0.1426 |     - |     - |     449 B |
| Bench_Span_CustomBaseUrl | .NET Framework 4.6.1 | 1,300.77 ns |  0.83 |    0.02 | 0.5493 |     - |     - |   1,733 B |

Still, necessity to parse custom `baseUrl` has negative performance impact. I wonder if we could reduce this overhead, by specifying `Uri` type for `baseUrl` in the constructor.

**Comment by tuscen** [comment]
Greate idea. I'll definetely try to include it in the next feature release.
