### ISSUE TITLE
Is it possible to get 

### ISSUE THREAD

**Issue by naserkaka** [TelegramBots/Telegram.Bot#999]
# I have a question or need help

Is it possible to get the mychatid without sending a message from telegram? I want to get it when the application starts

 static async void Bot_OnMessage(object sender, MessageEventArgs e)
        {
            mychatId = e.Message.Chat;

}
 public async static void sendMessage(string msg)
        {   // chat id : 402781067
           await botClient.SendTextMessageAsync(
                chatId: mychatId,
                text: msg
                );
        }

**Comment by Fedorus** [comment]
If you already know it - just replace mychatId  with number

**Comment by naserkaka** [comment]
I tried and I got this 
![public async static void sendMessage(str](https://user-images.githubusercontent.com/70115032/124514797-2816e780-ddde-11eb-9e07-9edbad6059c2.jpeg)

**Comment by Fedorus** [comment]
Has nothing to do with id )
I`d say that botClient == null

**Comment by naserkaka** [comment]
Thanks I solved it! yes it was because botclient was null

**Comment by tuscen** [comment]
Please, read message templates before posting. We don't answer questions in Github issues. If you have a question feel free to join our chat.
